Vireo: controllers.submit.DocumentInfo Class Reference
controllers.submit.DocumentInfo Class Reference
Classes
class TransientMember
Static Public Member Functions
static void documentInfo (Long subId)
static boolean verify (Submission sub)
static List< TransientMember > loadCommitteeMembers (Submission sub)
static boolean validateCommitteeMembers (Submission sub, List< TransientMember > members)
static List< TransientMember > parseCommitteeMembers ()
static boolean saveCommitteeMembers (Submission sub, List< TransientMember > members)
Static Public Member Functions inherited from controllers.AbstractVireoController
static void injectRepositories ()
static void checkForFirstUser ()
static void handleError (Throwable throwable)
Static Protected Member Functions
static boolean isValidDegreeMonth (Integer degreeMonth)
static boolean isValidDegreeYear (Integer degreeYear)
static boolean isValidDocType (String docType)
static boolean isValidRoleType (Submission sub, List< String > roles)
static List< Integer > getDegreeYears ()
static List< String > getValidDocumentTypes (Submission sub)
Static Protected Member Functions inherited from controllers.submit.AbstractSubmitStep
static Submission getSubmission ()
static boolean isFieldEnabled (FieldConfig field)
static boolean isFieldRequired (FieldConfig field)
Static Protected Member Functions inherited from controllers.AbstractVireoController
static boolean isEmpty (String value)
static boolean isNotEmpty (String value)
static String escapeJavaScript (String value)
static String toJSON (String[] values)
static String text2html (String value)
static boolean isFieldRequired (FieldConfig field)
Additional Inherited Members
Static Public Attributes inherited from controllers.AbstractVireoController
static SecurityContext context = Spring.getBeanOfType(SecurityContext.class)
static PersonRepository personRepo = Spring.getBeanOfType(PersonRepository.class)
static SubmissionRepository subRepo = Spring.getBeanOfType(SubmissionRepository.class)
static SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class)
static ProquestVocabularyRepository proquestRepo = Spring.getBeanOfType(ProquestVocabularyRepository.class)
static ErrorLog errorLog = Spring.getBeanOfType(ErrorLog.class)
static StateManager stateManager = Spring.getBeanOfType(StateManager.class)
static Indexer indexer = Spring.getBeanOfType(Indexer.class)
static Searcher searcher = Spring.getBeanOfType(Searcher.class)
static Boolean firstUser = null
Static Package Functions inherited from controllers.submit.AbstractSubmitStep
static void beforeSubmit ()
Detailed Description
This is the third step of the submission process. This is where students provide metedata about their document, committee members, and select among publication options.
Author
Scott Phillips
Bill Ingram
Dan Galewsky
Definition at line 53 of file DocumentInfo.java.
Member Function Documentation
static void controllers.submit.DocumentInfo.documentInfo (Long subId) static
The third step of the submission form.
We handle committee members a bit differently. Basically we always keep a List of Maps for each committee member while we are working with it. So there are several methods to parse the committee members from the current form data, validate the committee members, then save the committee members, and if this is the first time visiting the form there is a method to load committee members. It's complex, but the problem is Difficult.
Parameters
subId The id the submission.
Definition at line 70 of file DocumentInfo.java.
References org.tdl.vireo.model.Submission.addDocumentSubject(), org.tdl.vireo.model.Submission.getCommitteeContactEmail(), org.tdl.vireo.model.Submission.getDefenseDate(), controllers.submit.DocumentInfo.getDegreeYears(), org.tdl.vireo.model.Submission.getDocumentAbstract(), org.tdl.vireo.model.Submission.getDocumentTitle(), org.tdl.vireo.model.Submission.getGraduationMonth(), controllers.submit.AbstractSubmitStep.getSubmission(), controllers.submit.DocumentInfo.getValidDocumentTypes(), controllers.AbstractVireoController.isEmpty(), controllers.submit.AbstractSubmitStep.isFieldEnabled(), controllers.submit.AbstractSubmitStep.isFieldRequired(), controllers.submit.DocumentInfo.loadCommitteeMembers(), controllers.submit.DocumentInfo.parseCommitteeMembers(), controllers.submit.DocumentInfo.saveCommitteeMembers(), org.tdl.vireo.model.Submission.setDocumentKeywords(), org.tdl.vireo.model.Submission.setDocumentLanguage(), org.tdl.vireo.model.Submission.setDocumentTitle(), org.tdl.vireo.model.Submission.setDocumentType(), and controllers.submit.DocumentInfo.verify().
{
         // Validate the submission
         Submission sub = getSubmission();
         // Get our form paramaters.
         String title = params.get("title");
         String degreeMonth = params.get("degreeMonth");
         String degreeYear = params.get("degreeYear");
         Date defenseDate = null;
         DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
         try {
             if(params.get("defenseDate")!=null && !"".equals(params.get("defenseDate").trim()))
                 defenseDate = (Date)formatter.parse(params.get("defenseDate"));
         } catch (ParseException e) {
             validation.addError("defenseDate","Please format your defense date as mm/dd/yyyy");
         }
         String docType = params.get("docType");
         String abstractText = params.get("abstractText");
         String keywords = params.get("keywords");
         String subjectPrimary = params.get("subject-primary");
         String subjectSecondary = params.get("subject-secondary");
         String subjectTertiary = params.get("subject-tertiary");
         String docLanguage = null;
         if(isFieldRequired(DOCUMENT_LANGUAGE) && settingRepo.findAllLanguages().size()==1) {
             docLanguage = settingRepo.findAllLanguages().get(0).getName();
         } else {
             docLanguage = params.get("docLanguage");
             if (docLanguage != null && docLanguage.trim().length() == 0)
                 docLanguage = null;
         }
         Boolean publishedMaterialFlag = params.get("publishedMaterialFlag",Boolean.class);
         if (publishedMaterialFlag == null)
             publishedMaterialFlag = false;
         String publishedMaterial = params.get("publishedMaterial");
         if (!publishedMaterialFlag)
             publishedMaterial = null;
         String chairEmail = params.get("chairEmail");
         List<String> embargos = new ArrayList<String>();
         for(EmbargoGuarantor gaurantor : EmbargoGuarantor.values() ) {
             String embargoString = params.get("embargo-"+gaurantor.name());
             if(embargoString != null && embargoString.trim().length() != 0)
                 embargos.add(embargoString);
         }
         List<TransientMember> committee = parseCommitteeMembers();
         if ("documentInfo".equals(params.get("step"))) {
             // Save the data
             if (isFieldEnabled(DOCUMENT_TITLE))
                 sub.setDocumentTitle(title);
             if (isFieldEnabled(GRADUATION_DATE)) {
                 if (!isEmpty(degreeMonth)) {
                     try {
                         sub.setGraduationMonth(Integer.parseInt(degreeMonth));
                     } catch (RuntimeException re) {
                         validation.addError("degreeMonth", "Please select a valid degree month");
                     }
                 } else {
                     sub.setGraduationMonth(null);
                 }
                 if (!isEmpty(degreeYear)) {
                     try {
                         sub.setGraduationYear(Integer.parseInt(degreeYear));
                     } catch (RuntimeException re) {
                         validation.addError("degreeYear", "Please select a valid degree year");
                     }
                 } else {
                     sub.setGraduationYear(null);
                 }
             }
             if (isFieldEnabled(DEFENSE_DATE)) {
                 sub.setDefenseDate(defenseDate);
             }
             if (isFieldEnabled(DOCUMENT_TYPE))
                 sub.setDocumentType(docType);
             if (isFieldEnabled(DOCUMENT_ABSTRACT))
                 sub.setDocumentAbstract(abstractText);
             if (isFieldEnabled(DOCUMENT_KEYWORDS))
                 sub.setDocumentKeywords(keywords);
             if (isFieldEnabled(DOCUMENT_SUBJECTS)) {
                 sub.getDocumentSubjects().clear();
                 if (!isEmpty(subjectPrimary))
                     sub.addDocumentSubject(subjectPrimary);
                 if (!isEmpty(subjectSecondary))
                     sub.addDocumentSubject(subjectSecondary);
                 if (!isEmpty(subjectTertiary))
                     sub.addDocumentSubject(subjectTertiary);
             }
             if (isFieldEnabled(DOCUMENT_LANGUAGE))
                 sub.setDocumentLanguage(docLanguage);
             if (isFieldEnabled(COMMITTEE_CONTACT_EMAIL))
                 sub.setCommitteeContactEmail(chairEmail);
             if (isFieldEnabled(PUBLISHED_MATERIAL)) {
                 if (publishedMaterialFlag)
                     sub.setPublishedMaterial(publishedMaterial);
                 else
                     sub.setPublishedMaterial(null);
             }
             if (isFieldEnabled(EMBARGO_TYPE)) {
                 for(String embargo : embargos) {
                     try {
                         sub.addEmbargoType(settingRepo.findEmbargoType(Long.parseLong(embargo)));
                     } catch (RuntimeException re){
                         if (isFieldRequired(EMBARGO_TYPE))
                             validation.addError("embargo", "Please select a valid embargo option");
                     }
                 }
             }
             if (isFieldEnabled(COMMITTEE)) {
                 try {
                     saveCommitteeMembers(sub, committee);
                 } catch (RuntimeException re){ /*ignore*/ }
             }
             sub.save();
         } else {
             if (isFieldEnabled(DOCUMENT_TITLE))
                 title = sub.getDocumentTitle();
             if (isFieldEnabled(GRADUATION_DATE) && sub.getGraduationMonth() != null)
                 degreeMonth =  sub.getGraduationMonth().toString();
             if (isFieldEnabled(GRADUATION_DATE) && sub.getGraduationYear() != null)
                 degreeYear = sub.getGraduationYear().toString();
             if (isFieldEnabled(DEFENSE_DATE) && sub.getDefenseDate() != null)
                 defenseDate = sub.getDefenseDate();
             if (isFieldEnabled(DOCUMENT_TYPE))
                 docType = sub.getDocumentType();
             if (isFieldEnabled(DOCUMENT_ABSTRACT))
                 abstractText = sub.getDocumentAbstract();
             if (isFieldEnabled(DOCUMENT_KEYWORDS))
                 keywords = sub.getDocumentKeywords();
             if (isFieldEnabled(DOCUMENT_SUBJECTS)) {
                 List<String> subjects = sub.getDocumentSubjects();
                 if (subjects.size() > 0)
                     subjectPrimary = subjects.get(0);
                 if (subjects.size() > 1)
                     subjectSecondary = subjects.get(1);
                 if (subjects.size() > 2)
                     subjectTertiary = subjects.get(2);
             }
             if (isFieldEnabled(DOCUMENT_LANGUAGE)) {
                 docLanguage = sub.getDocumentLanguage();
             }
             // Get the list of committee members
             if (isFieldEnabled(COMMITTEE))
                 committee = loadCommitteeMembers(sub);
             if (isFieldEnabled(COMMITTEE_CONTACT_EMAIL))
                 chairEmail = sub.getCommitteeContactEmail();
             if (isFieldEnabled(PUBLISHED_MATERIAL))
                 publishedMaterial = sub.getPublishedMaterial();
             for(EmbargoGuarantor eg : EmbargoGuarantor.values()) {
                 String fieldName = eg.name().equals("DEFAULT") ? "EMBARGO_TYPE" : "EMBARGO_TYPE_"+eg.name();
                 FieldConfig field = FieldConfig.valueOf(fieldName);
                 if (isFieldEnabled(field) && sub.getEmbargoTypeByGuarantor(eg) != null) {
                     embargos.add(sub.getEmbargoTypeByGuarantor(eg).getId().toString());
                 }
             }
         }
         // Verify the form if we are submitting or if jumping from the confirm step.
         if ("documentInfo".equals(params.get("step")) ||
             "confirm".equals(flash.get("from-step"))) {
             verify(sub);
         }
         // If there are no errors then go to the next step
         if (params.get("submit_next") != null && !validation.hasErrors() ) {
             FileUpload.fileUpload(subId);
         }
         // List of valid degree years for drop-down population
         List<Integer> degreeYears = getDegreeYears();
         renderArgs.put("degreeYears", degreeYears);
         // List of all document types
         List<String> docTypes = getValidDocumentTypes(sub);
         renderArgs.put("docTypes", docTypes);
         // List of all *active* Embargo Types
         List<EmbargoType> embargoTypes = settingRepo.findAllActiveEmbargoTypes();
         renderArgs.put("embargoTypes", embargoTypes);
         // List of all subjects
         List<ProquestSubject> subjects = proquestRepo.findAllSubjects();
         renderArgs.put("subjects", subjects);
         // List available committe roles
         List<CommitteeMemberRoleType> availableRoles = settingRepo.findAllCommitteeMemberRoleTypes(sub.getDegreeLevel());
         renderArgs.put("availableRoles", availableRoles);
         // List of all languages
         List<Language> languages = settingRepo.findAllLanguages();
         renderArgs.put("docLanguages", languages);
         // Figure out how mayn committee spots to show.
         int committeeSlots = 4;
         if (committee.size() > 3)
             committeeSlots = committee.size();
         if (params.get("submit_add") != null)
             committeeSlots += 4;
         List<String> stickies = new ArrayList<String>();
         String stickiesRaw = settingRepo.getConfigValue(SUBMIT_DOCUMENT_INFO_STICKIES);
         if (stickiesRaw != null && !"null".equals(stickiesRaw)) {
             try {
                 CSVReader reader = new CSVReader(new StringReader(stickiesRaw));
                 stickies = Arrays.asList(reader.readNext());
                 reader.close();
             } catch (IOException ioe) {
                 throw new RuntimeException(ioe);
             }
         }
         if (publishedMaterial != null)
             publishedMaterialFlag = true;
         renderTemplate("Submit/documentInfo.html", subId, stickies,
                 title, degreeMonth, degreeYear, defenseDate, docType, abstractText, keywords,
                 subjectPrimary, subjectSecondary, subjectTertiary, docLanguage, committeeSlots,
                 committee, chairEmail, publishedMaterialFlag, publishedMaterial, embargos);
     }
static List<Integer> controllers.submit.DocumentInfo.getDegreeYears () static protected
For now, this method returns the current valid years based on the subsequent two years. This will possible move into a configuration setting eventually.
Returns
list of current valid degree years
Definition at line 549 of file DocumentInfo.java.
Referenced by controllers.submit.DocumentInfo.documentInfo(), and controllers.submit.DocumentInfo.isValidDegreeYear().
{
         Integer currentYear = Calendar.getInstance().get(Calendar.YEAR);
         List<Integer> validYears = new ArrayList<Integer>();
         validYears.add(currentYear - 3);
         validYears.add(currentYear - 2);
         validYears.add(currentYear - 1);
         validYears.add(currentYear);
         validYears.add(currentYear + 1);
         validYears.add(currentYear + 2);
         validYears.add(currentYear + 3);
         validYears.add(currentYear + 4);
         validYears.add(currentYear + 5);
         validYears.add(currentYear + 6);
         validYears.add(currentYear + 7);
         validYears.add(currentYear + 8);
         validYears.add(currentYear + 9);
         return validYears;
     }
static List<String> controllers.submit.DocumentInfo.getValidDocumentTypes (Submission sub) static protected
Returns a list of valid Document Types
Returns
list of valid document types for this submission's degree
Definition at line 575 of file DocumentInfo.java.
References org.tdl.vireo.model.Submission.getDegree().
Referenced by controllers.submit.DocumentInfo.documentInfo().
{
         List<DocumentType> validTypes = settingRepo.findAllDocumentTypes();
         // If a valid degree is set, then limit the choices to those of that same level.
         if (sub.getDegree() != null && settingRepo.findDegreeByName(sub.getDegree()) != null) {
             validTypes = settingRepo.findAllDocumentTypes(settingRepo.findDegreeByName(sub.getDegree()).getLevel());
         }
         List<String> typeNames = new ArrayList<String>();
         // Gather Document Type names, since we are soft-linking these to Submission
         for(DocumentType type : validTypes) {
             typeNames.add(type.getName());
         }
         return typeNames;
     }
static boolean controllers.submit.DocumentInfo.isValidDegreeMonth (Integer degreeMonth) static protected
Parameters
degreeMonth The month of the degree
Returns
True if the name is a valid degree month.
Definition at line 452 of file DocumentInfo.java.
References org.tdl.vireo.model.SettingsRepository.findAllGraduationMonths(), controllers.submit.AbstractSubmitStep.isFieldRequired(), and controllers.AbstractVireoController.settingRepo.
Referenced by controllers.submit.DocumentInfo.verify().
{
         if (degreeMonth == null) {
             if (isFieldRequired(GRADUATION_DATE))
                 return false;
             return true;
         }
         for (GraduationMonth month : settingRepo.findAllGraduationMonths()) {
             if (degreeMonth == month.getMonth()) {
                 return true;
             }
         }
         return false;
     }
static boolean controllers.submit.DocumentInfo.isValidDegreeYear (Integer degreeYear) static protected
Parameters
degreeYear The year of the degree
Returns
True if the name is a valid degree year.
Definition at line 472 of file DocumentInfo.java.
References controllers.submit.DocumentInfo.getDegreeYears(), and controllers.submit.AbstractSubmitStep.isFieldRequired().
Referenced by controllers.submit.DocumentInfo.verify().
{
         if (degreeYear == null) {
             if (isFieldRequired(GRADUATION_DATE))
                 return false;
             return true;
         }
         for (Integer y : getDegreeYears()) {
             if (degreeYear.equals(y)) {
                 return true;
             }
         }
         return false;
     }
static boolean controllers.submit.DocumentInfo.isValidDocType (String docType) static protected
Parameters
docType The document type.
Returns
True if the docType is a valid document type.
Definition at line 493 of file DocumentInfo.java.
References controllers.AbstractVireoController.isEmpty(), and controllers.submit.AbstractSubmitStep.isFieldRequired().
Referenced by controllers.submit.DocumentInfo.verify().
{
         if (isEmpty(docType)) {
             if (isFieldRequired(DOCUMENT_TYPE))
                 return false;
             return true;
         }
         List<DocumentType> docTypes = settingRepo.findAllDocumentTypes();
         for(DocumentType type : docTypes) {
             if(docType.equals(type.getName())) {
                 return true;
             }
         }
         return false;
     }
static boolean controllers.submit.DocumentInfo.isValidRoleType (Submission sub, List< String > roles) static protected
Determine if the provided roles are valid for this given degree level of the submission.
Parameters
sub The submission
roles The roles to validate.
Returns
True if valid, otherwise false.
Definition at line 520 of file DocumentInfo.java.
Referenced by controllers.submit.DocumentInfo.validateCommitteeMembers().
{
         List<CommitteeMemberRoleType> types = settingRepo.findAllCommitteeMemberRoleTypes(sub.getDegreeLevel());
         for (String role : roles) {
             boolean found = false;
             for (CommitteeMemberRoleType type : types) {
                 if (type.getName().equals(role)) {
                     found = true;
                     break;
                 }
             }
             if (!found)
                 return false;
         }
         return true;
     }
static List<TransientMember> controllers.submit.DocumentInfo.loadCommitteeMembers (Submission sub) static
Load committee members from the supplied submission object.
Parameters
sub The submission object
Returns
List of transient committee members.
Definition at line 601 of file DocumentInfo.java.
References org.tdl.vireo.model.Submission.getCommitteeMembers().
Referenced by controllers.submit.DocumentInfo.documentInfo(), and controllers.submit.DocumentInfo.verify().
{
         List<TransientMember> committee = new ArrayList<TransientMember>();
         for (CommitteeMember member: sub.getCommitteeMembers()) {
             TransientMember transientMember = new TransientMember(
                     member.getFirstName(),
                     member.getMiddleName(),
                     member.getLastName(),
                     member.getRoles());
             committee.add(transientMember);
         }
         return committee;
     }
static List<TransientMember> controllers.submit.DocumentInfo.parseCommitteeMembers () static
Construct the transient list for committee members from the html form parameters.
Returns
List of committee member.
Definition at line 655 of file DocumentInfo.java.
Referenced by controllers.submit.DocumentInfo.documentInfo().
{
         List<TransientMember> committee = new ArrayList<TransientMember>();
         int i = 1;
         while (params.get("committeeFirstName"+i) != null || params.get("committeeLastName"+i) != null) {
             String firstName = params.get("committeeFirstName"+i);
             String middleName = params.get("committeeMiddleName"+i);
             String lastName = params.get("committeeLastName"+i);
             String[] roles = params.get("committeeRoles"+i,String[].class);
             if (roles == null || (roles.length == 1 && roles[0].trim().length() == 0))
                 roles = new String[0];
             i++;
             if ((firstName == null  || firstName.trim().length() == 0) &&
                     (lastName == null   || lastName.trim().length() == 0))
                 // If the first or last name fields are blank then skip this one.
                 continue;
             TransientMember member = new TransientMember(
                     firstName,
                     middleName,
                     lastName,
                     roles);
             committee.add(member);
         }
         return committee;
     }
static boolean controllers.submit.DocumentInfo.saveCommitteeMembers (Submission sub, List< TransientMember > members) static
Save the transient list of committee members into the submission object.
Parameters
sub The submission object to be modified.
members The new list of committee members.
Definition at line 697 of file DocumentInfo.java.
References org.tdl.vireo.model.Submission.getCommitteeMembers().
Referenced by controllers.submit.DocumentInfo.documentInfo().
{
         for (CommitteeMember member : new ArrayList<CommitteeMember>(sub.getCommitteeMembers())) {
             member.delete();
         }
         int i = 1;
         for (TransientMember member : members) {
             String firstName = member.firstName;
             String middleName = member.middleName;
             String lastName = member.lastName;
             List<String> roles = member.roles;
             // Make sure that we have a first or last name
             if (firstName != null && firstName.trim().length() == 0)
                 firstName = null;
             if (lastName != null && lastName.trim().length() == 0)
                 lastName = null;
             if (firstName == null && lastName == null)
                 continue;
             CommitteeMember newMember = sub.addCommitteeMember(firstName, lastName, middleName).save();
             newMember.setDisplayOrder(i);
             for (String role : roles) {
                 newMember.addRole(role);
             }
             newMember.save();
             i++;
         }
         return true;
     }
static boolean controllers.submit.DocumentInfo.validateCommitteeMembers (Submission sub, List< TransientMember > members) static
Validate the transient list for committee members. This method checks that all members have their first and last names
Parameters
members List of maps for each committee member.
Definition at line 625 of file DocumentInfo.java.
References controllers.AbstractVireoController.isEmpty(), and controllers.submit.DocumentInfo.isValidRoleType().
Referenced by controllers.submit.DocumentInfo.verify().
{
         boolean atLeastOneMember = false;
         int i = 1;
         for (TransientMember member : members) {
             // Check that if we have a first name, then we have a last name.
             if (isEmpty(member.firstName) && isEmpty(member.lastName)) {
                 validation.addError("member"+i,"Please provide a first or last name for all committee members.");
             } else {
                 atLeastOneMember = true;
             }
             // roles
             if (!isValidRoleType(sub, member.roles))
                 validation.addError("member"+i,"One of the roles selected is invalid");
         }
         if (!atLeastOneMember)
             validation.addError("committee", "You must specify who is on your committee.");
         return true;
     }
static boolean controllers.submit.DocumentInfo.verify (Submission sub) static
Verify that all the document information is correct. This will be accessed from two places, the document info page as well as the confirmation page.
Returns
True if there are no errors found, otherwise false.
Definition at line 348 of file DocumentInfo.java.
References org.tdl.vireo.proquest.ProquestVocabularyRepository.findSubjectByDescription(), org.tdl.vireo.model.Submission.getCommitteeContactEmail(), org.tdl.vireo.model.Submission.getDefenseDate(), org.tdl.vireo.model.Submission.getDocumentAbstract(), org.tdl.vireo.model.Submission.getDocumentKeywords(), org.tdl.vireo.model.Submission.getDocumentLanguage(), org.tdl.vireo.model.Submission.getDocumentSubjects(), org.tdl.vireo.model.Submission.getDocumentTitle(), org.tdl.vireo.model.Submission.getDocumentType(), org.tdl.vireo.model.Submission.getGraduationMonth(), org.tdl.vireo.model.Submission.getGraduationYear(), org.tdl.vireo.model.Submission.getPublishedMaterial(), controllers.AbstractVireoController.isEmpty(), controllers.submit.AbstractSubmitStep.isFieldEnabled(), controllers.submit.AbstractSubmitStep.isFieldRequired(), controllers.submit.DocumentInfo.isValidDegreeMonth(), controllers.submit.DocumentInfo.isValidDegreeYear(), controllers.submit.DocumentInfo.isValidDocType(), controllers.submit.DocumentInfo.loadCommitteeMembers(), controllers.AbstractVireoController.proquestRepo, and controllers.submit.DocumentInfo.validateCommitteeMembers().
Referenced by controllers.submit.Confirm.confirm(), and controllers.submit.DocumentInfo.documentInfo().
{
         int numberOfErrorsBefore = validation.errors().size();
         // Document Title
         if(isFieldRequired(DOCUMENT_TITLE) && isEmpty(sub.getDocumentTitle()))
             validation.addError("title", "Please enter a thesis title");
         // Graduation Date (month & year)
         if (!isValidDegreeMonth(sub.getGraduationMonth()))
             validation.addError("degreeMonth", "Please select a degree month");
         if (!isValidDegreeYear(sub.getGraduationYear()))
             validation.addError("degreeYear", "Please select a degree year");
         // Defense Date
         Date now = new Date();
         Date min = new Date(-2208967200000L);
         Date max = new Date(now.getTime() + (365 * 24 * 60 * 60 * 1000L));
         DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
         if (isFieldRequired(DEFENSE_DATE) && (sub.getDefenseDate()==null))
             validation.addError("defenseDate", "Please enter a defense date");
         else if(sub.getDefenseDate()!=null && (!sub.getDefenseDate().after(min) || !sub.getDefenseDate().before(max)))
             validation.addError("defenseDate", "Please enter a defense date between "+formatter.format(min)+" and "+formatter.format(max));
         // Document Type
         if (!isValidDocType(sub.getDocumentType()))
             validation.addError("docType", "Please select a Document Type");
         // Document Abstract
         if (isFieldRequired(DOCUMENT_ABSTRACT) && isEmpty(sub.getDocumentAbstract()))
             validation.addError("abstractText", "Please enter an abstract");
         // Document Keywords
         if (isFieldRequired(DOCUMENT_KEYWORDS) && isEmpty(sub.getDocumentKeywords()))
             validation.addError("keywords", "Please enter at least one keyword");
         // Document Subjects
         if (isFieldEnabled(DOCUMENT_SUBJECTS)) {
             for (String subject : sub.getDocumentSubjects()) {
                 if (proquestRepo.findSubjectByDescription(subject) == null) {
                     validation.addError("subjects", "One of the selected subjects is invalid");
                 }
             }
             if (isFieldRequired(DOCUMENT_SUBJECTS) && sub.getDocumentSubjects().size() == 0) {
                 validation.addError("subjects", "Please provide atleast a primary subject.");
             }
         }
         // Language
         if (isFieldRequired(DOCUMENT_LANGUAGE) && isEmpty(sub.getDocumentLanguage()))
             validation.addError("language", "Please select a language.");
         // Committee members (make sure they aren't any double entries)
         if (isFieldRequired(COMMITTEE) && !validation.hasError("committee")) {
             List<TransientMember> committee = loadCommitteeMembers(sub);
             validateCommitteeMembers(sub,committee);
         }
         // Committee Contact Email
         if (isFieldRequired(COMMITTEE_CONTACT_EMAIL) && isEmpty(sub.getCommitteeContactEmail())) {
             validation.addError("chairEmail", "Please enter an email address for the committee chair");
         } else if (isFieldEnabled(COMMITTEE_CONTACT_EMAIL) && !isEmpty(sub.getCommitteeContactEmail())) {
             try {
                 new InternetAddress(sub.getCommitteeContactEmail()).validate();
             } catch (AddressException e) {
                 validation.addError("chairEmail","The committee chair email address '"+sub.getCommitteeContactEmail()+"' you provided is invalid.");
             }
         }
         // Previously Published
         if (isFieldEnabled(PUBLISHED_MATERIAL)) {
             if (sub.getPublishedMaterial() != null && sub.getPublishedMaterial().trim().length() == 0) {
                 validation.addError("publishedMaterial", "If the any material being submitted has been previously published then you must identify the material which was published. (i.e. the section or chapter).");
             }
         }
         // Embargo
         for(EmbargoGuarantor eg : EmbargoGuarantor.values()) {
             String fieldName = eg.name().equals("DEFAULT") ? "EMBARGO_TYPE" : "EMBARGO_TYPE_"+eg.name();
             FieldConfig field = FieldConfig.valueOf(fieldName);
             if (isFieldRequired(field) && sub.getEmbargoTypeByGuarantor(eg) == null)
                 validation.addError("embargo-"+eg.name(), "Please choose a "+eg.name().toLowerCase()+" embargo option");
         }
         // Check if we've added any new errors. If so return false;
         if (numberOfErrorsBefore == validation.errors().size())
             return true;
         else
             return false;
     }
The documentation for this class was generated from the following file:
app/controllers/submit/DocumentInfo.java