Vireo: controllers.submit.FileUpload Class Reference
controllers.submit.FileUpload Class Reference
Static Public Member Functions
static void fileUpload (Long subId)
static boolean verify (Submission sub)
Static Public Member Functions inherited from controllers.AbstractVireoController
static void injectRepositories ()
static void checkForFirstUser ()
static void handleError (Throwable throwable)
Additional Inherited Members
Static Public Attributes inherited from controllers.AbstractVireoController
static SecurityContext context = Spring.getBeanOfType(SecurityContext.class)
static PersonRepository personRepo = Spring.getBeanOfType(PersonRepository.class)
static SubmissionRepository subRepo = Spring.getBeanOfType(SubmissionRepository.class)
static SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class)
static ProquestVocabularyRepository proquestRepo = Spring.getBeanOfType(ProquestVocabularyRepository.class)
static ErrorLog errorLog = Spring.getBeanOfType(ErrorLog.class)
static StateManager stateManager = Spring.getBeanOfType(StateManager.class)
static Indexer indexer = Spring.getBeanOfType(Indexer.class)
static Searcher searcher = Spring.getBeanOfType(Searcher.class)
static Boolean firstUser = null
Static Protected Member Functions inherited from controllers.submit.AbstractSubmitStep
static Submission getSubmission ()
static boolean isFieldEnabled (FieldConfig field)
static boolean isFieldRequired (FieldConfig field)
Static Protected Member Functions inherited from controllers.AbstractVireoController
static boolean isEmpty (String value)
static boolean isNotEmpty (String value)
static String escapeJavaScript (String value)
static String URIEncode (String value)
static String toJSON (String[] values)
static String text2html (String value)
static boolean isFieldRequired (FieldConfig field)
Static Package Functions inherited from controllers.submit.AbstractSubmitStep
static void beforeSubmit ()
Detailed Description
The fourth step of the submission process where students upload their files. This step is pretty straight forward, the only tricky thing is that we make sure the uploaded file is a pdf. Other than that pretty much anything goes.
Author
Scott Phillips
Bill Ingram
Dan Galewsky
Definition at line 35 of file FileUpload.java.
Member Function Documentation
static void controllers.submit.FileUpload.fileUpload (Long subId) static
The fourth step of the submission process where students upload their files. We will always take the primary and supplementary file uploads no matter what button was clicked.
Parameters
subId The id of the submission.
Definition at line 46 of file FileUpload.java.
References org.tdl.vireo.model.AttachmentType.ADMINISTRATIVE, controllers.submit.AbstractSubmitStep.getSubmission(), controllers.submit.AbstractSubmitStep.isFieldEnabled(), controllers.Student.removeAdditional(), org.tdl.vireo.model.AttachmentType.SOURCE, org.tdl.vireo.model.AttachmentType.SUPPLEMENTAL, controllers.Student.uploadPrimaryDocument(), and controllers.submit.FileUpload.verify().
{
         // Locate the submission that this upload will be attached to
         Submission sub = getSubmission();
         // Upload or replace the primary document.
         if (isFieldEnabled(PRIMARY_ATTACHMENT)) {
             if (params.get("replacePrimary") != null) {
                 Attachment primaryDoc = sub.getPrimaryDocument();
                 if (primaryDoc != null) {
                     primaryDoc.delete();
                     sub.save();
                 }
             }
             if(params.get("primaryDocument",File.class) != null)
                 Student.uploadPrimaryDocument(sub);
         }
         // Manage additional files
         if (isFieldEnabled(SUPPLEMENTAL_ATTACHMENT) || isFieldEnabled(SOURCE_ATTACHMENT) || isFieldEnabled(ADMINISTRATIVE_ATTACHMENT)) {
             if (params.get("removeAdditional") != null)
                 Student.removeAdditional(sub);
             if(params.get("additionalDocument",File.class) != null) {
                 if(params.get("attachmentType").isEmpty())
                     validation.addError("attachmentType", "You must select an attachment type.");
                 else
                     Student.uploadAdditional(sub);
             }
         }
         // Verify the form if we are submitting or if jumping from the confirm step.
         if ("fileUpload".equals(params.get("step")) ||
             "confirm".equals(flash.get("from-step"))) {
             verify(sub);
         }
         // 'Save And Continue' button was clicked
         if (params.get("submit_next") != null && !validation.hasErrors()) {
             Confirm.confirm(subId);
         }
         // Initialize variables and display form
         Attachment primaryAttachment = sub.getPrimaryDocument();
         List<Attachment> additionalAttachments = sub.getAttachmentsByType(AttachmentType.SUPPLEMENTAL,AttachmentType.SOURCE,AttachmentType.ADMINISTRATIVE);
         List<String> stickies = new ArrayList<String>();
         String stickiesRaw = settingRepo.getConfigValue(SUBMIT_UPLOAD_FILES_STICKIES);
         if (stickiesRaw != null && !"null".equals(stickiesRaw)) {
             try {
                 CSVReader reader = new CSVReader(new StringReader(stickiesRaw));
                 stickies = Arrays.asList(reader.readNext());
                 reader.close();
             } catch (IOException ioe) {
                 throw new RuntimeException(ioe);
             }
         }
         List<String> attachmentTypes = new ArrayList<String>();
         for(AttachmentType type : AttachmentType.values()){
             attachmentTypes.add(type.toString());
         }
         renderTemplate("Submit/fileUpload.html",subId, primaryAttachment, additionalAttachments, attachmentTypes, stickies);
     }
static boolean controllers.submit.FileUpload.verify (Submission sub) static
Verify that the user has supplied a primary document. This will be used from both the fileUpload form and the confirmation page.
Returns
True if the primary document exists, otherwise false.
Definition at line 119 of file FileUpload.java.
References org.tdl.vireo.model.AttachmentType.ADMINISTRATIVE, org.tdl.vireo.model.Submission.getAttachments(), org.tdl.vireo.model.Submission.getAttachmentsByType(), org.tdl.vireo.model.Submission.getPrimaryDocument(), controllers.submit.AbstractSubmitStep.isFieldRequired(), org.tdl.vireo.model.AttachmentType.SOURCE, and org.tdl.vireo.model.AttachmentType.SUPPLEMENTAL.
Referenced by controllers.submit.Confirm.confirm(), and controllers.submit.FileUpload.fileUpload().
{
         int numberOfErrorsBefore = validation.errors().size();
         if (isFieldRequired(PRIMARY_ATTACHMENT) && sub.getPrimaryDocument() == null )
             validation.addError("primaryDocument", "A manuscript file must be uploaded.");
         if (isFieldRequired(SUPPLEMENTAL_ATTACHMENT) &&
                 sub.getAttachmentsByType(AttachmentType.SUPPLEMENTAL).size() == 0)
             validation.addError("supplementalDocument", "At least one supplemental file is required.");
         if (isFieldRequired(SOURCE_ATTACHMENT) &&
                 sub.getAttachmentsByType(AttachmentType.SOURCE).size() == 0)
             validation.addError("sourceDocument", "At least one source file is required.");
         if (isFieldRequired(ADMINISTRATIVE_ATTACHMENT) &&
                 sub.getAttachmentsByType(AttachmentType.ADMINISTRATIVE).size() == 0)
             validation.addError("administrativeDocument", "At least one administrative file is required.");
         // file size validation
         boolean validateFileSize = false;
         validateFileSize = Play.configuration.getProperty("fileSize.validate", "false").equals("true");
         if (validateFileSize) {
             // NOTE: this information is also expressed in a sticky note on the page.
             // As this cannot easily be generated from the same source,
             // it will need to be kept in sync manually.
             int maxFileSize = 512; // default, in MB
             try {
                 maxFileSize = Integer.parseInt(Play.configuration.getProperty("fileSize.maxFileSize"));
             } catch (Exception e) {
                 // just keep the default
                 String err = e.getMessage();
             }
             int maxFileSizeTotal = 4096; // default, in MB
             try {
                 maxFileSizeTotal = Integer.parseInt(Play.configuration.getProperty("fileSize.maxFileSizeTotal"));
             } catch (Exception e) {
                 // just keep the default
                 String err = e.getMessage();
             }
             long fileSizeTotal = 0;
             for (Attachment a : sub.getAttachments()) {
                 // get file size and convert to k
                 long fileSizeInBytes = a.getSize();
                 long fileSizeInMB = (fileSizeInBytes / 1024) / 1024;
                 if (fileSizeInMB > maxFileSize) {
                     validation.addError("fileSize", "No individual file may exceed " + maxFileSize + " MB.");
                 }
                 fileSizeTotal += fileSizeInMB;
             }
             if (fileSizeTotal > maxFileSizeTotal) {
                 validation.addError("fileSizeTotal", "The total of all files must not exceed " + maxFileSizeTotal + " MB (" + maxFileSizeTotal / 1024 + " GB).");
             }
         }
         if (numberOfErrorsBefore == validation.errors().size())
             return true;
         else
             return false;
     }
The documentation for this class was generated from the following file:
app/controllers/submit/FileUpload.java