Vireo: org.tdl.vireo.export.impl.Sword1DepositorImpl Class Reference
org.tdl.vireo.export.impl.Sword1DepositorImpl Class Reference
Public Member Functions
String getBeanName ()
void setBeanName (String beanName)
String getDisplayName ()
void setDisplayName (String displayName)
Map< String, String > getCollections (DepositLocation location)
String getCollectionName (DepositLocation location, String collection)
String deposit (DepositLocation location, ExportPackage exportPackage)
Protected Member Functions
Sword1DepositorImpl ()
Static Protected Member Functions
static void zipPackage (File zipFile, File dirFile) throws IOException
static void zipDirectory (String baseName, File directory, ZipOutputStream zos) throws IOException
Private Attributes
String beanName
String displayName
final String USER_AGENT = "Vireo Sword 1.0 Depositor"
Detailed Description
Sword, version 1, depositor. This supports identifying collections from the service document and depositing them into the repository.
Author
Scott Phillips
Definition at line 39 of file Sword1DepositorImpl.java.
Constructor & Destructor Documentation
org.tdl.vireo.export.impl.Sword1DepositorImpl.Sword1DepositorImpl () protected
Definition at line 50 of file Sword1DepositorImpl.java.
{
     }
Member Function Documentation
String org.tdl.vireo.export.impl.Sword1DepositorImpl.deposit (DepositLocation location, ExportPackage exportPackage)
Deposit the package into the remote location. The resulting depositID assigned by the location should be returned.
Parameters
location The deposit location, a repository and collection. If all values are not assigned then an IllegalArgument exception will be thrown.
exportPackage The package to be deposited.
Returns
The depositID
Exceptions
DepositException
Implements org.tdl.vireo.export.Depositor.
Definition at line 166 of file Sword1DepositorImpl.java.
References org.tdl.vireo.export.DepositException.FIELD.AUTHENTICATION, org.tdl.vireo.model.DepositLocation.getCollection(), org.tdl.vireo.export.ExportPackage.getFile(), org.tdl.vireo.model.DepositLocation.getOnBehalfOf(), org.tdl.vireo.model.DepositLocation.getPassword(), org.tdl.vireo.model.DepositLocation.getRepository(), org.tdl.vireo.model.DepositLocation.getUsername(), org.tdl.vireo.export.DepositException.FIELD.OTHER, org.tdl.vireo.export.DepositException.FIELD.REPOSITORY, org.tdl.vireo.export.impl.Sword1DepositorImpl.USER_AGENT, and org.tdl.vireo.export.impl.Sword1DepositorImpl.zipPackage().
{
         boolean zippedExport = false;
         File exportFile = null;
         try {
             // Check our input
             if (location == null)
                 throw new IllegalArgumentException("The deposit location is required.");
             if (exportPackage == null)
                 throw new IllegalArgumentException("The deposit package is required.");
             if ( exportPackage.getFile() == null ||  !exportPackage.getFile().exists())
                 throw new IllegalArgumentException("The deposit package does not exist on disk or is inaccessable.");
             if (location.getRepository() == null)
                 throw new IllegalArgumentException("The deposit location must have a repository URL defined.");
             if (location.getCollection() == null)
                 throw new IllegalArgumentException("The deposit location must have a collection URL defined.");
             URL repositoryURL = new URL(location.getRepository());
             // Check the package
             exportFile = exportPackage.getFile();
             String exportMimeType = exportPackage.getMimeType();
             // If we are given a directory, zip it up because sword requires one file submissions.
             if (exportFile.isDirectory()) {
                 File zipFile = File.createTempFile(exportFile.getName()+"-", ".zip");
                 zipPackage(zipFile, exportFile);
                 exportFile = zipFile;
                 exportMimeType = "application/zip";
                 zippedExport = true;
             }
             //Building the client
             Client client = new Client();
             client.setServer(
                     repositoryURL.getHost(),
                     repositoryURL.getPort());
             client.setUserAgent(USER_AGENT);
             //If the credentials include a username and password, set those on the client.
             if (location.getUsername() != null && location.getPassword() != null)
                 client.setCredentials(location.getUsername(), location.getPassword());
             PostMessage message = new PostMessage();
             message.setFilepath(exportFile.getAbsolutePath());
             message.setDestination(location.getCollection());
             message.setFiletype(exportMimeType);
             message.setUseMD5(false);
             message.setVerbose(false);
             message.setNoOp(false);
             message.setFormatNamespace(exportPackage.getFormat());
             message.setSlug("");
             message.setChecksumError(false);
             message.setUserAgent(USER_AGENT);
             if (location.getOnBehalfOf() != null)
                 message.setOnBehalfOf(location.getOnBehalfOf());
             DepositResponse response = client.postFile(message);
             if (response.getHttpResponse() < 200 || response.getHttpResponse() > 204 )
                 throw new RuntimeException("Sword server responed with a non success HTTP status code: "+response.getHttpResponse());
             String depositId = response.getEntry().getId();
             if (depositId == null)
                 throw new RuntimeException("Sword server failed to return a deposit id.");
             return depositId;
         } catch (MalformedURLException murle) {
             Logger.error(murle,"Unable to deposit()");
             throw new DepositException(FIELD.REPOSITORY,"The repository is an invalid URL",murle);
         } catch(SWORDClientException sce) {
             Logger.error(sce,"Unable to deposit()");
             FIELD field = FIELD.OTHER;
             String message = sce.getMessage();
             if (sce.getMessage().contains("Code: 401")) {
                 field = FIELD.AUTHENTICATION;
                 message = "Unauthorized credentials";
             } else if (sce.getMessage().contains("Code: 404")) {
                 field = FIELD.REPOSITORY;
                 message = "Repository URL not found";
             } else if (sce.getMessage().contains("Connection refused")) {
                 field = FIELD.REPOSITORY;
                 message = "Connection refused";
             } else if (sce.getMessage().contains("Unable to parse the XML")) {
                 field = FIELD.REPOSITORY;
                 message = "The repository does not appear to be a valid SWORD server.";
             }
             throw new DepositException(field, message, sce);
         } catch (IOException ioe) {
             Logger.error(ioe, "Unable to deposit()");
             throw new DepositException(FIELD.OTHER,ioe.getMessage(),ioe);
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to deposit()");
             throw new DepositException(FIELD.OTHER, re.getMessage(), re);
         } finally {
             // If we created a zip file make sure it gets cleaned up.
             if (zippedExport && exportFile != null)
                 exportFile.delete();
         }
     }
String org.tdl.vireo.export.impl.Sword1DepositorImpl.getBeanName ()
Returns
The technical spring bean name of this depositor implementation.
Implements org.tdl.vireo.export.Depositor.
Definition at line 55 of file Sword1DepositorImpl.java.
References org.tdl.vireo.export.impl.Sword1DepositorImpl.beanName.
{
         return beanName;
     }
String org.tdl.vireo.export.impl.Sword1DepositorImpl.getCollectionName (DepositLocation location, String collection)
Resolve the collection identifier into a displayable name for the collection.
Parameters
location The deposit location.
collection The collection identifier to resolve.
Returns
The displayable name of the collection.
Exceptions
DepositException
Implements org.tdl.vireo.export.Depositor.
Definition at line 155 of file Sword1DepositorImpl.java.
{
         Map<String, String> namesToCollections = this.getCollections(location);
         for( String name : namesToCollections.keySet())
         {
             if(namesToCollections.get(name).equals(collection))
                 return name;
         }
         return null;
     }
Map<String, String> org.tdl.vireo.export.impl.Sword1DepositorImpl.getCollections (DepositLocation location)
Retrieve a map of collection names, and their technical identifier.
Parameters
location The repository location.
Returns
A map of collection names & internal identifiers.
Exceptions
DepositException
Implements org.tdl.vireo.export.Depositor.
Definition at line 76 of file Sword1DepositorImpl.java.
References org.tdl.vireo.export.DepositException.FIELD.AUTHENTICATION, org.tdl.vireo.model.DepositLocation.getOnBehalfOf(), org.tdl.vireo.model.DepositLocation.getPassword(), org.tdl.vireo.model.DepositLocation.getRepository(), org.tdl.vireo.model.DepositLocation.getUsername(), org.tdl.vireo.export.DepositException.FIELD.OTHER, org.tdl.vireo.export.DepositException.FIELD.REPOSITORY, and org.tdl.vireo.export.impl.Sword1DepositorImpl.USER_AGENT.
{
         try {
             Map<String, String> foundCollections = new HashMap<String, String>();
             if(location == null || location.getRepository() == null)
                 throw new IllegalArgumentException("Bad deposit location or repository URL when trying to getCollections()");
             URL repositoryURL = new URL(location.getRepository());
             //Building the client
             Client client = new Client();
             client.setServer(repositoryURL.getHost(), repositoryURL.getPort());
             client.setUserAgent(USER_AGENT);
             //If the credentials include a username and password, set those on the client.
             if(location.getUsername() != null && location.getPassword() != null)
                 client.setCredentials(location.getUsername(), location.getPassword());
             //Obtaining the service document
             //If the credentials contain an onbehalfof user, retrieve the service document on behalf of that user.  Otherwise, simply retrieve the service document.
             ServiceDocument serviceDocument = null;
             try {
                 if(location.getOnBehalfOf() != null)
                 {
                     serviceDocument = client.getServiceDocument(location.getRepository(), location.getOnBehalfOf());
                 }
                 else
                 {
                     serviceDocument = client.getServiceDocument(location.getRepository());
                 }
             } catch (SWORDClientException e) {
                 throw new RuntimeException(e);
             }
             //Getting the service from the service document
             Service service = serviceDocument.getService();
             //Building the map of collections from the service
             for(Workspace workspace : service.getWorkspacesList())
             {
                 for(Collection collection : workspace.getCollections())
                 {
                     foundCollections.put(collection.getTitle(), collection.getLocation());
                 }
             }
             return foundCollections;
         } catch (MalformedURLException murle) {
             throw new DepositException(FIELD.REPOSITORY,"The repository is an invalid URL",murle);
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to getCollections()");
             FIELD field = FIELD.OTHER;
             String message = re.getMessage();
             if (re.getMessage().contains("Code: 401")) {
                 field = FIELD.AUTHENTICATION;
                 message = "Unauthorized credentials";
             } else if (re.getMessage().contains("Code: 404")) {
                 field = FIELD.REPOSITORY;
                 message = "Repository URL not found";
             } else if (re.getMessage().contains("Connection refused")) {
                 field = FIELD.REPOSITORY;
                 message = "Connection refused";
             } else if (re.getMessage().contains("Unable to parse the XML")) {
                 field = FIELD.REPOSITORY;
                 message = "The repository does not appear to be a valid SWORD server.";
             }
             throw new DepositException(field, message, re);
         }
     }
String org.tdl.vireo.export.impl.Sword1DepositorImpl.getDisplayName ()
Returns
The displayable name of this bean.
Implements org.tdl.vireo.export.Depositor.
Definition at line 66 of file Sword1DepositorImpl.java.
References org.tdl.vireo.export.impl.Sword1DepositorImpl.displayName.
{
         return displayName;
     }
void org.tdl.vireo.export.impl.Sword1DepositorImpl.setBeanName (String beanName)
Definition at line 60 of file Sword1DepositorImpl.java.
References org.tdl.vireo.export.impl.Sword1DepositorImpl.beanName.
{
         this.beanName = beanName;
     }
void org.tdl.vireo.export.impl.Sword1DepositorImpl.setDisplayName (String displayName)
Definition at line 70 of file Sword1DepositorImpl.java.
References org.tdl.vireo.export.impl.Sword1DepositorImpl.displayName.
{
         this.displayName = displayName;
     }
static void org.tdl.vireo.export.impl.Sword1DepositorImpl.zipDirectory (String baseName, File directory, ZipOutputStream zos) throws IOException static protected
Internal recursive method for zipping the files and sub-directories of a file into a single deposit package.
Parameters
baseName The base name to pre-pend to file names in the zip archive.
directory The directory to process.
zos The zip output stream.
Definition at line 323 of file Sword1DepositorImpl.java.
Referenced by org.tdl.vireo.export.impl.Sword1DepositorImpl.zipPackage().
     {
         // Add all the files
         File[] files = directory.listFiles();
         for (File file : files) {
             if (file.isDirectory()) {
                 zipDirectory(baseName + directory.getName() + File.separator, file, zos);
             } else {
                 InputStream is = new BufferedInputStream(new FileInputStream(file));
                 zos.putNextEntry(new ZipEntry(baseName + file.getName()));
                 byte[] buf = new byte[1024];
                 int len;
                 while ((len = is.read(buf)) > 0) {
                     zos.write(buf, 0, len);
                 }
                 is.close();
                 zos.closeEntry();
             }
         }
     }
static void org.tdl.vireo.export.impl.Sword1DepositorImpl.zipPackage (File zipFile, File dirFile) throws IOException static protected
Internal method for ziping a directory together into a single deposit package.
One tricky note, the file name of the directory is not included in the resulting zip.
Parameters
zipFile The file where the zip will be created.
dirFile The source directory.
Definition at line 298 of file Sword1DepositorImpl.java.
References org.tdl.vireo.export.impl.Sword1DepositorImpl.zipDirectory().
Referenced by org.tdl.vireo.export.impl.Sword1DepositorImpl.deposit().
{
         // The result is a directory, so we need to zip the directory up.
         FileOutputStream fos = new FileOutputStream(zipFile);
         ZipOutputStream zos  = new ZipOutputStream(fos);
         byte[] buffer = new byte[1024];
         int bufferLength;
         zipDirectory("",dirFile,zos);
         zos.close();
     }
Member Data Documentation
String org.tdl.vireo.export.impl.Sword1DepositorImpl.beanName private
The basic identity parameters for this service. All of these parameters will be injected from Spring
Definition at line 45 of file Sword1DepositorImpl.java.
Referenced by org.tdl.vireo.export.impl.Sword1DepositorImpl.getBeanName(), and org.tdl.vireo.export.impl.Sword1DepositorImpl.setBeanName().
String org.tdl.vireo.export.impl.Sword1DepositorImpl.displayName private
Definition at line 46 of file Sword1DepositorImpl.java.
Referenced by org.tdl.vireo.export.impl.Sword1DepositorImpl.getDisplayName(), and org.tdl.vireo.export.impl.Sword1DepositorImpl.setDisplayName().
final String org.tdl.vireo.export.impl.Sword1DepositorImpl.USER_AGENT = "Vireo Sword 1.0 Depositor" private
Definition at line 47 of file Sword1DepositorImpl.java.
Referenced by org.tdl.vireo.export.impl.Sword1DepositorImpl.deposit(), and org.tdl.vireo.export.impl.Sword1DepositorImpl.getCollections().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/export/impl/Sword1DepositorImpl.java