Vireo: org.tdl.vireo.email.impl.VireoEmailImpl Class Reference
org.tdl.vireo.email.impl.VireoEmailImpl Class Reference
Public Member Functions
List< InternetAddress > getTo ()
void addTo (String email)
void addTo (String email, String name)
void addTo (Person person)
void addTo (InternetAddress address)
List< InternetAddress > getCc ()
void addCc (String email)
void addCc (String email, String name)
void addCc (Person person)
void addCc (InternetAddress address)
List< InternetAddress > getBcc ()
void addBcc (String email)
void addBcc (String email, String name)
void addBcc (Person person)
void addBcc (InternetAddress address)
InternetAddress getReplyTo ()
void setReplyTo (String email)
void setReplyTo (String email, String name)
void setReplyTo (Person person)
void setReplyTo (InternetAddress address)
InternetAddress getFrom ()
void setFrom (String email)
String getSubject ()
void setSubject (String subject)
String getMessage ()
void setMessage (String message)
void setTemplate (EmailTemplate template)
Map< String, String > getParameters ()
void addParameter (String name, String value)
void addParameters (Submission sub)
void applyParameterSubstitution ()
Person getLogPerson ()
Submission getLogSubmission ()
void setLogOnCompletion (Person person, Submission submission)
String getSuccessLogMessage ()
void setSuccessLogMessage (String message)
String getFailureLogMessage (String reason)
void setFailureLogMessage (String message)
Public Attributes
SettingsRepository settingRepo
PersonRepository personRepo
SubmissionRepository subRepo
List< InternetAddress > to = new ArrayList<InternetAddress>()
List< InternetAddress > cc = new ArrayList<InternetAddress>()
List< InternetAddress > bcc = new ArrayList<InternetAddress>()
InternetAddress _replyTo
InternetAddress _from
String subject
String message
Map< String, String > parameters = new HashMap<String, String>()
Long logPersonId
Long logSubmissionId
String logSuccessMessage
String logFailureMessage
Protected Member Functions
VireoEmailImpl (SecurityContext context, PersonRepository personRepo, SubmissionRepository subRepo, SettingsRepository settingRepo)
Private Member Functions
void setFrom (String email, String name)
void setFrom (Person person)
void setFrom (InternetAddress address)
InternetAddress createAddress (String email, String name)
InternetAddress createAddress (Person person)
InternetAddress validateAddress (InternetAddress address)
Detailed Description
Implementation of the vireo email object.
Author
Scott Phillips
Definition at line 35 of file VireoEmailImpl.java.
Constructor & Destructor Documentation
org.tdl.vireo.email.impl.VireoEmailImpl.VireoEmailImpl (SecurityContext context, PersonRepository personRepo, SubmissionRepository subRepo, SettingsRepository settingRepo) protected
Construct a new vireo email impl. This should only be called by spring.
Parameters
context The security context.
personRepo The person repository.
subRepo The submisison repository.
Definition at line 70 of file VireoEmailImpl.java.
References org.tdl.vireo.constant.AppPref.CC_EMAILS, org.tdl.vireo.constant.AppConfig.EMAIL_FROM, org.tdl.vireo.constant.AppConfig.EMAIL_REPLY_TO, org.tdl.vireo.model.Person.getCurrentEmailAddress(), org.tdl.vireo.model.Person.getPreference(), org.tdl.vireo.model.NameFormat.LAST_FIRST, org.tdl.vireo.email.impl.VireoEmailImpl.personRepo, org.tdl.vireo.email.impl.VireoEmailImpl.settingRepo, and org.tdl.vireo.email.impl.VireoEmailImpl.subRepo.
{
         this.settingRepo = settingRepo;
         this.personRepo = personRepo;
         this.subRepo = subRepo;
         // Set the default from address
         this.setFrom(settingRepo.getConfigValue(AppConfig.EMAIL_FROM));
         this.setReplyTo(settingRepo.getConfigValue(AppConfig.EMAIL_REPLY_TO));
         // Check to see if the current person want's to be CC'ed
         Person person = context.getPerson();
         if (person != null && person.getPreference(AppPref.CC_EMAILS) != null) {
             String email = person.getEmail();
             if (person.getCurrentEmailAddress() != null)
                 email = person.getCurrentEmailAddress();
             this.addCc(email,person.getFormattedName(NameFormat.LAST_FIRST));
         }
     }
Member Function Documentation
void org.tdl.vireo.email.impl.VireoEmailImpl.addBcc (String email)
Add a new Blind Carbon Copy recipient.
Parameters
email An email address
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 147 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.addBcc().
{
         addBcc(email, null);
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.addBcc (String email, String name)
Add a new Blind Carbon Copy recipient.
Parameters
email An email address.
name A descriptive name
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 152 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.addBcc(), and org.tdl.vireo.email.impl.VireoEmailImpl.createAddress().
{
         addBcc(createAddress(email, name));
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.addBcc (Person person)
Add a new Carbon Copy recipient
Parameters
person The person object.
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 157 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.addBcc(), and org.tdl.vireo.email.impl.VireoEmailImpl.createAddress().
{
         addBcc(createAddress(person));
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.addBcc (InternetAddress address)
Add a new Blind Carbon Copy recipient
Parameters
address The address
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 162 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.validateAddress().
{
         bcc.add(validateAddress(address));
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.addCc (String email)
Add a new Carbon Copy recipient.
Parameters
email An email address
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 122 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.addCc().
{
         addCc(email, null);
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.addCc (String email, String name)
Add a new Carbon Copy recipient.
Parameters
email An email address
name A descriptive name
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 127 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.addCc(), and org.tdl.vireo.email.impl.VireoEmailImpl.createAddress().
{
         addCc(createAddress(email, name));
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.addCc (Person person)
Add a new Carbon Copy recipient
Parameters
person The person object.
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 132 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.addCc(), and org.tdl.vireo.email.impl.VireoEmailImpl.createAddress().
{
         addCc(createAddress(person));
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.addCc (InternetAddress address)
Add a new Carbon Copy recipient.
Parameters
address The address
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 137 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.validateAddress().
{
         cc.add(validateAddress(address));
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.addParameter (String name, String value)
Add a new parameter substitutions
Parameters
name The name of the new parameter. In the message or body this needs to be encoded as "{name}" for the value to be substituted.
value The value of the substitution.
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 278 of file VireoEmailImpl.java.
{
         parameters.put(name,value);
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.addParameters (Submission submission)
Add the set of predefined parameters based upon the value of the submission. These are:
FULL_NAME FIRST_NAME LAST_NAME DOCUMENT_TITLE GRAD_SEMESTER SUBMISSION_STATUS SUBMISSION_STATUS_ASSIGNED_TO
Parameters
submission The submission
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 283 of file VireoEmailImpl.java.
{
         this.parameters = StringVariableReplacement.setParameters(sub);
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.addTo (String email)
Add a new "To" recipient.
Parameters
email An email address
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 97 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.addTo().
{
         addTo(email, null);
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.addTo (String email, String name)
Add a new "To" recipient.
Parameters
email An email address
name A descriptive name
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 102 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.addTo(), and org.tdl.vireo.email.impl.VireoEmailImpl.createAddress().
{
         addTo(createAddress(email, name));
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.addTo (Person person)
Add a new "To" recipient
Parameters
person The person object.
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 107 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.addTo(), and org.tdl.vireo.email.impl.VireoEmailImpl.createAddress().
{
         addTo(createAddress(person));
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.addTo (InternetAddress address)
Add a new "To" recipient.
Parameters
address The address
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 112 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.validateAddress().
{
         to.add(validateAddress(address));
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.applyParameterSubstitution ()
Modify the email's subject and message to replace any parameters with their values. Parameters should be encoded in the message and subject as {name}, they will be replaced with the value of any defined parameter. If the parameter does not exist then the email will not be modified leaving {name} in the text.
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 290 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.message, org.tdl.vireo.email.impl.VireoEmailImpl.parameters, and org.tdl.vireo.email.impl.VireoEmailImpl.subject.
{
         subject = StringVariableReplacement.applyParameterSubstitution(subject, parameters);
         message = StringVariableReplacement.applyParameterSubstitution(message, parameters);
     }
InternetAddress org.tdl.vireo.email.impl.VireoEmailImpl.createAddress (String email, String name) private
Internal helper method to create an InternetAddress. This class will recast encoding errors as runtime exceptions while still allowing AddressExceptions to be passed through.
Parameters
email The email address.
name The address's name
Returns
A new InternetAddress
Definition at line 394 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.addBcc(), org.tdl.vireo.email.impl.VireoEmailImpl.addCc(), org.tdl.vireo.email.impl.VireoEmailImpl.addTo(), org.tdl.vireo.email.impl.VireoEmailImpl.createAddress(), org.tdl.vireo.email.impl.VireoEmailImpl.setFrom(), and org.tdl.vireo.email.impl.VireoEmailImpl.setReplyTo().
{
         try {
             InternetAddress address = new InternetAddress(email);
             if (name != null && name.trim().length() > 0)
                 address.setPersonal(name);
             return address;
         } catch (Exception e) {
             throw new RuntimeException(e);
         }
     }
InternetAddress org.tdl.vireo.email.impl.VireoEmailImpl.createAddress (Person person) private
Internal helper method to create InternedAddresses from people.
Parameters
person The person
Returns
A new InternetAddress
Definition at line 415 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.createAddress(), org.tdl.vireo.model.NameFormat.FIRST_LAST, and org.tdl.vireo.model.Person.getCurrentEmailAddress().
{
         String email = person.getEmail();
         if (person.getCurrentEmailAddress() != null)
             email = person.getCurrentEmailAddress();
         String name = person.getFormattedName(NameFormat.FIRST_LAST);
         return createAddress(email,name);
     }
List<InternetAddress> org.tdl.vireo.email.impl.VireoEmailImpl.getBcc ()
Returns
A list of all Blind Carbon Copy recipients of this email. This is the live list and may be modified.
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 142 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.bcc.
{
         return bcc;
     }
List<InternetAddress> org.tdl.vireo.email.impl.VireoEmailImpl.getCc ()
Returns
A list of all Carbon Copy recipients of this email. This is the live list and may be modified.
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 117 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.cc.
{
         return cc;
     }
String org.tdl.vireo.email.impl.VireoEmailImpl.getFailureLogMessage (String reason)
Parameters
reason Optionally provide a reason why the email message failed.
Returns
The failure log message
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 355 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.logFailureMessage, org.tdl.vireo.email.impl.VireoEmailImpl.message, org.tdl.vireo.email.impl.VireoEmailImpl.subject, and org.tdl.vireo.email.impl.VireoEmailImpl.to.
{
         if (logFailureMessage != null) {
             return logFailureMessage;
         }
         // Build a default success message
         String recipients = "";
         for (InternetAddress address : to) {
             if (recipients.length() != 0)
                 recipients += ", ";
             if (address.getPersonal() != null)
                 recipients += address.getPersonal();
             else
                 recipients += address.getAddress();
         }
         String because = "";
         if (reason != null && reason.trim().length() > 0)
             because = " because '"+reason+"'";
         return String.format("Failed to send email to %1s; %2s: '%3s'%4s",recipients,subject,message,because);
     }
InternetAddress org.tdl.vireo.email.impl.VireoEmailImpl.getFrom ()
Returns
The from address for this email.
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 192 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl._from.
{
         return _from;
     }
Person org.tdl.vireo.email.impl.VireoEmailImpl.getLogPerson ()
Returns
The person object for whom is responsible for sending this email. This person will be encoded in the log message as the sender.
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 298 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.logPersonId.
{
         if (logPersonId == null)
             return null;
         return personRepo.findPerson(logPersonId);
     }
Submission org.tdl.vireo.email.impl.VireoEmailImpl.getLogSubmission ()
Returns
The submission object where this email should be logged.
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 306 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.logSubmissionId.
{
         if (logSubmissionId == null)
             return null;
         return subRepo.findSubmission(logSubmissionId);
     }
String org.tdl.vireo.email.impl.VireoEmailImpl.getMessage ()
Returns
The message
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 257 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.message.
{
         return message;
     }
Map<String, String> org.tdl.vireo.email.impl.VireoEmailImpl.getParameters ()
Returns
A list of all proposed parameter substitutions.
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 273 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.parameters.
{
         return parameters;
     }
InternetAddress org.tdl.vireo.email.impl.VireoEmailImpl.getReplyTo ()
Returns
The reply to address for this email.
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 167 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl._replyTo.
{
         return _replyTo;
     }
String org.tdl.vireo.email.impl.VireoEmailImpl.getSubject ()
Returns
The subject
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 247 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.subject.
{
         return subject;
     }
String org.tdl.vireo.email.impl.VireoEmailImpl.getSuccessLogMessage ()
Returns
The successful log message.
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 328 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.logSuccessMessage, org.tdl.vireo.email.impl.VireoEmailImpl.message, org.tdl.vireo.email.impl.VireoEmailImpl.subject, and org.tdl.vireo.email.impl.VireoEmailImpl.to.
{
         if (logSuccessMessage != null) {
             return logSuccessMessage;
         }
         // Build a default success message
         String recipients = "";
         for (InternetAddress address : to) {
             if (recipients.length() != 0)
                 recipients += ", ";
             if (address.getPersonal() != null)
                 recipients += address.getPersonal();
             else
                 recipients += address.getAddress();
         }
         return String.format("Email sent to %1s; %2s: '%3s'",recipients,subject,message);
     }
List<InternetAddress> org.tdl.vireo.email.impl.VireoEmailImpl.getTo ()
Returns
A list of all "To" recipients of this email. This is the live list and may be modified.
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 92 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.to.
{
         return to;
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.setFailureLogMessage (String message)
Parameters
message Set the failure log message.
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 379 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.logFailureMessage, and org.tdl.vireo.email.impl.VireoEmailImpl.message.
{
         logFailureMessage = message;
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.setFrom (String email)
Set the from address.
Parameters
email An email address
Definition at line 203 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.setFrom().
{
         setFrom(email, null);
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.setFrom (String email, String name) private
Set the from address.
Parameters
email An email address
name A descriptive name.
Definition at line 222 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.createAddress(), and org.tdl.vireo.email.impl.VireoEmailImpl.setFrom().
{
         setFrom(createAddress(email, name));
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.setFrom (Person person) private
Set the new from address
Parameters
person The person object.
Definition at line 232 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.createAddress(), and org.tdl.vireo.email.impl.VireoEmailImpl.setFrom().
{
         setFrom(createAddress(person));
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.setFrom (InternetAddress address) private
Set the from address
Parameters
address The address
Definition at line 242 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl._from, and org.tdl.vireo.email.impl.VireoEmailImpl.validateAddress().
{
         _from = validateAddress(address);
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.setLogOnCompletion (Person person, Submission submission)
After this email message has been successfully set whether a log message should be set on the provided submission object. If no submission object is provided then no log message will be set. The specified person will be recorded as the person responsible for the log action, if no person is specified then no one will be specified as the log action.
Parameters
person The person responsible, or null if none.
submission The submission where completion should be logged, or null if no logs should be generated.
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 314 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.logPersonId, and org.tdl.vireo.email.impl.VireoEmailImpl.logSubmissionId.
{
         if (person == null)
             logPersonId = null;
         else
             logPersonId = person.getId();
         if (submission == null)
             logSubmissionId = null;
         else
             logSubmissionId = submission.getId();
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.setMessage (String message)
Set the message, which may contain variable parameters in the form {name}. The parameteres will be replaced with values when applyParamaterSubstitution is called.
Parameters
message The message
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 262 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.message.
{
         this.message = message;
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.setReplyTo (String email)
Set the new reply to address.
Parameters
email An email address
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 172 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.setReplyTo().
{
         setReplyTo(email, null);
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.setReplyTo (String email, String name)
Set the new reply to address
Parameters
email An email address
name A descriptive name
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 177 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.createAddress(), and org.tdl.vireo.email.impl.VireoEmailImpl.setReplyTo().
{
         setReplyTo(createAddress(email, name));
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.setReplyTo (Person person)
Set the new reply to address
Parameters
person The person object.
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 182 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.createAddress(), and org.tdl.vireo.email.impl.VireoEmailImpl.setReplyTo().
{
         setReplyTo(createAddress(person));
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.setReplyTo (InternetAddress address)
Set the new reply to address.
Parameters
address The address
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 187 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl._replyTo, and org.tdl.vireo.email.impl.VireoEmailImpl.validateAddress().
{
         _replyTo = validateAddress(address);
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.setSubject (String subject)
Set the subject, which may contain variables parameters in the form {name}. The parameters will be replaced with values when applyParameterSubstitution is called.
Parameters
subject The new subject.
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 252 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.subject.
{
         this.subject = subject;
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.setSuccessLogMessage (String message)
Parameters
message Set a successful log message.
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 350 of file VireoEmailImpl.java.
References org.tdl.vireo.email.impl.VireoEmailImpl.logSuccessMessage, and org.tdl.vireo.email.impl.VireoEmailImpl.message.
{
         logSuccessMessage = message;
     }
void org.tdl.vireo.email.impl.VireoEmailImpl.setTemplate (EmailTemplate template)
Set the subject and message based upon a vireo email template.
Parameters
template The template.
Implements org.tdl.vireo.email.VireoEmail.
Definition at line 267 of file VireoEmailImpl.java.
{
         this.subject = template.getSubject();
         this.message = template.getMessage();
     }
InternetAddress org.tdl.vireo.email.impl.VireoEmailImpl.validateAddress (InternetAddress address) private
Validate the provided email address, and throw a runtime exception if invalid.
Parameters
address The address to validate.
Definition at line 431 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.addBcc(), org.tdl.vireo.email.impl.VireoEmailImpl.addCc(), org.tdl.vireo.email.impl.VireoEmailImpl.addTo(), org.tdl.vireo.email.impl.VireoEmailImpl.setFrom(), and org.tdl.vireo.email.impl.VireoEmailImpl.setReplyTo().
{
         try {
             address.validate();
             return address;
         } catch (Exception e) {
             throw new RuntimeException(e);
         }
     }
Member Data Documentation
InternetAddress org.tdl.vireo.email.impl.VireoEmailImpl._from
Definition at line 47 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.getFrom(), and org.tdl.vireo.email.impl.VireoEmailImpl.setFrom().
InternetAddress org.tdl.vireo.email.impl.VireoEmailImpl._replyTo
Definition at line 46 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.getReplyTo(), and org.tdl.vireo.email.impl.VireoEmailImpl.setReplyTo().
List<InternetAddress> org.tdl.vireo.email.impl.VireoEmailImpl.bcc = new ArrayList<InternetAddress>()
Definition at line 45 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.getBcc().
List<InternetAddress> org.tdl.vireo.email.impl.VireoEmailImpl.cc = new ArrayList<InternetAddress>()
Definition at line 44 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.getCc().
String org.tdl.vireo.email.impl.VireoEmailImpl.logFailureMessage
Definition at line 58 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.getFailureLogMessage(), and org.tdl.vireo.email.impl.VireoEmailImpl.setFailureLogMessage().
Long org.tdl.vireo.email.impl.VireoEmailImpl.logPersonId
Definition at line 54 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.getLogPerson(), and org.tdl.vireo.email.impl.VireoEmailImpl.setLogOnCompletion().
Long org.tdl.vireo.email.impl.VireoEmailImpl.logSubmissionId
Definition at line 55 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.getLogSubmission(), and org.tdl.vireo.email.impl.VireoEmailImpl.setLogOnCompletion().
String org.tdl.vireo.email.impl.VireoEmailImpl.logSuccessMessage
Definition at line 57 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.getSuccessLogMessage(), and org.tdl.vireo.email.impl.VireoEmailImpl.setSuccessLogMessage().
String org.tdl.vireo.email.impl.VireoEmailImpl.message
Definition at line 50 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.applyParameterSubstitution(), org.tdl.vireo.email.impl.VireoEmailImpl.getFailureLogMessage(), org.tdl.vireo.email.impl.VireoEmailImpl.getMessage(), org.tdl.vireo.email.impl.VireoEmailImpl.getSuccessLogMessage(), org.tdl.vireo.email.impl.VireoEmailImpl.setFailureLogMessage(), org.tdl.vireo.email.impl.VireoEmailImpl.setMessage(), and org.tdl.vireo.email.impl.VireoEmailImpl.setSuccessLogMessage().
Map<String, String> org.tdl.vireo.email.impl.VireoEmailImpl.parameters = new HashMap<String, String>()
Definition at line 52 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.applyParameterSubstitution(), and org.tdl.vireo.email.impl.VireoEmailImpl.getParameters().
PersonRepository org.tdl.vireo.email.impl.VireoEmailImpl.personRepo
Definition at line 39 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.VireoEmailImpl().
SettingsRepository org.tdl.vireo.email.impl.VireoEmailImpl.settingRepo
Definition at line 38 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.VireoEmailImpl().
String org.tdl.vireo.email.impl.VireoEmailImpl.subject
Definition at line 49 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.applyParameterSubstitution(), org.tdl.vireo.email.impl.VireoEmailImpl.getFailureLogMessage(), org.tdl.vireo.email.impl.VireoEmailImpl.getSubject(), org.tdl.vireo.email.impl.VireoEmailImpl.getSuccessLogMessage(), and org.tdl.vireo.email.impl.VireoEmailImpl.setSubject().
SubmissionRepository org.tdl.vireo.email.impl.VireoEmailImpl.subRepo
Definition at line 40 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.VireoEmailImpl().
List<InternetAddress> org.tdl.vireo.email.impl.VireoEmailImpl.to = new ArrayList<InternetAddress>()
Definition at line 43 of file VireoEmailImpl.java.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.getFailureLogMessage(), org.tdl.vireo.email.impl.VireoEmailImpl.getSuccessLogMessage(), and org.tdl.vireo.email.impl.VireoEmailImpl.getTo().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/email/impl/VireoEmailImpl.java