Vireo: org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl Class Reference
org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl Class Reference
Public Member Functions
void setProquestVocabularyRepository (ProquestVocabularyRepository proquestRepo)
void setSettingsRepository (SettingsRepository settingRepo)
Phone parsePhone (final String fullPhone)
Address parseAddress (final String fullAddress)
ProquestLanguage languageCode (Locale locale)
String degreeCode (String degree)
String categorize (Attachment attachment)
Public Member Functions inherited from org.tdl.vireo.proquest.ProquestUtilityService
Phone parsePhone (String fullPhone)
Address parseAddress (String fullAddress)
Public Attributes
ProquestVocabularyRepository proquestRepo = null
SettingsRepository settingRepo = null
Static Public Attributes
static final Map< String, String > LANG = new HashMap<String,String>()
static final Map< String, String > CAT = new HashMap<String,String>()
Static Protected Member Functions
static final Address addressParsingAlgorithmByBill (final String fullAddress)
static final String reverse (final String string)
static final Address addressParsingAlgorithmByScott (final String fullAddress)
Static Protected Attributes
static final Pattern[] patterns
Static Package Functions
[static initializer]
[static initializer]
Detailed Description
Implementation of the proquest utility service to provide a set of helpfull algorithms while generating a proquest export.
Author
Scott Phillips
Definition at line 25 of file ProquestUtilityServiceImpl.java.
Member Function Documentation
org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.[static initializer] () static package
org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.[static initializer] () static package
static final Address org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.addressParsingAlgorithmByBill (final String fullAddress) static protected
Bill Ingram's address parsing algorithm.
This algorithm works by flattening the address onto one line then it tries to identify the address line by common suffixes or apartment identifiers. From that it then extracts the city, state, zip, and potentially country.
This algorithm does not match many addresses but those that it does are typically 100% accurate. It works on well formed American addresses and almost always fails on international addresses.
Parameters
fullAddress The full address
Returns
An address object if the parse was successful, otherwise return null.
Definition at line 127 of file ProquestUtilityServiceImpl.java.
Referenced by org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.parseAddress().
{
         // The address parts that we are trying to extract
         String addrline = null;
         String city     = null;
         String state    = null;
         String zip      = null;
         String cntry    = null;
         // Extract the address
         String oneLineAddress = fullAddress.replaceAll("\r\n"," ");
         oneLineAddress = oneLineAddress.replaceAll("\n"," ");
         // Case Insensitive
         // This does a <em>good enough</em> job of parsing, but is often incorrect
         Pattern pattern = Pattern.compile(
                 "(.+(?:(?:STREET|ST|DRIVE|DR|AVENUE|AVE|AV|ROAD|RD|LOOP|COURT|CT|CIRCLE|CR|TERRANCE|TERR|HIGHWAY|HWY|PARKWAY|PRKY|PLACE|PL|WAY|RIDGE|RDG|LANE|LN|BOULEVARD|BLVD)\\.?)(?:(?:,?\\s)(?:APT|UNIT|#)[\\.,]?\\s\\w+)?)(?:,?)\\n" +
                                                 // address
                 "(?:\\s)([a-zA-Z\\s]+),?"  +    // city
                 "(?:\\s)([a-zA-Z\\s]{2,})" +    // state
                 "(?:\\s)([\\d]+[\\-\\d]+)" +    // zip
                 "((?:\\s)([\\s\\D]+))?",        // country
                 Pattern.CASE_INSENSITIVE);
         Matcher matcher = pattern.matcher(oneLineAddress);
         if (!matcher.matches())
             return null;
         addrline = matcher.group(1);
         city     = matcher.group(2);
         state    = matcher.group(3);
         zip      = matcher.group(4);
         cntry    = matcher.group(5);
         return new Address(fullAddress, addrline, city, state, zip, cntry);
     }
static final Address org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.addressParsingAlgorithmByScott (final String fullAddress) static protected
Scott Phillips's address parsing algorithm.
This algorithm works by searching backwards. Starting at the end of the address identify the zip code. Once you have that assume anything following the zip code is the country, and then the two tokens preceding the zip code are the city and state. We do this by performing a series of regular expressions on a reverse address string. The difference between the regular expressions is how linent they are for extracting the city and state. The first one in the list demands that city and state are either separated by a new line or a comma. Each of the next versions back off of this by allowing spaces between these tokens. This sometimes breaks multi-word cities or state, but sometimes people just don't supply a city.
This algorithm works on most international and American addresses. However it will sometimes miss identify components like getting the city or state wrong. It will often not identify the country if it is specified before the zip code.
Parameters
fullAddress The full address
Returns
An address object if the parse was successful, otherwise return null.
Definition at line 237 of file ProquestUtilityServiceImpl.java.
References org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.patterns, and org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.reverse().
Referenced by org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.parseAddress().
{
         // The address parts that we are trying to extract
         String addrline = null;
         String city     = null;
         String state    = null;
         String zip      = null;
         String cntry    = null;
         String reverseAddress = reverse(fullAddress);
         Matcher matcher = null;
         for(Pattern pattern : patterns) {
             matcher = pattern.matcher(reverseAddress);
             if (matcher.matches())
                 break;
         }
         if (!matcher.matches())
             return null;
         cntry = reverse(matcher.group(1));
         zip = reverse(matcher.group(2));
         state = reverse(matcher.group(3));
         city = reverse(matcher.group(4));
         addrline = reverse(matcher.group(5));
         return new Address(fullAddress, addrline, city, state, zip, cntry);
     }
String org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.categorize (Attachment attachment)
ProQuest Categories:
audio code/script image pdf presentation spreadsheet text video webpage data other
Implements org.tdl.vireo.proquest.ProquestUtilityService.
Definition at line 327 of file ProquestUtilityServiceImpl.java.
References org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.CAT.
{
         String mimeType = attachment.getMimeType();
         String category = "other";
         // Start with the simple stuff first
         if (mimeType.startsWith("audio/"))
             category = "audio";
         if (mimeType.startsWith("image/"))
             category = "image";
         if (mimeType.startsWith("text/"))
             category = "text";
         if (mimeType.startsWith("video/"))
             category = "video";
         if (CAT.containsKey(mimeType))
             category = CAT.get(mimeType);
         return category;
     }
String org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.degreeCode (String degree)
Translate Vireo's full degree name into a ProQuest degree code.
Parameters
degree The degree to translate.
Returns
The degree code, or the full degree name if not found.
Implements org.tdl.vireo.proquest.ProquestUtilityService.
Definition at line 296 of file ProquestUtilityServiceImpl.java.
{
         if (degree == null)
             return null;
         String code = settingRepo.getConfigValue(AppConfig.getDegreeCodeConfig(degree));
         if (code != null && code.trim().length() != 0)
             return code;
         // fall back to the full degree name
         return degree;
     }
ProquestLanguage org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.languageCode (Locale locale)
Translate Vireo's ISO 1799 language into ProQuest's seemingly random language codes.
Parameters
locale Vireo's language locale. (may be null)
Returns
The ProQuest code for the language or null if none found.
Implements org.tdl.vireo.proquest.ProquestUtilityService.
Definition at line 268 of file ProquestUtilityServiceImpl.java.
{
         if (locale == null)
             return null;
         String iso639 = locale.getLanguage();
         String iso639_2b = locale.getISO3Language();
         // First lookup by the two letter language codes
         ProquestLanguage lang = null;
         if (iso639 != null) {
             lang = proquestRepo.findLanguageByCode(LANG.get(iso639.toUpperCase()));
         }
         // Second, fall back to the three leter language codes.
         if (iso639_2b != null && lang == null) {
             lang = proquestRepo.findLanguageByCode(LANG.get(iso639_2b.toUpperCase()));
         }
         // Don't implement ultimate fall back search because this causes incorrect mappings.
         // if (lang == null)
         //      lang = proquestRepo.findLanguageByCode(iso639);
         return lang;
     }
Address org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.parseAddress (final String fullAddress)
Definition at line 93 of file ProquestUtilityServiceImpl.java.
References org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.addressParsingAlgorithmByBill(), and org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.addressParsingAlgorithmByScott().
{
         // First try Bill's Address Parse
         Address address =  addressParsingAlgorithmByBill(fullAddress);
         // Second fall back to scott's address parse
         if (address == null)
             address = addressParsingAlgorithmByScott(fullAddress);
         // The final fall back is to just give up.
         if (address == null)
             address = new Address(fullAddress, null,null,null,null,null);
         return address;
     }
Phone org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.parsePhone (final String fullPhone)
Definition at line 54 of file ProquestUtilityServiceImpl.java.
{
         // The phone parts that we are trying extract
         String cntryCode = null;
         String areaCode  = null;
         String number    = null;
         String ext       = null;
         // Give it our best shot
         Pattern pattern = Pattern.compile(
                 "^(?:[\\+]?[\\(]?([\\d]{1,3})[\\s\\-\\.\\)]+)?" +  // cntry_code (optional)
                 "(?:[\\(]?([\\d]{1,3})[\\s\\-/\\)]+)"           +  // area_code
                 "([2-9][0-9\\s\\-\\.]{6,}[0-9])"                +  // number
                 "(?:[\\s\\D]+([\\d]{1,5}))?$"                      // ext (optional
                 );
         Matcher matcher = pattern.matcher(fullPhone);
         if(matcher.matches()) {
             cntryCode = matcher.group(1);
             areaCode  = matcher.group(2);
             number     = matcher.group(3);
             ext        = matcher.group(4);
         } else {
             String trimPhone = fullPhone.replaceAll("[^0-9]","");
             if (trimPhone.length() > 7) {
                 // The phone number is long enough to have an area code, split that off.
                 areaCode = trimPhone.substring(0,trimPhone.length() - 7);
                 number = trimPhone.substring(trimPhone.length() - 7, trimPhone.length());
             } else {
                 // We don't have an area code, so the whole things goes into phone
                 number = trimPhone;
             }
         }
         return new Phone(fullPhone, cntryCode, areaCode, number, ext);
     }
static final String org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.reverse (final String string) static protected
Reverse the string provided.
Definition at line 171 of file ProquestUtilityServiceImpl.java.
Referenced by org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.addressParsingAlgorithmByScott().
{
         return new StringBuilder(string).reverse().toString();
     }
void org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.setProquestVocabularyRepository (ProquestVocabularyRepository proquestRepo)
Inject the proquest repository dependency
Parameters
proquestRepo The proquest vocabulary repository.
Definition at line 37 of file ProquestUtilityServiceImpl.java.
References org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.proquestRepo.
{
         this.proquestRepo = proquestRepo;
     }
void org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.setSettingsRepository (SettingsRepository settingRepo)
Inject the settings repository dependency
Parameters
settingRepo The settings repository.
Definition at line 48 of file ProquestUtilityServiceImpl.java.
References org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.settingRepo.
{
         this.settingRepo = settingRepo;
     }
Member Data Documentation
final Map<String,String> org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.CAT = new HashMap<String,String>() static
A mapping of individual mimetypes to categories. We do not need to including a mapping in the mimetype is part of the category, like a mapping for text/plain to "text" because it starts with an identifiable prefix.
Definition at line 502 of file ProquestUtilityServiceImpl.java.
Referenced by org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.categorize().
final Map<String,String> org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.LANG = new HashMap<String,String>() static
Special mapping from iso's 2 and 3 letter language codes to proquest's crazy-on-crack language codes that follow no standard what-so-ever.
Definition at line 356 of file ProquestUtilityServiceImpl.java.
final Pattern [] org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.patterns static protected
Definition at line 177 of file ProquestUtilityServiceImpl.java.
Referenced by org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.addressParsingAlgorithmByScott().
ProquestVocabularyRepository org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.proquestRepo = null
Definition at line 28 of file ProquestUtilityServiceImpl.java.
Referenced by org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.setProquestVocabularyRepository().
SettingsRepository org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.settingRepo = null
Definition at line 29 of file ProquestUtilityServiceImpl.java.
Referenced by org.tdl.vireo.proquest.impl.ProquestUtilityServiceImpl.setSettingsRepository().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/proquest/impl/ProquestUtilityServiceImpl.java