Vireo: controllers.FirstUser Class Reference
controllers.FirstUser Class Reference
Classes
class EmbargoArray
class InitializeEmbargos
Static Public Member Functions
static void createUser ()
static boolean verify (String firstName, String lastName, String email, String password1, String password2, String netid)
Static Public Member Functions inherited from controllers.AbstractVireoController
static void injectRepositories ()
static void checkForFirstUser ()
static void handleError (Throwable throwable)
Static Public Attributes
static SystemEmailTemplateService systemEmailService = Spring.getBeanOfType(SystemEmailTemplateService.class)
static Indexer indexer = Spring.getBeanOfType(Indexer.class)
Static Public Attributes inherited from controllers.AbstractVireoController
static SecurityContext context = Spring.getBeanOfType(SecurityContext.class)
static PersonRepository personRepo = Spring.getBeanOfType(PersonRepository.class)
static SubmissionRepository subRepo = Spring.getBeanOfType(SubmissionRepository.class)
static SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class)
static ProquestVocabularyRepository proquestRepo = Spring.getBeanOfType(ProquestVocabularyRepository.class)
static ErrorLog errorLog = Spring.getBeanOfType(ErrorLog.class)
static StateManager stateManager = Spring.getBeanOfType(StateManager.class)
static Indexer indexer = Spring.getBeanOfType(Indexer.class)
static Searcher searcher = Spring.getBeanOfType(Searcher.class)
static Boolean firstUser = null
Static Private Member Functions
static List< AuthenticationMethod > getEnabledAuthenticationMethods ()
Static Private Attributes
static final String[] COMMITTEE_MEMBER_ROLE_TYPES_DEFINITIONS = {"Chair"}
static final EmbargoArray[] EMBARGO_DEFINTITIONS
Additional Inherited Members
Static Protected Member Functions inherited from controllers.AbstractVireoController
static boolean isEmpty (String value)
static boolean isNotEmpty (String value)
static String escapeJavaScript (String value)
static String toJSON (String[] values)
static String text2html (String value)
static boolean isFieldRequired (FieldConfig field)
Detailed Description
Definition at line 26 of file FirstUser.java.
Member Function Documentation
static void controllers.FirstUser.createUser () static
Definition at line 31 of file FirstUser.java.
References org.tdl.vireo.model.RoleType.ADMINISTRATOR, controllers.FirstUser.COMMITTEE_MEMBER_ROLE_TYPES_DEFINITIONS, org.tdl.vireo.model.DegreeLevel.DOCTORAL, controllers.AbstractVireoController.firstUser, controllers.FirstUser.getEnabledAuthenticationMethods(), org.tdl.vireo.model.DegreeLevel.MASTERS, org.tdl.vireo.model.DegreeLevel.UNDERGRADUATE, and controllers.FirstUser.verify().
{
         if(firstUser == null || firstUser == false)
                 Application.index();
         if(params.get("createFirstUser")!=null) {
             //Get form parameters
             String firstName = params.get("firstName");
             String lastName = params.get("lastName");
             String email = params.get("email");
             String password1 = params.get("password1");
             String password2 = params.get("password2");
             String netid = params.get("netid");
             verify(firstName, lastName, email, password1, password2, netid);
             if(!validation.hasErrors()) {
                 // Create the account.
                 context.turnOffAuthorization();
                 Person person = personRepo.createPerson(netid, email, firstName, lastName, RoleType.ADMINISTRATOR).save();
                 person.setPassword(password1);
                 person.save();
                 context.turnOffAuthorization();
                 context.login(person);
                 // Notify all the authentication methods of the new user.
                 List<AuthenticationMethod> methods = getEnabledAuthenticationMethods();
                 for (AuthenticationMethod method : methods)
                     method.personCreated(request, person);
                 // Log the person in
                 session.put("personId", person.getId());
                 session.put("firstName", person.getFirstName());
                 session.put("lastName", person.getLastName());
                 session.put("displayName", person.getDisplayName());
                 //Generate System Email Templates
                 systemEmailService.generateAllSystemEmailTemplates();
                 // Setup Embargos
                 new InitializeEmbargos().doJob();
                 // Setup default Committee Member Role Types
                 for(String roleType : COMMITTEE_MEMBER_ROLE_TYPES_DEFINITIONS) {
                     settingRepo.createCommitteeMemberRoleType(roleType, DegreeLevel.UNDERGRADUATE).save();
                     settingRepo.createCommitteeMemberRoleType(roleType, DegreeLevel.MASTERS).save();
                     settingRepo.createCommitteeMemberRoleType(roleType, DegreeLevel.DOCTORAL).save();
                 }
                 //Flag that any future user is not the first user.
                 firstUser = false;
                 // Go to the settings page
                 try {
                     SettingsTab.settingsRedirect();
                 } finally {
                     // Do a fresh rebuild of the index after the page has loaded.
                     indexer.deleteAndRebuild(false);
                 }
             } else {
                 renderTemplate("FirstUser/createUser.html",
                         firstName,
                         lastName,
                         email,
                         password1,
                         password2,
                         netid
                 );
             }
         }
         renderTemplate("FirstUser/createUser.html");
     }
static List<AuthenticationMethod> controllers.FirstUser.getEnabledAuthenticationMethods () static private
Returns
The list of all enabled authenticationMethods.
Definition at line 156 of file FirstUser.java.
Referenced by controllers.FirstUser.createUser().
{
         Map<String,AuthenticationMethod> methodMap = Spring.getBeansOfType(AuthenticationMethod.class);
         List<AuthenticationMethod> enabledMethods = new ArrayList<AuthenticationMethod>();
         for(AuthenticationMethod method : methodMap.values()) {
             if (method.isEnabled())
                 enabledMethods.add(method);
         }
         return enabledMethods;
     }
static boolean controllers.FirstUser.verify (String firstName, String lastName, String email, String password1, String password2, String netid) static
Verify that the new user information is correct.
Parameters
firstName (The first name provided)
lastName (The last name provided)
email (The email provided)
password1 (The password provided)
password2 (Verification of password1)
netid (The netid provided)
Returns
Definition at line 117 of file FirstUser.java.
Referenced by controllers.FirstUser.createUser().
{
         int numberOfErrorsBefore = validation.errors().size();
         if(firstName==null || firstName.isEmpty())
             validation.addError("firstName", "Please enter your first name.");
         if(lastName==null || lastName.isEmpty())
             validation.addError("lastName", "Please enter your last name.");
         if(email==null || email.isEmpty()) {
             validation.addError("email", "Please enter an email.");
         } else {
             try {
                 new InternetAddress(email).validate();
             } catch (AddressException ae) {
                 validation.addError("email", "The email provided is invalid.");
             }
         }
         if(password1==null || password1.isEmpty()) {
             validation.addError("password1", "Please enter a password.");
         } else if(password2==null || password2.isEmpty()) {
                 validation.addError("password2", "Please verify the password.");
         } else if(!password2.equals(password1)) {
                 validation.addError("passwords", "The passwords provided do not match.");
         }
         if(numberOfErrorsBefore == validation.errors().size())
             return false;
         else
             return true;
     }
Member Data Documentation
final String [] controllers.FirstUser.COMMITTEE_MEMBER_ROLE_TYPES_DEFINITIONS = {"Chair"} static private
Initial Committee Member Role Types
Definition at line 170 of file FirstUser.java.
Referenced by controllers.FirstUser.createUser().
final EmbargoArray [] controllers.FirstUser.EMBARGO_DEFINTITIONS static private
Initial Embargo Types to create
Definition at line 176 of file FirstUser.java.
Referenced by controllers.FirstUser.InitializeEmbargos.doJob().
Indexer controllers.FirstUser.indexer = Spring.getBeanOfType(Indexer.class) static
Definition at line 29 of file FirstUser.java.
SystemEmailTemplateService controllers.FirstUser.systemEmailService = Spring.getBeanOfType(SystemEmailTemplateService.class) static
Definition at line 28 of file FirstUser.java.
The documentation for this class was generated from the following file:
app/controllers/FirstUser.java