Vireo: org.tdl.vireo.batch.impl.TransitionServiceImpl Class Reference
org.tdl.vireo.batch.impl.TransitionServiceImpl Class Reference
Classes
class TransitionJob
Public Member Functions
void setPersonRepository (PersonRepository repo)
void setSubmissionRepository (SubmissionRepository repo)
void setErrorLog (ErrorLog errorLog)
void setSearcher (Searcher searcher)
void setSecurityContext (SecurityContext context)
void setJobManager (JobManager jobManager)
JobMetadata transition (SearchFilter filter, State state)
JobMetadata transition (SearchFilter filter, State state, DepositLocation location)
Public Attributes
PersonRepository personRepo
SubmissionRepository subRepo
ErrorLog errorLog
Searcher searcher
SecurityContext context
JobManager jobManager
DepositService depositService
Detailed Description
Implement the transition service. This follows a basic implementation that supports both changing the status of a submission, and in addition if instructed will also use the deposit service to deposit a transition.
Author
Scott Phillips
Definition at line 36 of file TransitionServiceImpl.java.
Member Function Documentation
void org.tdl.vireo.batch.impl.TransitionServiceImpl.setErrorLog (ErrorLog errorLog)
Parameters
errorLog The error log
Definition at line 75 of file TransitionServiceImpl.java.
References org.tdl.vireo.batch.impl.TransitionServiceImpl.errorLog.
{
         this.errorLog = errorLog;
     }
void org.tdl.vireo.batch.impl.TransitionServiceImpl.setJobManager (JobManager jobManager)
Parameters
jobManager The manager of background jobs
Definition at line 99 of file TransitionServiceImpl.java.
References org.tdl.vireo.batch.impl.TransitionServiceImpl.jobManager.
{
         this.jobManager = jobManager;
     }
void org.tdl.vireo.batch.impl.TransitionServiceImpl.setPersonRepository (PersonRepository repo)
Parameters
repo The person repository
Definition at line 59 of file TransitionServiceImpl.java.
{
         this.personRepo = repo;
     }
void org.tdl.vireo.batch.impl.TransitionServiceImpl.setSearcher (Searcher searcher)
Parameters
searcher Set the searcher used for identify batch of submissions to be processed.
Definition at line 84 of file TransitionServiceImpl.java.
References org.tdl.vireo.batch.impl.TransitionServiceImpl.searcher.
{
         this.searcher = searcher;
     }
void org.tdl.vireo.batch.impl.TransitionServiceImpl.setSecurityContext (SecurityContext context)
Parameters
context The security context managing who is currently logged in.
Definition at line 92 of file TransitionServiceImpl.java.
References org.tdl.vireo.batch.impl.TransitionServiceImpl.context.
{
         this.context = context;
     }
void org.tdl.vireo.batch.impl.TransitionServiceImpl.setSubmissionRepository (SubmissionRepository repo)
Parameters
repo The submission repository
Definition at line 67 of file TransitionServiceImpl.java.
{
         this.subRepo = repo;
     }
JobMetadata org.tdl.vireo.batch.impl.TransitionServiceImpl.transition (SearchFilter filter, State state)
Transition a batch of submissions from their current state into the specified state.
Parameters
filter The search filter identifying the records to be processed.
state The state of each submission should be transitioned in to.
Returns
The metadata for the background job to transition submissions. Use this object to keep track of the task's progress.
Implements org.tdl.vireo.batch.TransitionService.
Definition at line 105 of file TransitionServiceImpl.java.
{
         return transition(filter,state,null);
     }
JobMetadata org.tdl.vireo.batch.impl.TransitionServiceImpl.transition (SearchFilter filter, State state, DepositLocation location)
Transition a batch of submissions from their current state into the specified state. If that state is a depositable state and a deposit location is provided then each submissions will be deposited.
Parameters
filter The search filter identifying the records to be processed.
state The state each submission should be transitioned in to.
location If the state is depositable, the deposit location where the submission should be deposited.
Returns
The metadata for the background job to transition submissions. Use this object to keep track of the task's progress.
Implements org.tdl.vireo.batch.TransitionService.
Definition at line 110 of file TransitionServiceImpl.java.
References org.tdl.vireo.batch.impl.TransitionServiceImpl.context, org.tdl.vireo.model.DepositLocation.getCollection(), org.tdl.vireo.model.DepositLocation.getDepositor(), org.tdl.vireo.model.DepositLocation.getPackager(), org.tdl.vireo.model.DepositLocation.getRepository(), and org.tdl.vireo.security.SecurityContext.isAuthorizationActive().
{
         if (filter == null)
             throw new IllegalArgumentException("A search filter is required");
         if (state == null)
             throw new IllegalArgumentException("A state is required");
         if (location != null) {
             // If the location is provided check that it is good.
             if (location.getRepository() == null)
                 throw new IllegalArgumentException("A repository URL is required.");
             if (location.getCollection() == null)
                 throw new IllegalArgumentException("A collection URL is required.");
             if (location.getPackager() == null)
                 throw new IllegalArgumentException("A deposit packager is required.");
             if (location.getDepositor() == null)
                 throw new IllegalArgumentException("A depositor is required.");
         }
         if (context.isAuthorizationActive() && !context.isReviewer())
             throw new SecurityException("Unauthorized to transition submissions.");
         TransitionJob job = new TransitionJob(filter,state,location);
         job.now();
         return job.metadata;
     }
Member Data Documentation
SecurityContext org.tdl.vireo.batch.impl.TransitionServiceImpl.context
Definition at line 47 of file TransitionServiceImpl.java.
Referenced by org.tdl.vireo.batch.impl.TransitionServiceImpl.setSecurityContext(), org.tdl.vireo.batch.impl.TransitionServiceImpl.transition(), and org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.TransitionJob().
DepositService org.tdl.vireo.batch.impl.TransitionServiceImpl.depositService
Definition at line 53 of file TransitionServiceImpl.java.
ErrorLog org.tdl.vireo.batch.impl.TransitionServiceImpl.errorLog
Definition at line 41 of file TransitionServiceImpl.java.
Referenced by org.tdl.vireo.batch.impl.TransitionServiceImpl.setErrorLog().
JobManager org.tdl.vireo.batch.impl.TransitionServiceImpl.jobManager
Definition at line 50 of file TransitionServiceImpl.java.
Referenced by org.tdl.vireo.batch.impl.TransitionServiceImpl.setJobManager().
PersonRepository org.tdl.vireo.batch.impl.TransitionServiceImpl.personRepo
Definition at line 39 of file TransitionServiceImpl.java.
Searcher org.tdl.vireo.batch.impl.TransitionServiceImpl.searcher
Definition at line 44 of file TransitionServiceImpl.java.
Referenced by org.tdl.vireo.batch.impl.TransitionServiceImpl.setSearcher().
SubmissionRepository org.tdl.vireo.batch.impl.TransitionServiceImpl.subRepo
Definition at line 40 of file TransitionServiceImpl.java.
The documentation for this class was generated from the following file:
app/org/tdl/vireo/batch/impl/TransitionServiceImpl.java