Vireo: controllers.AbstractVireoController Class Reference
controllers.AbstractVireoController Class Reference abstract
Static Public Member Functions
static void injectRepositories ()
static void checkForFirstUser ()
static void handleError (Throwable throwable)
Static Public Attributes
static SecurityContext context = Spring.getBeanOfType(SecurityContext.class)
static PersonRepository personRepo = Spring.getBeanOfType(PersonRepository.class)
static SubmissionRepository subRepo = Spring.getBeanOfType(SubmissionRepository.class)
static SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class)
static ProquestVocabularyRepository proquestRepo = Spring.getBeanOfType(ProquestVocabularyRepository.class)
static ErrorLog errorLog = Spring.getBeanOfType(ErrorLog.class)
static StateManager stateManager = Spring.getBeanOfType(StateManager.class)
static Indexer indexer = Spring.getBeanOfType(Indexer.class)
static Searcher searcher = Spring.getBeanOfType(Searcher.class)
static Boolean firstUser = null
Static Protected Member Functions
static boolean isEmpty (String value)
static boolean isNotEmpty (String value)
static String escapeJavaScript (String value)
static String URIEncode (String value)
static String toJSON (String[] values)
static String text2html (String value)
static boolean isFieldRequired (FieldConfig field)
Detailed Description
This is a common ancestor for all Vireo controllers. It will hold any common code that is used by all controller methods. At the time of creation this just mean loading all the major spring dependencies and injected them into the view for templates to be able to access. However, it is expected that additional things will be added to this class.
Author
Scott Phillips
Definition at line 33 of file AbstractVireoController.java.
Member Function Documentation
static void controllers.AbstractVireoController.checkForFirstUser () static
Definition at line 65 of file AbstractVireoController.java.
References org.tdl.vireo.model.PersonRepository.findPersonsTotal(), controllers.AbstractVireoController.firstUser, and controllers.AbstractVireoController.personRepo.
{
         if(firstUser==null) {
             if(personRepo.findPersonsTotal()==0) {
                 firstUser = true;
             } else {
                 firstUser = false;
             }
         }
         if(firstUser==true)
             FirstUser.createUser();
     }
static String controllers.AbstractVireoController.escapeJavaScript (String value) static protected
Escape Javascrip strings. In Javascript double quotes must be escaped.
Parameters
value The java string.
Returns
A javascript escaped string
Definition at line 124 of file AbstractVireoController.java.
Referenced by controllers.AbstractVireoController.toJSON().
{
         if (value == null)
             return "";
         value = StringEscapeUtils.escapeJavaScript(value);
         value = value.replaceAll("\\\\'", "'");
         return value;
     }
static void controllers.AbstractVireoController.handleError (Throwable throwable) static
Catch any errors and report them to the log for review under the systems control panel.
Parameters
throwable The error encountered
Definition at line 85 of file AbstractVireoController.java.
{
         errorLog.logError(throwable, request);
     }
static void controllers.AbstractVireoController.injectRepositories () static
This is run before any action to inject the repositories into the template. This way the template can access information from any repository without it being explicit put in for each method.
Definition at line 54 of file AbstractVireoController.java.
References controllers.AbstractVireoController.context, controllers.AbstractVireoController.indexer, controllers.AbstractVireoController.personRepo, controllers.AbstractVireoController.proquestRepo, controllers.AbstractVireoController.settingRepo, controllers.AbstractVireoController.stateManager, and controllers.AbstractVireoController.subRepo.
{
         renderArgs.put("securityContext", context);
         renderArgs.put("personRepo", personRepo);
         renderArgs.put("subRepo", subRepo);
         renderArgs.put("settingRepo", settingRepo);
         renderArgs.put("proquestRepo", proquestRepo);
         renderArgs.put("stateManager", stateManager);
         renderArgs.put("indexer", indexer);
     }
static boolean controllers.AbstractVireoController.isEmpty (String value) static protected
Return true if the string is either null or only consists of whitespace.
Parameters
value The string to test.
Returns
True if the value is empty, otherwise false.
Definition at line 98 of file AbstractVireoController.java.
Referenced by controllers.submit.DocumentInfo.documentInfo(), controllers.AbstractVireoController.isNotEmpty(), controllers.submit.DocumentInfo.isValidDocType(), controllers.submit.DocumentInfo.validateCommitteeMembers(), controllers.submit.DocumentInfo.verify(), and controllers.submit.PersonalInfo.verify().
{
         if (value == null)
             return true;
         if (value.trim().length() == 0)
             return true;
         return false;
     }
static boolean controllers.AbstractVireoController.isFieldRequired (FieldConfig field) static protected
Return whether the specified field is required. If it is then return true, otherwise false.
Parameters
field The field to check whether it is required.
Returns
True if required, otherwise false.
Definition at line 201 of file AbstractVireoController.java.
{
         return "required".equals(settingRepo.getConfigValue(field.ENABLED));
     }
static boolean controllers.AbstractVireoController.isNotEmpty (String value) static protected
Return true if the string contains a textual value and not just whitespace.
Parameters
value The string to test.
Returns
True if the value has text, otherwise false.
Definition at line 113 of file AbstractVireoController.java.
References controllers.AbstractVireoController.isEmpty().
{
         return !isEmpty(value);
     }
static String controllers.AbstractVireoController.text2html (String value) static protected
Convert plain text into passable HTML. Separate text into paragraphs, preserve intending, and try not to mess with any embedded tags.
Parameters
value The input text.
Returns
HTML suitable for display.
Definition at line 175 of file AbstractVireoController.java.
Referenced by controllers.submit.Confirm.complete(), and controllers.submit.License.license().
{
         // null check
         if(value == null)
             value = "";
         String html = value.replaceAll("  ", "&nbsp;&nbsp;");
         String[] paragraphs = html.split("\n\\s*\n");
         html = "";
         for (String paragraph : paragraphs) {
             html += "<p>" + paragraph + "</p>";
         }
         html = html.replaceAll("\n", "<br/>");
         return html;
     }
static String controllers.AbstractVireoController.toJSON (String[] values) static protected
Convert a simple java array of strings into a JSON object.
Parameters
values The array to be encoded as JSON.
Returns
A json string.
Definition at line 149 of file AbstractVireoController.java.
References controllers.AbstractVireoController.escapeJavaScript().
{
         if (values == null)
             return "[]";
         String result = "[";
         for (String value: values) {
             if (result.length() > 1) {
                 result += ",";
             }
             result += "\""+escapeJavaScript(value)+"\"";
         }
         result += "]";
         return result;
     }
static String controllers.AbstractVireoController.URIEncode (String value) static protected
Definition at line 132 of file AbstractVireoController.java.
{
         String ret = value;
         try {
             ret = URLEncoder.encode(value, "UTF-8").replace("+", "%20");
         } catch (UnsupportedEncodingException e) {
             Logger.error(e, "Error URI Encoding value '%s'", value);
         }
         return ret;
     }
Member Data Documentation
SecurityContext controllers.AbstractVireoController.context = Spring.getBeanOfType(SecurityContext.class) static
Definition at line 36 of file AbstractVireoController.java.
Referenced by controllers.Authentication.checkForceSSL(), controllers.AbstractVireoController.injectRepositories(), controllers.Authentication.loginMethod(), controllers.Authentication.loginReturn(), controllers.Authentication.logout(), controllers.Authentication.recover(), and controllers.Authentication.register().
ErrorLog controllers.AbstractVireoController.errorLog = Spring.getBeanOfType(ErrorLog.class) static
Definition at line 41 of file AbstractVireoController.java.
Boolean controllers.AbstractVireoController.firstUser = null static
Definition at line 46 of file AbstractVireoController.java.
Referenced by controllers.AbstractVireoController.checkForFirstUser(), and controllers.FirstUser.createUser().
Indexer controllers.AbstractVireoController.indexer = Spring.getBeanOfType(Indexer.class) static
Definition at line 43 of file AbstractVireoController.java.
Referenced by controllers.AbstractVireoController.injectRepositories().
PersonRepository controllers.AbstractVireoController.personRepo = Spring.getBeanOfType(PersonRepository.class) static
Definition at line 37 of file AbstractVireoController.java.
Referenced by controllers.AbstractVireoController.checkForFirstUser(), and controllers.AbstractVireoController.injectRepositories().
ProquestVocabularyRepository controllers.AbstractVireoController.proquestRepo = Spring.getBeanOfType(ProquestVocabularyRepository.class) static
Definition at line 40 of file AbstractVireoController.java.
Referenced by controllers.AbstractVireoController.injectRepositories(), and controllers.submit.DocumentInfo.verify().
Searcher controllers.AbstractVireoController.searcher = Spring.getBeanOfType(Searcher.class) static
Definition at line 44 of file AbstractVireoController.java.
SettingsRepository controllers.AbstractVireoController.settingRepo = Spring.getBeanOfType(SettingsRepository.class) static
Definition at line 39 of file AbstractVireoController.java.
Referenced by controllers.AbstractVireoController.injectRepositories(), controllers.submit.PersonalInfo.isValidCollege(), controllers.submit.PersonalInfo.isValidDegree(), controllers.submit.DocumentInfo.isValidDegreeMonth(), controllers.submit.PersonalInfo.isValidDepartment(), controllers.submit.PersonalInfo.isValidMajor(), controllers.submit.PersonalInfo.isValidProgram(), controllers.submit.PersonalInfo.personalInfo(), and controllers.Authentication.updateProfile().
StateManager controllers.AbstractVireoController.stateManager = Spring.getBeanOfType(StateManager.class) static
Definition at line 42 of file AbstractVireoController.java.
Referenced by controllers.AbstractVireoController.injectRepositories().
SubmissionRepository controllers.AbstractVireoController.subRepo = Spring.getBeanOfType(SubmissionRepository.class) static
Definition at line 38 of file AbstractVireoController.java.
Referenced by controllers.submit.Confirm.generateCommitteEmailHash(), and controllers.AbstractVireoController.injectRepositories().
The documentation for this class was generated from the following file:
app/controllers/AbstractVireoController.java