Vireo: org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob Class Reference
org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob Class Reference
Public Member Functions
ExportJob (Packager packager, SearchFilter filter, OutputStream out)
void doJob () throws Exception
Public Attributes
final Packager packager
final SearchFilter filter
final OutputStream out
final Long personId
final JobMetadata meta
Private Member Functions
void copyRow (XSSFRow source, XSSFRow dest)
void copyCell (XSSFCell source, XSSFCell dest)
Detailed Description
Background job to export
Definition at line 125 of file ExportExcelServiceImpl.java.
Constructor & Destructor Documentation
org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.ExportJob (Packager packager, SearchFilter filter, OutputStream out)
Construct a new export job.
Parameters
packager The packager which will generate content.
filter The filter to select submissions.
out The output stream where to send the export too.
Definition at line 146 of file ExportExcelServiceImpl.java.
References org.tdl.vireo.export.impl.ExportExcelServiceImpl.context, org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.filter, org.tdl.vireo.security.SecurityContext.getPerson(), org.tdl.vireo.security.SecurityContext.isAuthorizationActive(), org.tdl.vireo.security.SecurityContext.isReviewer(), org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.meta, org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.out, org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.packager, and org.tdl.vireo.job.JobStatus.READY.
{
             this.packager = packager;
             this.filter = filter;
             this.out = out;
             if (context.getPerson() != null) {
                 if (!context.isReviewer())
                     throw new SecurityException("Not authorized to preform export operation.");
                 this.personId = context.getPerson().getId();
             } else {
                 if (!context.isAuthorizationActive())
                     throw new SecurityException("Not authorized to preform export operation.");
                 this.personId = null;
             }
             // Register the job's metadata
             meta = jobManager.register("Download " + packager.getDisplayName(), context.getPerson());
             meta.setJob(this);
             meta.setStatus(JobStatus.READY);
         }
Member Function Documentation
void org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.copyCell (XSSFCell source, XSSFCell dest) private
Copies an XSSFCell's value to another XSSFCell's value
Parameters
source - the source cell
dest - the destination cell
Definition at line 307 of file ExportExcelServiceImpl.java.
Referenced by org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.copyRow().
{
             switch (source.getCellType()) {
             case XSSFCell.CELL_TYPE_BLANK:
                 dest.setCellValue(source.getRawValue());
                 break;
             case XSSFCell.CELL_TYPE_BOOLEAN:
                 dest.setCellValue(source.getBooleanCellValue());
                 break;
             case XSSFCell.CELL_TYPE_ERROR:
                 dest.setCellValue(source.getErrorCellValue());
                 break;
             case XSSFCell.CELL_TYPE_FORMULA:
                 dest.setCellValue(source.getCellFormula());
                 break;
             case XSSFCell.CELL_TYPE_NUMERIC:
                 dest.setCellValue(source.getNumericCellValue());
                 break;
             case XSSFCell.CELL_TYPE_STRING:
                 dest.setCellValue(source.getStringCellValue());
                 break;
             }
         }
void org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.copyRow (XSSFRow source, XSSFRow dest) private
Copies an XSSFRow source to an XSSFRow destination, XSSFCell by XSSFCell
Parameters
source - the source row
dest - the destination row
Definition at line 293 of file ExportExcelServiceImpl.java.
References org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.copyCell().
Referenced by org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.doJob().
{
             for (Iterator it = source.cellIterator(); it.hasNext();) {
                 XSSFCell cell = (XSSFCell) it.next();
                 XSSFCell wbCell = dest.createCell(cell.getColumnIndex());
                 copyCell(cell, wbCell);
             }
         }
void org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.doJob () throws Exception
Run the back ground job.
Iterate through the submissions and stream each one into the a xlsx workbook.
The archive will be buffered, and sent directly to the ChunkStream to be transmitted to the browser.
This means we never have the complete archive on the server at any one time.
Exceptions
Exception
Definition at line 182 of file ExportExcelServiceImpl.java.
References org.tdl.vireo.search.SearchDirection.ASCENDING, org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.copyRow(), org.tdl.vireo.job.JobStatus.FAILED, org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.filter, org.tdl.vireo.job.JobMetadata.getProgress(), org.tdl.vireo.search.SearchOrder.ID, org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.meta, org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.out, org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.packager, org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.personId, org.tdl.vireo.job.JobStatus.RUNNING, org.tdl.vireo.export.impl.ExcelPackagerImpl.sheetName, and org.tdl.vireo.job.JobStatus.SUCCESS.
{
             try {
                 meta.setStatus(JobStatus.RUNNING);
                 if (personId != null) {
                     Person person = personRepo.findPerson(personId);
                     if (person == null)
                         throw new IllegalStateException("Unable to complete deposit job because person no longer exists.");
                     // Log the person in for this job.
                     context.login(person);
                 } else {
                     // Assume we're running as a background admin process.
                     context.turnOffAuthorization();
                 }
                 // Figure out how many submissions total we are exporting
                 long[] subIds = searcher.submissionSearch(filter, SearchOrder.ID, SearchDirection.ASCENDING);
                 meta.getProgress().total = subIds.length;
                 meta.getProgress().completed = 0;
                 // Start processing workbooks
                 BufferedOutputStream bos = new BufferedOutputStream(out);
                 XSSFWorkbook workbook = new XSSFWorkbook();
                 XSSFSheet wbkSheet = workbook.createSheet(ExcelPackagerImpl.sheetName);
                 // Iterate over all the items, adding each one to the export.
                 int i = 1;
                 for (long subId : subIds) {
                     Submission sub = subRepo.findSubmission(subId);
                     if (sub != null && packager instanceof AbstractExcelPackagerImpl) {
                         ExportExcel pkg = ((AbstractExcelPackagerImpl) packager).generateExcelPackage(sub, filter.getColumns());
                         XSSFSheet pkgSheet = pkg.getWorkbook().getSheet(ExcelPackagerImpl.sheetName);
                         // if this is the first submission, copy over its header (row 0)
                         if (i == 1) {
                             // create workbook heading row (0)
                             XSSFRow wbHeading = wbkSheet.createRow(0);
                             // get package heading row (0)
                             XSSFRow pkgHeading = pkgSheet.getRow(0);
                             // copy over row 0 to row 0
                             copyRow(pkgHeading, wbHeading);
                             // create workbook data row (1)
                             XSSFRow wbRow = wbkSheet.createRow(1);
                             // get package data row (1)
                             XSSFRow pkgRow = pkgSheet.getRow(1);
                             // copy over row 1 to row 1
                             copyRow(pkgRow, wbRow);
                         } else {
                             // create workbook data row (i)
                             XSSFRow wbRow = wbkSheet.createRow(i);
                             // get package data row (1)
                             XSSFRow pkgRow = pkgSheet.getRow(1);
                             // copy over row 1 to row i
                             copyRow(pkgRow, wbRow);
                         }
                         i++;
                     } else {
                         throw new Exception("Wrong packager type being used for this class or submission is null");
                     }
                     // Immediately save the transaction
                     JPA.em().getTransaction().commit();
                     JPA.em().clear();
                     JPA.em().getTransaction().begin();
                     // Don't let memory get out of control
                     System.gc();
                     meta.getProgress().completed++;
                 }
                 // write workbook to BufferedOutputStream
                 workbook.write(bos);
             } catch (RuntimeException re) {
                 Logger.fatal(re, "Unexepcted exception while exporting items. Aborted.");
                 meta.setMessage(re.toString());
                 meta.setStatus(JobStatus.FAILED);
                 errorLog.logError(re, meta);
                 throw re;
             } catch (IOException ioe) {
                 Logger.error(ioe, "Unexpected expection while exporting items. Aborted.");
                 meta.setMessage(ioe.toString());
                 meta.setStatus(JobStatus.FAILED);
                 errorLog.logError(ioe, meta);
                 throw ioe;
             } finally {
                 // Clean up the security context
                 if (personId != null) {
                     context.logout();
                 } else {
                     context.restoreAuthorization();
                 }
             }
             meta.setStatus(JobStatus.SUCCESS);
             meta.setJob(null);
         }
Member Data Documentation
final SearchFilter org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.filter
Definition at line 129 of file ExportExcelServiceImpl.java.
Referenced by org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.doJob(), and org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.ExportJob().
final JobMetadata org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.meta
Definition at line 134 of file ExportExcelServiceImpl.java.
Referenced by org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.doJob(), and org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.ExportJob().
final OutputStream org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.out
Definition at line 130 of file ExportExcelServiceImpl.java.
Referenced by org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.doJob(), and org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.ExportJob().
final Packager org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.packager
Definition at line 128 of file ExportExcelServiceImpl.java.
Referenced by org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.doJob(), and org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.ExportJob().
final Long org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.personId
Definition at line 131 of file ExportExcelServiceImpl.java.
Referenced by org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.doJob().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/export/impl/ExportExcelServiceImpl.java