Vireo: org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl Class Reference
org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl Class Reference
Public Member Functions
void setSubjects (Resource resource) throws IOException
void setLanguages (Resource resource) throws IOException
void setDegrees (Resource resource) throws IOException
List< ProquestSubject > findAllSubjects ()
ProquestSubject findSubjectByCode (String code)
ProquestSubject findSubjectByDescription (String description)
List< ProquestLanguage > findAllLanguages ()
ProquestLanguage findLanguageByCode (String code)
ProquestLanguage findLanguageByDescription (String description)
List< ProquestDegree > findAllDegrees ()
ProquestDegree findDegreeByCode (String code)
ProquestDegree findDegreeByDescription (String description)
Static Public Attributes
static List< ProquestSubject > subjects = new ArrayList<ProquestSubject>()
static List< ProquestLanguage > languages = new ArrayList<ProquestLanguage>()
static List< ProquestDegree > degrees = new ArrayList<ProquestDegree>()
Protected Member Functions
List< List< String > > _readSpreadsheet (File file) throws IOException
Private Member Functions
ProquestExcelVocabularyRepositoryImpl ()
Detailed Description
Controlled vocabulary repository for proquest values. This repository reads values at start up from excel spreedsheets for each value. The spreadsheets should be two columns, column A is the code, and column B is the description. The first row is always discarded as a header.
Author
Scott Phillips
Definition at line 40 of file ProquestExcelVocabularyRepositoryImpl.java.
Constructor & Destructor Documentation
org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.ProquestExcelVocabularyRepositoryImpl () private
Definition at line 52 of file ProquestExcelVocabularyRepositoryImpl.java.
{
         // Only spring can instantiate this class.
     }
Member Function Documentation
List<List<String> > org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl._readSpreadsheet (File file) throws IOException protected
Internal method to retrieve the contents of an excel spreadsheet. The contents of the spread sheet will be returned as a simple List of Lists corresponding to the rows and cells of the spreadsheet. This method does not handle multiple worksheets or any data types other than string.
Parameters
file The file to read.
Returns
The data read.
Definition at line 301 of file ProquestExcelVocabularyRepositoryImpl.java.
Referenced by org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.setDegrees(), org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.setLanguages(), and org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.setSubjects().
{
         // Read Workbook
         Workbook wb;
         InputStream is = new FileInputStream(file);
         try {
             String extension = FilenameUtils.getExtension(file.getName());
             if ("xlsx".equals(extension)) {
                 // Newer XML office format
                 // TODO: This appears to cause memory problems? I guess for now use the old format? Perhaps in a newer version of apache-poi this will work better.
                 wb = new XSSFWorkbook(is);
             } else {
                 // Older office 97 binary format
                 wb = new HSSFWorkbook(is);
             }
             // Read the data
             List<List<String>> rowsOut = new ArrayList<List<String>>();
             Sheet sheet = wb.getSheetAt(0);
             Iterator<Row> rows = sheet.rowIterator();
             while (rows.hasNext()) {
                 Row row = rows.next();
                 List<String> cellsOut = new ArrayList<String>();
                 Iterator<Cell> cells = row.cellIterator();
                 while (cells.hasNext()) {
                     Cell cell = cells.next();
                     String value = cell.getRichStringCellValue().getString();
                     cellsOut.add(value.trim());
                 }
                 rowsOut.add(cellsOut);
             }
             return rowsOut;
         } finally {
             wb = null;
             is.close();
             is = null;
             System.gc();
         }
     }
List<ProquestDegree> org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.findAllDegrees ()
Returns
A list of all degrees
Implements org.tdl.vireo.proquest.ProquestVocabularyRepository.
Definition at line 259 of file ProquestExcelVocabularyRepositoryImpl.java.
References org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.degrees.
{
         return new ArrayList<ProquestDegree>(degrees);
     }
List<ProquestLanguage> org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.findAllLanguages ()
Returns
A list of all languages
Implements org.tdl.vireo.proquest.ProquestVocabularyRepository.
Definition at line 226 of file ProquestExcelVocabularyRepositoryImpl.java.
References org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.languages.
{
         return new ArrayList<ProquestLanguage>(languages);
     }
List<ProquestSubject> org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.findAllSubjects ()
Returns
A list of all subjects
Implements org.tdl.vireo.proquest.ProquestVocabularyRepository.
Definition at line 190 of file ProquestExcelVocabularyRepositoryImpl.java.
References org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.subjects.
{
         return new ArrayList<ProquestSubject>(subjects);
     }
ProquestDegree org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.findDegreeByCode (String code)
Parameters
code The code to search for
Returns
The degree found, or null if not found.
Implements org.tdl.vireo.proquest.ProquestVocabularyRepository.
Definition at line 264 of file ProquestExcelVocabularyRepositoryImpl.java.
References org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.degrees.
{
         if (code == null)
             return null;
         for (ProquestDegree degree : degrees) {
             if (code.equals(degree.getCode())) {
                 return degree;
             }
         }
         return null;
     }
ProquestDegree org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.findDegreeByDescription (String description)
Parameters
description The description to search for
Returns
The degree found, or null if not found.
Implements org.tdl.vireo.proquest.ProquestVocabularyRepository.
Definition at line 278 of file ProquestExcelVocabularyRepositoryImpl.java.
References org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.degrees.
{
         if (description == null)
             return null;
         for (ProquestDegree degree : degrees) {
             if (description.equals(degree.getDescription())) {
                 return degree;
             }
         }
         return null;
     }
ProquestLanguage org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.findLanguageByCode (String code)
Parameters
code The code to search for
Returns
The language found, or null if not found.
Implements org.tdl.vireo.proquest.ProquestVocabularyRepository.
Definition at line 231 of file ProquestExcelVocabularyRepositoryImpl.java.
References org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.languages.
{
         if (code == null)
             return null;
         for (ProquestLanguage language : languages) {
             if (code.equals(language.getCode())) {
                 return language;
             }
         }
         return null;
     }
ProquestLanguage org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.findLanguageByDescription (String description)
Parameters
description The description to search for
Returns
The language found, or null if not found.
Implements org.tdl.vireo.proquest.ProquestVocabularyRepository.
Definition at line 245 of file ProquestExcelVocabularyRepositoryImpl.java.
References org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.languages.
{
         if (description == null)
             return null;
         for (ProquestLanguage language : languages) {
             if (description.equals(language.getDescription())) {
                 return language;
             }
         }
         return null;
     }
ProquestSubject org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.findSubjectByCode (String code)
Parameters
code The code to search for
Returns
The subject found, or null if not found.
Implements org.tdl.vireo.proquest.ProquestVocabularyRepository.
Definition at line 195 of file ProquestExcelVocabularyRepositoryImpl.java.
References org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.subjects.
{
         if (code == null)
             return null;
         for (ProquestSubject subject : subjects) {
             if (code.equals(subject.getCode())) {
                 return subject;
             }
         }
         return null;
     }
ProquestSubject org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.findSubjectByDescription (String description)
Parameters
description The description to search for
Returns
The subject found, or null if not found.
Implements org.tdl.vireo.proquest.ProquestVocabularyRepository.
Definition at line 210 of file ProquestExcelVocabularyRepositoryImpl.java.
References org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.subjects.
{
         if (description == null)
             return null;
         for (ProquestSubject subject : subjects) {
             if (description.equals(subject.getDescription())) {
                 return subject;
             }
         }
         return null;
     }
void org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.setDegrees (Resource resource) throws IOException
Set the degree vocabulary based upon the injected excel spreadsheet. The spreadsheet should consist of two columns; where column A is a degree code and column B is the description for that code. The first row of the spreadsheet is ignored as a header. Any previously defined degree will be removed.
Parameters
resource A file reference to an excel spread sheet (either hssf or xssf format).
Definition at line 155 of file ProquestExcelVocabularyRepositoryImpl.java.
References org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl._readSpreadsheet().
{
         File file = resource.getFile();
         if (file == null) {
             throw new IllegalArgumentException("Unable to load the proquest controlled vocabulary for degrees because the file was invalid.");
         }
         if (!file.exists()) {
             throw new IllegalArgumentException("Unable to load the proquest controlled vocabulary for degrees because the path '"+file.getPath()+"' does not exist.");
         }
         if (!file.canRead()) {
             throw new IllegalArgumentException("Unable to load the proquest controlled vocabulary for degrees because the path '"+file.getPath()+"' is not readable.");
         }
         List<List<String>> rows = _readSpreadsheet(file);
         // Ignore the heading row
         if (rows.size() > 0)
             rows.remove(0);
         // Read each remaining row as a degree.
         degrees.clear();
         for(List<String> row : rows) {
             String code = row.get(0);
             String description = row.get(1);
             ProquestDegree degree = new ProquestDegreeImpl(code.intern(),description.intern());
             degrees.add(degree);
         }
         Logger.debug("Loaded %d ProQuest controlled vocabulary for degrees from the spreadsheet: '%s'.", degrees.size(), file.getPath());
     }
void org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.setLanguages (Resource resource) throws IOException
Set the language vocabulary based upon the injected excel spreadsheet. The spreadsheet should consist of two columns; where column A is a language code and column B is the description for that code. The first row of the spreadsheet is ignored as a header. Any previously defined languages will be removed.
Parameters
resource A file reference to an excel spread sheet (either hssf or xssf format).
Definition at line 111 of file ProquestExcelVocabularyRepositoryImpl.java.
References org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl._readSpreadsheet().
{
         File file = resource.getFile();
         if (file == null) {
             throw new IllegalArgumentException("Unable to load the proquest controlled vocabulary for languages because the file was invalid.");
         }
         if (!file.exists()) {
             throw new IllegalArgumentException("Unable to load the proquest controlled vocabulary for languages because the path '"+file.getPath()+"' does not exist.");
         }
         if (!file.canRead()) {
             throw new IllegalArgumentException("Unable to load the proquest controlled vocabulary for languages because the path '"+file.getPath()+"' is not readable.");
         }
         List<List<String>> rows = _readSpreadsheet(file);
         // Ignore the heading row
         if (rows.size() > 0)
             rows.remove(0);
         // Read each remaining row as a language.
         languages.clear();
         for(List<String> row : rows) {
             String code = row.get(0);
             String description = row.get(1);
             ProquestLanguage language = new ProquestLanguageImpl(code.intern(),description.intern());
             languages.add(language);
         }
         Logger.debug("Loaded %d ProQuest controlled vocabulary for languages from the spreadsheet: '%s'.", languages.size(), file.getPath());
     }
void org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.setSubjects (Resource resource) throws IOException
Set the subjects vocabulary based upon the injected excel spreadsheet. The spreadsheet should consist of two columns; where column A is a subject code and column B is the description for that code. The first row of the spreadsheet is ignored as a header. Any previously defined subjects will be removed.
Parameters
resource A file reference to an excel spread sheet (either hssf or xssf format).
Definition at line 67 of file ProquestExcelVocabularyRepositoryImpl.java.
References org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl._readSpreadsheet().
{
         File file = resource.getFile();
         if (file == null) {
             throw new IllegalArgumentException("Unable to load the ProQuest controlled vocabulary for subjects because the file was invalid.");
         }
         if (!file.exists()) {
             throw new IllegalArgumentException("Unable to load the ProQuest controlled vocabulary for subjects because the path '"+file.getPath()+"' does not exist.");
         }
         if (!file.canRead()) {
             throw new IllegalArgumentException("Unable to load the ProQuest controlled vocabulary for subjects because the path '"+file.getPath()+"' is not readable.");
         }
         List<List<String>> rows = _readSpreadsheet(file);
         // Ignore the heading row
         if (rows.size() > 0)
             rows.remove(0);
         // Read each remaining row as a subject.
         subjects.clear();
         for(List<String> row : rows) {
             String code = row.get(0);
             String description = row.get(1);
             ProquestSubject subject = new ProquestSubjectImpl(code.intern(),description.intern());
             subjects.add(subject);
         }
         Logger.debug("Loaded %d ProQuest controlled vocabulary for subjects from the spreadsheet: '%s'.", subjects.size(), file.getPath());
     }
Member Data Documentation
List<ProquestDegree> org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.degrees = new ArrayList<ProquestDegree>() static
Definition at line 50 of file ProquestExcelVocabularyRepositoryImpl.java.
Referenced by org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.findAllDegrees(), org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.findDegreeByCode(), and org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.findDegreeByDescription().
List<ProquestLanguage> org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.languages = new ArrayList<ProquestLanguage>() static
Definition at line 47 of file ProquestExcelVocabularyRepositoryImpl.java.
Referenced by org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.findAllLanguages(), org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.findLanguageByCode(), and org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.findLanguageByDescription().
List<ProquestSubject> org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.subjects = new ArrayList<ProquestSubject>() static
Definition at line 44 of file ProquestExcelVocabularyRepositoryImpl.java.
Referenced by org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.findAllSubjects(), org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.findSubjectByCode(), and org.tdl.vireo.proquest.impl.ProquestExcelVocabularyRepositoryImpl.findSubjectByDescription().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/proquest/impl/ProquestExcelVocabularyRepositoryImpl.java