Vireo: org.tdl.vireo.search.impl.UriActiveSearchFilterImpl Class Reference
org.tdl.vireo.search.impl.UriActiveSearchFilterImpl Class Reference
Public Member Functions
void setPersonRepository (PersonRepository personRepo)
void setSubmissionRepository (SubmissionRepository subRepo)
void setSettingsRepository (SettingsRepository settingRepo)
List< Submission > getIncludedSubmissions ()
void addIncludedSubmission (Submission sub)
void removeIncludedSubmission (Submission sub)
List< Submission > getExcludedSubmissions ()
void addExcludedSubmission (Submission sub)
void removeExcludedSubmission (Submission sub)
List< ActionLog > getIncludedActionLogs ()
void addIncludedActionLog (ActionLog log)
void removeIncludedActionLog (ActionLog log)
List< ActionLog > getExcludedActionLogs ()
void addExcludedActionLog (ActionLog log)
void removeExcludedActionLog (ActionLog log)
List< String > getSearchText ()
void addSearchText (String text)
void removeSearchText (String text)
List< String > getStates ()
void addState (String state)
void removeState (String state)
List< Person > getAssignees ()
void addAssignee (Person assignee)
void removeAssignee (Person assignee)
List< EmbargoType > getEmbargoTypes ()
void addEmbargoType (EmbargoType type)
void removeEmbargoType (EmbargoType type)
List< Semester > getGraduationSemesters ()
void addGraduationSemester (Semester semester)
void removeGraduationSemester (Semester semester)
void addGraduationSemester (Integer year, Integer month)
void removeGraduationSemester (Integer year, Integer month)
List< String > getDegrees ()
void addDegree (String degree)
void removeDegree (String degree)
List< String > getDepartments ()
void addDepartment (String department)
void removeDepartment (String department)
List< String > getPrograms ()
void addProgram (String program)
void removeProgram (String program)
List< String > getColleges ()
void addCollege (String college)
void removeCollege (String college)
List< String > getMajors ()
void addMajor (String major)
void removeMajor (String major)
List< String > getDocumentTypes ()
void addDocumentType (String documentType)
void removeDocumentType (String documentType)
Boolean getUMIRelease ()
void setUMIRelease (Boolean value)
Date getDateRangeStart ()
void setDateRangeStart (Date start)
Date getDateRangeEnd ()
void setDateRangeEnd (Date end)
List< SearchOrder > getColumns ()
void setColumns (List< SearchOrder > columns)
List< CustomActionDefinition > getCustomActions ()
void addCustomAction (CustomActionDefinition customAction)
void removeCustomAction (CustomActionDefinition customAction)
String encode ()
void decode (String encoded)
void copyTo (SearchFilter other)
void copyFrom (SearchFilter other)
Public Attributes
PersonRepository personRepo = null
SubmissionRepository subRepo = null
SettingsRepository settingRepo = null
List< Submission > includedSubmissions = new ArrayList<Submission>()
List< Submission > excludedSubmissions = new ArrayList<Submission>()
List< ActionLog > includedActionLogs = new ArrayList<ActionLog>()
List< ActionLog > excludedActionLogs = new ArrayList<ActionLog>()
List< String > searchText = new ArrayList<String>()
List< String > states = new ArrayList<String>()
List< Person > assignees = new ArrayList<Person>()
List< EmbargoType > embargos = new ArrayList<EmbargoType>()
List< Semester > semesters = new ArrayList<Semester>()
List< String > degrees = new ArrayList<String>()
List< String > departments = new ArrayList<String>()
List< String > programs = new ArrayList<String>()
List< String > colleges = new ArrayList<String>()
List< String > majors = new ArrayList<String>()
List< String > documentTypes = new ArrayList<String>()
Boolean umiRelease = null
Date rangeStart = null
Date rangeEnd = null
List< SearchOrder > columns = new ArrayList<SearchOrder>()
List< CustomActionDefinition > customActions = new ArrayList<CustomActionDefinition>()
Protected Member Functions
void encodeList (StringBuilder result, List<?> values)
String escape (String raw)
String unescape (String escapped)
Package Functions
protected< T > List< T > decodeList (String encoded, Class< T > type)
Private Member Functions
UriActiveSearchFilterImpl ()
Detailed Description
An URI based implementation of active search.
The encode and decode strings generated by this are escaped using URI escaping rules, thus it's inherently URI safe.
Author
Scott Phillips
Micah Cooper
Definition at line 35 of file UriActiveSearchFilterImpl.java.
Constructor & Destructor Documentation
org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.UriActiveSearchFilterImpl () private
Use Spring to construct this object.
Definition at line 67 of file UriActiveSearchFilterImpl.java.
{
         // Use Spring
     }
Member Function Documentation
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.addAssignee (Person assignee)
Parameters
assignee A new assignee to add to the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 191 of file UriActiveSearchFilterImpl.java.
{
         assignees.add(assignee);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.addCollege (String college)
Parameters
college Add a new college to the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 291 of file UriActiveSearchFilterImpl.java.
{
         colleges.add(college);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.addCustomAction (CustomActionDefinition customAction)
Parameters
customAction The custom action to add to the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 376 of file UriActiveSearchFilterImpl.java.
{
         customActions.add(customAction);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.addDegree (String degree)
Parameters
degree A a new degree to the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 246 of file UriActiveSearchFilterImpl.java.
{
         degrees.add(degree);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.addDepartment (String department)
Parameters
department Add a new department to the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 261 of file UriActiveSearchFilterImpl.java.
{
         departments.add(department);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.addDocumentType (String documentType)
Parameters
documentType add a new documentType to the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 321 of file UriActiveSearchFilterImpl.java.
{
         documentTypes.add(documentType);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.addEmbargoType (EmbargoType type)
Parameters
type The embargo type to add to the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 206 of file UriActiveSearchFilterImpl.java.
{
         embargos.add(type);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.addExcludedActionLog (ActionLog log)
Parameters
log Add an individual logs this filter will exclude.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 146 of file UriActiveSearchFilterImpl.java.
{
         excludedActionLogs.add(log);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.addExcludedSubmission (Submission sub)
Parameters
sub Add an individual submission this filter will exclude.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 116 of file UriActiveSearchFilterImpl.java.
{
         excludedSubmissions.add(sub);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.addGraduationSemester (Semester semester)
Parameters
semester The graduation semester to add to the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 221 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.addGraduationSemester().
{
         semesters.add(semester);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.addGraduationSemester (Integer year, Integer month)
Add a graduation semester with the provided year and month.
Parameters
year The graduation year.
month The graduation month.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 231 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.addGraduationSemester().
{
         addGraduationSemester(new Semester(year,month));
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.addIncludedActionLog (ActionLog log)
Parameters
log Add an individual log this filter is limmitted too.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 131 of file UriActiveSearchFilterImpl.java.
{
         includedActionLogs.add(log);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.addIncludedSubmission (Submission sub)
Parameters
sub Add an individual submission this filter is limmitted too.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 101 of file UriActiveSearchFilterImpl.java.
{
         includedSubmissions.add(sub);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.addMajor (String major)
Parameters
major Add a new major to the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 306 of file UriActiveSearchFilterImpl.java.
{
         majors.add(major);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.addProgram (String program)
Parameters
program Add a new program to the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 276 of file UriActiveSearchFilterImpl.java.
{
         programs.add(program);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.addSearchText (String text)
Parameters
text The new text search to add.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 161 of file UriActiveSearchFilterImpl.java.
{
         searchText.add(text);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.addState (String state)
Parameters
status The new state to add to the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 176 of file UriActiveSearchFilterImpl.java.
{
         states.add(state);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.copyFrom (SearchFilter otherFilter)
Modify the state of this search filter so that it copies the exact state of the other filter. The other filter will not be modified.
Note, the current state of this filter will be completely lost.
Parameters
otherFilter The filter to copy from.
Implements org.tdl.vireo.search.ActiveSearchFilter.
Definition at line 577 of file UriActiveSearchFilterImpl.java.
{
         this.includedSubmissions = new ArrayList<Submission>(other.getIncludedSubmissions());
         this.excludedSubmissions = new ArrayList<Submission>(other.getExcludedSubmissions());
         this.includedActionLogs = new ArrayList<ActionLog>(other.getIncludedActionLogs());
         this.excludedActionLogs = new ArrayList<ActionLog>(other.getExcludedActionLogs());
         this.searchText = new ArrayList<String>(other.getSearchText());
         this.states = new ArrayList<String>(other.getStates());
         this.assignees = new ArrayList<Person>(other.getAssignees());
         this.embargos = new ArrayList<EmbargoType>(other.getEmbargoTypes());
         this.semesters = new ArrayList<Semester>(other.getGraduationSemesters());
         this.degrees = new ArrayList<String>(other.getDegrees());
         this.departments = new ArrayList<String>(other.getDepartments());
         this.colleges = new ArrayList<String>(other.getColleges());
         this.programs = new ArrayList<String>(other.getPrograms());
         this.majors = new ArrayList<String>(other.getMajors());
         this.documentTypes = new ArrayList<String>(other.getDocumentTypes());
         this.columns = new ArrayList<SearchOrder>(other.getColumns());
         this.customActions = new ArrayList<CustomActionDefinition>(other.getCustomActions());
         this.umiRelease = other.getUMIRelease();
         this.rangeStart = other.getDateRangeStart();
         this.rangeEnd = other.getDateRangeEnd();
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.copyTo (SearchFilter otherFilter)
Modify the state of the provided filter so that it matches the state of this filter exactly.
Note, the state of the other filter will be completely lost.
Parameters
otherFilter The filter to be modified.
Implements org.tdl.vireo.search.ActiveSearchFilter.
Definition at line 507 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.assignees, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.colleges, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.columns, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.customActions, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.degrees, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.departments, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.documentTypes, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.embargos, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.excludedActionLogs, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.excludedSubmissions, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.includedActionLogs, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.includedSubmissions, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.majors, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.programs, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.searchText, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.semesters, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.states.
{
         // We're going to be sneaky and take advantage of the fact that the list return by all filters are mutable.
         other.getIncludedSubmissions().clear();
         other.getIncludedSubmissions().addAll(this.includedSubmissions);
         other.getExcludedSubmissions().clear();
         other.getExcludedSubmissions().addAll(this.excludedSubmissions);
         other.getIncludedActionLogs().clear();
         other.getIncludedActionLogs().addAll(this.includedActionLogs);
         other.getExcludedActionLogs().clear();
         other.getExcludedActionLogs().addAll(this.excludedActionLogs);
         other.getSearchText().clear();
         other.getSearchText().addAll(this.searchText);
         other.getStates().clear();
         other.getStates().addAll(this.states);
         other.getAssignees().clear();
         for(Person assignee : this.assignees) {
             other.addAssignee(assignee);
         }
         /*
          *  For some reason this wont work.
          *  other.getAssignees().addAll(this.assignees);
          */
         other.getEmbargoTypes().clear();
         other.getEmbargoTypes().addAll(this.embargos);
         other.getGraduationSemesters().clear();
         other.getGraduationSemesters().addAll(this.semesters);
         other.getDegrees().clear();
         other.getDegrees().addAll(this.degrees);
         other.getDepartments().clear();
         other.getDepartments().addAll(this.departments);
         other.getColleges().clear();
         other.getColleges().addAll(this.colleges);
         other.getPrograms().clear();
         other.getPrograms().addAll(this.programs);
         other.getMajors().clear();
         other.getMajors().addAll(this.majors);
         other.getDocumentTypes().clear();
         other.getDocumentTypes().addAll(this.documentTypes);
         other.getColumns().clear();
         other.getColumns().addAll(this.columns);
         other.getCustomActions().clear();
         for(CustomActionDefinition customAction : this.customActions) {
             other.addCustomAction(customAction);
         }
         //other.getCustomActions().addAll(this.customActions);
         other.setUMIRelease(this.umiRelease);
         other.setDateRangeStart(this.rangeStart);
         other.setDateRangeEnd(this.rangeEnd);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode (String serialize)
Set the current state of this search filter to that of the encoded filter. The filter used here should have been generated by another ActiveSearchFilter of the same implementation and will restore the state of that original filter.
The current state of this filter will be completely lost.
Parameters
serialize The encoded filter state
Implements org.tdl.vireo.search.ActiveSearchFilter.
Definition at line 442 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.assignees, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.colleges, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.columns, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.customActions, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decodeList(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.degrees, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.departments, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.documentTypes, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.embargos, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.excludedActionLogs, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.excludedSubmissions, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.includedActionLogs, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.includedSubmissions, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.majors, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.programs, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.rangeEnd, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.rangeStart, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.searchText, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.semesters, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.states, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.umiRelease.
{
         try {
             String[] split = encoded.split(":",-1);
             if (split.length != 22)
                 throw new IllegalArgumentException("Unable to decode active search filter because it does not have the 19 expected number of components instead it has "+split.length);
             // Decode all the lists
             int i = 1;
             includedSubmissions = decodeList(split[i++],Submission.class);
             excludedSubmissions = decodeList(split[i++],Submission.class);
             includedActionLogs = decodeList(split[i++],ActionLog.class);
             excludedActionLogs = decodeList(split[i++],ActionLog.class);
             searchText = decodeList(split[i++],String.class);
             states = decodeList(split[i++],String.class);
             assignees = decodeList(split[i++],Person.class);
             embargos = decodeList(split[i++],EmbargoType.class);
             semesters = decodeList(split[i++],Semester.class);
             degrees = decodeList(split[i++],String.class);
             departments = decodeList(split[i++],String.class);
             colleges = decodeList(split[i++],String.class);
             programs = decodeList(split[i++],String.class);
             majors = decodeList(split[i++],String.class);
             documentTypes = decodeList(split[i++],String.class);
             columns = decodeList(split[i++],SearchOrder.class);
             customActions = decodeList(split[i++],CustomActionDefinition.class);
             // Handle the single values
             if ("true".equalsIgnoreCase(split[i])) {
                 umiRelease = true;
             } else if ("false".equalsIgnoreCase(split[i])) {
                 umiRelease = false;
             } else {
                 umiRelease = null;
             }
             i++;
             if (split[i].length() != 0) {
                 try {
                     rangeStart = new Date(Long.valueOf(split[i]));
                 } catch (RuntimeException re) {
                     Logger.warn("Unable to decode value '"+split[i]+"' for rangeStart.");
                 }
             } else {
                 rangeStart = null;
             }
             i++;
             if (split[i].length() != 0) {
                 try {
                     rangeEnd = new Date(Long.valueOf(split[i]));
                 } catch (RuntimeException re) {
                     Logger.warn("Unable to decode value '"+split[i]+"' for rangeEnd.");
                 }
             } else {
                 rangeEnd = null;
             }
         } catch (RuntimeException re) {
             // If anything other than the specific cases we have already caught
             // just wrapped the exception with more information.
             throw new RuntimeException("Unable to decode the search filter: " + encoded, re);
         }
     }
protected<T> List<T> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decodeList (String encoded, Class< T > type) package
Internal method to decode an individual list of items from its serialized form.
Parameters
encoded The encoded string.
type The type of object expected.
Returns
A list of encoded objects
Definition at line 613 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.unescape().
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode().
{
         String[] split = encoded.split(",");
         List<T> result = new ArrayList<T>();
         for (String raw : split) {
             if (raw.length() ==0)
                 continue;
             try {
                 if ( type == String.class) {
                     // List type is string
                     result.add( (T) unescape(raw));
                 } else if (type == Integer.class) {
                     // List type is integer, grad month or year
                     Integer value = Integer.valueOf(raw);
                     result.add((T) value);
                 } else if (type == Person.class){
                     // List type is person, just for assignee
                     if ("null".equals(raw)) {
                         result.add(null); // unassigned
                     } else {
                         Long personId = Long.valueOf(raw);
                         Person person = personRepo.findPerson(personId);
                         result.add((T) person);
                     }
                 } else if (type == Submission.class) {
                     // List type is submission
                     Long subId = Long.valueOf(raw);
                     Submission sub = subRepo.findSubmission(subId);
                     result.add((T) sub);
                 } else if (type == ActionLog.class) {
                     // List type is ActionLog
                     Long logId = Long.valueOf(raw);
                     ActionLog log = subRepo.findActionLog(logId);
                     result.add((T) log);
                 } else if (type == EmbargoType.class) {
                     // List type is embargo types
                     Long embargoId = Long.valueOf(raw);
                     EmbargoType embargo = settingRepo.findEmbargoType(embargoId);
                     result.add((T) embargo);
                 } else if (type == Semester.class) {
                     // List type is graduation semestens: year/month
                     String[] semesterSplit = raw.split("/");
                     Semester semester = new Semester();
                     if (!"null".equals(semesterSplit[0]))
                         semester.year = Integer.valueOf(semesterSplit[0]);
                     if (!"null".equals(semesterSplit[1]))
                         semester.month = Integer.valueOf(semesterSplit[1]);
                     result.add((T) semester);
                 } else if (type == SearchOrder.class) {
                     // List type is SearchOrder column
                     int columnId = Integer.valueOf(raw);
                     SearchOrder column = SearchOrder.find(columnId);
                     result.add((T) column);
                 } else if (type == CustomActionDefinition.class) {
                     // List type is CustomActionDefinition
                     Long customActionId = Long.valueOf(raw);
                     CustomActionDefinition customAction = settingRepo.findCustomActionDefinition(customActionId);
                     result.add((T) customAction);
                 } else {
                     throw new IllegalArgumentException("Unable to decode unexpected object type: "+ type);
                 }
             } catch (RuntimeException re) {
                 // Just log the error but keep on trucking. One legitimate
                 // reason why this may fail is if a person has been deleted
                 // since this filter was created, thus the person's id would no
                 // longer be valid.
                 Logger.warn(re,"Unable to decode value '"+raw+"' for type "+type.getName());
             }
         }
         return result;
     }
String org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode ()
The string generated by this encoding will be of the form:
:value1,value2:value1,value2:
Each list of values such as searchText, degrees, departments, etc, are separated by ":" and inside each of those lists individual values are separated by ",". Thus the null search filter would be: "::::::::::::::" All the lists would be null in this case.
Implements org.tdl.vireo.search.ActiveSearchFilter.
Definition at line 396 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.assignees, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.colleges, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.columns, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.customActions, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.degrees, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.departments, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.documentTypes, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.embargos, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encodeList(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.excludedActionLogs, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.excludedSubmissions, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.includedActionLogs, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.includedSubmissions, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.majors, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.programs, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.rangeEnd, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.rangeStart, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.searchText, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.semesters, org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.states, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.umiRelease.
{
         // Format: :one,two:other,bob:
         StringBuilder result = new StringBuilder();
         result.append(":");
         // Handle all the lists.
         encodeList(result,includedSubmissions);
         encodeList(result,excludedSubmissions);
         encodeList(result,includedActionLogs);
         encodeList(result,excludedActionLogs);
         encodeList(result,searchText);
         encodeList(result,states);
         encodeList(result,assignees);
         encodeList(result,embargos);
         encodeList(result,semesters);
         encodeList(result,degrees);
         encodeList(result,departments);
         encodeList(result,colleges);
         encodeList(result,programs);
         encodeList(result,majors);
         encodeList(result,documentTypes);
         encodeList(result,columns);
         encodeList(result,customActions);
         // Handle the single values.
         if (umiRelease != null) {
             result.append(umiRelease.toString());
         }
         result.append(":");
         if (rangeStart != null) {
             result.append(rangeStart.getTime());
         }
         result.append(":");
         if (rangeEnd != null) {
             result.append(rangeEnd.getTime());
         }
         result.append(":");
         return result.toString();
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encodeList (StringBuilder result, List<?> values) protected
Encode the list of provided objects. The result stringbuilder will be modified to include a comma separated list of values, and for convenience will end with a trailing ":". If the value type is string then it will be URI encoded prior to putting in the list.
Only three datatypes are supported by this method: String, Integer, Person, EmbargoType, and GraduationSemester. everything else will result in an error.
Parameters
result Where the encoded list will be appended.
values The values to encode.
Definition at line 715 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.escape(), org.tdl.vireo.search.Semester.month, and org.tdl.vireo.search.Semester.year.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode().
{
         boolean first = true;
         for (Object value: values) {
             if (first)
                 first = false;
             else
                 result.append(",");
             if (value == null) {
                 result.append("null");
             } else if (value instanceof String) {
                 // Plain old strings, the most common case.
                 result.append(escape((String)value));
             } else if (value instanceof Integer){
                 // Integers from grad month & year
                 result.append(String.valueOf((Integer) value));
             } else if (value instanceof Person) {
                 // Full person object from assignee
                 Long personId = ((Person) value).getId();
                 result.append(String.valueOf(personId));
             } else if (value instanceof Submission) {
                 // Full submission object
                 Long subId = ((Submission) value).getId();
                 result.append(String.valueOf(subId));
             } else if (value instanceof ActionLog) {
                 // Full actionlog object
                 Long logId = ((ActionLog) value).getId();
                 result.append(String.valueOf(logId));
             } else if (value instanceof EmbargoType) {
                 // Full embargo object
                 Long embargoId = ((EmbargoType) value).getId();
                 result.append(String.valueOf(embargoId));
             } else if (value instanceof SearchOrder) {
                 // Full SearchOrder(column) object
                 int columnId = ((SearchOrder)value).getId();
                 result.append(String.valueOf(columnId));
             } else if (value instanceof Semester) {
                 // Graduation semester: year/month
                 Semester semester = (Semester) value;
                 if (semester.year == null)
                     result.append("null");
                 else
                     result.append(String.valueOf(semester.year));
                 result.append("/");
                 if (semester.month == null)
                     result.append("null");
                 else
                     result.append(String.valueOf(semester.month));
             } else if (value instanceof CustomActionDefinition) {
                 // Full CustomActionDefinition object
                 Long customActionId = ((CustomActionDefinition)value).getId();
                 result.append(String.valueOf(customActionId));
             } else {
                 throw new IllegalArgumentException("Unable to encode unexpected object type: "+value.getClass().getName());
             }
         }
         // Signify end of list
         result.append(":");
     }
String org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.escape (String raw) protected
URI escape the provided value. This method will alse ensure that all ":" and "," are escaped as well even though they not nessesaraly be. Otherwise they will interfear with the encoding of other paramaters.
Parameters
raw The raw value to be escaped.
Returns
The resulting escaped value.
Definition at line 797 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encodeList().
{
         String escapped = URLEncoder.encode(raw);
         escapped = escapped.replaceAll(",", "%2C");
         escapped = escapped.replaceAll(":", "%3A");
         return escapped;
     }
List<Person> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getAssignees ()
Returns
The list of assignees to filter for.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 186 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.assignees.
{
         return assignees;
     }
List<String> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getColleges ()
Returns
The list of colleges
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 286 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.colleges.
{
         return colleges;
     }
List<SearchOrder> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getColumns ()
Returns
The list of columns associated with this SearchFilter
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 361 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.columns.
{
         return columns;
     }
List<CustomActionDefinition> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getCustomActions ()
Returns
The custom actions
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 371 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.customActions.
{
         return customActions;
     }
Date org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getDateRangeEnd ()
Returns
The end of the current date range search.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 351 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.rangeEnd.
{
         return rangeEnd;
     }
Date org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getDateRangeStart ()
Returns
The start of the current date range search.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 341 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.rangeStart.
{
         return rangeStart;
     }
List<String> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getDegrees ()
Returns
The list of degrees
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 241 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.degrees.
{
         return degrees;
     }
List<String> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getDepartments ()
Returns
The list of departments.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 256 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.departments.
{
         return departments;
     }
List<String> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getDocumentTypes ()
Returns
The list of document types
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 316 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.documentTypes.
{
         return documentTypes;
     }
List<EmbargoType> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getEmbargoTypes ()
Returns
The list of embago types to filter for.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 201 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.embargos.
{
         return embargos;
     }
List<ActionLog> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getExcludedActionLogs ()
Returns
A list of individual logs this filter will exclude.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 141 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.excludedActionLogs.
{
         return excludedActionLogs;
     }
List<Submission> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getExcludedSubmissions ()
Returns
A list of individual submissions this filter will exclude.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 111 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.excludedSubmissions.
{
         return excludedSubmissions;
     }
List<Semester> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getGraduationSemesters ()
Returns
The graduation semesters
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 216 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.semesters.
{
         return semesters;
     }
List<ActionLog> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getIncludedActionLogs ()
Returns
A list of individual logs this filter is restricted too.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 126 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.includedActionLogs.
{
         return includedActionLogs;
     }
List<Submission> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getIncludedSubmissions ()
Returns
A list of individual submissions this filter is restricted too.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 96 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.includedSubmissions.
{
         return includedSubmissions;
     }
List<String> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getMajors ()
Returns
The list of majors
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 301 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.majors.
{
         return majors;
     }
List<String> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getPrograms ()
Returns
The list of programs
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 271 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.programs.
{
         return programs;
     }
List<String> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getSearchText ()
Returns
The list of all free-form search parameters
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 156 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.searchText.
{
         return searchText;
     }
List<String> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getStates ()
Returns
The list of all submission states to search for. Only valid Spring Bean Names should be included in this list.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 171 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.states.
{
         return states;
     }
Boolean org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getUMIRelease ()
True -> applications are set to be released to UMI
False -> applications are not set to be released.
Null -> Either released or not.
Returns
How to filter for UMI release
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 331 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.umiRelease.
{
         return umiRelease;
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.removeAssignee (Person assignee)
Parameters
assignee The assignee to remove from the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 196 of file UriActiveSearchFilterImpl.java.
{
         assignees.remove(assignee);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.removeCollege (String college)
Parameters
college Remove a college from the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 296 of file UriActiveSearchFilterImpl.java.
{
         colleges.remove(college);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.removeCustomAction (CustomActionDefinition customAction)
Parameters
customAction The custom action to remove from the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 381 of file UriActiveSearchFilterImpl.java.
{
         customActions.remove(customAction);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.removeDegree (String degree)
Parameters
degree Remove a degree from the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 251 of file UriActiveSearchFilterImpl.java.
{
         degrees.remove(degree);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.removeDepartment (String department)
Parameters
department remove a department from the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 266 of file UriActiveSearchFilterImpl.java.
{
         departments.remove(department);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.removeDocumentType (String documentType)
Parameters
documentType Remove a document type from the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 326 of file UriActiveSearchFilterImpl.java.
{
         documentTypes.remove(documentType);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.removeEmbargoType (EmbargoType type)
Parameters
type The embargo type to remove from the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 211 of file UriActiveSearchFilterImpl.java.
{
         embargos.remove(type);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.removeExcludedActionLog (ActionLog log)
Parameters
log Remove an individual logs from this filter this filter will no longer exclude.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 151 of file UriActiveSearchFilterImpl.java.
{
         excludedActionLogs.remove(log);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.removeExcludedSubmission (Submission sub)
Parameters
sub Remove an individual submission from this filter this filter will no longer exclude.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 121 of file UriActiveSearchFilterImpl.java.
{
         excludedSubmissions.remove(sub);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.removeGraduationSemester (Semester semester)
Parameters
semester The graduation semester to remove from the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 226 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.removeGraduationSemester().
{
         semesters.remove(semester);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.removeGraduationSemester (Integer year, Integer month)
Remove a graduation semester with the provided year and month.
Parameters
year The graduation year.
month The graduation month.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 236 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.removeGraduationSemester().
{
         removeGraduationSemester(new Semester(year,month));
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.removeIncludedActionLog (ActionLog log)
Parameters
log Remove an individual log from this filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 136 of file UriActiveSearchFilterImpl.java.
{
         includedActionLogs.remove(log);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.removeIncludedSubmission (Submission sub)
Parameters
sub Remove an individual submission from this filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 106 of file UriActiveSearchFilterImpl.java.
{
         includedSubmissions.remove(sub);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.removeMajor (String major)
Parameters
major Remove a major from the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 311 of file UriActiveSearchFilterImpl.java.
{
         majors.remove(major);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.removeProgram (String program)
Parameters
program Remove a program from the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 281 of file UriActiveSearchFilterImpl.java.
{
         programs.remove(program);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.removeSearchText (String text)
Parameters
text The text search to remove
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 166 of file UriActiveSearchFilterImpl.java.
{
         searchText.remove(text);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.removeState (String state)
Parameters
status Remove the state from the filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 181 of file UriActiveSearchFilterImpl.java.
{
         states.remove(state);
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.setColumns (List< SearchOrder > columns)
Parameters
columns - The list of columns associated with this SearchFilter
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 366 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.columns.
{
         this.columns = columns;
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.setDateRangeEnd (Date end)
Parameters
end The new end of the date range, may be null for infinite
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 356 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.rangeEnd.
{
         rangeEnd = end;
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.setDateRangeStart (Date start)
Parameters
start The new start of the date range, may be null for infinite.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 346 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.rangeStart.
{
         rangeStart = start;
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.setPersonRepository (PersonRepository personRepo)
Parameters
personRepo The person repository to use for looking up people.
Definition at line 75 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.personRepo.
{
         this.personRepo = personRepo;
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.setSettingsRepository (SettingsRepository settingRepo)
Parameters
settingRepo The setting repository to use for looking up embargo types.
Definition at line 91 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.settingRepo.
{
         this.settingRepo = settingRepo;
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.setSubmissionRepository (SubmissionRepository subRepo)
Parameters
subRepo The submission repository to use for looking up submissions.
Definition at line 83 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.subRepo.
{
         this.subRepo = subRepo;
     }
void org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.setUMIRelease (Boolean value)
Parameters
value Set the UMI release filter.
Implements org.tdl.vireo.search.SearchFilter.
Definition at line 336 of file UriActiveSearchFilterImpl.java.
References org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.umiRelease.
{
         umiRelease = value;
     }
String org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.unescape (String escapped) protected
Unescape a previously escaped value. This will just do a regular URI escapeing on the value.
Parameters
escapped The escaped value.
Returns
The original raw string.
Definition at line 812 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decodeList().
{
         return URLDecoder.decode(escapped);
     }
Member Data Documentation
List<Person> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.assignees = new ArrayList<Person>()
Definition at line 49 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.copyTo(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode(), and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getAssignees().
List<String> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.colleges = new ArrayList<String>()
Definition at line 55 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.copyTo(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode(), and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getColleges().
List<SearchOrder> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.columns = new ArrayList<SearchOrder>()
Definition at line 61 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.copyTo(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getColumns(), and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.setColumns().
List<CustomActionDefinition> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.customActions = new ArrayList<CustomActionDefinition>()
Definition at line 62 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.copyTo(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode(), and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getCustomActions().
List<String> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.degrees = new ArrayList<String>()
Definition at line 52 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.copyTo(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode(), and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getDegrees().
List<String> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.departments = new ArrayList<String>()
Definition at line 53 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.copyTo(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode(), and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getDepartments().
List<String> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.documentTypes = new ArrayList<String>()
Definition at line 57 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.copyTo(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode(), and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getDocumentTypes().
List<EmbargoType> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.embargos = new ArrayList<EmbargoType>()
Definition at line 50 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.copyTo(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode(), and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getEmbargoTypes().
List<ActionLog> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.excludedActionLogs = new ArrayList<ActionLog>()
Definition at line 46 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.copyTo(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode(), and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getExcludedActionLogs().
List<Submission> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.excludedSubmissions = new ArrayList<Submission>()
Definition at line 44 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.copyTo(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode(), and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getExcludedSubmissions().
List<ActionLog> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.includedActionLogs = new ArrayList<ActionLog>()
Definition at line 45 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.copyTo(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode(), and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getIncludedActionLogs().
List<Submission> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.includedSubmissions = new ArrayList<Submission>()
Definition at line 43 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.copyTo(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode(), and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getIncludedSubmissions().
List<String> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.majors = new ArrayList<String>()
Definition at line 56 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.copyTo(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode(), and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getMajors().
PersonRepository org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.personRepo = null
Definition at line 38 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.setPersonRepository().
List<String> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.programs = new ArrayList<String>()
Definition at line 54 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.copyTo(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode(), and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getPrograms().
Date org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.rangeEnd = null
Definition at line 60 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getDateRangeEnd(), and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.setDateRangeEnd().
Date org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.rangeStart = null
Definition at line 59 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getDateRangeStart(), and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.setDateRangeStart().
List<String> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.searchText = new ArrayList<String>()
Definition at line 47 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.copyTo(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode(), and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getSearchText().
List<Semester> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.semesters = new ArrayList<Semester>()
Definition at line 51 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.copyTo(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode(), and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getGraduationSemesters().
SettingsRepository org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.settingRepo = null
Definition at line 40 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.setSettingsRepository().
List<String> org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.states = new ArrayList<String>()
Definition at line 48 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.copyTo(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode(), and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getStates().
SubmissionRepository org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.subRepo = null
Definition at line 39 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.setSubmissionRepository().
Boolean org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.umiRelease = null
Definition at line 58 of file UriActiveSearchFilterImpl.java.
Referenced by org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.decode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.encode(), org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.getUMIRelease(), and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.setUMIRelease().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/search/impl/UriActiveSearchFilterImpl.java