Vireo: org.tdl.vireo.security.impl.SecurityContextImpl Class Reference
org.tdl.vireo.security.impl.SecurityContextImpl Class Reference
Public Member Functions
void login (Person person)
void logout ()
Person getPerson ()
RoleType getRole ()
boolean isAdministrator ()
boolean isManager ()
boolean isReviewer ()
boolean isStudent ()
boolean isAuthenticated ()
void turnOffAuthorization ()
void restoreAuthorization ()
boolean isAuthorizationActive ()
Public Attributes
ThreadLocal< Person > personLocal = new ThreadLocal<Person>()
ThreadLocal< Stack< Boolean > > authorizationStateHistory = new ThreadLocal<Stack<Boolean>>()
Private Member Functions
void resetAuthorizationStack ()
Detailed Description
Simple ThreadLocal-backed Security context.
Author
Scott Phillips
Definition at line 15 of file SecurityContextImpl.java.
Member Function Documentation
Person org.tdl.vireo.security.impl.SecurityContextImpl.getPerson ()
Returns
The currently authenticated person, or null if none one is authenticated.
Implements org.tdl.vireo.security.SecurityContext.
Definition at line 37 of file SecurityContextImpl.java.
{
         return personLocal.get();
     }
RoleType org.tdl.vireo.security.impl.SecurityContextImpl.getRole ()
A sort of private method to return the role of the current user. Should this be pushed up to the interface level?
Returns
The current user's role or null.
Definition at line 47 of file SecurityContextImpl.java.
References org.tdl.vireo.security.impl.SecurityContextImpl.personLocal.
Referenced by org.tdl.vireo.security.impl.SecurityContextImpl.isAdministrator(), org.tdl.vireo.security.impl.SecurityContextImpl.isManager(), org.tdl.vireo.security.impl.SecurityContextImpl.isReviewer(), and org.tdl.vireo.security.impl.SecurityContextImpl.isStudent().
{
         if (personLocal.get() != null)
             return personLocal.get().getRole();
         return null;
     }
boolean org.tdl.vireo.security.impl.SecurityContextImpl.isAdministrator ()
Returns
true if the current user has the role ADMINISTRATOR
Implements org.tdl.vireo.security.SecurityContext.
Definition at line 54 of file SecurityContextImpl.java.
References org.tdl.vireo.model.RoleType.ADMINISTRATOR, and org.tdl.vireo.security.impl.SecurityContextImpl.getRole().
{
         RoleType role = getRole();
         if (role == RoleType.ADMINISTRATOR)
             return true;
         return false;
     }
boolean org.tdl.vireo.security.impl.SecurityContextImpl.isAuthenticated ()
Returns
true if there is a currently authenticated person.
Implements org.tdl.vireo.security.SecurityContext.
Definition at line 92 of file SecurityContextImpl.java.
{
         return personLocal.get() != null;
     }
boolean org.tdl.vireo.security.impl.SecurityContextImpl.isAuthorizationActive ()
Returns
whether authorization checks have been deactivated.
Implements org.tdl.vireo.security.SecurityContext.
Definition at line 114 of file SecurityContextImpl.java.
{
         try {
             return authorizationStateHistory.get().peek();
         } catch (EmptyStackException ese) {
             return true;
         }
     }
boolean org.tdl.vireo.security.impl.SecurityContextImpl.isManager ()
Returns
true if the current user has the role MANAGER or above.
Implements org.tdl.vireo.security.SecurityContext.
Definition at line 62 of file SecurityContextImpl.java.
References org.tdl.vireo.model.RoleType.ADMINISTRATOR, org.tdl.vireo.security.impl.SecurityContextImpl.getRole(), and org.tdl.vireo.model.RoleType.MANAGER.
{
         RoleType role = getRole();
         if (role == RoleType.ADMINISTRATOR ||
             role == RoleType.MANAGER)
             return true;
         return false;
     }
boolean org.tdl.vireo.security.impl.SecurityContextImpl.isReviewer ()
Returns
true if the current user has the role REVIEWER or above.
Implements org.tdl.vireo.security.SecurityContext.
Definition at line 71 of file SecurityContextImpl.java.
References org.tdl.vireo.model.RoleType.ADMINISTRATOR, org.tdl.vireo.security.impl.SecurityContextImpl.getRole(), org.tdl.vireo.model.RoleType.MANAGER, and org.tdl.vireo.model.RoleType.REVIEWER.
{
         RoleType role = getRole();
         if (role == RoleType.ADMINISTRATOR ||
             role == RoleType.MANAGER ||
             role == RoleType.REVIEWER)
             return true;
         return false;
     }
boolean org.tdl.vireo.security.impl.SecurityContextImpl.isStudent ()
Returns
true if the current user has the role STUDENT or above.
Implements org.tdl.vireo.security.SecurityContext.
Definition at line 81 of file SecurityContextImpl.java.
References org.tdl.vireo.model.RoleType.ADMINISTRATOR, org.tdl.vireo.security.impl.SecurityContextImpl.getRole(), org.tdl.vireo.model.RoleType.MANAGER, org.tdl.vireo.model.RoleType.REVIEWER, and org.tdl.vireo.model.RoleType.STUDENT.
{
         RoleType role = getRole();
         if (role == RoleType.ADMINISTRATOR ||
             role == RoleType.MANAGER ||
             role == RoleType.REVIEWER ||
             role == RoleType.STUDENT)
             return true;
         return false;
     }
void org.tdl.vireo.security.impl.SecurityContextImpl.login (Person person)
After a user's credentials have been verified log the user into the current security context. This allows other vireo components to access the currently authenticated user easily.
Parameters
person The authenticated person.
Implements org.tdl.vireo.security.SecurityContext.
Definition at line 22 of file SecurityContextImpl.java.
References org.tdl.vireo.security.impl.SecurityContextImpl.resetAuthorizationStack().
{
         personLocal.set(person);
         // Clear any previous history state, and turn the authorization state on.
         resetAuthorizationStack();
         authorizationStateHistory.get().push(true);
     }
void org.tdl.vireo.security.impl.SecurityContextImpl.logout ()
Logout the current user, effectively resetting the security context.
Implements org.tdl.vireo.security.SecurityContext.
Definition at line 31 of file SecurityContextImpl.java.
References org.tdl.vireo.security.impl.SecurityContextImpl.resetAuthorizationStack().
{
         personLocal.set(null);
         resetAuthorizationStack();
     }
void org.tdl.vireo.security.impl.SecurityContextImpl.resetAuthorizationStack () private
Definition at line 123 of file SecurityContextImpl.java.
References org.tdl.vireo.security.impl.SecurityContextImpl.authorizationStateHistory.
Referenced by org.tdl.vireo.security.impl.SecurityContextImpl.login(), org.tdl.vireo.security.impl.SecurityContextImpl.logout(), and org.tdl.vireo.security.impl.SecurityContextImpl.turnOffAuthorization().
{
         if (authorizationStateHistory.get() == null) {
             authorizationStateHistory.set(new Stack<Boolean>());
         } else {
             authorizationStateHistory.get().clear();
         }
     }
void org.tdl.vireo.security.impl.SecurityContextImpl.restoreAuthorization ()
Restore the authorization state to it's original state before the paired turnOffAuthorizations was called.
Implements org.tdl.vireo.security.SecurityContext.
Definition at line 105 of file SecurityContextImpl.java.
References org.tdl.vireo.security.impl.SecurityContextImpl.authorizationStateHistory.
{
         if (authorizationStateHistory.get() == null || authorizationStateHistory.get().size() == 0)
             throw new IllegalStateException("Unbalanced authorization state, each call to turnOffAuthorization() *must* be paired with exactly one restoreAuthorization()");
         authorizationStateHistory.get().pop();
     }
void org.tdl.vireo.security.impl.SecurityContextImpl.turnOffAuthorization ()
Turn off the authorization system. The caller must always pair this call with a restoration of authorization.
Implements org.tdl.vireo.security.SecurityContext.
Definition at line 97 of file SecurityContextImpl.java.
References org.tdl.vireo.security.impl.SecurityContextImpl.authorizationStateHistory, and org.tdl.vireo.security.impl.SecurityContextImpl.resetAuthorizationStack().
{
         if (authorizationStateHistory.get() == null)
             resetAuthorizationStack();
         authorizationStateHistory.get().push(false);
     }
Member Data Documentation
ThreadLocal<Stack<Boolean> > org.tdl.vireo.security.impl.SecurityContextImpl.authorizationStateHistory = new ThreadLocal<Stack<Boolean>>()
Definition at line 19 of file SecurityContextImpl.java.
Referenced by org.tdl.vireo.security.impl.SecurityContextImpl.resetAuthorizationStack(), org.tdl.vireo.security.impl.SecurityContextImpl.restoreAuthorization(), and org.tdl.vireo.security.impl.SecurityContextImpl.turnOffAuthorization().
ThreadLocal<Person> org.tdl.vireo.security.impl.SecurityContextImpl.personLocal = new ThreadLocal<Person>()
Definition at line 18 of file SecurityContextImpl.java.
Referenced by org.tdl.vireo.security.impl.SecurityContextImpl.getRole().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/security/impl/SecurityContextImpl.java