Vireo: org.tdl.vireo.search.impl.LuceneUpdateJob Class Reference
org.tdl.vireo.search.impl.LuceneUpdateJob Class Reference
Public Member Functions
LuceneUpdateJob (LuceneIndexerImpl indexer, Set< Long > submissionIds)
String getLabel ()
LuceneAbstractJobImpl mergeJob (LuceneAbstractJobImpl job)
void writeIndex () throws CorruptIndexException, LockObtainFailedException, IOException, InterruptedException
Public Member Functions inherited from org.tdl.vireo.search.impl.LuceneAbstractJobImpl
LuceneAbstractJobImpl (LuceneIndexerImpl indexer)
abstract LuceneAbstractJobImpl mergeJob (LuceneAbstractJobImpl job)
abstract String getLabel ()
int getProgress ()
int getTotal ()
void cancelJob ()
void doJob ()
abstract void writeIndex () throws CorruptIndexException, LockObtainFailedException, IOException, InterruptedException
void indexSubmission (IndexWriter writer, Submission sub) throws CorruptIndexException, IOException
Private Attributes
Set< Long > subIds
boolean indexing = false
Additional Inherited Members
Public Attributes inherited from org.tdl.vireo.search.impl.LuceneAbstractJobImpl
final LuceneIndexerImpl indexer
int progress = 0
int total = 0
boolean cancel = false
Detailed Description
Update the index for a given list of modified submissions.
This is the 'normal' job that is used after each web request to update the index. Unlike the rebuild job which looks at every item in vireo, this job instead only re-indexes a subset of those submissions. Also like the rebuild job searches may continue against the index while this job is processing.
Author
Scott Phillips
Definition at line 34 of file LuceneUpdateJob.java.
Constructor & Destructor Documentation
org.tdl.vireo.search.impl.LuceneUpdateJob.LuceneUpdateJob (LuceneIndexerImpl indexer, Set< Long > submissionIds)
Construct a new update index job.
Parameters
submissionIds The list of submissions to index.
Definition at line 47 of file LuceneUpdateJob.java.
References org.tdl.vireo.search.impl.LuceneAbstractJobImpl.progress, and org.tdl.vireo.search.impl.LuceneAbstractJobImpl.total.
Referenced by org.tdl.vireo.search.impl.LuceneUpdateJob.mergeJob().
{
         super(indexer);
         this.subIds = Collections.synchronizedSet(new LinkedSet<Long>());
         this.subIds.addAll(submissionIds);
         progress = 0;
         total = submissionIds.size();
     }
Member Function Documentation
String org.tdl.vireo.search.impl.LuceneUpdateJob.getLabel ()
Definition at line 56 of file LuceneUpdateJob.java.
Referenced by org.tdl.vireo.search.impl.LuceneUpdateJob.writeIndex().
{
         return "Update Index";
     }
LuceneAbstractJobImpl org.tdl.vireo.search.impl.LuceneUpdateJob.mergeJob (LuceneAbstractJobImpl job)
Definition at line 61 of file LuceneUpdateJob.java.
References org.tdl.vireo.search.impl.LuceneUpdateJob.indexing, org.tdl.vireo.search.impl.LuceneUpdateJob.LuceneUpdateJob(), org.tdl.vireo.search.impl.LuceneAbstractJobImpl.progress, and org.tdl.vireo.search.impl.LuceneAbstractJobImpl.total.
{
         synchronized (this) {
             if (indexing == true)
                 throw new IllegalStateException("Unable to modify an index job once it has started writting to the index.");
             if (job instanceof LuceneRebuildJobImpl) {
                 return job;
             } else if (job instanceof LuceneUpdateJob) {
                 LuceneUpdateJob updateJob = (LuceneUpdateJob) job;
                 this.subIds.addAll(updateJob.subIds);
                 progress = 0;
                 total = subIds.size();
                 return this;
             } else {
                 throw new IllegalArgumentException("Unable to merge index jobs because the other job is an unsupported: "+job.getClass().getName());
             }
         } // synchronized
     }
void org.tdl.vireo.search.impl.LuceneUpdateJob.writeIndex () throws CorruptIndexException, LockObtainFailedException, IOException, InterruptedException
Definition at line 83 of file LuceneUpdateJob.java.
References org.tdl.vireo.search.impl.LuceneAbstractJobImpl.cancel, org.tdl.vireo.search.impl.LuceneUpdateJob.getLabel(), org.tdl.vireo.search.impl.LuceneIndexerImpl.index, org.tdl.vireo.search.impl.LuceneAbstractJobImpl.indexer, org.tdl.vireo.search.impl.LuceneUpdateJob.indexing, org.tdl.vireo.search.impl.LuceneAbstractJobImpl.indexSubmission(), org.tdl.vireo.search.impl.LuceneAbstractJobImpl.progress, org.tdl.vireo.search.impl.LuceneIndexerImpl.standardAnalyzer, org.tdl.vireo.search.impl.LuceneUpdateJob.subIds, org.tdl.vireo.search.impl.LuceneAbstractJobImpl.total, and org.tdl.vireo.search.impl.LuceneIndexerImpl.version.
{
         synchronized (this) {
             indexing = true;
         }
         // Update the progress and total one last time before starting.
         progress = 0;
         total = subIds.size();
         IndexWriterConfig writerConfig = new IndexWriterConfig(indexer.version,indexer.standardAnalyzer);
         IndexWriter writer = new IndexWriter(indexer.index, writerConfig);
         try {
             for (Long id : subIds) {
                 // First, delete everything from with this submission id
                 // (submission and actionlogs!)
                 writer.deleteDocuments(new TermQuery(new Term("subId",
                         NumericUtils.longToPrefixCoded(id))));
                 if (JPA.isInsideTransaction())
                     JPAPlugin.closeTx(false);
                 JPAPlugin.startTx(true);
                 Submission sub = indexer.subRepo.findSubmission(id);
                 if (sub != null)
                     indexSubmission(writer, sub);
                 JPAPlugin.closeTx(false);
                 JPAPlugin.startTx(false);
                 progress++;
                 // Have we been asked to stop?
                 if (cancel) {
                     writer.rollback();
                     writer = null;
                     throw new InterruptedException("Lucene '"+this.getLabel()+"' job recieved a cancel request after processing "+progress+" number of submissions, rolling back changes.");
                 }
             }
         } finally {
             writer.close();
             subIds.clear();
             indexing = false;
         }
     }
Member Data Documentation
boolean org.tdl.vireo.search.impl.LuceneUpdateJob.indexing = false private
Definition at line 40 of file LuceneUpdateJob.java.
Referenced by org.tdl.vireo.search.impl.LuceneUpdateJob.mergeJob(), and org.tdl.vireo.search.impl.LuceneUpdateJob.writeIndex().
Set<Long> org.tdl.vireo.search.impl.LuceneUpdateJob.subIds private
Definition at line 37 of file LuceneUpdateJob.java.
Referenced by org.tdl.vireo.search.impl.LuceneUpdateJob.writeIndex().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/search/impl/LuceneUpdateJob.java