Vireo: org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl Class Reference
org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl Class Reference
Classes
class initializeSystemEmailTemplates
Public Member Functions
void setSettingsRepository (SettingsRepository settingRepo)
void setSecurityContext (SecurityContext context)
EmailTemplate generateSystemEmailTemplate (String name)
List< EmailTemplate > generateAllSystemEmailTemplates ()
List< String > getAllSystemEmailTemplateNames ()
Public Attributes
SecurityContext context
SettingsRepository settingRepo
Static Public Attributes
static final String BASE_PATH = Play.applicationPath + File.separator + "conf"+File.separator+"emails"+File.separator
static final Pattern SUBJECT_PATTERN = Pattern.compile("\\s*Subject:(.*)[\\n\\r]{1}")
Protected Member Functions
String encodeTemplateName (String name)
String decodeTemplateName (String path)
Detailed Description
Manage all pre-defined system email templates. This implementation manages all the templates found in /conf/emails/[name].email. On application start these templates will be loaded into persistent storage if they are not already present. Also at any time vireo can refresh the template with the pre-defined version individually with the generateSystemEmailTemplate() method.
Author
Scott Phillips
Definition at line 30 of file SystemEmailTemplateServiceImpl.java.
Member Function Documentation
String org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.decodeTemplateName (String path) protected
Decode a template file name into a template name.
Parameters
path The file name.
Returns
The template name.
Definition at line 168 of file SystemEmailTemplateServiceImpl.java.
Referenced by org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.getAllSystemEmailTemplateNames().
{
         if (path.endsWith(".email"))
             path = path.substring(0,path.length() - ".email".length());
         return path.replaceAll("_", " ");
     }
String org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.encodeTemplateName (String name) protected
Encode a template name to a file name on disk.
Parameters
name The template name.
Returns
The file path.
Definition at line 156 of file SystemEmailTemplateServiceImpl.java.
Referenced by org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.generateSystemEmailTemplate().
{
         return name.replaceAll(" ","_") + ".email";
     }
List<EmailTemplate> org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.generateAllSystemEmailTemplates ()
Scan all system defined email templates and if they do not exist in persistent storage load it into persistent storage. If the template already exists, then it will be left alone.
This method is intended to be called on application startup so that all templates get generated for a manager to modify without waiting for the event to be triggered.
Returns
A list of newly generated email templates, if no templates were generated because they all exist in persistent storage then an empty list is returned.
Implements org.tdl.vireo.email.SystemEmailTemplateService.
Definition at line 115 of file SystemEmailTemplateServiceImpl.java.
References org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.generateSystemEmailTemplate(), and org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.getAllSystemEmailTemplateNames().
{
         List<EmailTemplate> created = new ArrayList<EmailTemplate>();
         for (String name : getAllSystemEmailTemplateNames()) {
             EmailTemplate template = settingRepo.findEmailTemplateByName(name);
             if (template == null) {
                 template = generateSystemEmailTemplate(name);
                 created.add(template);
             }
         }
         return created;
     }
EmailTemplate org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.generateSystemEmailTemplate (String name)
Generate a fresh email template from the pre-defined templates. The email template will be saved to persistent storage. If the template already exists in the persistent storage then it's definition will be replaced with the default.
Parameters
name The name of the email template.
Returns
A new unsaved email template.
Implements org.tdl.vireo.email.SystemEmailTemplateService.
Definition at line 57 of file SystemEmailTemplateServiceImpl.java.
References org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.BASE_PATH, and org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.encodeTemplateName().
Referenced by org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.generateAllSystemEmailTemplates().
{
         try {
             String templatePath = BASE_PATH + encodeTemplateName(name);
             File templateFile = new File(templatePath);
             String data = FileUtils.readFileToString(templateFile);
             // Remove any comment lines
             data = data.replaceAll("\\s*#.*[\\n\\r]{1}", "");
             // Extract the subject
             Matcher subjectMatcher = SUBJECT_PATTERN.matcher(data);
             if (!subjectMatcher.find())
                 throw new IllegalStateException("Unable to identify the template's subject.");
             String subject = subjectMatcher.group(1).trim();
             // Trim the subject leaving just the body.
             int index = data.indexOf("\n");
             if (index < 0 )
                 index = data.indexOf("\r");
             String message = data.substring(index);
             if (subject == null || subject.length() == 0)
                 throw new IllegalStateException("Unable to identify the template's subject.");
             if (message == null || message.length() == 0)
                 throw new IllegalStateException("Unable to identify the template's message.");
             try {
                 context.turnOffAuthorization();
                 // Check if the template already exists
                 EmailTemplate template = settingRepo.findEmailTemplateByName(name);
                 if (template == null) {
                     // The template dosn't exist, so create a new one.
                     template = settingRepo.createEmailTemplate(name,subject, message);
                 } else {
                     // The template already exists. Update it's contents.
                     template.setSubject(subject);
                     template.setMessage(message);
                 }
                 template.setSystemRequired(true);
                 template.save();
                 return template;
             } finally {
                 context.restoreAuthorization();
             }
         } catch (Exception e) {
             throw new IllegalStateException(
                     "Unable to generate system email template: " + name, e);
         }
     }
List<String> org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.getAllSystemEmailTemplateNames ()
Returns
Return a list of the names of all pre-defined system email templates.
Implements org.tdl.vireo.email.SystemEmailTemplateService.
Definition at line 132 of file SystemEmailTemplateServiceImpl.java.
References org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.BASE_PATH, and org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.decodeTemplateName().
Referenced by org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.generateAllSystemEmailTemplates().
{
         File directory = new File(BASE_PATH);
         List<String> names = new ArrayList<String>();
         for (File file : directory.listFiles()) {
             if (file.isFile()) {
                 String fileName = file.getName();
                 String templateName = decodeTemplateName(fileName);
                 names.add(templateName);
             }
         }
         return names;
     }
void org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.setSecurityContext (SecurityContext context)
Parameters
context The security context.
Definition at line 51 of file SystemEmailTemplateServiceImpl.java.
References org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.context.
{
         this.context = context;
     }
void org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.setSettingsRepository (SettingsRepository settingRepo)
Parameters
settingRepo The settings repository used for generating email templates.
Definition at line 44 of file SystemEmailTemplateServiceImpl.java.
References org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.settingRepo.
{
         this.settingRepo = settingRepo;
     }
Member Data Documentation
final String org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.BASE_PATH = Play.applicationPath + File.separator + "conf"+File.separator+"emails"+File.separator static
Definition at line 34 of file SystemEmailTemplateServiceImpl.java.
Referenced by org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.generateSystemEmailTemplate(), and org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.getAllSystemEmailTemplateNames().
SecurityContext org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.context
Definition at line 38 of file SystemEmailTemplateServiceImpl.java.
Referenced by org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.setSecurityContext().
SettingsRepository org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.settingRepo
Definition at line 39 of file SystemEmailTemplateServiceImpl.java.
Referenced by org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.setSettingsRepository().
final Pattern org.tdl.vireo.email.impl.SystemEmailTemplateServiceImpl.SUBJECT_PATTERN = Pattern.compile("\\s*Subject:(.*)[\\n\\r]{1}") static
Definition at line 35 of file SystemEmailTemplateServiceImpl.java.
The documentation for this class was generated from the following file:
app/org/tdl/vireo/email/impl/SystemEmailTemplateServiceImpl.java