Vireo: org.tdl.vireo.state.impl.StateManagerImpl Class Reference
org.tdl.vireo.state.impl.StateManagerImpl Class Reference
Public Member Functions
State getState (String beanName)
List< State > getAllStates ()
State getInitialState ()
void setInitialState (State state)
State getCancelState ()
void setCancelState (State state)
void setAllStates (List< State > allStates)
Public Attributes
List< State > allStates = new ArrayList<State>()
State initialState = null
State cancelState = null
Detailed Description
This is a simple state manager, which knows about all the possible states available to vireo. And it also knows the state from which all submissions start with.
Author
Scott Phillips
Definition at line 18 of file StateManagerImpl.java.
Member Function Documentation
List<State> org.tdl.vireo.state.impl.StateManagerImpl.getAllStates ()
Returns
A list of all states.
Implements org.tdl.vireo.state.StateManager.
Definition at line 34 of file StateManagerImpl.java.
References org.tdl.vireo.state.impl.StateManagerImpl.allStates.
{
         return new ArrayList<State>(allStates);
     }
State org.tdl.vireo.state.impl.StateManagerImpl.getCancelState ()
Returns
The state where submissions should be assigned if they are cancelled.
Implements org.tdl.vireo.state.StateManager.
Definition at line 52 of file StateManagerImpl.java.
References org.tdl.vireo.state.impl.StateManagerImpl.cancelState.
{
         return cancelState;
     }
State org.tdl.vireo.state.impl.StateManagerImpl.getInitialState ()
Returns
The initial state that all submissions should be start with.
Implements org.tdl.vireo.state.StateManager.
Definition at line 39 of file StateManagerImpl.java.
References org.tdl.vireo.state.impl.StateManagerImpl.initialState.
{
         return initialState;
     }
State org.tdl.vireo.state.impl.StateManagerImpl.getState (String beanName)
Return the full state object identified by the technical bean name.
Parameters
beanName The technical bean name of the state.
Returns
The full state object.
Implements org.tdl.vireo.state.StateManager.
Definition at line 26 of file StateManagerImpl.java.
References org.tdl.vireo.state.impl.StateManagerImpl.allStates.
{
         for (State state : allStates)
             if (beanName.equals(state.getBeanName()))
                 return state;
         return null;
     }
void org.tdl.vireo.state.impl.StateManagerImpl.setAllStates (List< State > allStates)
Parameters
allStates Set the list of all possible states that submissions may be within.
Definition at line 69 of file StateManagerImpl.java.
References org.tdl.vireo.state.impl.StateManagerImpl.allStates.
{
         this.allStates = allStates;
     }
void org.tdl.vireo.state.impl.StateManagerImpl.setCancelState (State state)
Parameters
state Set the state where all canceled submission should be assigned too.
Definition at line 60 of file StateManagerImpl.java.
{
         this.cancelState = state;
     }
void org.tdl.vireo.state.impl.StateManagerImpl.setInitialState (State state)
Parameters
state Set the initial state where all submissions start with.
Definition at line 47 of file StateManagerImpl.java.
{
         this.initialState = state;
     }
Member Data Documentation
List<State> org.tdl.vireo.state.impl.StateManagerImpl.allStates = new ArrayList<State>()
Injected properties
Definition at line 21 of file StateManagerImpl.java.
Referenced by org.tdl.vireo.state.impl.StateManagerImpl.getAllStates(), org.tdl.vireo.state.impl.StateManagerImpl.getState(), and org.tdl.vireo.state.impl.StateManagerImpl.setAllStates().
State org.tdl.vireo.state.impl.StateManagerImpl.cancelState = null
Definition at line 23 of file StateManagerImpl.java.
Referenced by org.tdl.vireo.state.impl.StateManagerImpl.getCancelState().
State org.tdl.vireo.state.impl.StateManagerImpl.initialState = null
Definition at line 22 of file StateManagerImpl.java.
Referenced by org.tdl.vireo.state.impl.StateManagerImpl.getInitialState().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/state/impl/StateManagerImpl.java