Vireo: controllers.submit.AbstractSubmitStep Class Reference
controllers.submit.AbstractSubmitStep Class Reference
Static Protected Member Functions
static Submission getSubmission ()
static boolean isFieldEnabled (FieldConfig field)
static boolean isFieldRequired (FieldConfig field)
Static Protected Member Functions inherited from controllers.AbstractVireoController
static boolean isEmpty (String value)
static boolean isNotEmpty (String value)
static String escapeJavaScript (String value)
static String URIEncode (String value)
static String toJSON (String[] values)
static String text2html (String value)
static boolean isFieldRequired (FieldConfig field)
Static Package Functions
static void beforeSubmit ()
Additional Inherited Members
Static Public Member Functions inherited from controllers.AbstractVireoController
static void injectRepositories ()
static void checkForFirstUser ()
static void handleError (Throwable throwable)
Static Public Attributes inherited from controllers.AbstractVireoController
static SecurityContext context = Spring.getBeanOfType(SecurityContext.class)
static PersonRepository personRepo = Spring.getBeanOfType(PersonRepository.class)
static SubmissionRepository subRepo = Spring.getBeanOfType(SubmissionRepository.class)
static SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class)
static ProquestVocabularyRepository proquestRepo = Spring.getBeanOfType(ProquestVocabularyRepository.class)
static ErrorLog errorLog = Spring.getBeanOfType(ErrorLog.class)
static StateManager stateManager = Spring.getBeanOfType(StateManager.class)
static Indexer indexer = Spring.getBeanOfType(Indexer.class)
static Searcher searcher = Spring.getBeanOfType(Searcher.class)
static Boolean firstUser = null
Detailed Description
THIS CONTROLLER IS BEING REFACTORED.
Please don't touch right now.
Definition at line 24 of file AbstractSubmitStep.java.
Member Function Documentation
static void controllers.submit.AbstractSubmitStep.beforeSubmit () static package
Set up values needed to display submission status at the top of each page. If submissions are closed - always redirect to the submissionStatus page.
Definition at line 32 of file AbstractSubmitStep.java.
References controllers.Student.submissionList().
{
         if (settingRepo.findConfigurationByName(SUBMISSIONS_OPEN) == null)
             Student.submissionList();
         renderArgs.put("SUBMISSIONS_OPEN", settingRepo.findConfigurationByName(SUBMISSIONS_OPEN));
         renderArgs.put("CURRENT_SEMESTER", settingRepo.getConfigValue(CURRENT_SEMESTER, "current"));
         for(FieldConfig field : FieldConfig.values()) {
             renderArgs.put(field.name(),field );
         }
     }
static Submission controllers.submit.AbstractSubmitStep.getSubmission () static protected
Returns
the currently active submission checking for all the error conditions.
Definition at line 49 of file AbstractSubmitStep.java.
References org.tdl.vireo.model.Submission.getState(), and org.tdl.vireo.model.Submission.getSubmitter().
Referenced by controllers.submit.Confirm.confirm(), controllers.submit.DocumentInfo.documentInfo(), controllers.submit.FileUpload.fileUpload(), controllers.submit.License.license(), and controllers.submit.PersonalInfo.personalInfo().
{
         // We require an sub id.
         Long subId = params.get("subId", Long.class);
         if (subId == null) {
             error("Did not receive the expected submission id.");
         }
         // And the submission must exist.
         Submission sub = subRepo.findSubmission(subId);
         if (sub == null) {
             error("Unable to find the submission #"+subId);
         }
         // Check that we are the owner of the submission.
         Person submitter = context.getPerson();
         if (sub.getSubmitter() != submitter)
             unauthorized();
         // And check that it is in the initial state.
         State initialState = stateManager.getInitialState();
         if (sub.getState() != initialState)
             error("This submission is no longer editable.");
         return sub;
     }
static boolean controllers.submit.AbstractSubmitStep.isFieldEnabled (FieldConfig field) static protected
Return whether the specified field is enabled. If it is then return true, otherwise false.
Parameters
field The field to check whether it is enabled.
Returns
True if enabled, otherwise false.
Definition at line 84 of file AbstractSubmitStep.java.
Referenced by controllers.submit.DocumentInfo.documentInfo(), controllers.submit.FileUpload.fileUpload(), controllers.submit.PersonalInfo.personalInfo(), controllers.submit.DocumentInfo.verify(), and controllers.submit.PersonalInfo.verify().
{
         return !"disabled".equals(settingRepo.getConfigValue(field.ENABLED));
     }
static boolean controllers.submit.AbstractSubmitStep.isFieldRequired (FieldConfig field) static protected
Return whether the specified field is required. If it is then return true, otherwise false.
Parameters
field The field to check whether it is required.
Returns
True if required, otherwise false.
Definition at line 96 of file AbstractSubmitStep.java.
Referenced by controllers.submit.DocumentInfo.documentInfo(), controllers.submit.DocumentInfo.isValidDegreeMonth(), controllers.submit.DocumentInfo.isValidDegreeYear(), controllers.submit.DocumentInfo.isValidDocType(), controllers.submit.License.verify(), controllers.submit.FileUpload.verify(), controllers.submit.DocumentInfo.verify(), and controllers.submit.PersonalInfo.verify().
{
         return "required".equals(settingRepo.getConfigValue(field.ENABLED));
     }
The documentation for this class was generated from the following file:
app/controllers/submit/AbstractSubmitStep.java