Vireo: controllers.submit.FieldTags Class Reference
controllers.submit.FieldTags Class Reference
Static Public Member Functions
static void _ifEnabled (Map<?,?> args, Closure body, PrintWriter out, ExecutableTemplate template, int fromLine)
static void _ifRequired (Map<?,?> args, Closure body, PrintWriter out, ExecutableTemplate template, int fromLine)
static void _fieldClass (Map<?,?> args, Closure body, PrintWriter out, ExecutableTemplate template, int fromLine)
static void _fieldLabel (Map<?,?> args, Closure body, PrintWriter out, ExecutableTemplate template, int fromLine)
static void _fieldHelp (Map<?,?> args, Closure body, PrintWriter out, ExecutableTemplate template, int fromLine)
static void _errorClass (Map<?,?> args, Closure body, PrintWriter out, ExecutableTemplate template, int fromLine)
Static Public Attributes
static SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class)
Static Protected Member Functions
static boolean isRequired (ExecutableTemplate template, int fromLine, Object...fields)
static boolean isEnabled (ExecutableTemplate template, int fromLine, Object...fields)
Static Private Member Functions
static void throwTypeError (ExecutableTemplate template, int fromLine, Object...objects)
Detailed Description
These are a set of Play template tags that are used to easily access information about the configuration of a particular field.
Author
Scott Phillips
Definition at line 31 of file FieldTags.java.
Member Function Documentation
static void controllers.submit.FieldTags._errorClass (Map<?,?> args, Closure body, PrintWriter out, ExecutableTemplate template, int fromLine) static
Override the default errorClass tag that comes with Play to use the "error" class instead of "hasError" class.
Definition at line 178 of file FieldTags.java.
{
         if (args.get("arg") == null) {
             throw new TemplateExecutionException(template.template, fromLine, "Please specify the error key", new TagInternalException("Please specify the error key"));
         }
         if (Validation.hasError(args.get("arg").toString())) {
             out.print("error");
         }
     }
static void controllers.submit.FieldTags._fieldClass (Map<?,?> args, Closure body, PrintWriter out, ExecutableTemplate template, int fromLine) static
Display the enabled class for this field, either "required", "optional", or "disabled".
#{fieldClass STUDENT_FIRST_NAME /}
Definition at line 114 of file FieldTags.java.
References controllers.submit.FieldTags.isEnabled(), and controllers.submit.FieldTags.isRequired().
{
         // Get the field
         Object arg = args.get("arg");
         FieldConfig field;
         if (arg instanceof FieldConfig)
             field = (FieldConfig) arg;
         else
             throw new TemplateExecutionException(template.template, fromLine, "Wrong parameter type, try #{fieldClass field/}", new TagInternalException("Wrong parameter type"));
         // Display the class
         if (isRequired(template, fromLine, field))
             out.print("required");
         else if (isEnabled(template, fromLine, field))
             out.print("optional");
         else
             out.print("disabled");
     }
static void controllers.submit.FieldTags._fieldHelp (Map<?,?> args, Closure body, PrintWriter out, ExecutableTemplate template, int fromLine) static
Display the help text of the field.
#{fieldHelp STUDENT_FIRST_NAME /}
Definition at line 159 of file FieldTags.java.
{
         // Get the field
         Object arg = args.get("arg");
         FieldConfig field;
         if (arg instanceof FieldConfig)
             field = (FieldConfig) arg;
         else
             throw new TemplateExecutionException(template.template, fromLine, "Wrong parameter type, try #{fieldHelp field/}", new TagInternalException("Wrong parameter type"));
         // Display the help text
         out.print(settingRepo.getConfigValue(field.HELP));
     }
static void controllers.submit.FieldTags._fieldLabel (Map<?,?> args, Closure body, PrintWriter out, ExecutableTemplate template, int fromLine) static
Display the label text of the field.
#{fieldLabel STUDENT_FIRST_NAME /}
Definition at line 139 of file FieldTags.java.
{
         // Get the field
         Object arg = args.get("arg");
         FieldConfig field;
         if (arg instanceof FieldConfig)
             field = (FieldConfig) arg;
         else
             throw new TemplateExecutionException(template.template, fromLine, "Wrong parameter type, try #{fieldLabel field/}", new TagInternalException("Wrong parameter type"));
         // Display the label
         out.print(settingRepo.getConfigValue(field.LABEL));
     }
static void controllers.submit.FieldTags._ifEnabled (Map<?,?> args, Closure body, PrintWriter out, ExecutableTemplate template, int fromLine) static
Conditional tag to check if at least one of the passed fields is enabled. You may pas either a list of fields, or just one field.
#{ifEnabled [STUDENT_FIRST_NAME,STUDENT_MIDDLE_NAME,STUDENT_LAST_NAME]} ... do something if enabled ... #{/if} #{else} ... do something else ... #{/else}
Definition at line 47 of file FieldTags.java.
References controllers.submit.FieldTags.isEnabled().
{
         // Get the list of field arguments
         Object arg = args.get("arg");
         List fields;
         if (arg instanceof FieldConfig) {
             fields = new ArrayList();
             fields.add(arg);
         } else if (arg instanceof ArrayList) {
             fields = (List) arg;
         } else {
             throw new TemplateExecutionException(template.template, fromLine, "Wrong parameter type, try #{ifEnabled [field1,field2] }", new TagInternalException("Wrong parameter type"));
         }
         // If enabled
         if (isEnabled(template, fromLine, fields.toArray())) {
             body.call();
             TagContext.parent().data.put("_executeNextElse", false);
         } else {
             TagContext.parent().data.put("_executeNextElse", true);
         }
     }
static void controllers.submit.FieldTags._ifRequired (Map<?,?> args, Closure body, PrintWriter out, ExecutableTemplate template, int fromLine) static
Conditional tag to check if all of the passed fields are required. You may pas either a list of fields, or just one field.
#{ifRequired [STUDENT_FIRST_NAME,STUDENT_MIDDLE_NAME,STUDENT_LAST_NAME]} ... do something if all required ... #{/if} #{else} ... do something else ... #{/else}
Definition at line 82 of file FieldTags.java.
References controllers.submit.FieldTags.isRequired().
{
         // Get the list of field arguments
         Object arg = args.get("arg");
         List fields;
         if (arg instanceof FieldConfig) {
             fields = new ArrayList();
             fields.add(arg);
         } else if (arg instanceof ArrayList) {
             fields = (List) arg;
         } else {
             throw new TemplateExecutionException(template.template, fromLine, "Wrong parameter type, try #{ifRequired [field1,field2] }", new TagInternalException("Wrong parameter type"));
         }
         // If required
         if (isRequired(template, fromLine, fields.toArray())) {
             body.call();
             TagContext.parent().data.put("_executeNextElse", false);
         } else {
             TagContext.parent().data.put("_executeNextElse", true);
         }
     }
static boolean controllers.submit.FieldTags.isEnabled (ExecutableTemplate template, int fromLine, Object... fields) static protected
Internal method to check that at least one of the passed fields is enabled.
Parameters
fields The fields to check.
Returns
True if at least one field is enabled, otherwise fales.
Definition at line 220 of file FieldTags.java.
References org.tdl.vireo.constant.FieldConfig.ENABLED, org.tdl.vireo.model.SettingsRepository.getConfigValue(), controllers.submit.FieldTags.settingRepo, and controllers.submit.FieldTags.throwTypeError().
Referenced by controllers.submit.FieldTags._fieldClass(), and controllers.submit.FieldTags._ifEnabled().
{
         for (Object obj : fields) {
             if (!(obj instanceof FieldConfig))
                 throwTypeError(template, fromLine, fields);
             FieldConfig field = (FieldConfig) obj;
             if (!"disabled".equals(settingRepo.getConfigValue(field.ENABLED))) {
                 return true;
             }
         }
         return false;
     }
static boolean controllers.submit.FieldTags.isRequired (ExecutableTemplate template, int fromLine, Object... fields) static protected
Internal method to check that all the passed fields are set to be required.
Parameters
fields The fields to check.
Returns
True if all fields are marked as required, otherwise false.
Definition at line 197 of file FieldTags.java.
References org.tdl.vireo.constant.FieldConfig.ENABLED, org.tdl.vireo.model.SettingsRepository.getConfigValue(), controllers.submit.FieldTags.settingRepo, and controllers.submit.FieldTags.throwTypeError().
Referenced by controllers.submit.FieldTags._fieldClass(), and controllers.submit.FieldTags._ifRequired().
{
         for (Object obj : fields) {
             if (!(obj instanceof FieldConfig))
                 throwTypeError(template, fromLine, fields);
             FieldConfig field = (FieldConfig) obj;
             if (!"required".equals(settingRepo.getConfigValue(field.ENABLED))) {
                 return false;
             }
         }
         return true;
     }
static void controllers.submit.FieldTags.throwTypeError (ExecutableTemplate template, int fromLine, Object... objects) static private
Internal method to throw a type exception when one of the objects is not a FieldConfig.
Definition at line 239 of file FieldTags.java.
Referenced by controllers.submit.FieldTags.isEnabled(), and controllers.submit.FieldTags.isRequired().
{
         StringBuilder types = new StringBuilder("[");
         for (Object obj : objects) {
             if (types.length() != 1)
                 types.append(",");
             if (obj == null) {
                 types.append("null");
             } else {
                 types.append(obj.getClass().getName());
             }
         }
         types.append("]");
         throw new TemplateExecutionException(template.template, fromLine, "Wrong parameter type, one or more of the arguments are not FieldConfig objects: "+types.toString(), new TagInternalException("Wrong parameter type"));
     }
Member Data Documentation
SettingsRepository controllers.submit.FieldTags.settingRepo = Spring.getBeanOfType(SettingsRepository.class) static
Definition at line 33 of file FieldTags.java.
Referenced by controllers.submit.FieldTags.isEnabled(), and controllers.submit.FieldTags.isRequired().
The documentation for this class was generated from the following file:
app/controllers/submit/FieldTags.java