Vireo: controllers.Application Class Reference
controllers.Application Class Reference
Classes
class SubmissionStatus
Static Public Member Functions
static void index ()
Static Public Member Functions inherited from controllers.AbstractVireoController
static void injectRepositories ()
static void checkForFirstUser ()
static void handleError (Throwable throwable)
Static Public Attributes
static final String START_SUBMISSION = "{START_SUBMISSION}"
Static Public Attributes inherited from controllers.AbstractVireoController
static SecurityContext context = Spring.getBeanOfType(SecurityContext.class)
static PersonRepository personRepo = Spring.getBeanOfType(PersonRepository.class)
static SubmissionRepository subRepo = Spring.getBeanOfType(SubmissionRepository.class)
static SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class)
static ProquestVocabularyRepository proquestRepo = Spring.getBeanOfType(ProquestVocabularyRepository.class)
static ErrorLog errorLog = Spring.getBeanOfType(ErrorLog.class)
static StateManager stateManager = Spring.getBeanOfType(StateManager.class)
static Indexer indexer = Spring.getBeanOfType(Indexer.class)
static Searcher searcher = Spring.getBeanOfType(Searcher.class)
static Boolean firstUser = null
Additional Inherited Members
Static Protected Member Functions inherited from controllers.AbstractVireoController
static boolean isEmpty (String value)
static boolean isNotEmpty (String value)
static String escapeJavaScript (String value)
static String toJSON (String[] values)
static String text2html (String value)
static boolean isFieldRequired (FieldConfig field)
Detailed Description
This is a very simple controller that only handles the index page of the application.
Author
Scott Phillips
Definition at line 18 of file Application.java.
Member Function Documentation
static void controllers.Application.index () static
Vireo index page.
Definition at line 28 of file Application.java.
References org.tdl.vireo.constant.AppConfig.FRONT_PAGE_INSTRUCTIONS.
Referenced by controllers.Authentication.loginMethod(), controllers.submit.PersonalInfo.personalInfo(), controllers.Authentication.recover(), controllers.Authentication.register(), and controllers.Student.submissionDelete().
{
         // Get the text for the front page.
         String instructions = settingRepo.getConfigValue(AppConfig.FRONT_PAGE_INSTRUCTIONS);
         instructions = text2html(instructions);
         // Split the text into two blocks, one block before the
         // "start submission" button, and the other after.
         String instructionsBefore = "";
         String instructionsAfter = "";
         int idx = instructions.indexOf(START_SUBMISSION);
         if (idx > -1) {
             instructionsBefore = instructions.substring(0, idx);
             instructionsAfter = instructions.substring(idx + START_SUBMISSION.length(), instructions.length());
         } else {
             instructionsBefore = instructions;
         }
         SubmissionStatus subStatus = new SubmissionStatus();
         // Render the Application/index.html template
         render(instructionsBefore, instructionsAfter, subStatus);
     }
Member Data Documentation
final String controllers.Application.START_SUBMISSION = "{START_SUBMISSION}" static
The variable of where to place the start a submission button in the front page text.
Definition at line 23 of file Application.java.
The documentation for this class was generated from the following file:
app/controllers/Application.java