Vireo: controllers.settings.ConfigurableSettingsTab Class Reference
controllers.settings.ConfigurableSettingsTab Class Reference
Classes
enum LocaleComparator
Static Public Member Functions
static void configurableSettings ()
static void bulkAdd (String modelType, String bulkAdd)
static void editEmbargoTypeJSON (String embargoTypeId, String name, String description, Integer months, boolean active, String guarantor)
static void removeEmbargoTypeJSON (String embargoTypeId)
static void removeAllEmbargoTypes ()
static void reorderEmbargoTypesJSON (String embargoTypeIds)
static void alphabetizeAllEmbargoTypes ()
static void addEditCollegeJSON (String collegeId, String name, String emails)
static void removeCollegeJSON (String collegeId)
static void removeAllColleges ()
static void reorderCollegesJSON (String collegeIds)
static void alphabetizeAllColleges ()
static void addEditProgramJSON (String programId, String name, String emails)
static void removeProgramJSON (String programId)
static void removeAllPrograms ()
static void reorderProgramsJSON (String programIds)
static void alphabetizeAllPrograms ()
static void addEditDepartmentJSON (String departmentId, String name, String emails)
static void removeDepartmentJSON (String departmentId)
static void removeAllDepartments ()
static void reorderDepartmentsJSON (String departmentIds)
static void alphabetizeAllDepartments ()
static void addEditAdministrativeGroupJSON (String adminGroupId, String name, String emails)
static void removeAdministrativeGroupJSON (String adminGroupId)
static void removeAllAdministrativeGroups ()
static void reorderAdministrativeGroupsJSON (String adminGroupIds)
static void alphabetizeAllAdministrativeGroups ()
static void addMajorJSON (String name)
static void editMajorJSON (String majorId, String name)
static void removeMajorJSON (String majorId)
static void removeAllMajors ()
static void reorderMajorsJSON (String majorIds)
static void alphabetizeAllMajors ()
static void addDegreeJSON (String name, int level)
static void editDegreeJSON (String degreeId, String name, int level)
static void removeDegreeJSON (String degreeId)
static void removeAllDegrees ()
static void reorderDegreesJSON (String degreeIds)
static void alphabetizeAllDegrees ()
static void addDocumentTypeJSON (String name, int level)
static void editDocumentTypeJSON (String documentTypeId, String name, int level)
static void removeDocumentTypeJSON (String documentTypeId)
static void removeAllDocumentTypes ()
static void reorderDocumentTypesJSON (String documentTypeIds)
static void alphabetizeAllDocumentTypes ()
static void addCommitteeMemberRoleTypeJSON (String name, int level)
static void editCommitteeMemberRoleTypeJSON (String committeeMemberRoleTypeId, String name, int level)
static void removeCommitteeMemberRoleTypeJSON (String committeeMemberRoleTypeId)
static void removeAllCommitteeMemberRoleTypes ()
static void reorderCommitteeMemberRoleTypesJSON (String committeeMemberRoleTypeIds)
static void alphabetizeAllCommitteeMemberRoleTypes ()
static void addGraduationMonthJSON (String name)
static void editGraduationMonthJSON (String graduationMonthId, String name)
static void removeGraduationMonthJSON (String graduationMonthId)
static void removeAllGraduationMonths ()
static void reorderGraduationMonthsJSON (String graduationMonthIds)
static void alphabetizeAllGraduationMonths ()
static void addLanguageJSON (String name)
static void removeLanguageJSON (String languageId)
static void removeAllLanguages ()
static void reorderLanguagesJSON (String languageIds)
static void alphabetizeAllLanguages ()
static< T > Comparator< T > decending (final Comparator< T > other)
static< T > Comparator< T > ascending (final Comparator< T > other)
static Comparator< Locale > getLocaleComparator (final LocaleComparator...multipleOptions)
static Comparator
< AbstractOrderedModel > getModelCompator ()
Static Public Member Functions inherited from controllers.SettingsTab
static void settingsRedirect ()
static void updateProfileJSON (String field, String value)
Static Public Member Functions inherited from controllers.AbstractVireoController
static void injectRepositories ()
static void checkForFirstUser ()
static void handleError (Throwable throwable)
Static Public Attributes
static final ProquestUtilityService proquestUtils = Spring.getBeanOfType(ProquestUtilityService.class)
Static Public Attributes inherited from controllers.AbstractVireoController
static SecurityContext context = Spring.getBeanOfType(SecurityContext.class)
static PersonRepository personRepo = Spring.getBeanOfType(PersonRepository.class)
static SubmissionRepository subRepo = Spring.getBeanOfType(SubmissionRepository.class)
static SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class)
static ProquestVocabularyRepository proquestRepo = Spring.getBeanOfType(ProquestVocabularyRepository.class)
static ErrorLog errorLog = Spring.getBeanOfType(ErrorLog.class)
static StateManager stateManager = Spring.getBeanOfType(StateManager.class)
static Indexer indexer = Spring.getBeanOfType(Indexer.class)
static Searcher searcher = Spring.getBeanOfType(Searcher.class)
static Boolean firstUser = null
Static Private Member Functions
static String createEmailsJsonAndAddToMap (String emails, HashMap< Integer, String > emails_map)
Additional Inherited Members
Static Protected Member Functions inherited from controllers.SettingsTab
static void saveModelOrder (List<?extends AbstractOrderedModel > models)
static
< TextendsAbstractOrderedModel >
List< T > resolveIds (String idString, Class< T > type)
static int monthNameToInt (String monthName)
Static Protected Member Functions inherited from controllers.AbstractVireoController
static boolean isEmpty (String value)
static boolean isNotEmpty (String value)
static String escapeJavaScript (String value)
static String toJSON (String[] values)
static String text2html (String value)
static boolean isFieldRequired (FieldConfig field)
Detailed Description
Definition at line 44 of file ConfigurableSettingsTab.java.
Member Function Documentation
static void controllers.settings.ConfigurableSettingsTab.addCommitteeMemberRoleTypeJSON (String name, int level) static
Create a new CommitteeMemberRoleType. The id of the new roleType will be returned.
Parameters
name The name of the new roleType
level The level id for the new roleType
Definition at line 1529 of file ConfigurableSettingsTab.java.
{
         try {
             if (name == null || name.trim().length() == 0)
                 throw new IllegalArgumentException("Name is required");
             DegreeLevel degreeLevel = DegreeLevel.find(level);
             // Add the new type to the end of the list.
             List<CommitteeMemberRoleType> roleTypes = settingRepo.findAllCommitteeMemberRoleTypes();
             CommitteeMemberRoleType roleType = settingRepo.createCommitteeMemberRoleType(name, degreeLevel);
             roleTypes.add(roleType);
             saveModelOrder(roleTypes);
             name = escapeJavaScript(roleType.getName());
             renderJSON("{ \"success\": \"true\", \"id\": " + roleType.getId()   + ", \"name\": \"" + name + "\", \"level\": "+degreeLevel.getId()+" }");
         } catch (IllegalArgumentException iae) {
             String message = escapeJavaScript(iae.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         } catch (PersistenceException pe) {
             name = escapeJavaScript(name);
             renderJSON("{ \"failure\": \"true\", \"message\": \"Another committee member role type already exists with the name: '"+name+"'\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to add committee member role type");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.addDegreeJSON (String name, int level) static
Create a new Degree. The id of the new degree will be returned.
Parameters
name The name of the new degree
level The level id for the new degree
Definition at line 1179 of file ConfigurableSettingsTab.java.
{
         try {
             if (name == null || name.trim().length() == 0)
                 throw new IllegalArgumentException("Name is required");
             DegreeLevel degreeLevel = DegreeLevel.find(level);
             // Add the new degree to the end of the list.
             List<Degree> degrees = settingRepo.findAllDegrees();
             Degree degree = settingRepo.createDegree(name,degreeLevel);
             degrees.add(degree);
             saveModelOrder(degrees);
             name = escapeJavaScript(degree.getName());
             renderJSON("{ \"success\": \"true\", \"id\": " + degree.getId() + ", \"name\": \"" + name + "\", \"level\": "+degreeLevel.getId()+"}");
         } catch (IllegalArgumentException iae) {
             String message = escapeJavaScript(iae.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         } catch (PersistenceException pe) {
             name = escapeJavaScript(name);
             renderJSON("{ \"failure\": \"true\", \"message\": \"Another degree already exists with the name: '"+name+"'\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to add degree");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.addDocumentTypeJSON (String name, int level) static
Create a new DocumentType. The id of the new docType will be returned.
Parameters
name The name of the new docType
level The level id for the new documentType
Definition at line 1354 of file ConfigurableSettingsTab.java.
{
         try {
             if (name == null || name.trim().length() == 0)
                 throw new IllegalArgumentException("Name is required");
             DegreeLevel degreeLevel = DegreeLevel.find(level);
             // Add the new type to the end of the list.
             List<DocumentType> documentTypes = settingRepo.findAllDocumentTypes();
             DocumentType documentType = settingRepo.createDocumentType(name,degreeLevel);
             documentTypes.add(documentType);
             saveModelOrder(documentTypes);
             name = escapeJavaScript(documentType.getName());
             renderJSON("{ \"success\": \"true\", \"id\": " + documentType.getId()   + ", \"name\": \"" + name + "\", \"level\": "+degreeLevel.getId()+" }");
         } catch (IllegalArgumentException iae) {
             String message = escapeJavaScript(iae.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         } catch (PersistenceException pe) {
             name = escapeJavaScript(name);
             renderJSON("{ \"failure\": \"true\", \"message\": \"Another document type already exists with the name: '"+name+"'\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to add document type");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.addEditAdministrativeGroupJSON (String adminGroupId, String name, String emails) static
Create or edit a new Administrative Group. The id of the new administrative group will be returned.
Parameters
adminGroupId - The id of the administrative group we're editing
name - The name of the new administrative group
emails - The list of email addresses to associate with this administrative group
Definition at line 860 of file ConfigurableSettingsTab.java.
{
         try {
             if (name == null || name.trim().length() == 0)
                 throw new IllegalArgumentException("Name is required");
             // make sure emails isn't null
             if(emails == null) {
                 emails = "";
             }
             // remove whitespace from email address string
             emails = emails.replaceAll("\\s+","");
             // Add the new administrative groups to the end of the list.
             List<AdministrativeGroup> adminGroups = settingRepo.findAllAdministrativeGroups();
             // Create or modify the administrative group
             AdministrativeGroup adminGroup = null;
             String jsonEmails = "";
             if (adminGroupId != null && adminGroupId.trim().length() > 0) {
                 Long id = Long.valueOf(adminGroupId);
                 adminGroup = settingRepo.findAdministrativeGroup(id);
                 adminGroup.setName(name);
                 // create a new hashMap for the new emails
                 HashMap<Integer, String> emails_map = new HashMap<Integer, String>();
                 // create the json for the response and also add them to the created hashMap
                 jsonEmails = createEmailsJsonAndAddToMap(emails, emails_map);
                 // set the new emails with the hashMap
                 adminGroup.setEmails(emails_map);
                 adminGroup.save();
             } else {
                 // create a new hashMap for the new emails
                 HashMap<Integer, String> emails_map = new HashMap<Integer, String>();
                 // create the json for the response and also add them to the created hashMap
                 jsonEmails = createEmailsJsonAndAddToMap(emails, emails_map);
                 // create the new administrative group with the passed-in emails
                 adminGroup = settingRepo.createAdministrativeGroup(name, emails_map);
                 adminGroups.add(adminGroup);
             }
             saveModelOrder(adminGroups);
             name = escapeJavaScript(adminGroup.getName());
             renderJSON("{ \"success\": \"true\", \"id\": " + adminGroup.getId()
                     + ", \"name\": \"" + name + "\", \"emails\": " + jsonEmails+" }");
         } catch (IllegalArgumentException iae) {
             String message = escapeJavaScript(iae.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         } catch (PersistenceException pe) {
             name = escapeJavaScript(name);
             renderJSON("{ \"failure\": \"true\", \"message\": \"Another administrative group already exists with the name: '"+name+"'\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to add administrative group");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.addEditCollegeJSON (String collegeId, String name, String emails) static
Create or edit a new College. The id of the new college will be returned.
Parameters
collegeId - The id of the college we're editing
name - The name of the new college
emails - The list of email addresses to associate with this college
Definition at line 402 of file ConfigurableSettingsTab.java.
{
         try {
             if (name == null || name.trim().length() == 0)
                 throw new IllegalArgumentException("Name is required");
             // make sure emails isn't null
             if(emails == null) {
                 emails = "";
             }
             // remove whitespace from email address string
             emails = emails.replaceAll("\\s+","");
             // Add the new college to the end of the list.
             List<College> colleges = settingRepo.findAllColleges();
             // Create or modify the college
             College college = null;
             String jsonEmails = "";
             if (collegeId != null && collegeId.trim().length() > 0) {
                 Long id = Long.valueOf(collegeId);
                 college = settingRepo.findCollege(id);
                 college.setName(name);
                 // create a new hashMap for the new emails
                 HashMap<Integer, String> emails_map = new HashMap<Integer, String>();
                 // create the json for the response and also add them to the created hashMap
                 jsonEmails = createEmailsJsonAndAddToMap(emails, emails_map);
                 // set the new emails with the hashMap
                 college.setEmails(emails_map);
                 college.save();
             } else {
                 // create a new hashMap for the new emails
                 HashMap<Integer, String> emails_map = new HashMap<Integer, String>();
                 // create the json for the response and also add them to the created hashMap
                 jsonEmails = createEmailsJsonAndAddToMap(emails, emails_map);
                 // create the new college with the passed-in emails
                 college = settingRepo.createCollege(name, emails_map);
                 colleges.add(college);
             }
             saveModelOrder(colleges);
             name = escapeJavaScript(college.getName());
             renderJSON("{ \"success\": \"true\", \"id\": " + college.getId()
                     + ", \"name\": \"" + name + "\", \"emails\": " + jsonEmails+" }");
         } catch (IllegalArgumentException iae) {
             String message = escapeJavaScript(iae.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         } catch (PersistenceException pe) {
             name = escapeJavaScript(name);
             renderJSON("{ \"failure\": \"true\", \"message\": \"Another college already exists with the name: '"+name+"'\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to add college");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.addEditDepartmentJSON (String departmentId, String name, String emails) static
Create or edit a new Department. The id of the new department will be returned.
Parameters
departmentId - The id of the department we're editing
name - The name of the new department
emails - The list of email addresses to associate with this department
Definition at line 706 of file ConfigurableSettingsTab.java.
{
         try {
             if (name == null || name.trim().length() == 0)
                 throw new IllegalArgumentException("Name is required");
             // make sure emails isn't null
             if(emails == null) {
                 emails = "";
             }
             // remove whitespace from email address string
             emails = emails.replaceAll("\\s+","");
             // Add the new college to the end of the list.
             List<Department> departments = settingRepo.findAllDepartments();
             // Create or modify the college
             Department department = null;
             String jsonEmails = "";
             if (departmentId != null && departmentId.trim().length() > 0) {
                 Long id = Long.valueOf(departmentId);
                 department = settingRepo.findDepartment(id);
                 department.setName(name);
                 // create a new hashMap for the new emails
                 HashMap<Integer, String> emails_map = new HashMap<Integer, String>();
                 // create the json for the response and also add them to the created hashMap
                 jsonEmails = createEmailsJsonAndAddToMap(emails, emails_map);
                 department.setEmails(emails_map);
                 department.save();
             } else {
                 // create a new hashMap for the new emails
                 HashMap<Integer, String> emails_map = new HashMap<Integer, String>();
                 // create the json for the response and also add them to the created hashMap
                 jsonEmails = createEmailsJsonAndAddToMap(emails, emails_map);
                 department = settingRepo.createDepartment(name, emails_map);
                 departments.add(department);
             }
             saveModelOrder(departments);
             name = escapeJavaScript(department.getName());
             renderJSON("{ \"success\": \"true\", \"id\": " + department.getId()
                     + ", \"name\": \"" + name + "\", \"emails\": " + jsonEmails+" }");
         } catch (IllegalArgumentException iae) {
             String message = escapeJavaScript(iae.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         } catch (PersistenceException pe) {
             name = escapeJavaScript(name);
             renderJSON("{ \"failure\": \"true\", \"message\": \"Another department already exists with the name: '"+name+"'\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to add department");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.addEditProgramJSON (String programId, String name, String emails) static
Create or edit a new Program. The id of the new program will be returned.
Parameters
programId - The id of the program we're editing
name - The name of the new program
emails - The list of email addresses to associate with this program
Definition at line 555 of file ConfigurableSettingsTab.java.
{
         try {
             if (name == null || name.trim().length() == 0)
                 throw new IllegalArgumentException("Name is required");
             // make sure emails isn't null
             if(emails == null) {
                 emails = "";
             }
             // remove whitespace from email address string
             emails = emails.replaceAll("\\s+","");
             // Add the new college to the end of the list.
             List<Program> programs = settingRepo.findAllPrograms();
             // Create or modify the college
             Program program = null;
             String jsonEmails = "";
             if (programId != null && programId.trim().length() > 0) {
                 Long id = Long.valueOf(programId);
                 program = settingRepo.findProgram(id);
                 program.setName(name);
                 // create a new hashMap for the new emails
                 HashMap<Integer, String> emails_map = new HashMap<Integer, String>();
                 // create the json for the response and also add them to the created hashMap
                 jsonEmails = createEmailsJsonAndAddToMap(emails, emails_map);
                 program.setEmails(emails_map);
                 program.save();
             } else {
                 // create a new hashMap for the new emails
                 HashMap<Integer, String> emails_map = new HashMap<Integer, String>();
                 // create the json for the response and also add them to the created hashMap
                 jsonEmails = createEmailsJsonAndAddToMap(emails, emails_map);
                 program = settingRepo.createProgram(name, emails_map);
                 programs.add(program);
             }
             saveModelOrder(programs);
             name = escapeJavaScript(program.getName());
             renderJSON("{ \"success\": \"true\", \"id\": " + program.getId()
                     + ", \"name\": \"" + name + "\", \"emails\": " + jsonEmails+" }");
         } catch (IllegalArgumentException iae) {
             String message = escapeJavaScript(iae.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         } catch (PersistenceException pe) {
             name = escapeJavaScript(name);
             renderJSON("{ \"failure\": \"true\", \"message\": \"Another program already exists with the name: '"+name+"'\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to add program");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.addGraduationMonthJSON (String name) static
Create a new GraduationMonth. The id of the new month will be returned.
Parameters
name The name of the new graduation month
Definition at line 1702 of file ConfigurableSettingsTab.java.
{
         try {
             if (name == null || name.trim().length() == 0)
                 throw new IllegalArgumentException("Name is required");
             int monthInt = monthNameToInt(name);
             // Add the new month to the end of the list.
             List<GraduationMonth> months = settingRepo.findAllGraduationMonths();
             GraduationMonth month = settingRepo.createGraduationMonth(monthInt);
             months.add(month);
             saveModelOrder(months);
             name = escapeJavaScript(month.getMonthName());
             renderJSON("{ \"success\": \"true\", \"id\": " + month.getId() + ", \"name\": \"" + name + "\" }");
         } catch (IllegalArgumentException iae) {
             String message = escapeJavaScript(iae.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         } catch (PersistenceException pe) {
             name = escapeJavaScript(name);
             renderJSON("{ \"failure\": \"true\", \"message\": \"Another graduation month already exists with the name: '"+name+"'\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to add graduation month");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.addLanguageJSON (String name) static
Create a new Language. The id of the new language will be returned.
Parameters
name The description provided by proquest of the new language
Definition at line 1872 of file ConfigurableSettingsTab.java.
References org.tdl.vireo.proquest.ProquestUtilityService.languageCode().
{
         try {
             if (name == null || name.trim().length() == 0)
                 throw new IllegalArgumentException("Name is required");
             // Add the new program to the end of the list.
             List<Language> languages = settingRepo.findAllLanguages();
             Language language = settingRepo.createLanguage(name);
             languages.add(language);
             saveModelOrder(languages);
             String displayName = language.getLocale().getDisplayName();
             if (proquestUtils.languageCode(language.getLocale()) != null)
                 displayName += "&nbsp;&nbsp; &diams;";
             displayName = escapeJavaScript(displayName);
             renderJSON("{ \"success\": \"true\", \"id\": " + language.getId()
                     + ", \"name\": \"" + displayName + "\" }");
         } catch (IllegalArgumentException iae) {
             String message = escapeJavaScript(iae.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         } catch (PersistenceException pe) {
             name = escapeJavaScript(name);
             renderJSON("{ \"failure\": \"true\", \"message\": \"Another language already exists with the name: '"+name+"'\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to add program");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.addMajorJSON (String name) static
Create a new Major. The id of the new major will be returned.
Parameters
name The name of the new major
Definition at line 1012 of file ConfigurableSettingsTab.java.
{
         try {
             if (name == null || name.trim().length() == 0)
                 throw new IllegalArgumentException("Name is required");
             // Add the new major to the end of the list.
             List<Major> majors = settingRepo.findAllMajors();
             Major major = settingRepo.createMajor(name);
             majors.add(major);
             saveModelOrder(majors);
             name = escapeJavaScript(major.getName());
             renderJSON("{ \"success\": \"true\", \"id\": " + major.getId()
                     + ", \"name\": \"" + name + "\" }");
         } catch (IllegalArgumentException iae) {
             String message = escapeJavaScript(iae.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         } catch (PersistenceException pe) {
             name = escapeJavaScript(name);
             renderJSON("{ \"failure\": \"true\", \"message\": \"Another major already exists with the name: '"+name+"'\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to add major");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.alphabetizeAllAdministrativeGroups () static
Alphabetize all administrative groups.
Definition at line 991 of file ConfigurableSettingsTab.java.
{
         List<AdministrativeGroup> adminGroups = settingRepo.findAllAdministrativeGroups();
         Collections.sort(adminGroups, ascending(getModelCompator()));
         saveModelOrder(adminGroups);
         flash.put("open","availableAdminGroups");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.alphabetizeAllColleges () static
Alphabetize all colleges.
Definition at line 533 of file ConfigurableSettingsTab.java.
{
         List<College> colleges = settingRepo.findAllColleges();
         Collections.sort(colleges, ascending(getModelCompator()));
         saveModelOrder(colleges);
         flash.put("open","availableColleges");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.alphabetizeAllCommitteeMemberRoleTypes () static
Alphabetize all committee member role types.
Definition at line 1681 of file ConfigurableSettingsTab.java.
{
         List<CommitteeMemberRoleType> types = settingRepo.findAllCommitteeMemberRoleTypes();
         Collections.sort(types, ascending(getModelCompator()));
         saveModelOrder(types);
         flash.put("open","availableCommitteeMemberRoleTypes");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.alphabetizeAllDegrees () static
Alphabetize all degrees.
Definition at line 1331 of file ConfigurableSettingsTab.java.
{
         List<Degree> degrees = settingRepo.findAllDegrees();
         Collections.sort(degrees, ascending(getModelCompator()));
         saveModelOrder(degrees);
         flash.put("open","availableDegrees");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.alphabetizeAllDepartments () static
Alphabetize all departments.
Definition at line 838 of file ConfigurableSettingsTab.java.
{
         List<Department> departments = settingRepo.findAllDepartments();
         Collections.sort(departments, ascending(getModelCompator()));
         saveModelOrder(departments);
         flash.put("open","availableDepartments");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.alphabetizeAllDocumentTypes () static
Alphabetize all document types.
Definition at line 1506 of file ConfigurableSettingsTab.java.
{
         List<DocumentType> types = settingRepo.findAllDocumentTypes();
         Collections.sort(types, ascending(getModelCompator()));
         saveModelOrder(types);
         flash.put("open","availableDocumentTypes");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.alphabetizeAllEmbargoTypes () static
Alphabetize all embargo types.
Definition at line 380 of file ConfigurableSettingsTab.java.
{
         List<EmbargoType> embargos = settingRepo.findAllEmbargoTypes();
         Collections.sort(embargos, ascending(getModelCompator()));
         saveModelOrder(embargos);
         flash.put("open","availableEmbargoTypes");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.alphabetizeAllGraduationMonths () static
Alphabetize all graduation month.
Definition at line 1850 of file ConfigurableSettingsTab.java.
{
         List<GraduationMonth> months = settingRepo.findAllGraduationMonths();
         Collections.sort(months, ascending(getModelCompator()));
         saveModelOrder(months);
         flash.put("open","availableGraduationMonths");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.alphabetizeAllLanguages () static
Alphabetize all languages.
Definition at line 1983 of file ConfigurableSettingsTab.java.
{
         List<Language> languages = settingRepo.findAllLanguages();
         Collections.sort(languages, ascending(getModelCompator()));
         saveModelOrder(languages);
         flash.put("open","availableLanguages");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.alphabetizeAllMajors () static
Alphabetize all majors.
Definition at line 1156 of file ConfigurableSettingsTab.java.
{
         List<Major> majors = settingRepo.findAllMajors();
         Collections.sort(majors, ascending(getModelCompator()));
         saveModelOrder(majors);
         flash.put("open","availableMajors");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.alphabetizeAllPrograms () static
Alphabetize all programs.
Definition at line 684 of file ConfigurableSettingsTab.java.
{
         List<Program> programs = settingRepo.findAllPrograms();
         Collections.sort(programs, ascending(getModelCompator()));
         saveModelOrder(programs);
         flash.put("open","availablePrograms");
         configurableSettings();
     }
static <T> Comparator<T> controllers.settings.ConfigurableSettingsTab.ascending (final Comparator< T > other) static
Definition at line 2054 of file ConfigurableSettingsTab.java.
{
         return new Comparator<T>() {
             public int compare(T o1, T o2) {
                 return 1 * other.compare(o1, o2);
             }
         };
     }
static void controllers.settings.ConfigurableSettingsTab.bulkAdd (String modelType, String bulkAdd) static
Bulk add a set of colleges, programs, departments, or majors. The bulkAdd input is expected to be formated as one item per line. After completing the user will be redirected back to the configurableSettings tab.
Parameters
modelType The type of object being added in bulk.
bulkAdd The items to be added in bulk, one per line.
Definition at line 105 of file ConfigurableSettingsTab.java.
{
         // Build a list triming out any blank or duplicate values.
         String[] rawItems = bulkAdd.split("\n");
         List<String> items = new ArrayList<String>();
         for (String item : rawItems) {
             if (item == null)
                 continue;
             item = item.trim();
             if (item.length() == 0)
                 continue;
             if (items.contains(item))
                 continue;
             items.add(item);
         }
         // Retrieve all current models
         List<AbstractOrderedModel> models;
         if ("college".equals(modelType)) {
             models =(List) settingRepo.findAllColleges();
         } else if ("program".equals(modelType)) {
             models= (List) settingRepo.findAllPrograms();
         } else if ("department".equals(modelType)) {
             models = (List) settingRepo.findAllDepartments();
         } else if ("adminGroup".equals(modelType)) {
             models = (List) settingRepo.findAllAdministrativeGroups();
         } else if ("major".equals(modelType)) {
             models = (List) settingRepo.findAllMajors();
         } else {
             throw new IllegalArgumentException("Unknown modelType: "+modelType);
         }
         // Eliminate any values already created.
         Iterator<String> itr = items.iterator();
         while (itr.hasNext()) {
             String item = itr.next();
             for (AbstractOrderedModel model : models) {
                 if ("college".equals(modelType)) {
                     if (item.equals(((College) model).getName()))
                         itr.remove();
                 } else if ("program".equals(modelType)) {
                     if (item.equals(((Program) model).getName()))
                         itr.remove();
                 } else if ("department".equals(modelType)) {
                     if (item.equals(((Department) model).getName()))
                         itr.remove();
                 } else if ("adminGroup".equals(modelType)) {
                     if (item.equals(((AdministrativeGroup) model).getName()))
                         itr.remove();
                 } else if ("major".equals(modelType)) {
                     if (item.equals(((Major) model).getName()))
                         itr.remove();
                 } else {
                     throw new IllegalArgumentException("Unknown modelType: "+modelType);
                 }
             }
         }
         // Create everything that is left.
         for (String item : items) {
             item = item.trim();
             if ("college".equals(modelType)) {
                 models.add(settingRepo.createCollege(item));
             } else if ("program".equals(modelType)) {
                 models.add(settingRepo.createProgram(item));
             } else if ("department".equals(modelType)) {
                 models.add(settingRepo.createDepartment(item));
             } else if ("adminGroup".equals(modelType)) {
                 models.add(settingRepo.createAdministrativeGroup(item));
             } else if ("major".equals(modelType)) {
                 models.add(settingRepo.createMajor(item));
             } else {
                 throw new IllegalArgumentException("Unknown modelType: "+modelType);
             }
         }
         saveModelOrder(models);
         // Redirect back the configurable setting tab.
         if ("college".equals(modelType)) {
             flash.put("open","availableColleges");
         } else if ("program".equals(modelType)) {
             flash.put("open","availablePrograms");
         } else if ("department".equals(modelType)) {
             flash.put("open","availableDepartments");
         } else if ("adminGroup".equals(modelType)) {
             flash.put("open","availableAdminGroups");
         } else if ("major".equals(modelType)) {
             flash.put("open","availableMajors");
         } else {
             throw new IllegalArgumentException("Unknown modelType: "+modelType);
         }
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.configurableSettings () static
Display the configurable settings page.
Exceptions
Exception
Definition at line 53 of file ConfigurableSettingsTab.java.
References org.tdl.vireo.model.DegreeLevel.DOCTORAL, org.tdl.vireo.model.DegreeLevel.MASTERS, and org.tdl.vireo.model.DegreeLevel.UNDERGRADUATE.
{
         List<EmbargoType> embargos = settingRepo.findAllEmbargoTypes();
         List<College> colleges = settingRepo.findAllColleges();
         List<Program> programs = settingRepo.findAllPrograms();
         List<Department> departments = settingRepo.findAllDepartments();
         List<AdministrativeGroup> adminGroups = settingRepo.findAllAdministrativeGroups();
         List<Major> majors = settingRepo.findAllMajors();
         List<Degree> degrees = settingRepo.findAllDegrees();
         List<DocumentType> docTypes = settingRepo.findAllDocumentTypes();
         List<CommitteeMemberRoleType> roleTypes = settingRepo.findAllCommitteeMemberRoleTypes();
         List<GraduationMonth> gradMonths = settingRepo.findAllGraduationMonths();
         Locale locales[] = Locale.getAvailableLocales();
         List<Locale> localeLanguages = new ArrayList<Locale>(Arrays.asList(locales));
         Collections.sort(localeLanguages, ascending(getLocaleComparator(LocaleComparator.LANGUAGE_SORT, LocaleComparator.COUNTRY_SORT)));
         List<Language> languages = settingRepo.findAllLanguages();
         renderArgs.put("proquestUtils",proquestUtils);
         renderArgs.put("UNDERGRADUATE", DegreeLevel.UNDERGRADUATE);
         renderArgs.put("MASTERS", DegreeLevel.MASTERS);
         renderArgs.put("DOCTORAL", DegreeLevel.DOCTORAL);
         String nav = "settings";
         String subNav = "config";
         EmbargoGuarantor[] guarantors = EmbargoGuarantor.values();
         renderTemplate("SettingTabs/configurableSettings.html", guarantors, nav, subNav,
                 // The lonely tabel on the page
                 embargos,
                 // Sortable lists
                 colleges, programs, departments, adminGroups, majors, degrees, docTypes, roleTypes, gradMonths, languages,
                 // Locales
                 localeLanguages);
     }
static String controllers.settings.ConfigurableSettingsTab.createEmailsJsonAndAddToMap (String emails, HashMap< Integer, String > emails_map) static private
Helper function to create a JSON encoded string for a hashMap of email addresses
Will also modify the passed-in hashMap to add the email addresses
Will validate the email addresses in the process
Parameters
emails - the emails String from the request
emails_map - a blank map to add emails to
Returns
- JSON encoded string representing the hashMap of emails
Definition at line 2004 of file ConfigurableSettingsTab.java.
References org.tdl.vireo.services.Utilities.validateEmailAddress().
{
         String jsonEmails = "[";
         if(emails != null) {
             int i = 0;
             List<String> emails_list = (emails.length() == 0 ? new ArrayList<String>() : Arrays.asList(emails.split(",")));
             for(String email : emails_list) {
                 // validate email
                 if(!Utilities.validateEmailAddress(email, validation)){
                     throw new IllegalArgumentException("Invalid E-Mail Address detected! [" + email + "]");
                 }
                 emails_map.put(i, email);
                 jsonEmails += "{\"id\":" +i+ ",\"email\":\""+email+"\"},";
                 i++;
             }
             if(jsonEmails.length() > 1) {
                 jsonEmails = jsonEmails.substring(0,jsonEmails.length()-1);
             }
         }
         jsonEmails += "]";
         return jsonEmails;
     }
static <T> Comparator<T> controllers.settings.ConfigurableSettingsTab.decending (final Comparator< T > other) static
Definition at line 2046 of file ConfigurableSettingsTab.java.
{
         return new Comparator<T>() {
             public int compare(T o1, T o2) {
                 return -1 * other.compare(o1, o2);
             }
         };
     }
static void controllers.settings.ConfigurableSettingsTab.editCommitteeMemberRoleTypeJSON (String committeeMemberRoleTypeId, String name, int level) static
Edit an existing roleType's name. Both the id and new name will be returned.
Parameters
committeeMemberRoleTypeId The id of the roleType to be edited, in the form "committeeMemberRoleType_id"
name The new name
level The new level id
Definition at line 1576 of file ConfigurableSettingsTab.java.
{
         try {
             // Check input
             if (name == null || name.trim().length() == 0)
                 throw new IllegalArgumentException("Name is required");
             DegreeLevel degreeLevel = DegreeLevel.find(level);
             // Save the new type
             String[] parts = committeeMemberRoleTypeId.split("_");
             Long id = Long.valueOf(parts[1]);
             CommitteeMemberRoleType roleType = settingRepo.findCommitteeMemberRoleType(id);
             roleType.setName(name);
             roleType.setLevel(degreeLevel);
             roleType.save();
             name = escapeJavaScript(name);
             renderJSON("{ \"success\": \"true\", \"id\": " + roleType.getId() + ", \"name\": \"" + name + "\", \"level\": "+degreeLevel.getId()+" }");
         } catch (IllegalArgumentException iae) {
             String message = escapeJavaScript(iae.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         } catch (PersistenceException pe) {
             name = escapeJavaScript(name);
             renderJSON("{ \"failure\": \"true\", \"message\": \"Another committee member role type already exists with the name: '"+name+"'\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to edit committee member role type");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.editDegreeJSON (String degreeId, String name, int level) static
Edit an existing degree's name. Both the id and new name will be returned.
Parameters
degreeId The id of the degree to be edited, in the form "degree_id"
name The new name
level The new level id
Definition at line 1226 of file ConfigurableSettingsTab.java.
{
         try {
             // Check input
             if (name == null || name.trim().length() == 0)
                 throw new IllegalArgumentException("Name is required");
             DegreeLevel degreeLevel = DegreeLevel.find(level);
             // Save the new degree
             String[] parts = degreeId.split("_");
             Long id = Long.valueOf(parts[1]);
             Degree degree = settingRepo.findDegree(id);
             degree.setName(name);
             degree.setLevel(degreeLevel);
             degree.save();
             name = escapeJavaScript(name);
             renderJSON("{ \"success\": \"true\", \"id\": " + degree.getId() + ", \"name\": \"" + name + "\", \"level\": "+degreeLevel.getId()+"}");
         } catch (IllegalArgumentException iae) {
             String message = escapeJavaScript(iae.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         } catch (PersistenceException pe) {
             name = escapeJavaScript(name);
             renderJSON("{ \"failure\": \"true\", \"message\": \"Another degree already exists with the name: '"+name+"'\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to edit degree");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.editDocumentTypeJSON (String documentTypeId, String name, int level) static
Edit an existing documentType's name. Both the id and new name will be returned.
Parameters
documentTypeId The id of the documentType to be edited, in the form "documentType_id"
name The new name
level The new level id
Definition at line 1401 of file ConfigurableSettingsTab.java.
{
         try {
             // Check input
             if (name == null || name.trim().length() == 0)
                 throw new IllegalArgumentException("Name is required");
             DegreeLevel degreeLevel = DegreeLevel.find(level);
             // Save the new type
             String[] parts = documentTypeId.split("_");
             Long id = Long.valueOf(parts[1]);
             DocumentType documentType = settingRepo.findDocumentType(id);
             documentType.setName(name);
             documentType.setLevel(degreeLevel);
             documentType.save();
             name = escapeJavaScript(name);
             renderJSON("{ \"success\": \"true\", \"id\": " + documentType.getId() + ", \"name\": \"" + name + "\", \"level\": "+degreeLevel.getId()+" }");
         } catch (IllegalArgumentException iae) {
             String message = escapeJavaScript(iae.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         } catch (PersistenceException pe) {
             name = escapeJavaScript(name);
             renderJSON("{ \"failure\": \"true\", \"message\": \"Another document type already exists with the name: '"+name+"'\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to edit document type");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.editEmbargoTypeJSON (String embargoTypeId, String name, String description, Integer months, boolean active, String guarantor) static
Create or edit an existing embargo type.
Parameters
embargoId (Optional) The id of the embargo type, in the form "embargoType_id". If no id is provided then a new embargo type will be created.
name The name of the type
description The description of the type.
months The duration, in months, for this embargo.
active Whether this embargo is active.
Definition at line 227 of file ConfigurableSettingsTab.java.
References org.tdl.vireo.model.NameFormat.FIRST_LAST, org.tdl.vireo.model.EmbargoType.getDescription(), org.tdl.vireo.model.EmbargoType.getDuration(), org.tdl.vireo.model.EmbargoType.getGuarantor(), org.tdl.vireo.model.AbstractModel.getId(), and org.tdl.vireo.model.EmbargoType.getName().
{
         Logger.info(embargoTypeId +" - "+ name +" - "+ description +" - "+ guarantor);
         try {
             if (name == null || name.trim().length() == 0)
                 throw new IllegalArgumentException("Name is required");
             if (description == null || description.trim().length() == 0)
                 throw new IllegalArgumentException("Description is required");
             // Create or modify the embargo
             EmbargoType embargo = null;
             if (embargoTypeId != null && embargoTypeId.trim().length() > 0) {
                 // Modify an existing embargo
                 Long id = Long.valueOf(embargoTypeId);
                 embargo = settingRepo.findEmbargoType(id);
                 embargo.setName(name);
                 embargo.setDescription(description);
                 embargo.setDuration(months);
                 embargo.setActive(active);
                 embargo.setGuarantor(EmbargoGuarantor.valueOf(guarantor));
                 embargo.save();
             } else {
                 List<EmbargoType> embargos = settingRepo.findAllEmbargoTypes();
                 // Create a new embargo
                 embargo = settingRepo.createEmbargoType(name, description, months, active, EmbargoGuarantor.valueOf(guarantor));
                 embargos.add(embargo);
                 saveModelOrder(embargos);
             }
             Logger.info("%s (%d: %s) has edited embargo #%d.\nEmbargo Name = '%s'\nEmbargo Description = '%s'\nEmbargo Duration = '%d'\nEmbargo Active = '%b'",
                     context.getPerson().getFormattedName(NameFormat.FIRST_LAST),
                     context.getPerson().getId(),
                     context.getPerson().getEmail(),
                     embargo.getId(),
                     embargo.getName(),
                     embargo.getDescription(),
                     embargo.getDuration(),
                     embargo.isActive(),
                     embargo.getGuarantor());
             name = escapeJavaScript(embargo.getName());
             description = escapeJavaScript(embargo.getDescription());
             renderJSON("{ \"success\": \"true\", \"id\": " + embargo.getId() + ", \"name\": \"" + name + "\", \"description\": \"" + description + "\", \"active\": \"" + active + "\", \"months\": \"" + months + "\", \"guarantor\": \"" + guarantor + "\" }");
         } catch (IllegalArgumentException iae) {
             String message = escapeJavaScript(iae.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         } catch (PersistenceException pe) {
             name = escapeJavaScript(name);
             renderJSON("{ \"failure\": \"true\", \"message\": \"Another embargo type already exists with the name: '"+name+"'\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to add/edit embargo.");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.editGraduationMonthJSON (String graduationMonthId, String name) static
Edit an existing month's name. Both the id and new name will be returned.
Parameters
graduationMonthId The id of the month to be edited, in the form "graduationMonth_id"
name The new name of the month
Definition at line 1746 of file ConfigurableSettingsTab.java.
{
         try {
             // Check input
             if (name == null || name.trim().length() == 0)
                 throw new IllegalArgumentException("Month name is required");
             int monthInt = monthNameToInt(name);
             // Save the new month
             String[] parts = graduationMonthId.split("_");
             Long id = Long.valueOf(parts[1]);
             GraduationMonth month = settingRepo.findGraduationMonth(id);
             month.setMonth(monthInt);
             month.save();
             name = escapeJavaScript(month.getMonthName());
             renderJSON("{ \"success\": \"true\", \"id\": " + month.getId() + ", \"name\": \"" + name + "\" }");
         } catch (IllegalArgumentException iae) {
             String message = escapeJavaScript(iae.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         } catch (PersistenceException pe) {
             name = escapeJavaScript(name);
             renderJSON("{ \"failure\": \"true\", \"message\": \"Another graduation month already exists with the name: '"+name+"'\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to edit graduation month");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.editMajorJSON (String majorId, String name) static
Edit an existing major's name. Both the id and new name will be returned.
Parameters
majorId The id of the major to be edited, in the form "major_id"
name The new name
Definition at line 1053 of file ConfigurableSettingsTab.java.
{
         try {
             // Check input
             if (name == null || name.trim().length() == 0)
                 throw new IllegalArgumentException("Name is required");
             // Save the new major
             String[] parts = majorId.split("_");
             Long id = Long.valueOf(parts[1]);
             Major major = settingRepo.findMajor(id);
             major.setName(name);
             major.save();
             name = escapeJavaScript(name);
             renderJSON("{ \"success\": \"true\", \"id\": " + major.getId()
                     + ", \"name\": \"" + name + "\" }");
         } catch (IllegalArgumentException iae) {
             String message = escapeJavaScript(iae.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         } catch (PersistenceException pe) {
             name = escapeJavaScript(name);
             renderJSON("{ \"failure\": \"true\", \"message\": \"Another major already exists with the name: '"+name+"'\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to edit major");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static Comparator<Locale> controllers.settings.ConfigurableSettingsTab.getLocaleComparator (final LocaleComparator... multipleOptions) static
Definition at line 2062 of file ConfigurableSettingsTab.java.
{
         return new Comparator<Locale>() {
             public int compare(Locale o1, Locale o2) {
                 for (LocaleComparator option : multipleOptions) {
                     int result = option.compare(o1, o2);
                     if (result != 0) {
                         return result;
                     }
                 }
                 return 0;
             }
         };
     }
static Comparator<AbstractOrderedModel> controllers.settings.ConfigurableSettingsTab.getModelCompator () static
Returns
A comparator that can sort abstract models. The particular sorting is dependent upon the specific model type but is mostly based upon the model's name, although sometimes another parameter is considered.
Definition at line 2082 of file ConfigurableSettingsTab.java.
References org.tdl.vireo.model.EmbargoType.getDuration(), org.tdl.vireo.model.CommitteeMemberRoleType.getLevel(), org.tdl.vireo.model.Degree.getLevel(), org.tdl.vireo.model.DocumentType.getLevel(), and org.tdl.vireo.model.EmbargoType.getName().
{
         return new Comparator<AbstractOrderedModel>() {
             private String _getName(AbstractOrderedModel model) {
                 if (model == null)
                     return "";
                 if (model instanceof EmbargoType) {
                     EmbargoType type = (EmbargoType) model;
                     if (type.getDuration() != null) {
                         // Determinate embargos
                         return String.format("%2d - %s", type.getDuration(),type.getName());
                     } else {
                         return String.format("999 - %s", type.getName());
                     }
                 }
                 if (model instanceof College) {
                     return ((College) model).getName();
                 }
                 if (model instanceof Program) {
                     return ((Program) model).getName();
                 }
                 if (model instanceof Department) {
                     return ((Department) model).getName();
                 }
                 if (model instanceof AdministrativeGroup) {
                     return ((AdministrativeGroup) model).getName();
                 }
                 if (model instanceof Major) {
                     return ((Major) model).getName();
                 }
                 if (model instanceof Degree) {
                     Degree degree = ((Degree) model);
                     return (degree.getLevel().getId() - 5) + "-"+degree.getName();
                 }
                 if (model instanceof DocumentType) {
                     DocumentType type = ((DocumentType) model);
                     return (type.getLevel().getId() - 5) + "-"+type.getName();
                 }
                 if (model instanceof CommitteeMemberRoleType) {
                     CommitteeMemberRoleType type = ((CommitteeMemberRoleType) model);
                     return (type.getLevel().getId() - 5) + "-"+type.getName();
                 }
                 if (model instanceof GraduationMonth) {
                     int month = ((GraduationMonth) model).getMonth();
                     if (month < 10)
                         return "0"+month;
                     else
                         return ""+month;
                 }
                 if (model instanceof Language) {
                     return ((Language) model).getLocale().getDisplayName();
                 }
                 throw new IllegalArgumentException("Unknown model type: "+model.getClass().getName());
             }
             public int compare(AbstractOrderedModel o1, AbstractOrderedModel o2) {
                 return _getName(o1).compareTo(_getName(o2));
             }
         };
     }
static void controllers.settings.ConfigurableSettingsTab.removeAdministrativeGroupJSON (String adminGroupId) static
Remove an existing administrative group
Parameters
adminGroupId The id of the administrative group to be removed
Definition at line 928 of file ConfigurableSettingsTab.java.
{
         try {
             // Delete the old administrative group
             Long id = Long.valueOf(adminGroupId);
             AdministrativeGroup adminGroup = settingRepo.findAdministrativeGroup(id);
             adminGroup.delete();
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to remove administrative group");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.removeAllAdministrativeGroups () static
Remove all existing administrative groups
Definition at line 949 of file ConfigurableSettingsTab.java.
{
         List<AdministrativeGroup> adminGroups = settingRepo.findAllAdministrativeGroups();
         for (AdministrativeGroup adminGroup : adminGroups) {
             adminGroup.delete();
         }
         flash.put("open","availableAdminGroups");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.removeAllColleges () static
Remove all existing colleges
Definition at line 491 of file ConfigurableSettingsTab.java.
{
         List<College> colleges = settingRepo.findAllColleges();
         for (College college : colleges) {
             college.delete();
         }
         flash.put("open","availableColleges");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.removeAllCommitteeMemberRoleTypes () static
Remove all existing committee member role types
Definition at line 1639 of file ConfigurableSettingsTab.java.
{
         List<CommitteeMemberRoleType> types = settingRepo.findAllCommitteeMemberRoleTypes();
         for (CommitteeMemberRoleType type : types) {
             type.delete();
         }
         flash.put("open","availableCommitteeMemberRoleTypes");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.removeAllDegrees () static
Remove all existing degrees
Definition at line 1289 of file ConfigurableSettingsTab.java.
{
         List<Degree> degrees = settingRepo.findAllDegrees();
         for (Degree degree : degrees) {
             degree.delete();
         }
         flash.put("open","availableDegrees");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.removeAllDepartments () static
Remove all existing departments
Definition at line 794 of file ConfigurableSettingsTab.java.
{
         List<Department> departments = settingRepo.findAllDepartments();
         for (Department department : departments) {
             department.delete();
         }
         flash.put("open","availableDepartments");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.removeAllDocumentTypes () static
Remove all existing document types
Definition at line 1464 of file ConfigurableSettingsTab.java.
{
         List<DocumentType> types = settingRepo.findAllDocumentTypes();
         for (DocumentType type : types) {
             type.delete();
         }
         flash.put("open","availableDocumentTypes");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.removeAllEmbargoTypes () static
Remove all existing embargo types.
Definition at line 329 of file ConfigurableSettingsTab.java.
References org.tdl.vireo.model.NameFormat.FIRST_LAST.
{
         List<EmbargoType> embargos = settingRepo.findAllEmbargoTypes();
         for (EmbargoType embargo : embargos) {
             embargo.delete();
             Logger.info(
                     "%s (%d: %s) has deleted embargo #%d.\nEmbargo Name = '%s'\nEmbargo Description = '%s'\nEmbargo Duration = '%d'\nEmbargo Active = '%b'",
                     context.getPerson().getFormattedName(NameFormat.FIRST_LAST),
                     context.getPerson().getId(),
                     context.getPerson().getEmail(), embargo.getId(),
                     embargo.getName(), embargo.getDescription(),
                     embargo.getDuration(), embargo.isActive());
         }
         flash.put("open","availableEmbargoTypes");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.removeAllGraduationMonths () static
Remove all existing graduation months
Definition at line 1808 of file ConfigurableSettingsTab.java.
{
         List<GraduationMonth> months = settingRepo.findAllGraduationMonths();
         for (GraduationMonth month : months) {
             month.delete();
         }
         flash.put("open", "availableGraduationMonths");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.removeAllLanguages () static
Remove all existing languages
Definition at line 1939 of file ConfigurableSettingsTab.java.
{
         List<Language> languages = settingRepo.findAllLanguages();
         for (Language language : languages) {
             language.delete();
         }
         flash.put("open", "availableLanguages");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.removeAllMajors () static
Remove all existing majors
Definition at line 1113 of file ConfigurableSettingsTab.java.
{
         List<Major> majors = settingRepo.findAllMajors();
         for (Major major : majors) {
             major.delete();
         }
         flash.put("open","availableMajors");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.removeAllPrograms () static
Remove all existing programs
Definition at line 642 of file ConfigurableSettingsTab.java.
{
         List<Program> programs = settingRepo.findAllPrograms();
         for (Program program : programs) {
             program.delete();
         }
         flash.put("open","availablePrograms");
         configurableSettings();
     }
static void controllers.settings.ConfigurableSettingsTab.removeCollegeJSON (String collegeId) static
Remove an existing college
Parameters
collegeId The id of the college to be removed
Definition at line 470 of file ConfigurableSettingsTab.java.
{
         try {
             // Delete the old college
             Long id = Long.valueOf(collegeId);
             College college = settingRepo.findCollege(id);
             college.delete();
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to remove college");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.removeCommitteeMemberRoleTypeJSON (String committeeMemberRoleTypeId) static
Remove an existing committee member role type
Parameters
committeeMemberRoleTypeId The id of the roleType to be removed of the form "committeeMemberRoleType_id"
Definition at line 1617 of file ConfigurableSettingsTab.java.
{
         try {
             // Delete the old documentType
             String[] parts = committeeMemberRoleTypeId.split("_");
             Long id = Long.valueOf(parts[1]);
             CommitteeMemberRoleType roleType = settingRepo.findCommitteeMemberRoleType(id);
             roleType.delete();
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to remove committee member role type");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.removeDegreeJSON (String degreeId) static
Remove an existing degree
Parameters
degreeId The id of the degree to be removed of the form "degree_id"
Definition at line 1267 of file ConfigurableSettingsTab.java.
{
         try {
             // Delete the old degree
             String[] parts = degreeId.split("_");
             Long id = Long.valueOf(parts[1]);
             Degree degree = settingRepo.findDegree(id);
             degree.delete();
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to remove degree");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.removeDepartmentJSON (String departmentId) static
Remove an existing department
Parameters
departmentId The id of the department to be removed of the form "department_id"
Definition at line 773 of file ConfigurableSettingsTab.java.
{
         try {
             // Delete the old department
             Long id = Long.valueOf(departmentId);
             Department department = settingRepo.findDepartment(id);
             department.delete();
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to remove department");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.removeDocumentTypeJSON (String documentTypeId) static
Remove an existing documentType
Parameters
documentTypeId The id of the documentType to be removed of the form "documentType_id"
Definition at line 1442 of file ConfigurableSettingsTab.java.
{
         try {
             // Delete the old documentType
             String[] parts = documentTypeId.split("_");
             Long id = Long.valueOf(parts[1]);
             DocumentType documentType = settingRepo.findDocumentType(id);
             documentType.delete();
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to remove document type");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.removeEmbargoTypeJSON (String embargoTypeId) static
Remove an existing embargo type.
Parameters
embargoId The id of the embargo type to be removed.
Definition at line 296 of file ConfigurableSettingsTab.java.
References org.tdl.vireo.model.NameFormat.FIRST_LAST.
{
         try {
             String[] parts = embargoTypeId.split("_");
             Long id = Long.valueOf(parts[1]);
             EmbargoType embargo = settingRepo.findEmbargoType(id);
             embargo.delete();
             Logger.info("%s (%d: %s) has deleted embargo #%d.\nEmbargo Name = '%s'\nEmbargo Description = '%s'\nEmbargo Duration = '%d'\nEmbargo Active = '%b'",
                     context.getPerson().getFormattedName(NameFormat.FIRST_LAST),
                     context.getPerson().getId(),
                     context.getPerson().getEmail(),
                     embargo.getId(),
                     embargo.getName(),
                     embargo.getDescription(),
                     embargo.getDuration(),
                     embargo.isActive(),
                     embargo.getGuarantor());
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to remove embargo type");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.removeGraduationMonthJSON (String graduationMonthId) static
Remove an existing graduation month
Parameters
graduationMonthId The id of the graduation month to be removed of the form "graduationMonth_id"
Definition at line 1787 of file ConfigurableSettingsTab.java.
{
         try {
             // Delete the old college
             String[] parts = graduationMonthId.split("_");
             Long id = Long.valueOf(parts[1]);
             GraduationMonth month = settingRepo.findGraduationMonth(id);
             month.delete();
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to remove graduation month");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.removeLanguageJSON (String languageId) static
Remove an existing language
Parameters
languageId The id of the language to be removed of the form "language_id"
Definition at line 1917 of file ConfigurableSettingsTab.java.
{
         try {
             // Delete the old college
             String[] parts = languageId.split("_");
             Long id = Long.valueOf(parts[1]);
             Language language = settingRepo.findLanguage(id);
             language.delete();
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to remove language");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.removeMajorJSON (String majorId) static
Remove an existing major
Parameters
majorId The id of the major to be removed of the form "major_id"
Definition at line 1091 of file ConfigurableSettingsTab.java.
{
         try {
             // Delete the old major
             String[] parts = majorId.split("_");
             Long id = Long.valueOf(parts[1]);
             Major major = settingRepo.findMajor(id);
             major.delete();
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to remove major");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.removeProgramJSON (String programId) static
Remove an existing program
Parameters
programId The id of the program to be removed of the form "program_id"
Definition at line 621 of file ConfigurableSettingsTab.java.
{
         try {
             // Delete the old program
             Long id = Long.valueOf(programId);
             Program program = settingRepo.findProgram(id);
             program.delete();
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to remove program");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.reorderAdministrativeGroupsJSON (String adminGroupIds) static
Reorder a list of administrative groups.
Parameters
adminGroupIds An ordered list of ids in the form: "adminGroup_1,adminGroup_3,adminGroup_2"
Definition at line 967 of file ConfigurableSettingsTab.java.
{
         try {
             if (adminGroupIds != null && adminGroupIds.trim().length() > 0) {
                 // Save the new order
                 List<AdministrativeGroup> adminGroups = resolveIds(adminGroupIds, AdministrativeGroup.class);
                 saveModelOrder(adminGroups);
             }
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to reorder administrative groups");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.reorderCollegesJSON (String collegeIds) static
Reorder a list of colleges.
Parameters
collegeIds An ordered list of ids in the form: "college_1,college_3,college_2"
Definition at line 509 of file ConfigurableSettingsTab.java.
{
         try {
             if (collegeIds != null && collegeIds.trim().length() > 0) {
                 // Save the new order
                 List<College> colleges = resolveIds(collegeIds, College.class);
                 saveModelOrder(colleges);
             }
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to reorder colleges");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.reorderCommitteeMemberRoleTypesJSON (String committeeMemberRoleTypeIds) static
Reorder a list of committee member role types.
Parameters
committeeMemberRoleTypeIds An ordered list of ids in the form: "committeeMemberRoleType_1,committeeMemberRoleType_3,committeeMemberRoleType_2"
Definition at line 1658 of file ConfigurableSettingsTab.java.
{
         try {
             if (committeeMemberRoleTypeIds != null && committeeMemberRoleTypeIds.trim().length() > 0) {
                 // Save the new order
                 List<CommitteeMemberRoleType> roleTypes = resolveIds(committeeMemberRoleTypeIds, CommitteeMemberRoleType.class);
                 saveModelOrder(roleTypes);
             }
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to reoder committee member role types");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.reorderDegreesJSON (String degreeIds) static
Reorder a list of degrees.
Parameters
degreeIds An ordered list of ids in the form: "degree_1,degree_3,degree_2"
Definition at line 1308 of file ConfigurableSettingsTab.java.
{
         try {
             if (degreeIds != null && degreeIds.trim().length() > 0) {
                 // Save the new order
                 List<Degree> degrees = resolveIds(degreeIds, Degree.class);
                 saveModelOrder(degrees);
             }
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to reoder degrees");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.reorderDepartmentsJSON (String departmentIds) static
Reorder a list of departments.
Parameters
departmentIds An ordered list of ids in the form: "department_1,department_3,department_2"
Definition at line 813 of file ConfigurableSettingsTab.java.
{
         try {
             if (departmentIds != null && departmentIds.trim().length() > 0) {
                 // Save the new order
                 List<Department> departments = resolveIds(departmentIds,
                         Department.class);
                 saveModelOrder(departments);
             }
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to reoder departments");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.reorderDocumentTypesJSON (String documentTypeIds) static
Reorder a list of documentTypes.
Parameters
documentTypeIds An ordered list of ids in the form: "documentType_1,documentType_3,documentType_2"
Definition at line 1483 of file ConfigurableSettingsTab.java.
{
         try {
             if (documentTypeIds != null && documentTypeIds.trim().length() > 0) {
                 // Save the new order
                 List<DocumentType> documentTypes = resolveIds(documentTypeIds, DocumentType.class);
                 saveModelOrder(documentTypes);
             }
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to reoder document types");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.reorderEmbargoTypesJSON (String embargoTypeIds) static
Reorder a list of embargo types.
Parameters
embargoIds An ordered list of ids in the form: "embargo_1,embargo_3,embargo_2"
Definition at line 357 of file ConfigurableSettingsTab.java.
{
         try {
             if (embargoTypeIds != null && embargoTypeIds.trim().length() > 0) {
                 // Save the new order
                 List<EmbargoType> embargos = resolveIds(embargoTypeIds, EmbargoType.class);
                 saveModelOrder(embargos);
             }
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to reorder embargos");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.reorderGraduationMonthsJSON (String graduationMonthIds) static
Reorder a list of graduation months.
Parameters
graduationMonthIds An ordered list of ids in the form: "graduationMonth_1,graduationMonth_3,graduationMonth_2"
Definition at line 1827 of file ConfigurableSettingsTab.java.
{
         try {
             if (graduationMonthIds != null && graduationMonthIds.trim().length() > 0) {
                 // Save the new order
                 List<GraduationMonth> months = resolveIds(graduationMonthIds, GraduationMonth.class);
                 saveModelOrder(months);
             }
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to reorder graduation month");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.reorderLanguagesJSON (String languageIds) static
Reorder a list of languages.
Parameters
languageIds An ordered list of ids in the form: "language_1,language_3,language_2"
Definition at line 1959 of file ConfigurableSettingsTab.java.
{
         try {
             if (languageIds != null && languageIds.trim().length() > 0) {
                 // Save the new order
                 List<Language> languages = resolveIds(languageIds, Language.class);
                 saveModelOrder(languages);
             }
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to reorder languages");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.reorderMajorsJSON (String majorIds) static
Reorder a list of majors.
Parameters
majorIds An ordered list of ids in the form: "major_1,major_3,major_2"
Definition at line 1132 of file ConfigurableSettingsTab.java.
{
         try {
             if (majorIds != null && majorIds.trim().length() > 0) {
                 // Save the new order
                 List<Major> majors = resolveIds(majorIds, Major.class);
                 saveModelOrder(majors);
             }
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to reorder majors");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
static void controllers.settings.ConfigurableSettingsTab.reorderProgramsJSON (String programIds) static
Reorder a list of programs.
Parameters
programIds An ordered list of ids in the form: "program_1,program_3,program_2"
Definition at line 660 of file ConfigurableSettingsTab.java.
{
         try {
             if (programIds != null && programIds.trim().length() > 0) {
                 // Save the new order
                 List<Program> programs = resolveIds(programIds, Program.class);
                 saveModelOrder(programs);
             }
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to reorder programs");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message
                     + "\" }");
         }
     }
Member Data Documentation
final ProquestUtilityService controllers.settings.ConfigurableSettingsTab.proquestUtils = Spring.getBeanOfType(ProquestUtilityService.class) static
Definition at line 46 of file ConfigurableSettingsTab.java.
The documentation for this class was generated from the following file:
app/controllers/settings/ConfigurableSettingsTab.java