Vireo: org.tdl.vireo.export.impl.DepositServiceImpl Class Reference
org.tdl.vireo.export.impl.DepositServiceImpl Class Reference
Classes
class DepositJob
Public Member Functions
void setPersonRepository (PersonRepository repo)
void setErrorLog (ErrorLog errorLog)
void setSecurityContext (SecurityContext context)
void setJobManager (JobManager jobManager)
void deposit (DepositLocation location, Submission submission, State successState, boolean wait)
Public Attributes
PersonRepository personRepo
ErrorLog errorLog
SecurityContext context
JobManager jobManager
Detailed Description
Implementation of the deposit service interface.
Author
Scott Phillips
Definition at line 41 of file DepositServiceImpl.java.
Member Function Documentation
void org.tdl.vireo.export.impl.DepositServiceImpl.deposit (DepositLocation location, Submission submission, State successState, boolean wait)
Deposit one submission and if successfully change to the published state.
Deposits may take a substantial amount of time depending on how responsive the remote server is and the size of the submission. Most uses cases should use not wait for competition before returning.
As many errors as possible will be checked before separating into a separate thread as possible. I.e. the location will be checked for all the required attribute, the state of the submission object etc. However some errors may not occur until deposit time. When these errors occur the submission will remain in it's current state and an action log item will be generated detailing the error encountered.
Parameters
location The deposit location where this submission should be deposited into. The location must be complete, containing a repository URL, collection URL, and packager. It is also unwise if the depositor is different than this implementation.
submission The single submission to deposit.
successState The state the submission should will be transition into upon successfully depositing. If the deposit failed then the submission will remain in it's original state.
wait If true the method will not return until the deposit is completed, otherwise depositing will take place in a background thread.
Implements org.tdl.vireo.export.DepositService.
Definition at line 86 of file DepositServiceImpl.java.
References org.tdl.vireo.model.DepositLocation.getCollection(), org.tdl.vireo.model.DepositLocation.getDepositor(), org.tdl.vireo.model.AbstractModel.getId(), org.tdl.vireo.model.DepositLocation.getPackager(), and org.tdl.vireo.model.DepositLocation.getRepository().
{
         // Check our input
         if (location == null)
             throw new IllegalArgumentException("A deposit location is required.");
         if (location.getRepository() == null)
             throw new IllegalArgumentException("A repository URL is required.");
         if (location.getCollection() == null)
             throw new IllegalArgumentException("A collection URL is required.");
         if (location.getPackager() == null)
             throw new IllegalArgumentException("A deposit packager is required.");
         if (location.getDepositor() == null)
             throw new IllegalArgumentException("A depositor is required.");
         if (submission == null || submission.getId() == null)
             throw new IllegalArgumentException("A persisted submission object is required");
         // kick off a job to deposit this submission
         DepositJob job = new DepositJob(location,submission,successState,wait);
         if (wait) {
             // Do it within this thread.
             job.doJob();
         } else {
             // Schedule for background execution.
             job.now();
         }
     }
void org.tdl.vireo.export.impl.DepositServiceImpl.setErrorLog (ErrorLog errorLog)
Parameters
errorLog The error log
Definition at line 65 of file DepositServiceImpl.java.
References org.tdl.vireo.export.impl.DepositServiceImpl.errorLog.
{
         this.errorLog = errorLog;
     }
void org.tdl.vireo.export.impl.DepositServiceImpl.setJobManager (JobManager jobManager)
Parameters
jobManager The manager for background jobs.
Definition at line 80 of file DepositServiceImpl.java.
References org.tdl.vireo.export.impl.DepositServiceImpl.jobManager.
{
         this.jobManager = jobManager;
     }
void org.tdl.vireo.export.impl.DepositServiceImpl.setPersonRepository (PersonRepository repo)
Parameters
repo The person repository
Definition at line 57 of file DepositServiceImpl.java.
{
         this.personRepo = repo;
     }
void org.tdl.vireo.export.impl.DepositServiceImpl.setSecurityContext (SecurityContext context)
Parameters
context The security context managing who is currently logged in.
Definition at line 73 of file DepositServiceImpl.java.
References org.tdl.vireo.export.impl.DepositServiceImpl.context.
{
         this.context = context;
     }
Member Data Documentation
SecurityContext org.tdl.vireo.export.impl.DepositServiceImpl.context
Definition at line 48 of file DepositServiceImpl.java.
Referenced by org.tdl.vireo.export.impl.DepositServiceImpl.DepositJob.DepositJob(), and org.tdl.vireo.export.impl.DepositServiceImpl.setSecurityContext().
ErrorLog org.tdl.vireo.export.impl.DepositServiceImpl.errorLog
Definition at line 45 of file DepositServiceImpl.java.
Referenced by org.tdl.vireo.export.impl.DepositServiceImpl.setErrorLog().
JobManager org.tdl.vireo.export.impl.DepositServiceImpl.jobManager
Definition at line 51 of file DepositServiceImpl.java.
Referenced by org.tdl.vireo.export.impl.DepositServiceImpl.setJobManager().
PersonRepository org.tdl.vireo.export.impl.DepositServiceImpl.personRepo
Definition at line 44 of file DepositServiceImpl.java.
The documentation for this class was generated from the following file:
app/org/tdl/vireo/export/impl/DepositServiceImpl.java