Vireo: controllers.submit.Confirm Class Reference
controllers.submit.Confirm Class Reference
Static Public Member Functions
static void confirm (Long subId)
static void complete (Long subId)
Static Public Member Functions inherited from controllers.AbstractVireoController
static void injectRepositories ()
static void checkForFirstUser ()
static void handleError (Throwable throwable)
Static Protected Member Functions
static String generateCommitteEmailHash (Submission sub)
Static Protected Member Functions inherited from controllers.submit.AbstractSubmitStep
static Submission getSubmission ()
static boolean isFieldEnabled (FieldConfig field)
static boolean isFieldRequired (FieldConfig field)
Static Protected Member Functions inherited from controllers.AbstractVireoController
static boolean isEmpty (String value)
static boolean isNotEmpty (String value)
static String escapeJavaScript (String value)
static String toJSON (String[] values)
static String text2html (String value)
static boolean isFieldRequired (FieldConfig field)
Additional Inherited Members
Static Public Attributes inherited from controllers.AbstractVireoController
static SecurityContext context = Spring.getBeanOfType(SecurityContext.class)
static PersonRepository personRepo = Spring.getBeanOfType(PersonRepository.class)
static SubmissionRepository subRepo = Spring.getBeanOfType(SubmissionRepository.class)
static SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class)
static ProquestVocabularyRepository proquestRepo = Spring.getBeanOfType(ProquestVocabularyRepository.class)
static ErrorLog errorLog = Spring.getBeanOfType(ErrorLog.class)
static StateManager stateManager = Spring.getBeanOfType(StateManager.class)
static Indexer indexer = Spring.getBeanOfType(Indexer.class)
static Searcher searcher = Spring.getBeanOfType(Searcher.class)
static Boolean firstUser = null
Static Package Functions inherited from controllers.submit.AbstractSubmitStep
static void beforeSubmit ()
Detailed Description
This is the fifth, and last step, of the submission process. We allow students to review all their information and make one final confirmation before completing the submission.
Author
Scott Phillips
Bill Ingram
Dan Galewsky
Gad Krumholz
Definition at line 33 of file Confirm.java.
Member Function Documentation
static void controllers.submit.Confirm.complete (Long subId) static
After completing a submission, show a set of instructions on what the student should do next.
Parameters
subid The id of the completed submission.
Definition at line 124 of file Confirm.java.
References controllers.AbstractVireoController.text2html().
Referenced by controllers.submit.Confirm.confirm().
{
         // Get the post submission instructions for display
         String instructions = settingRepo.getConfigValue(SUBMIT_INSTRUCTIONS);
         instructions = text2html(instructions);
         renderTemplate("Submit/complete.html", instructions);
     }
static void controllers.submit.Confirm.confirm (Long subId) static
Confirm the submission has passed the verification from all the previous steps. Then allow the user to review their information before confirming the submission.
Parameters
subId The submission's id.
Definition at line 44 of file Confirm.java.
References org.tdl.vireo.model.AttachmentType.ADMINISTRATIVE, controllers.submit.Confirm.complete(), org.tdl.vireo.model.NameFormat.FIRST_LAST, controllers.submit.Confirm.generateCommitteEmailHash(), org.tdl.vireo.state.State.getDisplayName(), org.tdl.vireo.model.AbstractModel.getId(), org.tdl.vireo.model.Submission.getState(), controllers.submit.AbstractSubmitStep.getSubmission(), org.tdl.vireo.model.AttachmentType.SOURCE, org.tdl.vireo.model.AttachmentType.SUPPLEMENTAL, controllers.submit.License.verify(), controllers.submit.FileUpload.verify(), controllers.submit.DocumentInfo.verify(), and controllers.submit.PersonalInfo.verify().
{
         // Locate the submission
         Submission sub = getSubmission();
         Person submitter = context.getPerson();
         if (!PersonalInfo.verify(sub))
             validation.addError("personalInfo", "There are errors on this page to correct.");
         if (!License.verify(sub))
             validation.addError("license","There are errors on this page to correct.");
         if (!DocumentInfo.verify(sub))
             validation.addError("documentInfo", "There are errors on this page to correct.");
         if (!FileUpload.verify(sub))
             validation.addError("fileUpload", "There are errors on this page to correct.");
         flash.put("from-step","confirm");
         if (params.get("submit_confirm") != null && !validation.hasErrors()) {
             try {
                 context.turnOffAuthorization();
                 if (sub.getState() == stateManager.getInitialState()) {
                     // Only do these things if this is the first submission.
                     // Generate an committee hash
                     generateCommitteEmailHash(sub);
                     // Clear the approval dates
                     sub.setCommitteeApprovalDate(null);
                     sub.setCommitteeEmbargoApprovalDate(null);
                     // Set the submission date
                     sub.setSubmissionDate(new Date());
                 }
                 // Transition to the next state
                 State prevState = sub.getState();
                 State nextState = prevState.getTransitions(sub).get(0);
                 // This will trigger emails being sent out if they are configured in email workflow rules
                 sub.setState(nextState);
                 sub.save();
                 Logger.info("%s (%d: %s) has completed %s submission #%d.",
                         submitter.getFormattedName(NameFormat.FIRST_LAST),
                         submitter.getId(),
                         submitter.getEmail(),
                         prevState.getDisplayName(),
                         sub.getId());
             } finally {
                 context.restoreAuthorization();
             }
             complete(subId);
         }
         List<ActionLog> logs = subRepo.findActionLog(sub);
         Attachment primaryDocument = sub.getPrimaryDocument();
         List<Attachment> additionalDocuments = sub.getAttachmentsByType(AttachmentType.SUPPLEMENTAL,AttachmentType.SOURCE,AttachmentType.ADMINISTRATIVE);
         String grantor = settingRepo.getConfigValue(GRANTOR,"Unknown Institution");
         boolean showEditLinks = true;
         renderTemplate("Submit/confirm.html",subId, sub, grantor, showEditLinks, submitter, logs,
                 primaryDocument,
                 additionalDocuments);
     }
static String controllers.submit.Confirm.generateCommitteEmailHash (Submission sub) static protected
Generate security hash for this submission. This method will make sure that it is not being used by another submission before assigning a hash.
Parameters
sub The submission to assign the hash too.
Returns
The new hash.
Definition at line 140 of file Confirm.java.
References org.tdl.vireo.model.SubmissionRepository.findSubmissionByEmailHash(), and controllers.AbstractVireoController.subRepo.
Referenced by controllers.submit.Confirm.confirm().
{
         String hash = null;
         do {
             byte[] randomBytes = new byte[8];
             new Random().nextBytes(randomBytes);
             String proposed = Base64.encodeBase64URLSafeString(randomBytes);
             proposed = proposed.replaceAll("[^A-Za-z0-9]","");
             // Check if the hash already exists
             if (subRepo.findSubmissionByEmailHash(proposed) == null) {
                 // We're done, otherwise keep looping.
                 hash = proposed;
             }
         } while (hash == null);
         sub.setCommitteeEmailHash(hash);
         return hash;
     }
The documentation for this class was generated from the following file:
app/controllers/submit/Confirm.java