Vireo: org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob Class Reference
org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob Class Reference
Public Member Functions
TransitionJob (SearchFilter filter, State state, DepositLocation location)
void doJob ()
Public Attributes
final SearchFilter filter
final State state
final DepositLocation location
final Long personId
final JobMetadata metadata
Detailed Description
The background job to update submissions.
Definition at line 148 of file TransitionServiceImpl.java.
Constructor & Destructor Documentation
org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.TransitionJob (SearchFilter filter, State state, DepositLocation location)
Construct a new background transition job.
Parameters
filter The filter to use to search for submissions.
state The new state submissions should be set too.
location The location where submissions should be deposited to (may be null)
Definition at line 169 of file TransitionServiceImpl.java.
References org.tdl.vireo.batch.impl.TransitionServiceImpl.context, org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.filter, org.tdl.vireo.security.SecurityContext.getPerson(), org.tdl.vireo.state.State.isDepositable(), org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.location, org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.metadata, org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.personId, org.tdl.vireo.job.JobStatus.READY, and org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.state.
{
             this.filter = filter;
             this.state = state;
             this.location = location;
             if (context.getPerson() != null)
                 personId = context.getPerson().getId();
             else
                 personId = null;
             String jobName = "Batch Update Status";
             if (state.isDepositable() && location != null)
                 jobName = "Batch Deposit";
             metadata = jobManager.register(jobName,context.getPerson());
             metadata.setJob(this);
             metadata.setStatus(JobStatus.READY);
             metadata.setMessage("Waiting to start...");
         }
Member Function Documentation
void org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.doJob ()
Do the work.
Definition at line 194 of file TransitionServiceImpl.java.
References org.tdl.vireo.search.SearchDirection.ASCENDING, org.tdl.vireo.job.JobStatus.FAILED, org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.filter, org.tdl.vireo.job.JobMetadata.getProgress(), org.tdl.vireo.search.SearchOrder.ID, org.tdl.vireo.state.State.isDepositable(), org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.location, org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.metadata, org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.personId, org.tdl.vireo.job.JobStatus.RUNNING, org.tdl.vireo.job.JobMetadata.setMessage(), org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.state, and org.tdl.vireo.job.JobStatus.SUCCESS.
{
             try {
                 metadata.setStatus(JobStatus.RUNNING);
                 metadata.setMessage("Preparing to run...");
                 // Handle authorization
                 if (personId != null) {
                     Person person = personRepo.findPerson(personId);
                     if (person == null)
                         throw new IllegalStateException("Unable to complete transition job because person no longer exists.");
                     context.login(person);
                 } else {
                     context.turnOffAuthorization();
                 }
                 // Figure out how many submissions total we are exporting
                 long[] subIds = searcher.submissionSearch(filter, SearchOrder.ID, SearchDirection.ASCENDING);
                 metadata.getProgress().total = subIds.length;
                 metadata.getProgress().completed = 0;
                 // Transition!
                 if (state.isDepositable() && location != null)
                     metadata.setMessage("Depositing submissions...");
                 else
                     metadata.setMessage("Updating submissions...");
                 for (long subId : subIds) {
                     Submission sub = subRepo.findSubmission(subId);
                     if (state.isDepositable() && location != null) {
                         // We're doing a deposit transition
                         depositService.deposit(location, sub, state, true);
                     } else {
                         // Do a regular transition
                         sub.setState(state);
                         sub.save();
                     }
                     // Immediately save the transaction
                     JPA.em().getTransaction().commit();
                     JPA.em().clear();
                     JPA.em().getTransaction().begin();
                     // Don't let memory get out of controll
                     System.gc();
                     metadata.getProgress().completed++;
                 }
                 metadata.setMessage(null);
                 metadata.setStatus(JobStatus.SUCCESS);
             } catch (RuntimeException re) {
                 Logger.fatal(re,"Unexpected exception while attempting to transition items. Aborted.");
                 errorLog.logError(re, metadata);
                 metadata.setMessage(re.toString());
                 metadata.setStatus(JobStatus.FAILED);
             } finally {
                 if (personId != null) {
                     context.logout();
                 } else {
                     context.restoreAuthorization();
                 }
                 metadata.setJob(null);
             }
         }
Member Data Documentation
final SearchFilter org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.filter
Definition at line 151 of file TransitionServiceImpl.java.
Referenced by org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.doJob(), and org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.TransitionJob().
final DepositLocation org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.location
Definition at line 153 of file TransitionServiceImpl.java.
Referenced by org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.doJob(), and org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.TransitionJob().
final JobMetadata org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.metadata
Definition at line 155 of file TransitionServiceImpl.java.
Referenced by org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.doJob(), and org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.TransitionJob().
final Long org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.personId
Definition at line 154 of file TransitionServiceImpl.java.
Referenced by org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.doJob(), and org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.TransitionJob().
final State org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.state
Definition at line 152 of file TransitionServiceImpl.java.
Referenced by org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.doJob(), and org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.TransitionJob().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/batch/impl/TransitionServiceImpl.java