Vireo: org.tdl.vireo.services.StringVariableReplacement Class Reference
org.tdl.vireo.services.StringVariableReplacement Class Reference
Static Public Member Functions
static Map< String, String > setParameters (Submission sub)
static String applyParameterSubstitution (String string, Map< String, String > parameters)
Detailed Description
This service allows for the manipulation of strings–both setting parameters and handling place holder replacements.
Author
Micah Cooper
Jeremy Huff
Definition at line 21 of file StringVariableReplacement.java.
Member Function Documentation
static String org.tdl.vireo.services.StringVariableReplacement.applyParameterSubstitution (String string, Map< String, String > parameters) static
This replaces placeholders within a string with the corresponding value in the parameters, if present. retuns null if not present.
Parameters
string A string containing values to be replaced.
parameters A map of the strings to be replaced with their corresponding value
Returns
The new string, else null
Definition at line 119 of file StringVariableReplacement.java.
{
         if(string == null)
             return null;
         for (String name : parameters.keySet()) {
             String value = parameters.get(name);
             string = string.replaceAll("\\{"+name+"\\}", value);
         }
         return string;
     }
static Map<String, String> org.tdl.vireo.services.StringVariableReplacement.setParameters (Submission sub) static
This generates a map of the strings to be replaced with a specific submissions meta data.
Parameters
sub The Submission object.
Returns
A key value Map of the Source String and the Replacement String.
Definition at line 34 of file StringVariableReplacement.java.
References org.tdl.vireo.model.NameFormat.FIRST_LAST, org.tdl.vireo.model.Submission.getAssignee(), org.tdl.vireo.model.Submission.getCommitteeEmailHash(), org.tdl.vireo.model.Submission.getDepositId(), org.tdl.vireo.model.Submission.getDocumentTitle(), org.tdl.vireo.model.Submission.getDocumentType(), org.tdl.vireo.model.Submission.getGraduationMonth(), org.tdl.vireo.model.Submission.getGraduationYear(), org.tdl.vireo.model.Submission.getState(), org.tdl.vireo.model.Submission.getStudentFirstName(), and org.tdl.vireo.model.Submission.getStudentLastName().
{
         Map<String, String> parameters = new HashMap<String, String>();
         if (sub.getStudentFirstName() != null || sub.getStudentLastName() != null)
             parameters.put("FULL_NAME", sub.getStudentFormattedName(NameFormat.FIRST_LAST));
         if (sub.getStudentFirstName() != null)
             parameters.put("FIRST_NAME", sub.getStudentFirstName());
         if (sub.getStudentLastName() != null)
             parameters.put("LAST_NAME", sub.getStudentLastName());
         if (sub.getDocumentTitle() != null)
             parameters.put("DOCUMENT_TITLE", sub.getDocumentTitle());
         if (sub.getDocumentType() != null)
             parameters.put("DOCUMENT_TYPE", sub.getDocumentType());
         if (sub.getState() != null)
             parameters.put("SUBMISSION_STATUS",sub.getState().getDisplayName());
         if (sub.getGraduationYear() != null) {
             String gradSemester = String.valueOf(sub.getGraduationYear());
             if (sub.getGraduationMonth() != null) {
                 Integer monthInt = sub.getGraduationMonth();
                 String monthName = new DateFormatSymbols().getMonths()[monthInt];
                 gradSemester = monthName+", "+gradSemester;
             }
             parameters.put("GRAD_SEMESTER", gradSemester);
         }
         if (sub.getAssignee() != null)
             parameters.put("SUBMISSION_ASSIGNED_TO",sub.getAssignee().getFormattedName(NameFormat.FIRST_LAST));
         else
             parameters.put("SUBMISSION_ASSIGNED_TO", "n/a");
         // URL for the student to view their submission(s)
         ActionDefinition studentAction = Router.reverse("Student.submissionList");
         studentAction.absolute();
         parameters.put("STUDENT_URL", studentAction.url);
         // URL for the submission directly
         Map<String, Object> params = new HashMap<String, Object>();
         params.put("subId", String.valueOf(sub.getId()));
         ActionDefinition submissionAction = Router.reverse("Student.submissionView", params);
         submissionAction.absolute();
         parameters.put("SUBMISSION_URL", submissionAction.url);
         // Advisor url for reviews
         if (sub.getCommitteeEmailHash() != null) {
             Map<String,Object> routeArgs = new HashMap<String,Object>();
             routeArgs.put("token", sub.getCommitteeEmailHash());
             ActionDefinition advisorAction = Router.reverse("Advisor.review",routeArgs);
             advisorAction.absolute();
             parameters.put("ADVISOR_URL", advisorAction.url);
         }
         //Deposit ID
         String depositID = "No deposit ID found!";
         if(sub.getDepositId() != null) depositID = sub.getDepositId();
         parameters.put("DEPOSIT_URI", depositID);
         parameters.put("SEPARATOR", File.separator);
         return parameters;
     }
The documentation for this class was generated from the following file:
app/org/tdl/vireo/services/StringVariableReplacement.java