Vireo: controllers.Application.SubmissionStatus Class Reference
controllers.Application.SubmissionStatus Class Reference
Public Member Functions
SubmissionStatus ()
Boolean getHasSubmissions ()
Boolean getAllowMultiple ()
String getCurrentSemester ()
Long getNcSubmissionId ()
Long getIpSubmissionId ()
Boolean getSubmissionNeedsCorrections ()
Boolean getSubmissionInProgress ()
Boolean getSubmissionsOpen ()
Private Attributes
Boolean hasSubmissions = false
Boolean submissionInProgress = false
Boolean submissionNeedsCorrections = false
Long ipSubmissionId = (long) 0
Long ncSubmissionId = (long) 0
Boolean allowMultiple = settingRepo.getConfigBoolean(AppConfig.ALLOW_MULTIPLE_SUBMISSIONS)
Boolean submissionsOpen = settingRepo.getConfigBoolean(AppConfig.SUBMISSIONS_OPEN)
String currentSemester = settingRepo.getConfigValue(AppConfig.CURRENT_SEMESTER)
Detailed Description
Helper class to pass submission statuses to template
Author
Gad Krumholz
Definition at line 59 of file Application.java.
Constructor & Destructor Documentation
controllers.Application.SubmissionStatus.SubmissionStatus ()
Definition at line 74 of file Application.java.
References controllers.Application.SubmissionStatus.hasSubmissions, controllers.Application.SubmissionStatus.ipSubmissionId, controllers.Application.SubmissionStatus.ncSubmissionId, controllers.Application.SubmissionStatus.submissionInProgress, and controllers.Application.SubmissionStatus.submissionNeedsCorrections.
{
             // go through all of the submissions for the currently authenticated user
             for (Submission submission : subRepo.findSubmission(context.getPerson())) {
 //              Logger.debug("Sub Id: %s", submission.getId());
 //              Logger.debug("isActive: %s", submission.getState().isActive()); // Submitted, Under Review, Needs Corrections, Corrections Received, Waiting on Req, On Hold, Approved
 //              Logger.debug("isApproved: %s", submission.getState().isApproved()); // Approved
 //              Logger.debug("isArchived: %s", submission.getState().isArchived());// Pending Pub, Published, Withdrawn, Cancelled
 //              Logger.debug("isDeletable: %s", submission.getState().isDeletable()); // Withdrawn, Cancelled
 //              Logger.debug("isDepositable: %s", submission.getState().isDepositable()); // Published
 //              Logger.debug("isEditableByReviewer: %s", submission.getState().isEditableByReviewer()); // Submitted, Under Review, Needs Corrections, Corrections Received, Waiting on Req, On Hold, Approved, Pending Pub, Published, Withdrawn, Cancelled
 //              Logger.debug("isEditableByStudent: %s", submission.getState().isEditableByStudent()); // Needs Corrections
 //              Logger.debug("isInProgress: %s", submission.getState().isInProgress()); // In Progress
 //              Logger.debug("isInWorkflow: %s", submission.getState().isInWorkflow()); // Submitted, Corrections Received, Approved, Pending Pub, Published
                 // if we have any submissions
                 hasSubmissions = true;
                 // if submission has "In Progress" state
                 if (submission.getState().isInProgress()) {
                     submissionInProgress = true;
                     ipSubmissionId = submission.getId();
                 }
                 // if submission has "Needs Corrections" state
                 if (submission.getState().isEditableByStudent()) {
                     submissionNeedsCorrections = true;
                     ncSubmissionId = submission.getId();
                 }
             }
         } // end SubmissionStatus()
Member Function Documentation
Boolean controllers.Application.SubmissionStatus.getAllowMultiple ()
Definition at line 108 of file Application.java.
References controllers.Application.SubmissionStatus.allowMultiple.
Referenced by controllers.submit.PersonalInfo.personalInfo().
{
             return allowMultiple;
         }
String controllers.Application.SubmissionStatus.getCurrentSemester ()
Definition at line 112 of file Application.java.
References controllers.Application.SubmissionStatus.currentSemester.
{
             return currentSemester;
         }
Boolean controllers.Application.SubmissionStatus.getHasSubmissions ()
Definition at line 104 of file Application.java.
References controllers.Application.SubmissionStatus.hasSubmissions.
{
             return hasSubmissions;
         }
Long controllers.Application.SubmissionStatus.getIpSubmissionId ()
Definition at line 120 of file Application.java.
References controllers.Application.SubmissionStatus.ipSubmissionId.
{
             return ipSubmissionId;
         }
Long controllers.Application.SubmissionStatus.getNcSubmissionId ()
Definition at line 116 of file Application.java.
References controllers.Application.SubmissionStatus.ncSubmissionId.
{
             return ncSubmissionId;
         }
Boolean controllers.Application.SubmissionStatus.getSubmissionInProgress ()
Definition at line 128 of file Application.java.
References controllers.Application.SubmissionStatus.submissionInProgress.
{
             return submissionInProgress;
         }
Boolean controllers.Application.SubmissionStatus.getSubmissionNeedsCorrections ()
Definition at line 124 of file Application.java.
References controllers.Application.SubmissionStatus.submissionNeedsCorrections.
{
             return submissionNeedsCorrections;
         }
Boolean controllers.Application.SubmissionStatus.getSubmissionsOpen ()
Definition at line 132 of file Application.java.
References controllers.Application.SubmissionStatus.submissionsOpen.
{
             return submissionsOpen;
         }
Member Data Documentation
Boolean controllers.Application.SubmissionStatus.allowMultiple = settingRepo.getConfigBoolean(AppConfig.ALLOW_MULTIPLE_SUBMISSIONS) private
Definition at line 70 of file Application.java.
Referenced by controllers.Application.SubmissionStatus.getAllowMultiple().
String controllers.Application.SubmissionStatus.currentSemester = settingRepo.getConfigValue(AppConfig.CURRENT_SEMESTER) private
Definition at line 72 of file Application.java.
Referenced by controllers.Application.SubmissionStatus.getCurrentSemester().
Boolean controllers.Application.SubmissionStatus.hasSubmissions = false private
Definition at line 61 of file Application.java.
Referenced by controllers.Application.SubmissionStatus.getHasSubmissions(), and controllers.Application.SubmissionStatus.SubmissionStatus().
Long controllers.Application.SubmissionStatus.ipSubmissionId = (long) 0 private
Definition at line 65 of file Application.java.
Referenced by controllers.Application.SubmissionStatus.getIpSubmissionId(), and controllers.Application.SubmissionStatus.SubmissionStatus().
Long controllers.Application.SubmissionStatus.ncSubmissionId = (long) 0 private
Definition at line 67 of file Application.java.
Referenced by controllers.Application.SubmissionStatus.getNcSubmissionId(), and controllers.Application.SubmissionStatus.SubmissionStatus().
Boolean controllers.Application.SubmissionStatus.submissionInProgress = false private
Definition at line 62 of file Application.java.
Referenced by controllers.Application.SubmissionStatus.getSubmissionInProgress(), and controllers.Application.SubmissionStatus.SubmissionStatus().
Boolean controllers.Application.SubmissionStatus.submissionNeedsCorrections = false private
Definition at line 63 of file Application.java.
Referenced by controllers.Application.SubmissionStatus.getSubmissionNeedsCorrections(), and controllers.Application.SubmissionStatus.SubmissionStatus().
Boolean controllers.Application.SubmissionStatus.submissionsOpen = settingRepo.getConfigBoolean(AppConfig.SUBMISSIONS_OPEN) private
Definition at line 71 of file Application.java.
Referenced by controllers.Application.SubmissionStatus.getSubmissionsOpen().
The documentation for this class was generated from the following file:
app/controllers/Application.java