Vireo: org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel > Class Reference
org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel > Class Reference abstract
Public Member Functions
T save ()
T delete ()
T refresh ()
T merge ()
T detach ()
void assertAdministrator ()
void assertManager ()
void assertReviewer ()
void assertAdministratorOrOwner (Person owner)
void assertManagerOrOwner (Person owner)
void assertReviewerOrOwner (Person owner)
Public Member Functions inherited from org.tdl.vireo.model.AbstractModel
Long getId ()
Detailed Description
Abstract parent class of all JPA-based models. This class merges the return datatypes the basic save, delete, refresh, merge methods between our Vireo interfaces and Play's model object. This is also a place for sharing code between the model implementations such as assertions about the current security context etc.
Author
Scott Phillips
Parameters
<T> The specific model implementation type.
Definition at line 26 of file JpaAbstractModel.java.
Member Function Documentation
void org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.assertAdministrator ()
Assert that the current user is an administrator, if not then a Security Exception will be thrown.
Definition at line 70 of file JpaAbstractModel.java.
References org.tdl.vireo.security.SecurityContext.isAuthorizationActive().
{
         SecurityContext context = Spring.getBeanOfType(SecurityContext.class);
         if (context.isAuthorizationActive() && !context.isAdministrator())
             throw new SecurityException("This operation requires administrative level access.");
     }
void org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.assertAdministratorOrOwner (Person owner)
Assert that the current user is an administrator or the supplied person. If not then a Security Exception will be thrown.
Parameters
owner The owner of the object being asserted.
Definition at line 107 of file JpaAbstractModel.java.
References org.tdl.vireo.security.SecurityContext.isAuthorizationActive().
{
         SecurityContext context = Spring.getBeanOfType(SecurityContext.class);
         if (context.isAuthorizationActive() && !(owner.equals(context.getPerson()) || context.isAdministrator()))
             throw new SecurityException("This operation requires administrative level access, or you must be the owner of this object.");
     }
void org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.assertManager ()
Assert that the current user is an manager or above, if not then a Security Exception will be thrown.
Definition at line 81 of file JpaAbstractModel.java.
References org.tdl.vireo.security.SecurityContext.isAuthorizationActive().
{
         SecurityContext context = Spring.getBeanOfType(SecurityContext.class);
         if (context.isAuthorizationActive() && !context.isManager())
             throw new SecurityException("This operation requires manager level access.");
     }
void org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.assertManagerOrOwner (Person owner)
Assert that the current user is an manager or above, or the supplied person. If not then a Security Exception will be thrown.
Parameters
owner The owner of the object being asserted.
Definition at line 122 of file JpaAbstractModel.java.
References org.tdl.vireo.security.SecurityContext.isAuthorizationActive().
{
         SecurityContext context = Spring.getBeanOfType(SecurityContext.class);
         if (context.isAuthorizationActive() && !(owner.equals(context.getPerson()) || context.isManager()))
             throw new SecurityException("This operation requires manager level access, or you must be the owner of this object.");
     }
void org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.assertReviewer ()
Assert that the current user is an reviewer or above, if not then a Security Exception will be thrown.
Definition at line 92 of file JpaAbstractModel.java.
References org.tdl.vireo.security.SecurityContext.isAuthorizationActive().
{
         SecurityContext context = Spring.getBeanOfType(SecurityContext.class);
         if (context.isAuthorizationActive() && !context.isReviewer())
             throw new SecurityException("This operation requires reviewer level access.");
     }
void org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.assertReviewerOrOwner (Person owner)
Assert that the current user is an reviewer or above, or the supplied person. If not then a Security Exception will be thrown.
Parameters
owner The owner of the object being asserted.
Definition at line 137 of file JpaAbstractModel.java.
References org.tdl.vireo.security.SecurityContext.isAuthorizationActive().
{
         SecurityContext context = Spring.getBeanOfType(SecurityContext.class);
         if (context.isAuthorizationActive() && !(owner.equals(context.getPerson()) || context.isReviewer()))
             throw new SecurityException("This operation requires reviewer level access, or you must be the owner of this object.");
     }
T org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.delete ()
Remove the object from persistent storage.
Returns
The deleted object, for convenience.
Implements org.tdl.vireo.model.AbstractModel.
Definition at line 40 of file JpaAbstractModel.java.
                       {
         T result =  super.delete();
         // Tell the indexer that this object has been updated.
         Indexer indexer = Spring.getBeanOfType(Indexer.class);
         indexer.updated(result);
         return result;
     }
T org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.detach ()
Remove this object as a currently managed entity. After calling this method accessing relationship information may result in an exception, and it is no longer valid to call any persistence method. In order to restore the object to a persistable state the merge() method needs to be called.
Returns
the detached model, for convienence
Implements org.tdl.vireo.model.AbstractModel.
Definition at line 61 of file JpaAbstractModel.java.
                       {
         this.em().detach(this);
         return (T) this;
     }
T org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.merge ()
Merge this object to obtain a managed entity. Note the object returned may be a new instance of the object merged into the current transaction.
Returns
The merged model
Implements org.tdl.vireo.model.AbstractModel.
Definition at line 56 of file JpaAbstractModel.java.
                      {
         return super.merge();
     }
T org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.refresh ()
Refresh the entity state. This will reset any in memory changes to the object and reload the state from the persistent storage.
Returns
the refreshed object, for convenience.
Implements org.tdl.vireo.model.AbstractModel.
Definition at line 51 of file JpaAbstractModel.java.
{
         return super.refresh();
     }
T org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.save ()
Persist any changes made to this object.
Returns
The saved object, for convenience.
Implements org.tdl.vireo.model.AbstractModel.
Definition at line 29 of file JpaAbstractModel.java.
                     {
         T result = super.save();
         // Tell the indexer that this object has been updated.
         Indexer indexer = Spring.getBeanOfType(Indexer.class);
         indexer.updated(result);
         return result;
     }
The documentation for this class was generated from the following file:
app/org/tdl/vireo/model/jpa/JpaAbstractModel.java