Vireo: org.tdl.vireo.model.jpa.HashedBlob Class Reference
org.tdl.vireo.model.jpa.HashedBlob Class Reference
Public Member Functions
HashedBlob ()
InputStream get ()
void set (InputStream is, String type)
long length ()
String type ()
boolean exists ()
File getFile ()
String getUUID ()
int[] sqlTypes ()
Class returnedClass ()
boolean equals (Object o, Object o1) throws HibernateException
int hashCode (Object o) throws HibernateException
Object nullSafeGet (ResultSet rs, String[] names, SessionImplementor session, Object owner) throws HibernateException, SQLException
void nullSafeSet (PreparedStatement st, Object value, int index, SessionImplementor session) throws HibernateException, SQLException
Object deepCopy (Object o) throws HibernateException
boolean isMutable ()
Serializable disassemble (Object o) throws HibernateException
Object assemble (Serializable srlzbl, Object o) throws HibernateException
Object replace (Object o, Object o1, Object o2) throws HibernateException
Static Public Member Functions
static String getUUID (String dbValue)
static File getStore ()
Private Member Functions
HashedBlob (String UUID, String type)
Static Private Member Functions
static boolean equal (Object a, Object b)
Private Attributes
String UUID
String type
File file
Detailed Description
This is a slight update upon the default Play "blob" datatype. The HashedBlob will hash the data files out into sub directories instead of leaving them all in one directory.
Author
Scott Phillips
Gad Krumholz
Definition at line 33 of file HashedBlob.java.
Constructor & Destructor Documentation
org.tdl.vireo.model.jpa.HashedBlob.HashedBlob ()
Definition at line 39 of file HashedBlob.java.
Referenced by org.tdl.vireo.model.jpa.HashedBlob.deepCopy(), org.tdl.vireo.model.jpa.HashedBlob.nullSafeGet(), and org.tdl.vireo.model.jpa.HashedBlob.nullSafeSet().
 {}
org.tdl.vireo.model.jpa.HashedBlob.HashedBlob (String UUID, String type) private
Definition at line 41 of file HashedBlob.java.
References org.tdl.vireo.model.jpa.HashedBlob.type(), and org.tdl.vireo.model.jpa.HashedBlob.UUID.
{
         this.UUID = UUID;
         this.type = type;
     }
Member Function Documentation
Object org.tdl.vireo.model.jpa.HashedBlob.assemble (Serializable srlzbl, Object o) throws HibernateException
Definition at line 166 of file HashedBlob.java.
{
         throw new UnsupportedOperationException("Not supported yet.");
     }
Object org.tdl.vireo.model.jpa.HashedBlob.deepCopy (Object o) throws HibernateException
Definition at line 151 of file HashedBlob.java.
References org.tdl.vireo.model.jpa.HashedBlob.HashedBlob(), org.tdl.vireo.model.jpa.HashedBlob.type(), and org.tdl.vireo.model.jpa.HashedBlob.UUID.
{
         if(o == null) {
             return null;
         }
         return new HashedBlob(((HashedBlob)o).UUID, ((HashedBlob)o).type);
     }
Serializable org.tdl.vireo.model.jpa.HashedBlob.disassemble (Object o) throws HibernateException
Definition at line 162 of file HashedBlob.java.
{
         throw new UnsupportedOperationException("Not supported yet.");
     }
static boolean org.tdl.vireo.model.jpa.HashedBlob.equal (Object a, Object b) static private
Definition at line 116 of file HashedBlob.java.
Referenced by org.tdl.vireo.model.jpa.HashedBlob.equals().
{
       return a == b || (a != null && a.equals(b));
     }
boolean org.tdl.vireo.model.jpa.HashedBlob.equals (Object o, Object o1) throws HibernateException
Definition at line 120 of file HashedBlob.java.
References org.tdl.vireo.model.jpa.HashedBlob.equal(), org.tdl.vireo.model.jpa.HashedBlob.type(), and org.tdl.vireo.model.jpa.HashedBlob.UUID.
{
         if(o instanceof HashedBlob && o1 instanceof HashedBlob) {
             return equal(((HashedBlob)o).UUID, ((HashedBlob)o1).UUID) &&
                     equal(((HashedBlob)o).type, ((HashedBlob)o1).type);
         }
         return equal(o, o1);
     }
boolean org.tdl.vireo.model.jpa.HashedBlob.exists ()
Definition at line 74 of file HashedBlob.java.
References org.tdl.vireo.model.jpa.HashedBlob.getFile(), and org.tdl.vireo.model.jpa.HashedBlob.UUID.
Referenced by org.tdl.vireo.model.jpa.HashedBlob.get().
{
         return UUID != null && getFile().exists();
     }
InputStream org.tdl.vireo.model.jpa.HashedBlob.get ()
Definition at line 46 of file HashedBlob.java.
References org.tdl.vireo.model.jpa.HashedBlob.exists(), and org.tdl.vireo.model.jpa.HashedBlob.getFile().
{
         if(exists()) {
             try {
                 return new FileInputStream(getFile());
             } catch(Exception e) {
                 throw new UnexpectedException(e);
             }
         }
         return null;
     }
File org.tdl.vireo.model.jpa.HashedBlob.getFile ()
This is the one method that is different from the original Blob type.
A hash directory is calculated and set as the parent folder for the file.
Returns
A file pointer to the data.
Definition at line 85 of file HashedBlob.java.
References org.tdl.vireo.model.jpa.HashedBlob.file, org.tdl.vireo.model.jpa.HashedBlob.getStore(), org.tdl.vireo.model.jpa.HashedBlob.getUUID(), and org.tdl.vireo.model.jpa.HashedBlob.UUID.
Referenced by org.tdl.vireo.model.jpa.HashedBlob.exists(), org.tdl.vireo.model.jpa.HashedBlob.get(), org.tdl.vireo.model.jpa.HashedBlob.length(), and org.tdl.vireo.model.jpa.HashedBlob.set().
{
     if (file == null) {
             String UUID = getUUID();
             String name1 = UUID.substring(0, 2);
             String name2 = UUID.substring(2, 4);
             String name3 = UUID.substring(4, 6);
             String name4 = UUID.substring(6, 8);
             File hashDir = new File(getStore(), name1 + File.separator + name2
                     + File.separator + name3 + File.separator + name4);
             file = new File(hashDir, UUID);
         }
         return file;
     }
static File org.tdl.vireo.model.jpa.HashedBlob.getStore () static
Definition at line 180 of file HashedBlob.java.
Referenced by org.tdl.vireo.model.jpa.HashedBlob.getFile().
{
         String name = Play.applicationPath + File.separator + Play.configuration.getProperty("attachments.path", "attachments");
         File store = null;
         if(new File(name).isAbsolute()) {
             store = new File(name);
         } else {
             store = Play.getFile(name);
         }
         if(!store.exists()) {
             store.mkdirs();
         }
         return store;
     }
String org.tdl.vireo.model.jpa.HashedBlob.getUUID ()
Definition at line 102 of file HashedBlob.java.
References org.tdl.vireo.model.jpa.HashedBlob.UUID.
Referenced by org.tdl.vireo.model.jpa.HashedBlob.getFile().
{
         return UUID;
     }
static String org.tdl.vireo.model.jpa.HashedBlob.getUUID (String dbValue) static
Definition at line 176 of file HashedBlob.java.
{
        return dbValue.split("[|]")[0];
     }
int org.tdl.vireo.model.jpa.HashedBlob.hashCode (Object o) throws HibernateException
Definition at line 128 of file HashedBlob.java.
{
         return o.hashCode();
     }
boolean org.tdl.vireo.model.jpa.HashedBlob.isMutable ()
Definition at line 158 of file HashedBlob.java.
{
         return true;
     }
long org.tdl.vireo.model.jpa.HashedBlob.length ()
Definition at line 66 of file HashedBlob.java.
References org.tdl.vireo.model.jpa.HashedBlob.getFile().
{
         return getFile().length();
     }
Object org.tdl.vireo.model.jpa.HashedBlob.nullSafeGet (ResultSet rs, String[] names, SessionImplementor session, Object owner) throws HibernateException, SQLException
Definition at line 133 of file HashedBlob.java.
References org.tdl.vireo.model.jpa.HashedBlob.HashedBlob().
{
         String val = (String) StringType.INSTANCE.get(rs, names[0], session);
         if(val == null || val.length() == 0 || !val.contains("|")) {
             return new HashedBlob();
         }
         return new HashedBlob(val.split("[|]")[0], val.split("[|]")[1]);
     }
void org.tdl.vireo.model.jpa.HashedBlob.nullSafeSet (PreparedStatement st, Object value, int index, SessionImplementor session) throws HibernateException, SQLException
Definition at line 143 of file HashedBlob.java.
References org.tdl.vireo.model.jpa.HashedBlob.HashedBlob().
{
         if(value != null) {
             st.setString(index, ((HashedBlob)value).UUID + "|" + ((HashedBlob)value).type);
         } else {
             st.setNull(index, Types.VARCHAR);
         }
     }
Object org.tdl.vireo.model.jpa.HashedBlob.replace (Object o, Object o1, Object o2) throws HibernateException
Definition at line 170 of file HashedBlob.java.
{
         throw new UnsupportedOperationException("Not supported yet.");
     }
Class org.tdl.vireo.model.jpa.HashedBlob.returnedClass ()
Definition at line 112 of file HashedBlob.java.
{
         return HashedBlob.class;
     }
void org.tdl.vireo.model.jpa.HashedBlob.set (InputStream is, String type)
Definition at line 57 of file HashedBlob.java.
References org.tdl.vireo.model.jpa.HashedBlob.getFile(), and org.tdl.vireo.model.jpa.HashedBlob.type().
{
         this.UUID = Codec.UUID();
         this.type = type;
         // Make sure the hash directory exists.
         getFile().getParentFile().mkdirs();
         IO.write(is, getFile());
     }
int [] org.tdl.vireo.model.jpa.HashedBlob.sqlTypes ()
Definition at line 108 of file HashedBlob.java.
{
         return new int[] {Types.VARCHAR};
     }
String org.tdl.vireo.model.jpa.HashedBlob.type ()
Definition at line 70 of file HashedBlob.java.
Referenced by org.tdl.vireo.model.jpa.HashedBlob.deepCopy(), org.tdl.vireo.model.jpa.HashedBlob.equals(), org.tdl.vireo.model.jpa.HashedBlob.HashedBlob(), and org.tdl.vireo.model.jpa.HashedBlob.set().
{
         return type;
     }
Member Data Documentation
File org.tdl.vireo.model.jpa.HashedBlob.file private
Definition at line 37 of file HashedBlob.java.
Referenced by org.tdl.vireo.model.jpa.HashedBlob.getFile().
String org.tdl.vireo.model.jpa.HashedBlob.type private
Definition at line 36 of file HashedBlob.java.
String org.tdl.vireo.model.jpa.HashedBlob.UUID private
Definition at line 35 of file HashedBlob.java.
Referenced by org.tdl.vireo.model.jpa.HashedBlob.deepCopy(), org.tdl.vireo.model.jpa.HashedBlob.equals(), org.tdl.vireo.model.jpa.HashedBlob.exists(), org.tdl.vireo.model.jpa.HashedBlob.getFile(), org.tdl.vireo.model.jpa.HashedBlob.getUUID(), and org.tdl.vireo.model.jpa.HashedBlob.HashedBlob().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/model/jpa/HashedBlob.java