Vireo: org.tdl.vireo.job.impl.JobManagerImpl Class Reference
org.tdl.vireo.job.impl.JobManagerImpl Class Reference
Public Member Functions
synchronized JobMetadata findJob (UUID jobId)
synchronized List< JobMetadata > findAllJobs ()
synchronized List< JobMetadata > findJobsByStatus (JobStatus...statusList)
synchronized List< JobMetadata > findJobsByOwner (Person owner)
synchronized List< JobMetadata > findJobsByType (Class type)
void waitForJobs (UUID id)
void waitForJobs ()
void waitForJobs (Person owner)
void waitForJobs (Class type)
synchronized JobMetadata register (String name, Person owner)
JobMetadata register (String name)
synchronized void deregister (JobMetadata job)
void setMaxSize (int size)
synchronized String toString ()
Public Attributes
int maxSize = 50
Protected Attributes
List< JobMetadata > jobs = Collections.synchronizedList(new LinkedList())
Private Member Functions
void _prune ()
Detailed Description
Implementation of the job manager interface.
This class provides synchronized access to a list of background operations.
Author
Scott Phillips
Definition at line 24 of file JobManagerImpl.java.
Member Function Documentation
void org.tdl.vireo.job.impl.JobManagerImpl._prune () private
Internal private method to prune background operations if they have completed. This condition should never occur because the background operations should always deregister themselves no matter what. But if it does happen then it's nice to be able to recover without keeping a dangling memory reference around forever.
Definition at line 214 of file JobManagerImpl.java.
References org.tdl.vireo.job.impl.JobManagerImpl.jobs, and org.tdl.vireo.job.impl.JobManagerImpl.maxSize.
Referenced by org.tdl.vireo.job.impl.JobManagerImpl.register().
{
         // Prune if we are too big.
         while (jobs.size() > maxSize) {
             // Find the last completed operation and remove that.
             Iterator<JobMetadata> itr = jobs.iterator();
             while (itr.hasNext()) {
                 if (!itr.next().getStatus().isActive()) {
                     itr.remove();
                     break;
                 }
             }
             // if we exhausted the list and didn't find any to prune then just return. There is nothing we can do here.
             if (!itr.hasNext())
                 return;
         }
     }
synchronized void org.tdl.vireo.job.impl.JobManagerImpl.deregister (JobMetadata job)
Deregister or remove this job's metadata from the manager. While the manager will periodically prune old jobs which have been completed. By calling deregister the job will be immediately removed.
Parameters
job The job to deregister.
Implements org.tdl.vireo.job.JobManager.
Definition at line 191 of file JobManagerImpl.java.
{
         jobs.remove(job);
     }
synchronized List<JobMetadata> org.tdl.vireo.job.impl.JobManagerImpl.findAllJobs ()
Returns
Return all jobs registered with the manager. Note the manager will periodically prune old jobs which have been completed.
Implements org.tdl.vireo.job.JobManager.
Definition at line 48 of file JobManagerImpl.java.
References org.tdl.vireo.job.impl.JobManagerImpl.jobs.
{
         List<JobMetadata> all = new ArrayList<JobMetadata>(jobs);
         Collections.reverse(all);
         return all;
     }
synchronized JobMetadata org.tdl.vireo.job.impl.JobManagerImpl.findJob (UUID jobId)
Locate an individual job's metadata by its UUID.
Parameters
jobId The UUID of the job.
Returns
The job metadata found, or null if not found.
Implements org.tdl.vireo.job.JobManager.
Definition at line 33 of file JobManagerImpl.java.
References org.tdl.vireo.job.impl.JobManagerImpl.jobs.
{
         if (jobId == null)
             throw new IllegalArgumentException("Unable to find background operations with a specific id without the id specified.");
         for (JobMetadata job: jobs) {
             if (jobId.equals(job.getId()))
                 return job;
         }
         return null;
     }
synchronized List<JobMetadata> org.tdl.vireo.job.impl.JobManagerImpl.findJobsByOwner (Person owner)
Find all jobs by the provided person.
Parameters
owner The owner of the job.
Returns
A list of all jobs found.
Implements org.tdl.vireo.job.JobManager.
Definition at line 72 of file JobManagerImpl.java.
References org.tdl.vireo.model.AbstractModel.getId(), and org.tdl.vireo.job.impl.JobManagerImpl.jobs.
{
         if (owner == null || owner.getId() == null)
             throw new IllegalArgumentException("Unable to find background operations from a specific owner without the owner specified.");
         List<JobMetadata> found = new ArrayList<JobMetadata>();
         Long personId = owner.getId();
         for (JobMetadata job: jobs) {
             if (personId.equals(job.getOwnerId())) {
                 found.add(job);
             }
         }
         Collections.reverse(found);
         return found;
     }
synchronized List<JobMetadata> org.tdl.vireo.job.impl.JobManagerImpl.findJobsByStatus (JobStatus... status)
Find all jobs with one of the provided status.
Parameters
status A varargs list of possible states to search for.
Returns
A list of all jobs found.
Implements org.tdl.vireo.job.JobManager.
Definition at line 55 of file JobManagerImpl.java.
References org.tdl.vireo.job.impl.JobManagerImpl.jobs.
Referenced by org.tdl.vireo.job.impl.JobManagerImpl.waitForJobs().
{
         List<JobMetadata> found = new ArrayList<JobMetadata>();
         for (JobMetadata job: jobs) {
             for (JobStatus status : statusList) {
                 if (job.getStatus() == status) {
                     found.add(job);
                 }
             }
         }
         Collections.reverse(found);
         return found;
     }
synchronized List<JobMetadata> org.tdl.vireo.job.impl.JobManagerImpl.findJobsByType (Class type)
Find all jobs of the provided type.
Parameters
type The type of jobs to locate.
Returns
A list of all jobs found.
Implements org.tdl.vireo.job.JobManager.
Definition at line 91 of file JobManagerImpl.java.
References org.tdl.vireo.job.impl.JobManagerImpl.jobs.
{
         if ( type == null )
             throw new IllegalArgumentException("Unable to find background operations of a specific type without the type specified.");
         List<JobMetadata> found = new ArrayList<JobMetadata>();
         for (JobMetadata job: jobs) {
             if (type.isInstance(job)) {
                 found.add(job);
             }
         }
         Collections.reverse(found);
         return found;
     }
synchronized JobMetadata org.tdl.vireo.job.impl.JobManagerImpl.register (String name, Person owner)
Register a new jobMetadata with the provided name and owned by the provided person.
Parameters
name The displayable name of the job.
owner The owner or initiator of the job.
Returns
A new job metadata.
Implements org.tdl.vireo.job.JobManager.
Definition at line 168 of file JobManagerImpl.java.
References org.tdl.vireo.job.impl.JobManagerImpl._prune(), and org.tdl.vireo.job.JobMetadata.getId().
{
         Long ownerId = null;
         if (owner != null && owner.getId() != null)
             ownerId = owner.getId();
         JobMetadataImpl job = new JobMetadataImpl(name, ownerId);
         jobs.add(job);
         _prune();
         return job;
     }
JobMetadata org.tdl.vireo.job.impl.JobManagerImpl.register (String name)
Register a new jobMedatata with the provided name. The job will be recorded as having no owner.
Parameters
name The displayable name of the job.
Returns
A new job metadata.
Implements org.tdl.vireo.job.JobManager.
Definition at line 185 of file JobManagerImpl.java.
{
         return register(name,null);
     }
void org.tdl.vireo.job.impl.JobManagerImpl.setMaxSize (int size)
Set the maximum size for the operation queue.
Parameters
size The maximum operation queue size.
Definition at line 203 of file JobManagerImpl.java.
{
         this.maxSize = size;
     }
synchronized String org.tdl.vireo.job.impl.JobManagerImpl.toString ()
Helpfull method to display the state of the job queue
Definition at line 238 of file JobManagerImpl.java.
References org.tdl.vireo.job.impl.JobManagerImpl.jobs.
{
         StringBuilder string = new StringBuilder();
         for (JobMetadata job : jobs) {
             string.append(job.getId());
             string.append(": ");
             string.append(job.getStatus().name());
             string.append(", ");
             string.append(job.getProgress().toString());
             if (job.getOwnerId() != null) {
                 string.append(" (");
                 string.append(job.getOwnerId());
                 string.append(")");
             }
             string.append("\n");
         }
         return string.toString();
     }
void org.tdl.vireo.job.impl.JobManagerImpl.waitForJobs (UUID id)
Yield the current thread until the specified job has completed.
Parameters
id The UUID of the job to wait for.
Implements org.tdl.vireo.job.JobManager.
Definition at line 108 of file JobManagerImpl.java.
References org.tdl.vireo.job.JobMetadata.getStatus().
{
         JobMetadata job = this.findJob(id);
         if (job == null)
             return;
         while (job.getStatus().isActive()) {
             Thread.yield();
         }
     }
void org.tdl.vireo.job.impl.JobManagerImpl.waitForJobs ()
Yield the current thread until there are no more active jobs.
Implements org.tdl.vireo.job.JobManager.
Definition at line 121 of file JobManagerImpl.java.
References org.tdl.vireo.job.JobStatus.ACTIVE, and org.tdl.vireo.job.impl.JobManagerImpl.findJobsByStatus().
{
         while (this.findJobsByStatus(JobStatus.ACTIVE).size() > 0) {
             Thread.yield();
         }
     }
void org.tdl.vireo.job.impl.JobManagerImpl.waitForJobs (Person owner)
Yield the current thread until all jobs by the specified owner has completed.
Parameters
owner The owner to wait for.
Implements org.tdl.vireo.job.JobManager.
Definition at line 129 of file JobManagerImpl.java.
References org.tdl.vireo.job.impl.JobManagerImpl.jobs.
{
         int active;
         do {
             active = 0;
             List<JobMetadata> jobs = this.findJobsByOwner(owner);
             for (JobMetadata job : jobs) {
                 if (job.getStatus().isActive()) {
                     active++;
                 }
             }
             if (active > 0)
                 Thread.yield();
         } while ( active > 0 );
     }
void org.tdl.vireo.job.impl.JobManagerImpl.waitForJobs (Class type)
Yield the current thread until all jobs of the specified type have completed.
Parameters
type The job type to wait for.
Implements org.tdl.vireo.job.JobManager.
Definition at line 149 of file JobManagerImpl.java.
References org.tdl.vireo.job.impl.JobManagerImpl.jobs.
{
         int active;
         do {
             active = 0;
             List<JobMetadata> jobs = this.findJobsByType(type);
             for (JobMetadata job : jobs) {
                 if (job.getStatus().isActive()) {
                     active++;
                 }
             }
             if (active > 0)
                 Thread.yield();
         } while ( active > 0 );
     }
Member Data Documentation
List<JobMetadata> org.tdl.vireo.job.impl.JobManagerImpl.jobs = Collections.synchronizedList(new LinkedList()) protected
Definition at line 30 of file JobManagerImpl.java.
Referenced by org.tdl.vireo.job.impl.JobManagerImpl._prune(), org.tdl.vireo.job.impl.JobManagerImpl.findAllJobs(), org.tdl.vireo.job.impl.JobManagerImpl.findJob(), org.tdl.vireo.job.impl.JobManagerImpl.findJobsByOwner(), org.tdl.vireo.job.impl.JobManagerImpl.findJobsByStatus(), org.tdl.vireo.job.impl.JobManagerImpl.findJobsByType(), org.tdl.vireo.job.impl.JobManagerImpl.toString(), and org.tdl.vireo.job.impl.JobManagerImpl.waitForJobs().
int org.tdl.vireo.job.impl.JobManagerImpl.maxSize = 50
Definition at line 27 of file JobManagerImpl.java.
Referenced by org.tdl.vireo.job.impl.JobManagerImpl._prune().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/job/impl/JobManagerImpl.java