Vireo: org.tdl.vireo.model.jpa.JpaSubmissionImpl Class Reference
org.tdl.vireo.model.jpa.JpaSubmissionImpl Class Reference
Public Member Functions
JpaSubmissionImpl save ()
JpaSubmissionImpl delete ()
JpaSubmissionImpl detach ()
Person getSubmitter ()
String getStudentFirstName ()
void setStudentFirstName (String firstName)
String getStudentLastName ()
void setStudentLastName (String lastName)
String getStudentMiddleName ()
void setStudentMiddleName (String middleName)
Integer getStudentBirthYear ()
void setStudentBirthYear (Integer year)
String getOrcid ()
void setOrcid (String orcidString)
String getStudentFormattedName (NameFormat format)
String getDocumentTitle ()
void setDocumentTitle (String title)
String getDocumentAbstract ()
void setDocumentAbstract (String docAbstract)
String getDocumentKeywords ()
void setDocumentKeywords (String keywords)
List< String > getDocumentSubjects ()
void addDocumentSubject (String subject)
void removeDocumentSubject (String subject)
void setDocumentLanguage (String language)
String getDocumentLanguage ()
Locale getDocumentLanguageLocale ()
String getPublishedMaterial ()
void setPublishedMaterial (String material)
List< EmbargoType > getEmbargoTypes ()
void addEmbargoType (EmbargoType embargo)
void removeEmbargoType (EmbargoType embargo)
EmbargoType getEmbargoTypeByGuarantor (EmbargoGuarantor guarantor)
Attachment getPrimaryDocument ()
List< Attachment > getSupplementalDocuments ()
List< Attachment > getAttachmentsByType (AttachmentType...types)
List< Attachment > getAttachments ()
Attachment addAttachment (File file, AttachmentType type) throws IOException
Attachment addAttachment (byte[] content, String filename, AttachmentType type) throws IOException
Attachment findAttachmentById (Long id)
Attachment findAttachmentByName (String name)
List< CommitteeMember > getCommitteeMembers ()
CommitteeMember addCommitteeMember (String firstName, String lastName, String middleName)
String getCommitteeContactEmail ()
void setCommitteeContactEmail (String email)
String getCommitteeEmailHash ()
void setCommitteeEmailHash (String hash)
Date getCommitteeApprovalDate ()
void setCommitteeApprovalDate (Date date)
Date getCommitteeEmbargoApprovalDate ()
void setCommitteeEmbargoApprovalDate (Date date)
Date getSubmissionDate ()
void setSubmissionDate (Date date)
Date getApprovalDate ()
void setApprovalDate (Date date)
Date getLicenseAgreementDate ()
void setLicenseAgreementDate (Date date)
Date getDefenseDate ()
void setDefenseDate (Date date)
String getDegree ()
void setDegree (String degree)
DegreeLevel getDegreeLevel ()
void setDegreeLevel (DegreeLevel level)
String getDepartment ()
void setDepartment (String department)
Long getDepartmentId ()
void setDepartmentId (Long departmentId)
String getCollege ()
void setCollege (String college)
Long getCollegeId ()
void setCollegeId (Long id)
String getProgram ()
void setProgram (String program)
Long getProgramId ()
void setProgramId (Long programId)
String getMajor ()
void setMajor (String major)
String getDocumentType ()
void setDocumentType (String documentType)
Integer getGraduationYear ()
void setGraduationYear (Integer year)
Integer getGraduationMonth ()
void setGraduationMonth (Integer month)
State getState ()
void setState (State state)
Person getAssignee ()
void setAssignee (Person assignee)
Boolean getUMIRelease ()
void setUMIRelease (Boolean umiRelease)
List< CustomActionValue > getCustomActions ()
CustomActionValue getCustomAction (CustomActionDefinition definition)
CustomActionValue addCustomAction (CustomActionDefinition definition, Boolean value)
String getDepositId ()
void setDepositId (String depositId)
Date getDepositDate ()
void setDepositDate (Date depositDate)
String getReviewerNotes ()
void setReviewerNotes (String notes)
String getLastLogEntry ()
Date getLastLogDate ()
ActionLog logAction (String entry)
ActionLog logAction (String entry, Attachment attachment)
Public Member Functions inherited from org.tdl.vireo.model.AbstractModel
Long getId ()
public< T extends AbstractModel > T refresh ()
public< T extends AbstractModel > T merge ()
Public Attributes
Person submitter
String studentFirstName
String studentLastName
String studentMiddleName
Integer studentBirthYear
String orcid
String documentTitle
String documentAbstract
String documentKeywords
List< String > documentSubjects
String documentLanguage
String publishedMaterial
List< Long > embargoTypeIds
List< Attachment > attachments
List< CommitteeMember > committeeMembers
String committeeContactEmail
String committeeEmailHash
Date committeeApprovalDate
Date committeeEmbargoApprovalDate
Date submissionDate
Date approvalDate
Date licenseAgreementDate
Date defenseDate
String degree
DegreeLevel degreeLevel
String department
Long departmentId
String college
Long collegeId
String program
Long programId
String major
String documentType
Integer graduationYear
Integer graduationMonth
String stateName
Person assignee
Boolean UMIRelease
List< CustomActionValue > customActions
String depositId
Date depositDate
String reviewerNotes
String lastActionLogEntry
Date lastActionLogDate
List< ActionLog > actionLogs
Protected Member Functions
JpaSubmissionImpl (Person submitter)
void removeAttachment (Attachment attachment)
void removeCommitteeMember (CommitteeMember member)
void removeCustomAction (CustomActionValue value)
void generateLog (String entry, boolean always)
void generateChangeLog (String fieldName, String newValue, boolean always)
void updatePrimaryDocumentName ()
Protected Attributes
List< ActionLog > pendingLogs = new ArrayList<ActionLog>()
boolean documentSubjectsChanged = false
Private Member Functions
void onPostLoad ()
Attachment generateActionLogAttachment ()
boolean equals (Object a, Object b)
Detailed Description
JPA specific implementation of Vireo's Submission interface.
Author
Scott Phillips
Definition at line 70 of file JpaSubmissionImpl.java.
Constructor & Destructor Documentation
org.tdl.vireo.model.jpa.JpaSubmissionImpl.JpaSubmissionImpl (Person submitter) protected
Construct a new JpaSubmissionImpl
Parameters
submitter The student submitting this submission.
Definition at line 213 of file JpaSubmissionImpl.java.
{
         if (submitter == null)
             throw new IllegalArgumentException("Submissions require a submitter");
         assertReviewerOrOwner(submitter);
         this.submitter = submitter;
         this.documentSubjects = new ArrayList<String>();
         this.embargoTypeIds = new ArrayList<Long>();
         this.attachments = new ArrayList<Attachment>();
         this.committeeMembers = new ArrayList<CommitteeMember>();
         this.customActions = new ArrayList<CustomActionValue>();
         this.actionLogs = new ArrayList<ActionLog>();
         this.stateName = (Spring.getBeanOfType(StateManager.class).getInitialState()).getBeanName();
         generateLog("Submission created", true);
     }
Member Function Documentation
Attachment org.tdl.vireo.model.jpa.JpaSubmissionImpl.addAttachment (File file, AttachmentType type) throws IOException
Add a new attachment from a file.
Parameters
file The new attachment file.
type The type of the attachment.
Returns
The newly created attachment.
Implements org.tdl.vireo.model.Submission.
Definition at line 749 of file JpaSubmissionImpl.java.
{
         Attachment attachment = new JpaAttachmentImpl(this, type, file);
         attachments.add(attachment);
         return attachment;
     }
Attachment org.tdl.vireo.model.jpa.JpaSubmissionImpl.addAttachment (byte[] content, String filename, AttachmentType type) throws IOException
Add a new attachment from a byte arra.
Parameters
content The contents of the new attachment.
filename The filename of the file.
type The type of attachment.
Returns
The newly created attachment.
Implements org.tdl.vireo.model.Submission.
Definition at line 758 of file JpaSubmissionImpl.java.
{
         Attachment attachment = new JpaAttachmentImpl(this, type, filename, content);
         attachments.add(attachment);
         return attachment;
     }
CommitteeMember org.tdl.vireo.model.jpa.JpaSubmissionImpl.addCommitteeMember (String firstName, String lastName, String middleName)
Add a new committeeMember
Parameters
firstName The first name of the new member.
lastName The last name of the new member.
middleName The middle name of the new member.
Returns
The newly created member.
Implements org.tdl.vireo.model.Submission.
Definition at line 794 of file JpaSubmissionImpl.java.
{
         CommitteeMember member = new JpaCommitteeMemberImpl(this, firstName,
                 lastName, middleName);
         committeeMembers.add(member);
         return member;
     }
CustomActionValue org.tdl.vireo.model.jpa.JpaSubmissionImpl.addCustomAction (CustomActionDefinition definition, Boolean value)
Add a new custom action.
Parameters
definition The custom action definition.
value The value of the custom action.
Returns
The newly created custom action value.
Implements org.tdl.vireo.model.Submission.
Definition at line 1259 of file JpaSubmissionImpl.java.
{
         CustomActionValue customAction = new JpaCustomActionValueImpl(this,
                 definition, value);
         customActions.add(customAction);
         return customAction;
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.addDocumentSubject (String subject)
Add a new subject to the end of the list of subjects for this document.
Parameters
subject The subject to add.
Implements org.tdl.vireo.model.Submission.
Definition at line 500 of file JpaSubmissionImpl.java.
{
         documentSubjects.add(subject);
         documentSubjectsChanged = true;
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.addEmbargoType (EmbargoType embargo)
Parameters
embargo The new embargo type.
Implements org.tdl.vireo.model.Submission.
Definition at line 576 of file JpaSubmissionImpl.java.
References org.tdl.vireo.model.AbstractModel.getId(), and org.tdl.vireo.model.EmbargoType.getName().
{
         assertReviewerOrOwner(submitter);
         if (!this.embargoTypeIds.contains(embargo.getId())) {
             List<EmbargoType> temp = getEmbargoTypes();
             for(EmbargoType embargoType : temp) {
                 if(embargoType.getGuarantor()==embargo.getGuarantor())
                     embargoTypeIds.remove(embargoType.getId());
             }
             this.embargoTypeIds.add(embargo.getId());
             generateChangeLog("Embargo type",embargo.getName()+"("+embargo.getGuarantor()+")", false);
         }
     }
JpaSubmissionImpl org.tdl.vireo.model.jpa.JpaSubmissionImpl.delete ()
Remove the object from persistent storage.
Returns
The deleted object, for convenience.
Implements org.tdl.vireo.model.AbstractModel.
Definition at line 291 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         // Don't rely on the cascade for deleting attachments because the files
         // need to be deleted on disk.
         List<Attachment> attachmentsCopy = new ArrayList<Attachment>(attachments);
         for (Attachment attachment : attachmentsCopy) {
             attachment.delete();
         }
         // Explicitly delete the committee members because their roles will not
         // delete on cascade.
         List<CommitteeMember> membersCopy = new ArrayList<CommitteeMember>(committeeMembers);
         for (CommitteeMember member : membersCopy) {
             member.delete();
         }
         // Delete all action logs associated with this submission
         em().createQuery(
             "DELETE FROM JpaActionLogImpl " +
                     "WHERE Submission_Id = ? "
             ).setParameter(1, this.getId())
             .executeUpdate();
         embargoTypeIds.clear();
         return super.delete();
     }
JpaSubmissionImpl org.tdl.vireo.model.jpa.JpaSubmissionImpl.detach ()
Remove this object as a currently managed entity. After calling this method accessing relationship information may result in an exception, and it is no longer valid to call any persistence method. In order to restore the object to a persistable state the merge() method needs to be called.
Returns
the detached model, for convienence
Implements org.tdl.vireo.model.AbstractModel.
Definition at line 323 of file JpaSubmissionImpl.java.
{
         submitter.detach();
         if (assignee != null)
             assignee.detach();
 //      if (embargoTypeIds != null) {
 //          for (Long embargoTypeId : embargoTypeIds)
 //              embargoTypeId
 //      }
 //      for (EmbargoType embargoType : getEmbargoTypes()) {
 //          embargoType.detach();
 //        }
         return super.detach();
     }
boolean org.tdl.vireo.model.jpa.JpaSubmissionImpl.equals (Object a, Object b) private
Return true if the two objects are equals, accounting for nulls.
Parameters
a An object
b An object
Returns
True if a is the same as b, otherwise false.
Definition at line 1443 of file JpaSubmissionImpl.java.
{
         if (a == null) {
             if (b == null)
                 return true;
             else
                 return false;
         } else {
             return a.equals(b);
         }
     }
Attachment org.tdl.vireo.model.jpa.JpaSubmissionImpl.findAttachmentById (Long id)
Returns
The specific attachment
Implements org.tdl.vireo.model.Submission.
Definition at line 767 of file JpaSubmissionImpl.java.
{
         for(Attachment attachment : attachments) {
             if(id.compareTo(attachment.getId())==0)
                 return attachment;
         }
         return null;
     }
Attachment org.tdl.vireo.model.jpa.JpaSubmissionImpl.findAttachmentByName (String name)
Returns
the specific attachment
Implements org.tdl.vireo.model.Submission.
Definition at line 776 of file JpaSubmissionImpl.java.
{
         if (name == null)
             return null;
         for(Attachment attachment : attachments) {
             if(name.equals(attachment.getName()))
                 return attachment;
         }
         return null;
     }
Attachment org.tdl.vireo.model.jpa.JpaSubmissionImpl.generateActionLogAttachment () private
Definition at line 653 of file JpaSubmissionImpl.java.
{
         // create an Excel Workbook to store the action log as an attachment
         Attachment actionLogAttachment = null;
         String sheetName = "ActionLog";
         XSSFWorkbook wb = new XSSFWorkbook();
         XSSFSheet sheet = wb.createSheet(sheetName);
         XSSFRow header = sheet.createRow(0);
         int rowNum = 1;
         XSSFRow row = sheet.createRow(rowNum);
         int colNum = 0;
         for(ActionLog actionLog : actionLogs){
             if(rowNum == 1) {
                 header.createCell(colNum).setCellValue("Action Date");
             }
             row.createCell(colNum).setCellValue(actionLog.getActionDate());
             colNum++;
             if(rowNum == 1) {
                 header.createCell(colNum).setCellValue("Attachment Type");
             }
             if(actionLog.getAttachment() != null) {
                 row.createCell(colNum).setCellValue(actionLog.getAttachment().getType().name());
             }
             colNum++;
             if(rowNum == 1) {
                 header.createCell(colNum).setCellValue("Attachment Date");
             }
             if(actionLog.getAttachment() != null) {
                 row.createCell(colNum).setCellValue(actionLog.getAttachment().getDate());
             }
             colNum++;
             if(rowNum == 1) {
                 header.createCell(colNum).setCellValue("Attachment Name");
             }
             if(actionLog.getAttachment() != null) {
                 row.createCell(colNum).setCellValue(actionLog.getAttachment().getName());
             }
             colNum++;
             if(rowNum == 1) {
                 header.createCell(colNum).setCellValue("Attachment Size");
             }
             if(actionLog.getAttachment() != null) {
                 row.createCell(colNum).setCellValue(actionLog.getAttachment().getSize());
             }
             colNum++;
             if(rowNum == 1) {
                 header.createCell(colNum).setCellValue("Action Entry");
             }
             row.createCell(colNum).setCellValue(actionLog.getEntry());
             colNum++;
             if(rowNum == 1) {
                 header.createCell(colNum).setCellValue("Submission State");
             }
             row.createCell(colNum).setCellValue(actionLog.getSubmissionState().getBeanName());
             colNum++;
             rowNum++;
             row = sheet.createRow(rowNum);
             colNum = 0;
         }
         try {
             File actionLogFile = File.createTempFile("actionlog-", ".xlsx");
             actionLogFile.deleteOnExit();
             FileOutputStream actionLogFileOS = new FileOutputStream(actionLogFile);
             wb.write(actionLogFileOS);
             actionLogFileOS.flush();
             actionLogFileOS.close();
             actionLogAttachment = new ActionLogAttachment(this, actionLogFile);
         } catch (IOException e){
             play.Logger.error("Error while generating Action Log Attachment! [%s]", e);
         }
         return actionLogAttachment;
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.generateChangeLog (String fieldName, String newValue, boolean always) protected
Internal method for generating log events.
This will create a preformatted action log entry for a field change. The log will then be appended to the list of pending changes which will be persisted when the submission object is saved.
Parameters
fieldName The name of the field being updated.
newValue The new value of the field. (may be null)
always This log message should be generated no matter what state the submission is currently in.
Definition at line 1408 of file JpaSubmissionImpl.java.
{
         String entry;
         if (newValue == null)
             entry = fieldName + " cleared";
         else
             entry = String.format(
                 "%s changed to '%s'",
                 fieldName,
                 newValue);
         generateLog(entry,always);
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.generateLog (String entry, boolean always) protected
Internal method for generating log events.
This will create an ActionLog entry and append it to a list of pending changes. Then when this object is saved() those logs will be persisted in the database.
Parameters
entry The log entry (note, "by User" will be appended to the end of the log entry)
always This log message should be generated no matter what state the submission is currently in.
Definition at line 1383 of file JpaSubmissionImpl.java.
References org.tdl.vireo.state.StateManager.getInitialState().
{
         if (!always) {
             // Ignore if the submission is in the initial state.
             StateManager manager = Spring.getBeanOfType(StateManager.class);
             if (manager.getInitialState() == this.getState())
                 return;
         }
         pendingLogs.add(logAction(entry));
     }
Date org.tdl.vireo.model.jpa.JpaSubmissionImpl.getApprovalDate ()
Returns
The date the submission was approved for release, or null if it has not been approved.
Implements org.tdl.vireo.model.Submission.
Definition at line 904 of file JpaSubmissionImpl.java.
{
         return approvalDate;
     }
Person org.tdl.vireo.model.jpa.JpaSubmissionImpl.getAssignee ()
Returns
The assigned reviewer for this submission.
Implements org.tdl.vireo.model.Submission.
Definition at line 1190 of file JpaSubmissionImpl.java.
{
         return assignee;
     }
List<Attachment> org.tdl.vireo.model.jpa.JpaSubmissionImpl.getAttachments ()
Returns
The unordered list of all attachments.
Implements org.tdl.vireo.model.Submission.
Definition at line 733 of file JpaSubmissionImpl.java.
{
         return attachments;
     }
List<Attachment> org.tdl.vireo.model.jpa.JpaSubmissionImpl.getAttachmentsByType (AttachmentType... types)
Parameters
type The type of attachment.
Returns
Return a list of all attachments of the given type.
Implements org.tdl.vireo.model.Submission.
Definition at line 632 of file JpaSubmissionImpl.java.
References org.tdl.vireo.model.AttachmentType.ACTIONLOG.
{
         List<Attachment> filteredAttachments = new ArrayList<Attachment>();
         for (AttachmentType type : types) {
             // generate an action log attachment
             if(type == AttachmentType.ACTIONLOG) {
                 filteredAttachments.add(generateActionLogAttachment());
             }
             // get an attachment from JPA
             else {
                 for (Attachment attachment : attachments) {
                     if (type == attachment.getType())
                         filteredAttachments.add(attachment);
                 }
             }
         }
         return filteredAttachments;
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getCollege ()
Returns
The college that will award this degree.
Implements org.tdl.vireo.model.Submission.
Definition at line 1027 of file JpaSubmissionImpl.java.
{
         return college;
     }
Long org.tdl.vireo.model.jpa.JpaSubmissionImpl.getCollegeId ()
Returns
- The college id that will award this degree
Implements org.tdl.vireo.model.Submission.
Definition at line 1048 of file JpaSubmissionImpl.java.
{
         return collegeId;
     }
Date org.tdl.vireo.model.jpa.JpaSubmissionImpl.getCommitteeApprovalDate ()
Returns
The date the committee approved this submission, or null if it has not been approved.
Implements org.tdl.vireo.model.Submission.
Definition at line 844 of file JpaSubmissionImpl.java.
{
         return committeeApprovalDate;
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getCommitteeContactEmail ()
Returns
Get the committee's contact email address.
Implements org.tdl.vireo.model.Submission.
Definition at line 814 of file JpaSubmissionImpl.java.
{
         return committeeContactEmail;
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getCommitteeEmailHash ()
Returns
The secrete committee email hash for approvals.
Implements org.tdl.vireo.model.Submission.
Definition at line 829 of file JpaSubmissionImpl.java.
{
         return committeeEmailHash;
     }
Date org.tdl.vireo.model.jpa.JpaSubmissionImpl.getCommitteeEmbargoApprovalDate ()
Returns
The date the committee approved the embargo type of this submission, or null if it has not been approved.
Implements org.tdl.vireo.model.Submission.
Definition at line 863 of file JpaSubmissionImpl.java.
{
         return committeeEmbargoApprovalDate;
     }
List<CommitteeMember> org.tdl.vireo.model.jpa.JpaSubmissionImpl.getCommitteeMembers ()
Returns
The a list of all committee mebers associated with this submission.
Implements org.tdl.vireo.model.Submission.
Definition at line 788 of file JpaSubmissionImpl.java.
{
         return committeeMembers;
     }
CustomActionValue org.tdl.vireo.model.jpa.JpaSubmissionImpl.getCustomAction (CustomActionDefinition definition)
Parameters
definition The definition of the single action to return.
Returns
The value for the provided custom action definition, otherwise null if no value found for the definition.
Implements org.tdl.vireo.model.Submission.
Definition at line 1235 of file JpaSubmissionImpl.java.
References org.tdl.vireo.model.CustomActionValue.getDefinition().
{
         Iterator<CustomActionValue> valueItr = customActions.iterator();
         while (valueItr.hasNext()) {
             CustomActionValue value = valueItr.next();
             if (value.getDefinition().equals(definition))
                 return value;
         }
         return null;
     }
List<CustomActionValue> org.tdl.vireo.model.jpa.JpaSubmissionImpl.getCustomActions ()
Returns
An unordered list of all custom action values.
Implements org.tdl.vireo.model.Submission.
Definition at line 1230 of file JpaSubmissionImpl.java.
{
         return customActions;
     }
Date org.tdl.vireo.model.jpa.JpaSubmissionImpl.getDefenseDate ()
Returns
The date of the submitter's defense.
Implements org.tdl.vireo.model.Submission.
Definition at line 942 of file JpaSubmissionImpl.java.
{
         return defenseDate;
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getDegree ()
Returns
The degree for this submission.
Implements org.tdl.vireo.model.Submission.
Definition at line 963 of file JpaSubmissionImpl.java.
{
         return degree;
     }
DegreeLevel org.tdl.vireo.model.jpa.JpaSubmissionImpl.getDegreeLevel ()
Returns
The degree level for this submission
Implements org.tdl.vireo.model.Submission.
Definition at line 978 of file JpaSubmissionImpl.java.
{
         return degreeLevel;
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getDepartment ()
Returns
The degree department that will award this degree.
Implements org.tdl.vireo.model.Submission.
Definition at line 996 of file JpaSubmissionImpl.java.
{
         return department;
     }
Long org.tdl.vireo.model.jpa.JpaSubmissionImpl.getDepartmentId ()
Returns
- The department id that will award this degree
Implements org.tdl.vireo.model.Submission.
Definition at line 1017 of file JpaSubmissionImpl.java.
{
         return departmentId;
     }
Date org.tdl.vireo.model.jpa.JpaSubmissionImpl.getDepositDate ()
Returns
The date the submission was deposited.
Implements org.tdl.vireo.model.Submission.
Definition at line 1283 of file JpaSubmissionImpl.java.
{
         return depositDate;
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getDepositId ()
Returns
The deposit id associated with submission. It usually is a URL but different repositories may use another identifier type.
Implements org.tdl.vireo.model.Submission.
Definition at line 1268 of file JpaSubmissionImpl.java.
{
         return depositId;
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getDocumentAbstract ()
Returns
The document abstract
Implements org.tdl.vireo.model.Submission.
Definition at line 463 of file JpaSubmissionImpl.java.
{
         return documentAbstract;
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getDocumentKeywords ()
Returns
A list of document keywords
Implements org.tdl.vireo.model.Submission.
Definition at line 479 of file JpaSubmissionImpl.java.
{
         return documentKeywords;
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getDocumentLanguage ()
Returns
Language of the document
Implements org.tdl.vireo.model.Submission.
Definition at line 533 of file JpaSubmissionImpl.java.
{
         return documentLanguage;
     }
Locale org.tdl.vireo.model.jpa.JpaSubmissionImpl.getDocumentLanguageLocale ()
Returns
The locale of the document language, or null if not set or invalid.
Implements org.tdl.vireo.model.Submission.
Definition at line 538 of file JpaSubmissionImpl.java.
{
         return JpaLanguageImpl._toLocale(documentLanguage);
     }
List<String> org.tdl.vireo.model.jpa.JpaSubmissionImpl.getDocumentSubjects ()
Returns
the mutable list of document subjects. So you may use the add/remove/clear methods available on the list interface to modify this data. The list in it's current form will be saved when the submission object is receives a save() action.
Implements org.tdl.vireo.model.Submission.
Definition at line 495 of file JpaSubmissionImpl.java.
{
         return documentSubjects;
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getDocumentTitle ()
Returns
The document title.
Implements org.tdl.vireo.model.Submission.
Definition at line 448 of file JpaSubmissionImpl.java.
{
         return documentTitle;
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getDocumentType ()
Returns
The document type for this submission.
Implements org.tdl.vireo.model.Submission.
Definition at line 1104 of file JpaSubmissionImpl.java.
{
         return documentType;
     }
EmbargoType org.tdl.vireo.model.jpa.JpaSubmissionImpl.getEmbargoTypeByGuarantor (EmbargoGuarantor guarantor)
Parameters
guarantor The guarantor of the embargo.
Returns
The type of embargo for this submission, affiliated with the specifed guarantor.
Implements org.tdl.vireo.model.Submission.
Definition at line 599 of file JpaSubmissionImpl.java.
References org.tdl.vireo.model.EmbargoType.getGuarantor().
{
         if(embargoTypeIds != null && embargoTypeIds.size()>0) {
             SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class);
             for(Long embargo : embargoTypeIds) {
                 EmbargoType embargoType = settingRepo.findEmbargoType(embargo);
                 if(embargoType != null) {
                     if(embargoType.getGuarantor()==guarantor)
                         return embargoType;
                 }
             }
         }
         return null;
     }
List<EmbargoType> org.tdl.vireo.model.jpa.JpaSubmissionImpl.getEmbargoTypes ()
Returns
The type of embargo for this submission. Either requested or approved.
Implements org.tdl.vireo.model.Submission.
Definition at line 563 of file JpaSubmissionImpl.java.
{
         SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class);
         List<EmbargoType> ret = new ArrayList<EmbargoType>();
         for (Long embargoTypeId : embargoTypeIds) {
             EmbargoType embargoType = settingRepo.findEmbargoType(embargoTypeId);
             if(embargoType!=null) {
                 ret.add(embargoType);
             }
         }
         return ret;
     }
Integer org.tdl.vireo.model.jpa.JpaSubmissionImpl.getGraduationMonth ()
Returns
The graduation month
Implements org.tdl.vireo.model.Submission.
Definition at line 1143 of file JpaSubmissionImpl.java.
{
         return graduationMonth;
     }
Integer org.tdl.vireo.model.jpa.JpaSubmissionImpl.getGraduationYear ()
Returns
The graduation year
Implements org.tdl.vireo.model.Submission.
Definition at line 1122 of file JpaSubmissionImpl.java.
{
         return graduationYear;
     }
Date org.tdl.vireo.model.jpa.JpaSubmissionImpl.getLastLogDate ()
This is a short cut method to improve the performance of displaying search results. It is suggested that implementors cache the date of the last action log to improve performance.
Returns
The date of the last log event to affect this submission.
Implements org.tdl.vireo.model.Submission.
Definition at line 1330 of file JpaSubmissionImpl.java.
{
         return lastActionLogDate;
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getLastLogEntry ()
This is a short cut method to improve the performance of displaying search results. It is suggested that implementors cache the entry of the last action log item to improve performance.
Returns
The entry of the last log event to affect this submission.
Implements org.tdl.vireo.model.Submission.
Definition at line 1325 of file JpaSubmissionImpl.java.
{
         return lastActionLogEntry;
     }
Date org.tdl.vireo.model.jpa.JpaSubmissionImpl.getLicenseAgreementDate ()
Returns
The date the submitter agreed to the license for this submission, or null if the submitter has not agreed.
Implements org.tdl.vireo.model.Submission.
Definition at line 923 of file JpaSubmissionImpl.java.
{
         return licenseAgreementDate;
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getMajor ()
Returns
The major that will award this degree.
Implements org.tdl.vireo.model.Submission.
Definition at line 1089 of file JpaSubmissionImpl.java.
{
         return major;
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getOrcid ()
Returns
The ORCID identifier of the student who authored this submission.
Implements org.tdl.vireo.model.Submission.
Definition at line 423 of file JpaSubmissionImpl.java.
{
         return orcid;
     }
Attachment org.tdl.vireo.model.jpa.JpaSubmissionImpl.getPrimaryDocument ()
Returns
The attachment who's type is PRIMARY.
Implements org.tdl.vireo.model.Submission.
Definition at line 615 of file JpaSubmissionImpl.java.
References org.tdl.vireo.model.AttachmentType.PRIMARY.
{
         for (Attachment attachment : attachments) {
             if (AttachmentType.PRIMARY == attachment.getType())
                 return attachment;
         }
         return null;
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getProgram ()
Returns
The program associated with the submission
Implements org.tdl.vireo.model.Submission.
Definition at line 1058 of file JpaSubmissionImpl.java.
{
         return program;
     }
Long org.tdl.vireo.model.jpa.JpaSubmissionImpl.getProgramId ()
Returns
- The program id that will award this degree
Implements org.tdl.vireo.model.Submission.
Definition at line 1079 of file JpaSubmissionImpl.java.
{
         return programId;
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getPublishedMaterial ()
Whether this submission contains material which has been previously published. Null indicates that no material has been previously published, otherwise a human readable description of the published material is supplied.
Returns
Previously published descriptor
Implements org.tdl.vireo.model.Submission.
Definition at line 543 of file JpaSubmissionImpl.java.
{
         return publishedMaterial;
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getReviewerNotes ()
Returns
Return the current reviewer notes. May only be accessed if a reviewer or above.
Implements org.tdl.vireo.model.Submission.
Definition at line 1296 of file JpaSubmissionImpl.java.
{
         return this.reviewerNotes;
     }
State org.tdl.vireo.model.jpa.JpaSubmissionImpl.getState ()
Returns
The current application's state
Implements org.tdl.vireo.model.Submission.
Definition at line 1166 of file JpaSubmissionImpl.java.
{
         return Spring.getBeanOfType(StateManager.class).getState(stateName);
     }
Integer org.tdl.vireo.model.jpa.JpaSubmissionImpl.getStudentBirthYear ()
Returns
The birth year for the student woh authored this submission.
Implements org.tdl.vireo.model.Submission.
Definition at line 403 of file JpaSubmissionImpl.java.
{
         return studentBirthYear;
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getStudentFirstName ()
Returns
The first name of the student who authored this submission.
Implements org.tdl.vireo.model.Submission.
Definition at line 343 of file JpaSubmissionImpl.java.
{
         return studentFirstName;
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getStudentFormattedName (NameFormat format)
Parameters
format The format specifying how the name should be constructed.
Returns
The student's name according to the format specified.
Implements org.tdl.vireo.model.Submission.
Definition at line 442 of file JpaSubmissionImpl.java.
{
         return NameFormat.format(format, studentFirstName, studentMiddleName, studentLastName, studentBirthYear);
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getStudentLastName ()
Returns
The last name of the student who authored this submission.
Implements org.tdl.vireo.model.Submission.
Definition at line 364 of file JpaSubmissionImpl.java.
{
         return studentLastName;
     }
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.getStudentMiddleName ()
Returns
The middle name of the student who authored this submission.
Implements org.tdl.vireo.model.Submission.
Definition at line 385 of file JpaSubmissionImpl.java.
{
         return studentMiddleName;
     }
Date org.tdl.vireo.model.jpa.JpaSubmissionImpl.getSubmissionDate ()
Returns
The date the submission was submitted for review.
Implements org.tdl.vireo.model.Submission.
Definition at line 882 of file JpaSubmissionImpl.java.
{
         return submissionDate;
     }
Person org.tdl.vireo.model.jpa.JpaSubmissionImpl.getSubmitter ()
Returns
The original submitter who created this submission. This may not necessarily the graduating student. In cases where the submission is being made by a proxy like by a staff member then the submitter would be the person object for the staff member who original created the submission.
Implements org.tdl.vireo.model.Submission.
Definition at line 338 of file JpaSubmissionImpl.java.
{
         return submitter;
     }
List<Attachment> org.tdl.vireo.model.jpa.JpaSubmissionImpl.getSupplementalDocuments ()
Returns
The unordered list of attachments who's type is SUPPLEMENTAL
Implements org.tdl.vireo.model.Submission.
Definition at line 625 of file JpaSubmissionImpl.java.
References org.tdl.vireo.model.AttachmentType.SUPPLEMENTAL.
{
         return getAttachmentsByType(AttachmentType.SUPPLEMENTAL);
     }
Boolean org.tdl.vireo.model.jpa.JpaSubmissionImpl.getUMIRelease ()
Returns
Weather the student has selected to release this submission to UMI.
Implements org.tdl.vireo.model.Submission.
Definition at line 1208 of file JpaSubmissionImpl.java.
{
         return UMIRelease;
     }
ActionLog org.tdl.vireo.model.jpa.JpaSubmissionImpl.logAction (String entry)
Create an action log entry about this submission.
Parameters
entry The entry text to be saved, note " by User" will be appended to the end of this entry text recording who made the action.
Returns
The unsaved action log object.
Implements org.tdl.vireo.model.Submission.
Definition at line 1336 of file JpaSubmissionImpl.java.
{
         return logAction(entry, null);
     }
ActionLog org.tdl.vireo.model.jpa.JpaSubmissionImpl.logAction (String entry, Attachment attachment)
Create an action log entry about this submission. This is method is not included in the public interface at the present time. Maybe in the future we will move it up there. This method operates exactly the same as the "logAction" method, which is defined in the public interface, but accepts an attachment object. The action log object generated will be associated with the attachment object present.
Parameters
entry The entry text to be saved, note " by User" will be appended to the end of this entry text recording who made the action.
attachment The attachment this action log item is associated with (may be null).
Returns
The unsaved action log object.
Definition at line 1356 of file JpaSubmissionImpl.java.
{
         SecurityContext context = Spring.getBeanOfType(SecurityContext.class);
         Person actor = context.getPerson();
         // The "By whom ever" is duplicating data and just uneeded.
         //if (actor != null)
         //  entry += " by " + actor.getFormattedName(NameFormat.FIRST_LAST);
         ActionLog log = new JpaActionLogImpl(this, this.getState(), actor, new Date(), attachment, entry, false);
         pendingLogs.add(log);
         return log;
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.onPostLoad () private
Insure that the pendingLogs array is initialized when loading the object from the database.
Definition at line 203 of file JpaSubmissionImpl.java.
{
          pendingLogs = new ArrayList<ActionLog>();
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.removeAttachment (Attachment attachment) protected
Internal call back method when an attachment has been deleted.
Parameters
attachment The attachment to remove.
Definition at line 743 of file JpaSubmissionImpl.java.
{
         attachments.remove(attachment);
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.removeCommitteeMember (CommitteeMember member) protected
Internal call back for when a committee member has been deleted, so that it will be removed from the list.
Parameters
member The member to remove.
Definition at line 809 of file JpaSubmissionImpl.java.
{
         this.committeeMembers.remove(member);
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.removeCustomAction (CustomActionValue value) protected
Internal call back to notify the parent submission when a custom action value has been deleted.
Parameters
value The value being deleted.
Definition at line 1254 of file JpaSubmissionImpl.java.
{
         customActions.remove(value);
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.removeDocumentSubject (String subject)
Remove the first occurrence of the subject from the list of subjects for this document..
Parameters
subject The subject to remove.
Implements org.tdl.vireo.model.Submission.
Definition at line 506 of file JpaSubmissionImpl.java.
{
         documentSubjects.remove(subject);
         documentSubjectsChanged = true;
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.removeEmbargoType (EmbargoType embargo)
Parameters
embargo The new embargo type.
Implements org.tdl.vireo.model.Submission.
Definition at line 592 of file JpaSubmissionImpl.java.
References org.tdl.vireo.model.AbstractModel.getId().
{
         if(embargoTypeIds.contains(embargo.getId())){
             embargoTypeIds.remove(embargo.getId());
         }
     }
JpaSubmissionImpl org.tdl.vireo.model.jpa.JpaSubmissionImpl.save ()
Persist any changes made to this object.
Returns
The saved object, for convenience.
Implements org.tdl.vireo.model.AbstractModel.
Definition at line 233 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (documentSubjectsChanged) {
             // Generate a note that the subjects have been updated.
             String entry = "";
             if (documentSubjects.size() == 0)
                 entry = "Document subjects cleared";
             else {
                 for (String subject : documentSubjects) {
                     if (entry.length() != 0)
                         entry += "; ";
                     entry += "'"+subject+"'";
                 }
                 entry = "Document subjects changed to "+entry;
             }
             generateLog(entry,false);
             documentSubjectsChanged = false;
         }
         if (pendingLogs.size() > 0) {
             lastActionLogEntry = pendingLogs.get(pendingLogs.size()-1).getEntry();
             lastActionLogDate = pendingLogs.get(pendingLogs.size()-1).getActionDate();
         }
         // Scrub all user-exposed String fields of Unicode control stuff
         this.documentTitle = Utilities.scrubControl(this.documentTitle, "");
         this.documentAbstract = Utilities.scrubControl(this.documentAbstract, " ");
         this.documentKeywords = Utilities.scrubControl(this.documentKeywords, " ");
         this.publishedMaterial = Utilities.scrubControl(this.publishedMaterial, " ");
         // Scrub all user-exposed String fields of Unicode control stuff
         this.documentTitle = Utilities.scrubControl(this.documentTitle, "");
         this.documentAbstract = Utilities.scrubControl(this.documentAbstract, " ");
         this.documentKeywords = Utilities.scrubControl(this.documentKeywords, " ");
         this.publishedMaterial = Utilities.scrubControl(this.publishedMaterial, " ");
         // make sure we don't try to save an ActionLogAttachment
         for(int i=0; i < attachments.size(); i++) {
             Attachment attachment = attachments.get(i);
             if(attachment instanceof ActionLogAttachment) {
                 attachments.remove(i);
             }
         }
         super.save();
         // After saving save all pending actionlogs
         for(ActionLog log : pendingLogs) {
             log.save();
         }
         pendingLogs.clear();
         return this;
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setApprovalDate (Date date)
Parameters
date The new date this submission was approved.
Implements org.tdl.vireo.model.Submission.
Definition at line 909 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.approvalDate,date)) {
             this.approvalDate = date;
             if (date == null)
                 generateLog("Submission approval cleared",true);
             else
                 generateLog("Submission approval set",true);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setAssignee (Person assignee)
Parameters
assignee The new assigned reviewer.
Implements org.tdl.vireo.model.Submission.
Definition at line 1195 of file JpaSubmissionImpl.java.
References org.tdl.vireo.model.NameFormat.FIRST_LAST, and org.tdl.vireo.model.Person.getFormattedName().
{
         assertReviewer();
         this.assignee = assignee;
         if (assignee == null)
             generateChangeLog("Assignee", null,true);
         else
             generateChangeLog("Assignee",assignee.getFormattedName(NameFormat.FIRST_LAST),true);
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setCollege (String college)
Parameters
college The new college.
Implements org.tdl.vireo.model.Submission.
Definition at line 1032 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.college,college)) {
             this.college = college;
             generateChangeLog("College",college,false);
             // set collegeId column
             SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class);
             College collegeJPA =settingRepo.findCollegeByName(college);
             if(collegeJPA != null) {
                 setCollegeId(collegeJPA.getId());
             }
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setCollegeId (Long id)
Parameters
id - the college id that will award this degree
Implements org.tdl.vireo.model.Submission.
Definition at line 1053 of file JpaSubmissionImpl.java.
{
         this.collegeId = id;
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setCommitteeApprovalDate (Date date)
Parameters
date Set the date the committee approved this submission.
Implements org.tdl.vireo.model.Submission.
Definition at line 849 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.committeeApprovalDate,date)) {
             this.committeeApprovalDate = date;
             if (date == null)
                 generateLog("Committee approval of submission cleared",false);
             else
                 generateLog("Committee approval of submission set",false);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setCommitteeContactEmail (String email)
Parameters
email Set the committee's contact email address.
Implements org.tdl.vireo.model.Submission.
Definition at line 819 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.committeeContactEmail,email)) {
             this.committeeContactEmail = email;
             generateChangeLog("Committee contact email address", email, false);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setCommitteeEmailHash (String hash)
Parameters
hash The new secrete committee email hash.
Implements org.tdl.vireo.model.Submission.
Definition at line 834 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.committeeEmailHash,hash)) {
             this.committeeEmailHash = hash;
             generateLog("New committee email hash generated", false);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setCommitteeEmbargoApprovalDate (Date date)
Parameters
date Set the date the committee approved the embargo type of this submission.
Implements org.tdl.vireo.model.Submission.
Definition at line 868 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.committeeEmbargoApprovalDate,date)) {
             this.committeeEmbargoApprovalDate = date;
             if (date == null)
                 generateLog("Committee approval of embargo cleared",false);
             else
                 generateLog("Committee approval of embargo set",false);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setDefenseDate (Date date)
Parameters
date The date of the submitter's defense.
Implements org.tdl.vireo.model.Submission.
Definition at line 947 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.defenseDate,date)) {
             this.defenseDate = date;
             if (date == null) {
                 generateLog("Defense date cleared",true);
             } else {
                 DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
                 generateChangeLog("Defense date",formatter.format(date),true);
             }
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setDegree (String degree)
Parameters
degree The new degree for this submission.
Implements org.tdl.vireo.model.Submission.
Definition at line 968 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.degree,degree)) {
             this.degree = degree;
             generateChangeLog("Degree",degree,false);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setDegreeLevel (DegreeLevel level)
Parameters
level The new degree level for this submission
Implements org.tdl.vireo.model.Submission.
Definition at line 983 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.degreeLevel,level)) {
             this.degreeLevel = level;
             generateChangeLog(
                     "Degree level",
                     (degreeLevel == null) ? null : degreeLevel.name(),
                     false);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setDepartment (String department)
Parameters
department The new department.
Implements org.tdl.vireo.model.Submission.
Definition at line 1001 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.department,department)) {
             this.department = department;
             generateChangeLog("Department",department,false);
             // set departmentId column
             SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class);
             Department departmentJPA = settingRepo.findDepartmentByName(department);
             if(departmentJPA != null) {
                 setDepartmentId(departmentJPA.getId());
             }
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setDepartmentId (Long id)
Parameters
id - the department id that will award this degree
Implements org.tdl.vireo.model.Submission.
Definition at line 1022 of file JpaSubmissionImpl.java.
{
         this.departmentId = departmentId;
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setDepositDate (Date depositDate)
Parameters
depositDate The date the submission was deposited.
Implements org.tdl.vireo.model.Submission.
Definition at line 1288 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         this.depositDate = depositDate;
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setDepositId (String depositId)
Parameters
depositId Set the deposit id for this submission.
Implements org.tdl.vireo.model.Submission.
Definition at line 1273 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.depositId,depositId)) {
             this.depositId = depositId;
             generateChangeLog("Repository deposit ID",depositId,false);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setDocumentAbstract (String docAbstract)
Parameters
docAbstract The new document abstract
Implements org.tdl.vireo.model.Submission.
Definition at line 468 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.documentAbstract,docAbstract)) {
             this.documentAbstract = docAbstract;
             generateChangeLog("Document abstract", docAbstract, false);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setDocumentKeywords (String keywords)
Parameters
keywords A new list of document keywords
Implements org.tdl.vireo.model.Submission.
Definition at line 484 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.documentKeywords,keywords)) {
             this.documentKeywords = keywords;
             generateChangeLog("Document keywords", keywords, false);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setDocumentLanguage (String language)
Parameters
language The new language of the document. Must be a valid java locale.
Implements org.tdl.vireo.model.Submission.
Definition at line 512 of file JpaSubmissionImpl.java.
References org.tdl.vireo.model.jpa.JpaLanguageImpl._toLocale().
{
         if (language != null) {
             if(language.isEmpty())
                 language = null;
             else if(JpaLanguageImpl._toLocale(language) == null)
                 throw new IllegalArgumentException("Language is an invalid locale");
         }
         assertReviewerOrOwner(submitter);
         if (!equals(this.documentLanguage,language)) {
             this.documentLanguage = language;
             if(language != null)
                 generateChangeLog("Document language",JpaLanguageImpl._toLocale(language).getDisplayName(),false);
             else
                 generateChangeLog("Document language",null,false);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setDocumentTitle (String title)
Parameters
title The new document title.
Implements org.tdl.vireo.model.Submission.
Definition at line 453 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.documentTitle,title)) {
             this.documentTitle = title;
             generateChangeLog("Document title", title, false);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setDocumentType (String documentType)
Parameters
documentType The new document type.
Implements org.tdl.vireo.model.Submission.
Definition at line 1110 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.documentType,documentType)) {
             this.documentType = documentType;
             generateChangeLog("Document type",documentType,false);
             updatePrimaryDocumentName();
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setGraduationMonth (Integer month)
Parameters
month The new graduation month.
Implements org.tdl.vireo.model.Submission.
Definition at line 1148 of file JpaSubmissionImpl.java.
{
         if (month != null && (month < 0 || month > 11))
             throw new IllegalArgumentException("Month is out of bounds.");
         assertReviewerOrOwner(submitter);
         if (!equals(this.graduationMonth,month)) {
             this.graduationMonth = month;
             if (month == null)
                 generateChangeLog("Graduation month", null,false);
             else
                 generateChangeLog("Graduation month", new DateFormatSymbols().getMonths()[month],false);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setGraduationYear (Integer year)
Parameters
year The new graduation year
Implements org.tdl.vireo.model.Submission.
Definition at line 1127 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.graduationYear,year)) {
             this.graduationYear = year;
             if (year == null)
                 generateChangeLog("Graduation year", null,false);
             else
                 generateChangeLog("Graduation year", String.valueOf(year),false);
             updatePrimaryDocumentName();
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setLicenseAgreementDate (Date date)
Parameters
date The new date the submitter agreed to the license.
Implements org.tdl.vireo.model.Submission.
Definition at line 928 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.licenseAgreementDate,date)) {
             this.licenseAgreementDate = date;
             if (date == null)
                 generateLog("Submission license agreement cleared",true);
             else
                 generateLog("Submission license agreement set",true);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setMajor (String major)
Parameters
major The new major.
Implements org.tdl.vireo.model.Submission.
Definition at line 1094 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.major,major)) {
             this.major = major;
             generateChangeLog("Major",major,false);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setOrcid (String orcidString)
Parameters
orcidString The ORCID identifier of the student who authored this submission.
Implements org.tdl.vireo.model.Submission.
Definition at line 428 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (orcidString != null && orcidString.trim().length() == 0)
             orcidString = null;
         if (!equals(this.orcid,orcidString)) {
             this.orcid = orcidString;
             generateChangeLog("Student's ORCID identifier", orcidString, false);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setProgram (String program)
Parameters
program The program associated with the submission
Implements org.tdl.vireo.model.Submission.
Definition at line 1063 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.program,program)) {
             this.program = program;
             generateChangeLog("Program",program,false);
             // set programId column
             SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class);
             Program programJPA = settingRepo.findProgramByName(program);
             if(programJPA != null) {
                 setProgramId(programJPA.getId());
             }
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setProgramId (Long id)
Parameters
id - the program id that will award this degree
Implements org.tdl.vireo.model.Submission.
Definition at line 1084 of file JpaSubmissionImpl.java.
{
         this.programId = programId;
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setPublishedMaterial (String material)
Set whether this submission contains any material that has been previously published. If the value is null, then no material has been previously published. If it is not null then some material may have been previously published and the contents of this field should indicate which material has been published.
Parameters
material English description identifying the material previously published.
Implements org.tdl.vireo.model.Submission.
Definition at line 548 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.publishedMaterial,material)) {
             this.publishedMaterial = material;
             if(material != null)
                 generateChangeLog("Published material",material,false);
             else
                 generateChangeLog("Published material",null,false);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setReviewerNotes (String notes)
Set new reviewer notes, may only be set by reviewers or above. Changes are logged in the action log, but will be marked as private.
Parameters
notes The new notes for this submission.
Implements org.tdl.vireo.model.Submission.
Definition at line 1301 of file JpaSubmissionImpl.java.
{
         assertReviewer();
         if (!equals(this.reviewerNotes,notes)) {
             this.reviewerNotes = notes;
             // Generate a private note
             String entry;
             if (notes == null)
                 entry = "Reviewer notes cleared";
             else
                 entry = String.format(
                     "Reviewer notes changed to '%s'",
                     notes);
             ActionLog log = logAction(entry);
             log.setPrivate(true);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setState (State state)
Parameters
state The new state of this submission
Implements org.tdl.vireo.model.Submission.
Definition at line 1171 of file JpaSubmissionImpl.java.
References org.tdl.vireo.state.State.getBeanName(), org.tdl.vireo.state.State.getDisplayName(), and org.tdl.vireo.state.State.isApproved().
{
         if (state == null)
             throw new IllegalArgumentException("State is required");
         assertReviewer();
         if (!equals(this.stateName,state.getBeanName())) {
             this.stateName = state.getBeanName();
             generateChangeLog("Submission status",state.getDisplayName(),true);
             // RUN Workflow Email Rule
             EmailRuleService.runEmailRules(this);
             // Check if this state is approved
             if (this.approvalDate == null && state.isApproved())
                 this.setApprovalDate(new Date());
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setStudentBirthYear (Integer year)
Parameters
year The new birth year for the student.
Implements org.tdl.vireo.model.Submission.
Definition at line 408 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.studentBirthYear,year)) {
             this.studentBirthYear = year;
             if (year == null)
                 generateChangeLog("Student birth year", null,false);
             else
                 generateChangeLog("Student birth year", String.valueOf(year),false);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setStudentFirstName (String firstName)
Parameters
firstName The new first name of the student.
Implements org.tdl.vireo.model.Submission.
Definition at line 348 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (firstName != null && firstName.trim().length() == 0)
             firstName = null;
         if (!equals(this.studentFirstName,firstName)) {
             this.studentFirstName = firstName;
             generateChangeLog("Student first name", firstName, false);
             updatePrimaryDocumentName();
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setStudentLastName (String lastName)
Parameters
lastName The new last name of the student.
Implements org.tdl.vireo.model.Submission.
Definition at line 369 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (lastName != null && lastName.trim().length() == 0)
             lastName = null;
         if (!equals(this.studentLastName,lastName)) {
             this.studentLastName = lastName;
             generateChangeLog("Student last name", lastName, false);
             updatePrimaryDocumentName();
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setStudentMiddleName (String middleName)
Parameters
middleName The new middle name of the student.
Implements org.tdl.vireo.model.Submission.
Definition at line 389 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (middleName != null && middleName.trim().length() == 0)
             middleName = null;
         if (!equals(this.studentMiddleName,middleName)) {
             this.studentMiddleName = middleName;
             generateChangeLog("Student middle name", middleName, false);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setSubmissionDate (Date date)
Parameters
data The new date the submission was submitted for review.
Implements org.tdl.vireo.model.Submission.
Definition at line 887 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.submissionDate,date)) {
             this.submissionDate = date;
             if (date == null) {
                 generateLog("Submission date cleared",true);
             } else {
                 DateFormat format = new SimpleDateFormat("MM/dd/yyyy");
                 String formattedDate = format.format(date);
                 generateLog("Submission date set to "+formattedDate,true);
             }
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.setUMIRelease (Boolean umiRelease)
Parameters
umiRelease The new UMI release status.
Implements org.tdl.vireo.model.Submission.
Definition at line 1213 of file JpaSubmissionImpl.java.
{
         assertReviewerOrOwner(submitter);
         if (!equals(this.UMIRelease,umiRelease)) {
             this.UMIRelease = umiRelease;
             if (umiRelease == null)
                 generateLog("UMI Release cleared",false);
             else if (umiRelease == true)
                 generateChangeLog("UMI Release","Yes",false);
             else
                 generateChangeLog("UMI Release","No",false);
         }
     }
void org.tdl.vireo.model.jpa.JpaSubmissionImpl.updatePrimaryDocumentName () protected
This is called when information that could potentially effect the name of the primary document has been modified. This method is called to see if the attachment should be updated.
Definition at line 1426 of file JpaSubmissionImpl.java.
{
         Attachment primary = this.getPrimaryDocument();
         if (primary != null) {
             ((JpaAttachmentImpl) primary).renamePrimaryDocument();
             primary.save();
         }
     }
Member Data Documentation
List<ActionLog> org.tdl.vireo.model.jpa.JpaSubmissionImpl.actionLogs
Definition at line 188 of file JpaSubmissionImpl.java.
Date org.tdl.vireo.model.jpa.JpaSubmissionImpl.approvalDate
Definition at line 131 of file JpaSubmissionImpl.java.
Person org.tdl.vireo.model.jpa.JpaSubmissionImpl.assignee
Definition at line 167 of file JpaSubmissionImpl.java.
List<Attachment> org.tdl.vireo.model.jpa.JpaSubmissionImpl.attachments
Definition at line 112 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.college
Definition at line 147 of file JpaSubmissionImpl.java.
Long org.tdl.vireo.model.jpa.JpaSubmissionImpl.collegeId
Definition at line 149 of file JpaSubmissionImpl.java.
Date org.tdl.vireo.model.jpa.JpaSubmissionImpl.committeeApprovalDate
Definition at line 124 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.committeeContactEmail
Definition at line 118 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.committeeEmailHash
Definition at line 121 of file JpaSubmissionImpl.java.
Date org.tdl.vireo.model.jpa.JpaSubmissionImpl.committeeEmbargoApprovalDate
Definition at line 126 of file JpaSubmissionImpl.java.
List<CommitteeMember> org.tdl.vireo.model.jpa.JpaSubmissionImpl.committeeMembers
Definition at line 116 of file JpaSubmissionImpl.java.
List<CustomActionValue> org.tdl.vireo.model.jpa.JpaSubmissionImpl.customActions
Definition at line 171 of file JpaSubmissionImpl.java.
Date org.tdl.vireo.model.jpa.JpaSubmissionImpl.defenseDate
Definition at line 135 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.degree
Definition at line 138 of file JpaSubmissionImpl.java.
DegreeLevel org.tdl.vireo.model.jpa.JpaSubmissionImpl.degreeLevel
Definition at line 139 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.department
Definition at line 142 of file JpaSubmissionImpl.java.
Long org.tdl.vireo.model.jpa.JpaSubmissionImpl.departmentId
Definition at line 144 of file JpaSubmissionImpl.java.
Date org.tdl.vireo.model.jpa.JpaSubmissionImpl.depositDate
Definition at line 176 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.depositId
Definition at line 174 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.documentAbstract
Definition at line 90 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.documentKeywords
Definition at line 92 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.documentLanguage
Definition at line 99 of file JpaSubmissionImpl.java.
List<String> org.tdl.vireo.model.jpa.JpaSubmissionImpl.documentSubjects
Definition at line 96 of file JpaSubmissionImpl.java.
boolean org.tdl.vireo.model.jpa.JpaSubmissionImpl.documentSubjectsChanged = false protected
Definition at line 196 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.documentTitle
Definition at line 88 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.documentType
Definition at line 159 of file JpaSubmissionImpl.java.
List<Long> org.tdl.vireo.model.jpa.JpaSubmissionImpl.embargoTypeIds
Definition at line 109 of file JpaSubmissionImpl.java.
Integer org.tdl.vireo.model.jpa.JpaSubmissionImpl.graduationMonth
Definition at line 162 of file JpaSubmissionImpl.java.
Integer org.tdl.vireo.model.jpa.JpaSubmissionImpl.graduationYear
Definition at line 161 of file JpaSubmissionImpl.java.
Date org.tdl.vireo.model.jpa.JpaSubmissionImpl.lastActionLogDate
Definition at line 184 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.lastActionLogEntry
Definition at line 182 of file JpaSubmissionImpl.java.
Date org.tdl.vireo.model.jpa.JpaSubmissionImpl.licenseAgreementDate
Definition at line 133 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.major
Definition at line 157 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.orcid
Definition at line 85 of file JpaSubmissionImpl.java.
List<ActionLog> org.tdl.vireo.model.jpa.JpaSubmissionImpl.pendingLogs = new ArrayList<ActionLog>() protected
Definition at line 192 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.program
Definition at line 152 of file JpaSubmissionImpl.java.
Long org.tdl.vireo.model.jpa.JpaSubmissionImpl.programId
Definition at line 154 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.publishedMaterial
Definition at line 102 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.reviewerNotes
Definition at line 179 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.stateName
Definition at line 164 of file JpaSubmissionImpl.java.
Integer org.tdl.vireo.model.jpa.JpaSubmissionImpl.studentBirthYear
Definition at line 81 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.studentFirstName
Definition at line 76 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.studentLastName
Definition at line 78 of file JpaSubmissionImpl.java.
String org.tdl.vireo.model.jpa.JpaSubmissionImpl.studentMiddleName
Definition at line 80 of file JpaSubmissionImpl.java.
Date org.tdl.vireo.model.jpa.JpaSubmissionImpl.submissionDate
Definition at line 129 of file JpaSubmissionImpl.java.
Person org.tdl.vireo.model.jpa.JpaSubmissionImpl.submitter
Definition at line 73 of file JpaSubmissionImpl.java.
Boolean org.tdl.vireo.model.jpa.JpaSubmissionImpl.UMIRelease
Definition at line 168 of file JpaSubmissionImpl.java.
The documentation for this class was generated from the following file:
app/org/tdl/vireo/model/jpa/JpaSubmissionImpl.java