Vireo: org.tdl.vireo.export.impl.ChunkStreamImpl Class Reference
org.tdl.vireo.export.impl.ChunkStreamImpl Class Reference
Classes
class BufferFullException
Public Member Functions
ChunkStreamImpl (String contentType, String contentDisposition, int bufferSize)
String getContentType ()
String getContentDisposition ()
synchronized void close ()
boolean hasNextChunk ()
synchronized Promise< byte[]> nextChunk ()
void write (int b) throws IOException
void write (byte[] b) throws IOException
void write (byte[] b, int off, int len) throws IOException
void flush ()
Public Attributes
final String contentType
final String contentDisposition
Protected Member Functions
void writeOrWait (byte[] event) throws IOException
Protected Attributes
final int bufferSize
final ConcurrentLinkedQueue
< byte[]> chunks = new ConcurrentLinkedQueue<byte[]>()
Promise< byte[]> nextChunk
boolean open
Private Member Functions
synchronized void synchronizedWrite (byte[] event) throws BufferFullException, IOException
Detailed Description
Okay, this is awesome!
This class is an output stream, that can produce play style promises for chunked content. This means that anytime we want to do file IO we can use this class to stream that file directly to the browser. Play is really powerful.
Author
Scott Phillips
Definition at line 21 of file ChunkStreamImpl.java.
Constructor & Destructor Documentation
org.tdl.vireo.export.impl.ChunkStreamImpl.ChunkStreamImpl (String contentType, String contentDisposition, int bufferSize)
Construct a new chunk.
Parameters
contentType The content type, typically "application/zip".
contentDisposition The content disposition, typically "attachment; filename=[name]"
bufferSize The maximum size of chunks to keep in the queue before throtteling the producer.
Definition at line 51 of file ChunkStreamImpl.java.
References org.tdl.vireo.export.impl.ChunkStreamImpl.bufferSize, org.tdl.vireo.export.impl.ChunkStreamImpl.contentDisposition, and org.tdl.vireo.export.impl.ChunkStreamImpl.contentType.
{
         this.contentType = contentType;
         this.contentDisposition = contentDisposition;
         this.bufferSize = bufferSize;
         this.open = true;
     }
Member Function Documentation
synchronized void org.tdl.vireo.export.impl.ChunkStreamImpl.close ()
Definition at line 69 of file ChunkStreamImpl.java.
References org.tdl.vireo.export.impl.ChunkStreamImpl.nextChunk().
{
         this.open = false;
         if (nextChunk != null) {
             nextChunk.invoke(new byte[0]);
         }
     }
void org.tdl.vireo.export.impl.ChunkStreamImpl.flush ()
Definition at line 146 of file ChunkStreamImpl.java.
References org.tdl.vireo.export.impl.ChunkStreamImpl.chunks.
{
         while(!chunks.isEmpty()) {
             Thread.yield();
         }
     }
String org.tdl.vireo.export.impl.ChunkStreamImpl.getContentDisposition ()
The "Content-Disposition" header is a way to tell the browser that the data being sent should be saved to disk and not attempt to render it in the browser. The format of this field will be in "[type]; filename=[name]". The possible types are attachment, or inline. Attachments are saved to disk, while inline content is attempted to be rendered in the browser. If the attachment type is used, then an optional parameter may be supplied to suggest the filename for the data.
Returns
The content disposition HTTP header.
Implements org.tdl.vireo.export.ChunkStream.
Definition at line 64 of file ChunkStreamImpl.java.
References org.tdl.vireo.export.impl.ChunkStreamImpl.contentDisposition.
{
         return contentDisposition;
     }
String org.tdl.vireo.export.impl.ChunkStreamImpl.getContentType ()
The "Content-Type" header both helps the webserver and the browser understand the material being streamed. Typically the mimetype of "application/zip" will be used.
Returns
The content type HTTP header.
Implements org.tdl.vireo.export.ChunkStream.
Definition at line 59 of file ChunkStreamImpl.java.
References org.tdl.vireo.export.impl.ChunkStreamImpl.contentType.
{
         return contentType;
     }
boolean org.tdl.vireo.export.impl.ChunkStreamImpl.hasNextChunk ()
Returns
True if the if the stream is open, or there are events waiting to be consumed.
Implements org.tdl.vireo.export.ChunkStream.
Definition at line 77 of file ChunkStreamImpl.java.
References org.tdl.vireo.export.impl.ChunkStreamImpl.chunks, and org.tdl.vireo.export.impl.ChunkStreamImpl.open.
{
         if (chunks.isEmpty())
             return open;
         else
             return !chunks.isEmpty();
     }
synchronized Promise<byte[]> org.tdl.vireo.export.impl.ChunkStreamImpl.nextChunk ()
One of two cases, here is what they mean:
1) The queue is empty, but we're sure to get some more chunks pretty soon. So we return an unfulfilled promise for the next chunk. We store a pointer to this promise, so that when we do recieve the next chunk we can add the data to the promise. The consumer will see this and then grab the chunk's data.
2) The queue has a back log of chunks. We just grab the next chunk and hand it over to the consumer.
Implements org.tdl.vireo.export.ChunkStream.
Definition at line 98 of file ChunkStreamImpl.java.
References org.tdl.vireo.export.impl.ChunkStreamImpl.chunks.
Referenced by org.tdl.vireo.export.impl.ChunkStreamImpl.close(), and org.tdl.vireo.export.impl.ChunkStreamImpl.synchronizedWrite().
{
         if (nextChunk != null)
             throw new IllegalStateException("ChunkStream is consuming chunks without waiting for the previous chunk to be consumed.");
         if (chunks.isEmpty()) {
             // The queue of chunks is empty right now, so return a promise that
             // when we get the next one we'll send the chunk.
             nextChunk = new Promise<byte[]>();
             return nextChunk;
         } else {
             // There is a backlog in the queue, so send the chunk.
             Promise<byte[]> nextChunk = new Promise<byte[]>();
             nextChunk.invoke(chunks.remove());
             return nextChunk;
         }
     }
synchronized void org.tdl.vireo.export.impl.ChunkStreamImpl.synchronizedWrite (byte[] event) throws BufferFullException, IOException private
Internal method for writing chunks into the stream. No one but writeOrWait() should call this method. If the buffer is full, then an exception will be thrown for writeOrWait to catch and retry.
Assuming the buffer is fine, the new chunk is added to the queue. Then we check to see if there are any outstanding unfulfilled promise out there. If so, we send the next chunk to that promise so the consumer can now to start reading the stream again.
Parameters
event The new chunk to be written.
Exceptions
BufferFullException When the buffer is full.
Definition at line 198 of file ChunkStreamImpl.java.
References org.tdl.vireo.export.impl.ChunkStreamImpl.bufferSize, org.tdl.vireo.export.impl.ChunkStreamImpl.chunks, org.tdl.vireo.export.impl.ChunkStreamImpl.nextChunk(), and org.tdl.vireo.export.impl.ChunkStreamImpl.open.
Referenced by org.tdl.vireo.export.impl.ChunkStreamImpl.writeOrWait().
{
         if (!open)
             throw new IOException("Unable to publish chunks into a closed ChunkStream.");
         if (chunks.size() > bufferSize) {
             // The buffer so throw an exception that can be caught by the
             // nonsynchronized method.
             throw new BufferFullException();
         }
         chunks.offer(event);
         if (nextChunk != null) {
             // A promise already exists, so now that something has been
             // published into the queue let the consumer know about the new
             // chunk.
             nextChunk.invoke(chunks.remove());
             nextChunk = null;
         }
     }
void org.tdl.vireo.export.impl.ChunkStreamImpl.write (int b) throws IOException
Definition at line 119 of file ChunkStreamImpl.java.
References org.tdl.vireo.export.impl.ChunkStreamImpl.writeOrWait().
{
         byte[] chunk = new byte[1];
         chunk[0] = (byte) b;
         writeOrWait(chunk);
     }
void org.tdl.vireo.export.impl.ChunkStreamImpl.write (byte[] b) throws IOException
Definition at line 128 of file ChunkStreamImpl.java.
References org.tdl.vireo.export.impl.ChunkStreamImpl.writeOrWait().
{
         byte[] chunk = new byte[b.length];
         System.arraycopy(b, 0, chunk, 0, b.length);
         writeOrWait(chunk);
     }
void org.tdl.vireo.export.impl.ChunkStreamImpl.write (byte[] b, int off, int len) throws IOException
Definition at line 137 of file ChunkStreamImpl.java.
References org.tdl.vireo.export.impl.ChunkStreamImpl.writeOrWait().
{
         byte[] chunk = new byte[len];
         System.arraycopy(b, off, chunk, 0, len);
         writeOrWait(chunk);
     }
void org.tdl.vireo.export.impl.ChunkStreamImpl.writeOrWait (byte[] event) throws IOException protected
Our first internal method to write chunks into the stream. This method will attempt to write the chunk, but if it fails because the buffer is full then it will progressively back of publishing. This is to give the consumer time to catch up. However if after about one minute the consumer hasn't caught up then we assume there's a big problem and blow up with an IO Exception.
Note, this method is not synchronized so that it does not block. The lower level write method synchronizedWrite is.
Parameters
event The chunk to be written into the stream.
Definition at line 166 of file ChunkStreamImpl.java.
References org.tdl.vireo.export.impl.ChunkStreamImpl.synchronizedWrite().
Referenced by org.tdl.vireo.export.impl.ChunkStreamImpl.write().
{
         for (int attempts = 0; attempts < 350; attempts++) {
             try {
                 // First try to publish with out any overhead
                 synchronizedWrite(event);
                 return;
             } catch (BufferFullException bfe) {
                 try {
                     Thread.sleep(attempts);
                 } catch (InterruptedException ie) {
                     // wake up and try to publish again.
                 }
             }
         }
         throw new IOException("ChunkStream buffer is full, the client probably disconnected.");
     }
Member Data Documentation
final int org.tdl.vireo.export.impl.ChunkStreamImpl.bufferSize protected
Definition at line 28 of file ChunkStreamImpl.java.
Referenced by org.tdl.vireo.export.impl.ChunkStreamImpl.ChunkStreamImpl(), and org.tdl.vireo.export.impl.ChunkStreamImpl.synchronizedWrite().
final ConcurrentLinkedQueue<byte[]> org.tdl.vireo.export.impl.ChunkStreamImpl.chunks = new ConcurrentLinkedQueue<byte[]>() protected
Definition at line 31 of file ChunkStreamImpl.java.
Referenced by org.tdl.vireo.export.impl.ChunkStreamImpl.flush(), org.tdl.vireo.export.impl.ChunkStreamImpl.hasNextChunk(), org.tdl.vireo.export.impl.ChunkStreamImpl.nextChunk(), and org.tdl.vireo.export.impl.ChunkStreamImpl.synchronizedWrite().
final String org.tdl.vireo.export.impl.ChunkStreamImpl.contentDisposition
Definition at line 25 of file ChunkStreamImpl.java.
Referenced by org.tdl.vireo.export.impl.ChunkStreamImpl.ChunkStreamImpl(), and org.tdl.vireo.export.impl.ChunkStreamImpl.getContentDisposition().
final String org.tdl.vireo.export.impl.ChunkStreamImpl.contentType
Definition at line 24 of file ChunkStreamImpl.java.
Referenced by org.tdl.vireo.export.impl.ChunkStreamImpl.ChunkStreamImpl(), and org.tdl.vireo.export.impl.ChunkStreamImpl.getContentType().
Promise<byte[]> org.tdl.vireo.export.impl.ChunkStreamImpl.nextChunk protected
Definition at line 34 of file ChunkStreamImpl.java.
boolean org.tdl.vireo.export.impl.ChunkStreamImpl.open protected
Definition at line 37 of file ChunkStreamImpl.java.
Referenced by org.tdl.vireo.export.impl.ChunkStreamImpl.hasNextChunk(), and org.tdl.vireo.export.impl.ChunkStreamImpl.synchronizedWrite().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/export/impl/ChunkStreamImpl.java