Vireo: org.tdl.vireo.services.EmailRuleService Class Reference
org.tdl.vireo.services.EmailRuleService Class Reference
Classes
class initializeSystemEmailWorkflowRules
Public Member Functions
void setSettingsRepository (SettingsRepository settingRepo)
void setSecurityContext (SecurityContext context)
void generateAllSystemEmailRules ()
Static Public Member Functions
static void runEmailRules (Submission submission)
Public Attributes
SecurityContext context
SettingsRepository settingRepo
Static Private Member Functions
static boolean ruleIsValid (EmailWorkflowRule ewflRule, Submission submission)
static void sendEmail (EmailWorkflowRule EmailWorkflowRule, Submission submission)
static VireoEmail createEmail (EmailService emailService, EmailWorkflowRule EmailWorkflowRule, Submission submission)
Detailed Description
Author
Gad Krumholz
Definition at line 32 of file EmailRuleService.java.
Member Function Documentation
static VireoEmail org.tdl.vireo.services.EmailRuleService.createEmail (EmailService emailService, EmailWorkflowRule EmailWorkflowRule, Submission submission) static private
This will generate a VireoEmail from the right recipients from the rule
Parameters
emailService
the emailService from Spring
EmailWorkflowRule
the workflow email rule
submission
the submission
Returns
- a new VireoEmail with the correct email template and recipients
Definition at line 177 of file EmailRuleService.java.
Referenced by org.tdl.vireo.services.EmailRuleService.sendEmail().
{
         // get all the recipients from the rule
         List<String> recipients = EmailWorkflowRule.getRecipients(submission);
         // create the email
         VireoEmail vireoEmail = emailService.createEmail();
         // add all recipients to the TO of this email
         for (String email : recipients) {
             vireoEmail.addTo(email);
         }
         // set the correct email template for this rule
         vireoEmail.setTemplate(EmailWorkflowRule.getEmailTemplate());
         // add the parameters into the email body
         vireoEmail.addParameters(submission);
         return vireoEmail;
     }
void org.tdl.vireo.services.EmailRuleService.generateAllSystemEmailRules ()
Definition at line 217 of file EmailRuleService.java.
References org.tdl.vireo.email.RecipientType.Advisor, org.tdl.vireo.model.ConditionType.Always, org.tdl.vireo.model.SettingsRepository.createEmailWorkflowRule(), org.tdl.vireo.model.SettingsRepository.createEmailWorkflowRuleCondition(), org.tdl.vireo.model.SettingsRepository.findEmailTemplateByName(), org.tdl.vireo.model.jpa.JpaEmailWorkflowRuleImpl.getCondition(), org.tdl.vireo.services.EmailRuleService.settingRepo, and org.tdl.vireo.email.RecipientType.Student.
{
         // turn off authorization if we're saving
         context.turnOffAuthorization();
         // get the Submitted state
         State submitted = Spring.getBeanOfType(StateManager.class).getState("Submitted");
         // get all of the current Submitted rules
         List<EmailWorkflowRule> submittedRules = settingRepo.findEmailWorkflowRulesByState(submitted);
         // our Always conditions
         JpaEmailWorkflowRuleConditionImpl conditionAdvisor = (JpaEmailWorkflowRuleConditionImpl) settingRepo.createEmailWorkflowRuleCondition(ConditionType.Always);
         JpaEmailWorkflowRuleConditionImpl conditionStudent = (JpaEmailWorkflowRuleConditionImpl) settingRepo.createEmailWorkflowRuleCondition(ConditionType.Always);
         // our email templates to use for the default system email rules
         JpaEmailTemplateImpl advisorEmailTemplate = (JpaEmailTemplateImpl) settingRepo.findEmailTemplateByName("SYSTEM Advisor Review Request");
         JpaEmailTemplateImpl studentEmailTemplate = (JpaEmailTemplateImpl) settingRepo.findEmailTemplateByName("SYSTEM Initial Submission");
         // always send to advisor on submission
         JpaEmailWorkflowRuleImpl advisorRule = (JpaEmailWorkflowRuleImpl) settingRepo.createEmailWorkflowRule(submitted);
         advisorRule.setCondition(conditionAdvisor); // always save a new copy of condition
         advisorRule.setEmailTemplate(advisorEmailTemplate);
         advisorRule.setRecipientType(RecipientType.Advisor);
         advisorRule.setIsSystem(true);
         // always send to student on submission
         JpaEmailWorkflowRuleImpl studentRule = (JpaEmailWorkflowRuleImpl) settingRepo.createEmailWorkflowRule(submitted);
         studentRule.setCondition(conditionStudent); // always save a new copy of condition
         studentRule.setEmailTemplate(studentEmailTemplate);
         studentRule.setRecipientType(RecipientType.Student);
         studentRule.setIsSystem(true);
         boolean foundAdvisor = false, foundStudent = false;
         for (EmailWorkflowRule rule : submittedRules) {
             // if this is a system-installed rule
             if(rule.isSystem()) {
                 // compare conditions for advisor rule
                 if (rule.getCondition().getConditionType() == advisorRule.getCondition().getConditionType()) {
                     // compare recipients for advisor rule
                     if (rule.getRecipientType() == advisorRule.getRecipientType()) {
                         foundAdvisor = true;
                     }
                 }
                 // compare conditions for student rule
                 if (rule.getCondition().getConditionType() == studentRule.getCondition().getConditionType()) {
                     // compare recipients for student rule
                     if (rule.getRecipientType() == studentRule.getRecipientType()) {
                         foundStudent = true;
                     }
                 }
             }
         }
         // if the rules weren't found, add them
         if (!foundAdvisor) {
             if(advisorRule.getCondition() != null) {
                 advisorRule.getCondition().save();
             }
             advisorRule.save();
         }
         if (!foundStudent) {
             if(studentRule.getCondition() != null) {
                 studentRule.getCondition().save();
             }
             studentRule.save();
         }
         // turn on authorization after we're done
         context.restoreAuthorization();
     }
static boolean org.tdl.vireo.services.EmailRuleService.ruleIsValid (EmailWorkflowRule ewflRule, Submission submission) static private
Checks the validity of a rule to make sure it should run or not
Parameters
EmailWorkflowRule
the workflow email rule to check
submission
the submission to check against
Returns
- returns true if rule is valid, false if condition is not set or recipients is emtpy
Definition at line 116 of file EmailRuleService.java.
References org.tdl.vireo.model.AbstractWorkflowRule.getCondition(), and org.tdl.vireo.model.EmailWorkflowRule.getRecipients().
Referenced by org.tdl.vireo.services.EmailRuleService.runEmailRules().
{
         boolean conditionValid = true, recipientsValid = true, ruleEnabled = true;
         // check condition != null
         if (ewflRule.getCondition() != null) {
             // check condition type and id != null
             if (ewflRule.getCondition().getConditionType() == null) {
                 conditionValid = false;
             }
             switch (ewflRule.getCondition().getConditionType()) {
             case College:
             case Department:
             case Program:
                 if (ewflRule.getCondition().getConditionId() == null) {
                     conditionValid = false;
                 }
                 break;
             case Always:
                 break;
             default:
                 throw new UnsupportedOperationException();
             }
         } else {
             conditionValid = false;
         }
         // check recipients
         if (ewflRule.getRecipients(submission).size() == 0) {
             recipientsValid = false;
         }
         // check to see if rule is disabled
         ruleEnabled = (!ewflRule.isDisabled()); // if rule isDisabled(true) return false(rule is not enabled)
         return (conditionValid && recipientsValid && ruleEnabled);
     }
static void org.tdl.vireo.services.EmailRuleService.runEmailRules (Submission submission) static
This static class will take a submission and go through all of the JPA email rules
to decide if an email needs to be sent (and to whom) depending on the rule's condition and recipients
Parameters
submission
the submission
Definition at line 42 of file EmailRuleService.java.
References org.tdl.vireo.model.College.getName(), org.tdl.vireo.model.Department.getName(), org.tdl.vireo.model.Program.getName(), org.tdl.vireo.model.Submission.getState(), org.tdl.vireo.services.EmailRuleService.ruleIsValid(), org.tdl.vireo.services.EmailRuleService.sendEmail(), and org.tdl.vireo.services.EmailRuleService.settingRepo.
{
         // Get all the rules
         SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class);
         List<EmailWorkflowRule> rules = settingRepo.findAllEmailWorkflowRules();
         // for every rule in JPA
         for (EmailWorkflowRule ewflRule : rules) {
             // verify the rule is valid/complete before running it
             if (ruleIsValid(ewflRule, submission)) {
                 // if the rule's state matches the transitioned state in the submission
                 if (ewflRule.getAssociatedState().getBeanName().equals(submission.getState().getBeanName())) {
                     // apply condition to send only when condition is met
                     switch (ewflRule.getCondition().getConditionType()) {
                     case Always:
                         // send the email
                         sendEmail(ewflRule, submission);
                         break;
                     case College:
                         // get the collegeId out of the rule
                         Long collegeId = ewflRule.getCondition().getConditionId();
                         // get the college out of JPA
                         College ruleCollege = settingRepo.findCollege(collegeId);
                         // compare the rule's college with the submission's college
                         if (ruleCollege != null && ruleCollege.getName().equals(submission.getCollege())) {
                             // send the email
                             sendEmail(ewflRule, submission);
                         } else {
                             Logger.error("This rule's college with id #%d doesn't exist! ", collegeId);
                         }
                         break;
                     case Department:
                         // get the departmentId out of the rule
                         Long departmentId = ewflRule.getCondition().getConditionId();
                         // get the department out of JPA
                         Department ruleDepartment = settingRepo.findDepartment(departmentId);
                         // compare the rule's department with the submission's department
                         if (ruleDepartment != null && ruleDepartment.getName().equals(submission.getDepartment())) {
                             // send the email
                             sendEmail(ewflRule, submission);
                         } else {
                             Logger.error("This rule's department with id #%d doesn't exist! ", departmentId);
                         }
                         break;
                     case Program:
                         // get the programId out of the rule
                         Long programId = ewflRule.getCondition().getConditionId();
                         // get the program out of JPA
                         Program ruleProgram = settingRepo.findProgram(programId);
                         // compare the rule's program with the submission's program
                         if (ruleProgram != null && ruleProgram.getName().equals(submission.getProgram())) {
                             // send the email
                             sendEmail(ewflRule, submission);
                         } else {
                             Logger.error("This rule's program with id #%d doesn't exist! ", programId);
                         }
                         break;
                     default:
                         // what are we doing here?!
                         throw new UnsupportedOperationException();
                     }
                 }
             }
         }
     }
static void org.tdl.vireo.services.EmailRuleService.sendEmail (EmailWorkflowRule EmailWorkflowRule, Submission submission) static private
This will generate and send the email to the right recipients from the rule
Parameters
EmailWorkflowRule
the workflow email rule
submission
the submission
Definition at line 157 of file EmailRuleService.java.
References org.tdl.vireo.services.EmailRuleService.createEmail().
Referenced by org.tdl.vireo.services.EmailRuleService.runEmailRules().
{
         // get the EmailService from Spring
         EmailService emailService = Spring.getBeanOfType(EmailService.class);
         // generate the email with the right template and recipients
         VireoEmail email = createEmail(emailService, EmailWorkflowRule, submission);
         // send the email NOW (not as a Job)
         emailService.sendEmail(email, true);
     }
void org.tdl.vireo.services.EmailRuleService.setSecurityContext (SecurityContext context)
Parameters
context The security context.
Definition at line 213 of file EmailRuleService.java.
References org.tdl.vireo.services.EmailRuleService.context.
{
         this.context = context;
     }
void org.tdl.vireo.services.EmailRuleService.setSettingsRepository (SettingsRepository settingRepo)
Parameters
settingRepo The settings repository used for generating email templates.
Definition at line 205 of file EmailRuleService.java.
References org.tdl.vireo.services.EmailRuleService.settingRepo.
{
         this.settingRepo = settingRepo;
     }
Member Data Documentation
SecurityContext org.tdl.vireo.services.EmailRuleService.context
Definition at line 198 of file EmailRuleService.java.
Referenced by org.tdl.vireo.services.EmailRuleService.setSecurityContext().
SettingsRepository org.tdl.vireo.services.EmailRuleService.settingRepo
Definition at line 199 of file EmailRuleService.java.
Referenced by org.tdl.vireo.services.EmailRuleService.generateAllSystemEmailRules(), org.tdl.vireo.services.EmailRuleService.runEmailRules(), and org.tdl.vireo.services.EmailRuleService.setSettingsRepository().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/services/EmailRuleService.java