Vireo: org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob Class Reference
org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob Class Reference
Public Member Functions
ExportJob (Packager packager, SearchFilter filter, OutputStream out)
void doJob () throws IOException
Public Attributes
final Packager packager
final SearchFilter filter
final OutputStream out
final Long personId
final JobMetadata meta
Protected Member Functions
void zipDirectory (String baseName, File directory, ZipOutputStream zos) throws IOException
void zipFile (String baseName, File file, ZipOutputStream zos) throws IOException
Detailed Description
Background job to export
Definition at line 140 of file ExportServiceImpl.java.
Constructor & Destructor Documentation
org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.ExportJob (Packager packager, SearchFilter filter, OutputStream out)
Construct a new export job.
Parameters
packager The packager which will generate content.
filter The filter to select submissions.
out The output stream where to send the export too.
Definition at line 161 of file ExportServiceImpl.java.
References org.tdl.vireo.export.impl.ExportServiceImpl.context, org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.filter, org.tdl.vireo.security.SecurityContext.getPerson(), org.tdl.vireo.security.SecurityContext.isAuthorizationActive(), org.tdl.vireo.security.SecurityContext.isReviewer(), org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.meta, org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.out, org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.packager, and org.tdl.vireo.job.JobStatus.READY.
{
             this.packager = packager;
             this.filter = filter;
             this.out = out;
             if (context.getPerson() != null) {
                 if (!context.isReviewer())
                     throw new SecurityException("Not authorized to preform export operation.");
                 this.personId = context.getPerson().getId();
             } else {
                 if (!context.isAuthorizationActive())
                     throw new SecurityException("Not authorized to preform export operation.");
                 this.personId = null;
             }
             // Register the job's metadata
             meta = jobManager.register("Download " + packager.getDisplayName(),context.getPerson());
             meta.setJob(this);
             meta.setStatus(JobStatus.READY);
         }
Member Function Documentation
void org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.doJob () throws IOException
Run the back ground job.
Iterate through the submissions and stream each one into the a zip archived. The archive will be buffered, and sent directly to the ChunkStream to be transmitted to the browser. This means we never have the complete archive on the server at any one time.
Definition at line 194 of file ExportServiceImpl.java.
References org.tdl.vireo.search.SearchDirection.ASCENDING, org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.filter, org.tdl.vireo.job.JobMetadata.getProgress(), org.tdl.vireo.search.SearchOrder.ID, org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.meta, org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.out, org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.personId, org.tdl.vireo.job.JobStatus.RUNNING, org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.zipDirectory(), and org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.zipFile().
{
             try {
                 meta.setStatus(JobStatus.RUNNING);
                 if (personId != null) {
                     Person person = personRepo.findPerson(personId);
                     if (person == null)
                         throw new IllegalStateException("Unable to complete deposit job because person no longer exists.");
                     // Log the person in for this job.
                     context.login(person);
                 } else {
                     // Assume we're running as a background admin process.
                     context.turnOffAuthorization();
                 }
                 // Figure out how many submissions total we are exporting
                 long[] subIds = searcher.submissionSearch(filter, SearchOrder.ID, SearchDirection.ASCENDING);
                 meta.getProgress().total = subIds.length;
                 meta.getProgress().completed = 0;
                 // Start processing bitstreams
                 BufferedOutputStream bos = new BufferedOutputStream(out);
                 ZipOutputStream zos = new ZipOutputStream(bos);
                 String archiveFolder = packager.getBeanName()+File.separator;
                 try {
                     // Iterate over all the items, adding each one to the export.
                     for (long subId : subIds) {
                         Submission sub = subRepo.findSubmission(subId);
                         ExportPackage pkg = packager.generatePackage(sub);
                         try {
                             String entryName = null;
                             if(pkg.getEntryName()!=null){
                                 entryName = pkg.getEntryName();
                             } else {
                                 entryName = archiveFolder + "submission_" + sub.getId();
                             }
                             if (pkg.getFile().isDirectory()) {
                                 zipDirectory(entryName + File.separator, pkg.getFile(), zos);
                             } else {
                                 zipFile(entryName, pkg.getFile(), zos);
                             }
                         } finally {
                             // Ensure the package isdeleted.
                             pkg.delete();
                         }
                         // Immediately save the transaction
                         JPA.em().getTransaction().commit();
                         JPA.em().clear();
                         JPA.em().getTransaction().begin();
                         // Don't let memory get out of control
                         System.gc();
                         meta.getProgress().completed++;
                     }
                 } finally {
                     // Ensure the ziparchive is closed.
                     try {
                         zos.close();
                     } catch (Exception e) {
                         Logger.error(e,"Unable to close export zip archive, Ignoring.");
                     }
                 }
             } catch (RuntimeException re) {
                 Logger.fatal(re,"Unexepcted exception while exporting items. Aborted.");
                 meta.setMessage(re.toString());
                 meta.setStatus(JobStatus.FAILED);
                 errorLog.logError(re, meta);
                 throw re;
             } catch (IOException ioe) {
                 Logger.error(ioe,"Unexpected expection while exporting items. Aborted.");
                 meta.setMessage(ioe.toString());
                 meta.setStatus(JobStatus.FAILED);
                 errorLog.logError(ioe, meta);
                 throw ioe;
             } finally {
                 // Clean up the security context
                 if (personId != null) {
                     context.logout();
                 } else {
                     context.restoreAuthorization();
                 }
             }
             meta.setStatus(JobStatus.SUCCESS);
             meta.setJob(null);
         }
void org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.zipDirectory (String baseName, File directory, ZipOutputStream zos) throws IOException protected
Zip a directory, and any sub directories that it may contain.
Parameters
baseName The base name for this directory.
directory The directory to include in the archive.
zos The archive's output stream.
Exceptions
IOException
Definition at line 304 of file ExportServiceImpl.java.
Referenced by org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.doJob().
         {
             // Add all the files
             File[] files = directory.listFiles();
             for (File file : files) {
                 if (file.isDirectory()) {
                     zipDirectory(baseName + file.getName() + File.separator, file, zos);
                 } else {
                     InputStream is = new BufferedInputStream(new FileInputStream(file));
                     zos.putNextEntry(new ZipEntry(baseName + file.getName()));
                     byte[] buf = new byte[1024];
                     int len;
                     while ((len = is.read(buf)) > 0) {
                         zos.write(buf, 0, len);
                     }
                     is.close();
                     zos.closeEntry();
                 }
             }
         }
void org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.zipFile (String baseName, File file, ZipOutputStream zos) throws IOException protected
Zip a single file and include it in the archive. This method will use the baseName for the entry name, with the extension of the actual file. This is intended to be used at the top level of the export where we want everything to be "submission_#", but for single file exports it's nice to have the correct extension for the file type.
Parameters
baseName The base name for this entry.
file The file to include in the archive.
zos The output stream for the zip archive.
Definition at line 344 of file ExportServiceImpl.java.
Referenced by org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.doJob().
{
             // Add all the files
             InputStream is = new BufferedInputStream(new FileInputStream(file));
             String extension = FilenameUtils.getExtension(file.getName());
             zos.putNextEntry(new ZipEntry(baseName+"."+extension));
             byte[] buf = new byte[1024];
             int len;
             while ((len = is.read(buf)) > 0) {
                 zos.write(buf, 0, len);
             }
             is.close();
             zos.closeEntry();
         }
Member Data Documentation
final SearchFilter org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.filter
Definition at line 144 of file ExportServiceImpl.java.
Referenced by org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.doJob(), and org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.ExportJob().
final JobMetadata org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.meta
Definition at line 149 of file ExportServiceImpl.java.
Referenced by org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.doJob(), and org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.ExportJob().
final OutputStream org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.out
Definition at line 145 of file ExportServiceImpl.java.
Referenced by org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.doJob(), and org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.ExportJob().
final Packager org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.packager
Definition at line 143 of file ExportServiceImpl.java.
Referenced by org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.ExportJob().
final Long org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.personId
Definition at line 146 of file ExportServiceImpl.java.
Referenced by org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.doJob().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/export/impl/ExportServiceImpl.java