Vireo: org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl Class Reference
org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl Class Reference
Public Member Functions
Degree createDegree (String name, DegreeLevel level)
Degree findDegree (Long id)
Degree findDegreeByName (String name)
List< Degree > findAllDegrees ()
Major createMajor (String name)
Major findMajor (Long id)
List< Major > findAllMajors ()
College createCollege (String name)
College createCollege (String name, HashMap< Integer, String > emails)
College findCollege (Long id)
College findCollegeByName (String name)
List< College > findAllColleges ()
Program createProgram (String name)
Program createProgram (String name, HashMap< Integer, String > emails)
Program findProgram (Long id)
Program findProgramByName (String name)
List< Program > findAllPrograms ()
Department createDepartment (String name)
Department createDepartment (String name, HashMap< Integer, String > emails)
Department findDepartment (Long id)
Department findDepartmentByName (String name)
List< Department > findAllDepartments ()
AdministrativeGroup createAdministrativeGroup (String name)
AdministrativeGroup createAdministrativeGroup (String name, HashMap< Integer, String > emails)
AdministrativeGroup findAdministrativeGroup (Long id)
AdministrativeGroup findAdministrativeGroupByName (String name)
List< AdministrativeGroup > findAllAdministrativeGroups ()
DocumentType createDocumentType (String name, DegreeLevel level)
DocumentType findDocumentType (Long id)
List< DocumentType > findAllDocumentTypes (DegreeLevel level)
List< DocumentType > findAllDocumentTypes ()
EmbargoType createEmbargoType (String name, String description, Integer duration, boolean active)
EmbargoType createEmbargoType (String name, String description, Integer duration, boolean active, EmbargoGuarantor guarantor)
EmbargoType findEmbargoType (Long id)
List< EmbargoType > findAllEmbargoTypes ()
EmbargoType findSystemEmbargoTypeByNameAndGuarantor (String name, EmbargoGuarantor guarantor)
EmbargoType findNonSystemEmbargoTypeByNameAndGuarantor (String name, EmbargoGuarantor guarantor)
List< EmbargoType > findAllActiveEmbargoTypes ()
GraduationMonth createGraduationMonth (int month)
GraduationMonth findGraduationMonth (Long id)
List< GraduationMonth > findAllGraduationMonths ()
CommitteeMemberRoleType createCommitteeMemberRoleType (String name, DegreeLevel level)
CommitteeMemberRoleType findCommitteeMemberRoleType (Long id)
List< CommitteeMemberRoleType > findAllCommitteeMemberRoleTypes (DegreeLevel level)
List< CommitteeMemberRoleType > findAllCommitteeMemberRoleTypes ()
AbstractWorkflowRuleCondition createEmailWorkflowRuleCondition (ConditionType condition)
AbstractWorkflowRuleCondition findEmailWorkflowRuleCondition (Long id)
List
< AbstractWorkflowRuleCondition > findAllEmailWorkflowRuleConditions ()
EmailWorkflowRule createEmailWorkflowRule (State associatedState)
EmailWorkflowRule findEmailWorkflowRule (Long id)
List< EmailWorkflowRule > findEmailWorkflowRulesByState (State state)
List< EmailWorkflowRule > findAllEmailWorkflowRules ()
EmailTemplate createEmailTemplate (String name, String subject, String message)
EmailTemplate findEmailTemplate (Long id)
EmailTemplate findEmailTemplateByName (String name)
EmailTemplate findNonSystemEmailTemplateByName (String name)
EmailTemplate findSystemEmailTemplateByName (String name)
List< EmailTemplate > findAllEmailTemplates ()
CustomActionDefinition createCustomActionDefinition (String label, Boolean isStudentVisible)
CustomActionDefinition findCustomActionDefinition (Long id)
List< CustomActionDefinition > findAllCustomActionDefinition ()
Language createLanguage (String name)
Language findLanguage (Long id)
Language findLanguageByName (String name)
List< Language > findAllLanguages ()
Configuration createConfiguration (String name, String value)
Configuration findConfiguration (Long id)
Configuration findConfigurationByName (String name)
String getConfigValue (String name, String defaultValue)
String getConfigValue (String name)
boolean getConfigBoolean (String name)
List< Configuration > findAllConfigurations ()
void setConfigurationDefaults (Map< String, String > defaults)
DepositLocation createDepositLocation (String name)
DepositLocation findDepositLocation (Long id)
DepositLocation findDepositLocationByName (String name)
List< DepositLocation > findAllDepositLocations ()
Detailed Description
Jpa specific implementation of the Vireo Repository interface.
Author
Scott Phillips
Definition at line 36 of file JpaSettingsRepositoryImpl.java.
Member Function Documentation
AdministrativeGroup org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createAdministrativeGroup (String name)
Create a new administrative group object.
Parameters
name The name of the administrative group.
Returns
A new administrative group object.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 169 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaAdministrativeGroupImpl(name);
     }
AdministrativeGroup org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createAdministrativeGroup (String name, HashMap< Integer, String > emails)
Create a new administrative group object with email.
Parameters
name The name of the administrative group.
emails A list of emails.
Returns
A new administrative group object.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 174 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaAdministrativeGroupImpl(name, emails);
     }
College org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createCollege (String name)
Create a new college object.
Parameters
name The name of the college.
Returns
A new college object.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 78 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaCollegeImpl(name);
     }
College org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createCollege (String name, HashMap< Integer, String > emails)
Create a new college object with email.
Parameters
name The name of the college.
emails A list of emails.
Returns
A new college object.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 83 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaCollegeImpl(name, emails);
     }
CommitteeMemberRoleType org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createCommitteeMemberRoleType (String name, DegreeLevel level)
Create a new committee member role type
Parameters
name The name of the role.
level The level this role is available for.
Returns
A role type object.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 290 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaCommitteeMemberRoleTypeImpl(name, level);
     }
Configuration org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createConfiguration (String name, String value)
Create a new system wide configuration.
Parameters
name The name of the canfiguration parameter.
value The value.
Returns
A new configuration object.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 451 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaConfigurationImpl(name,value);
     }
CustomActionDefinition org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createCustomActionDefinition (String label, Boolean isStudentVisible)
Create a new custom action definition
Parameters
label The action's label
Returns
A new custom action definition.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 408 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaCustomActionDefinitionImpl(label, isStudentVisible);
     }
Degree org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createDegree (String name, DegreeLevel level)
Create a new Degree object
Parameters
name Name of the degree.
level Level of the degree.
Returns
A new degree object.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 43 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaDegreeImpl(name, level);
     }
Department org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createDepartment (String name)
Create a new department object.
Parameters
name The name of the department.
Returns
A new department object.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 138 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaDepartmentImpl(name);
     }
Department org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createDepartment (String name, HashMap< Integer, String > emails)
Create a new department object with email.
Parameters
name The name of the department.
emails A list of emails.
Returns
A new department object.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 143 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaDepartmentImpl(name, emails);
     }
DepositLocation org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createDepositLocation (String name)
Create a new deposit location
Parameters
name The name of the new deposit location.
Returns
A new deposit location object.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 512 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaDepositLocationImpl(name);
     }
DocumentType org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createDocumentType (String name, DegreeLevel level)
Create a new document type object.
Parameters
name The name of the document type.
level The level this document type is applicable for.
Returns
A new document type object.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 203 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaDocumentTypeImpl(name, level);
     }
EmailTemplate org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createEmailTemplate (String name, String subject, String message)
Create a new email template
Parameters
name The template's name
subject The template's subject
message The template's messages
Returns
A new email template object.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 366 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaEmailTemplateImpl(name, subject, message);
     }
EmailWorkflowRule org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createEmailWorkflowRule (State associatedState)
Create a new EmailWorkflowRule model.
Parameters
associatedState - Workflow Email Rules's Associated State.
Returns
- a new EmailWorkflowRule
Exceptions
SecurityException
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 332 of file JpaSettingsRepositoryImpl.java.
{
            return new JpaEmailWorkflowRuleImpl(associatedState);
     }
AbstractWorkflowRuleCondition org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createEmailWorkflowRuleCondition (ConditionType condition)
Create a new EmailWorkflowRuleCondition
Parameters
condition - Workflow Rule's associated condition type
Returns
- a new EmailWorkflowRuleCondition
Exceptions
SecurityException
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 317 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaEmailWorkflowRuleConditionImpl(condition);
     }
EmbargoType org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createEmbargoType (String name, String description, Integer duration, boolean active)
Create a new embargo type.
Parameters
name The unique name of the embargo type
description A description of the embargo.
duration How long the embargo should last messured in months. Null for ideterminate, zero for no embargo, and negative numbers are not allowed.
active Weather the embargo is currently active.
Returns
A new embargo type.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 230 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaEmbargoTypeImpl(name, description, duration, active, null);
     }
EmbargoType org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createEmbargoType (String name, String description, Integer duration, boolean active, EmbargoGuarantor guarantor)
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 236 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaEmbargoTypeImpl(name, description, duration, active, guarantor);
     }
GraduationMonth org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createGraduationMonth (int month)
Create a new graduation month.
Parameters
month The graduation month.
Returns
A new graduation month object.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 271 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaGraduationMonthImpl(month);
     }
Language org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createLanguage (String name)
Create a language
Parameters
name The description provided by Proquest of the language.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 427 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaLanguageImpl(name);
     }
Major org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createMajor (String name)
Create a new Major object.
Parameters
name The name of the major.
Returns
A new major object.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 63 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaMajorImpl(name);
     }
Program org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createProgram (String name)
Create a new program object.
Parameters
name The name of the program
Returns
A new program object.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 108 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaProgramImpl(name);
     }
Program org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.createProgram (String name, HashMap< Integer, String > emails)
Create a new program object with email.
Parameters
name The name of the program.
emails A list of emails.
Returns
A new program object.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 113 of file JpaSettingsRepositoryImpl.java.
{
         return new JpaProgramImpl(name, emails);
     }
AdministrativeGroup org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAdministrativeGroup (Long id)
Find a administrative group by unique id.
Parameters
id The administrative group's id.
Returns
The administrative group object or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 179 of file JpaSettingsRepositoryImpl.java.
{
         return (AdministrativeGroup) JpaAdministrativeGroupImpl.findById(id);
     }
AdministrativeGroup org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAdministrativeGroupByName (String name)
Find a administrative group by unique name.
Parameters
name The administrative group's name.
Returns
The administrative group object or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 184 of file JpaSettingsRepositoryImpl.java.
References org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllAdministrativeGroups().
{
         for(AdministrativeGroup adminGroup : findAllAdministrativeGroups()) {
             if(adminGroup.getName().equals(name)) {
                 return adminGroup;
             }
         }
         return null;
     }
List<EmbargoType> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllActiveEmbargoTypes ()
Find all embargo types objects in order.
Returns
A list of all embargo types, or an empty list if there are none.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 262 of file JpaSettingsRepositoryImpl.java.
{
         return (List) JpaEmbargoTypeImpl.find("active = (?1) order by displayOrder", true).fetch();
     }
List<AdministrativeGroup> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllAdministrativeGroups ()
Find all administrative groups objects in order.
Returns
A list of all administrative groups, or an empty list if there are none.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 194 of file JpaSettingsRepositoryImpl.java.
Referenced by org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAdministrativeGroupByName().
{
         return (List) JpaAdministrativeGroupImpl.find("order by displayOrder").fetch();
     }
List<College> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllColleges ()
Find all college objects in order.
Returns
A list of all colleges, or an empty list if there are none.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 103 of file JpaSettingsRepositoryImpl.java.
Referenced by org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findCollegeByName().
{
         return (List) JpaCollegeImpl.find("order by displayOrder").fetch();
     }
List<CommitteeMemberRoleType> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllCommitteeMemberRoleTypes (DegreeLevel level)
Find all committee member role type objects in order that are valid for a particular degree level.
Parameters
level The degree level to find.
Returns
A list of all role types, or an empty list if there are none.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 300 of file JpaSettingsRepositoryImpl.java.
References org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllCommitteeMemberRoleTypes().
{
         if (level == null)
             return findAllCommitteeMemberRoleTypes();
         return JpaCommitteeMemberRoleTypeImpl.find("level = (?1)", level).fetch();
     }
List<CommitteeMemberRoleType> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllCommitteeMemberRoleTypes ()
Find all committee role type objects in order.
Returns
A list of all role types, or an empty list if there are none.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 308 of file JpaSettingsRepositoryImpl.java.
Referenced by org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllCommitteeMemberRoleTypes().
{
         return (List) JpaCommitteeMemberRoleTypeImpl.find("order by displayOrder").fetch();
     }
List<Configuration> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllConfigurations ()
Find all system wide configuration parameters.
Returns
A list of all system wide configuration parameters, or an empty list if there are none.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 488 of file JpaSettingsRepositoryImpl.java.
{
         return (List) JpaConfigurationImpl.findAll();
     }
List<CustomActionDefinition> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllCustomActionDefinition ()
Find all custom action definitions in order.
Returns
A list of all custom action definitions, or an empty list if there are none.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 418 of file JpaSettingsRepositoryImpl.java.
{
         return (List) JpaCustomActionDefinitionImpl.find("order by displayOrder").fetch();
     }
List<Degree> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllDegrees ()
Find all degree objects in order.
Returns
A list of all degrees, or an empty list if there are none.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 58 of file JpaSettingsRepositoryImpl.java.
{
         return (List) JpaDegreeImpl.find("order by displayOrder").fetch();
     }
List<Department> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllDepartments ()
Find all department objects in order.
Returns
A list of all departments, or an empty list if there are none.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 164 of file JpaSettingsRepositoryImpl.java.
Referenced by org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findDepartmentByName().
{
         return (List) JpaDepartmentImpl.find("order by displayOrder").fetch();
     }
List<DepositLocation> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllDepositLocations ()
Find all defined deposit locations.
Returns
A list of all deposit locations.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 527 of file JpaSettingsRepositoryImpl.java.
{
         return (List) JpaDepositLocationImpl.find("order by displayOrder").fetch();
     }
List<DocumentType> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllDocumentTypes (DegreeLevel level)
Find all document type objects in order that are valid for a particular degree level.
Parameters
level The degree level to find.
Returns
A list of all document types, or an empty list if there are none.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 213 of file JpaSettingsRepositoryImpl.java.
References org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllDocumentTypes().
{
         if (level == null)
             return findAllDocumentTypes();
         return JpaDocumentTypeImpl.find("level = (?1)", level).fetch();
     }
List<DocumentType> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllDocumentTypes ()
Find all document type objects in order.
Returns
A list of all document types, or an empty list if there are none.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 221 of file JpaSettingsRepositoryImpl.java.
Referenced by org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllDocumentTypes().
{
         return (List) JpaDocumentTypeImpl.find("order by displayOrder").fetch();
     }
List<EmailTemplate> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllEmailTemplates ()
Find all email templates in order.
Returns
A list of all email templates, or an empty list if there are none.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 399 of file JpaSettingsRepositoryImpl.java.
{
         return (List) JpaEmailTemplateImpl.find("order by displayOrder").fetch();
     }
List<AbstractWorkflowRuleCondition> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllEmailWorkflowRuleConditions ()
Returns
- All of the EmailWorkflowRuleCondition objects
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 327 of file JpaSettingsRepositoryImpl.java.
{
         return (List) JpaEmailWorkflowRuleConditionImpl.find("order by displayOrder").fetch();
     }
List<EmailWorkflowRule> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllEmailWorkflowRules ()
Returns
All Workflow Email Rule objects
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 357 of file JpaSettingsRepositoryImpl.java.
{
         return (List) JpaEmailWorkflowRuleImpl.find("order by displayOrder").fetch();
     }
List<EmbargoType> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllEmbargoTypes ()
Find all embargo types objects in order.
Returns
A list of all embargo types, or an empty list if there are none.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 247 of file JpaSettingsRepositoryImpl.java.
{
         return (List) JpaEmbargoTypeImpl.find("order by displayOrder").fetch();
     }
List<GraduationMonth> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllGraduationMonths ()
Find all graduation months in order.
Returns
A list of all graduation months, or an empty list if there are none.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 281 of file JpaSettingsRepositoryImpl.java.
{
         return (List) JpaGraduationMonthImpl.find("order by displayOrder").fetch();
     }
List<Language> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllLanguages ()
Find all available languages.
Returns
A list of all available languages, or an empty list if there are none.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 442 of file JpaSettingsRepositoryImpl.java.
{
         return (List) JpaLanguageImpl.find("order by displayOrder").fetch();
     }
List<Major> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllMajors ()
Find all majors objects in order.
Returns
A list of all majors, or an empty list if there are none.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 73 of file JpaSettingsRepositoryImpl.java.
{
         return (List) JpaMajorImpl.find("order by displayOrder").fetch();
     }
List<Program> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllPrograms ()
Find all program objects in order.
Returns
A list of all programs, or an empty list if there are none.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 133 of file JpaSettingsRepositoryImpl.java.
Referenced by org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findProgramByName().
{
         return (List) JpaProgramImpl.find("order by displayOrder").fetch();
     }
College org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findCollege (Long id)
Find a college by unique id.
Parameters
id The college's id.
Returns
The college object or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 88 of file JpaSettingsRepositoryImpl.java.
{
         return (College) JpaCollegeImpl.findById(id);
     }
College org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findCollegeByName (String name)
Find a college by unique name.
Parameters
name The college's name.
Returns
The college object or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 93 of file JpaSettingsRepositoryImpl.java.
References org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllColleges().
{
         for(College college : findAllColleges()) {
             if(college.getName().equals(name)) {
                 return college;
             }
         }
         return null;
     }
CommitteeMemberRoleType org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findCommitteeMemberRoleType (Long id)
Find a committee member role type by id.
Parameters
id The type's id.
Returns
The role type object, or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 295 of file JpaSettingsRepositoryImpl.java.
{
         return (CommitteeMemberRoleType) JpaCommitteeMemberRoleTypeImpl.findById(id);
     }
Configuration org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findConfiguration (Long id)
Find a system wide configuration object by id.
Parameters
id The configuration's id.
Returns
The configuration object, or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 456 of file JpaSettingsRepositoryImpl.java.
{
         return (Configuration) JpaConfigurationImpl.findById(id);
     }
Configuration org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findConfigurationByName (String name)
Find a system wide configuration object by name.
Parameters
name The configuration's name.
Returns
The configuration object, or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 461 of file JpaSettingsRepositoryImpl.java.
Referenced by org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.getConfigValue().
{
         return JpaConfigurationImpl.find("name = (?1)", name).first();
     }
CustomActionDefinition org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findCustomActionDefinition (Long id)
Find custom action definition by id.
Parameters
id The action's id.
Returns
The custom action definition, or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 413 of file JpaSettingsRepositoryImpl.java.
{
         return (CustomActionDefinition) JpaCustomActionDefinitionImpl.findById(id);
     }
Degree org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findDegree (Long id)
Find degree by unique id.
Parameters
id The degree's id.
Returns
The degree object or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 48 of file JpaSettingsRepositoryImpl.java.
{
         return (Degree) JpaDegreeImpl.findById(id);
     }
Degree org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findDegreeByName (String name)
Find degree by name.
Parameters
name The name given to the degree.
Returns
The degree object or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 53 of file JpaSettingsRepositoryImpl.java.
{
         return JpaDegreeImpl.find("name = (?1)", name).first();
     }
Department org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findDepartment (Long id)
Find department by unique id
Parameters
id The department's id.
Returns
The department object or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 148 of file JpaSettingsRepositoryImpl.java.
{
         return (Department) JpaDepartmentImpl.findById(id);
     }
Department org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findDepartmentByName (String name)
Find department by unique name
Parameters
name The department's name.
Returns
The department object or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 154 of file JpaSettingsRepositoryImpl.java.
References org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllDepartments().
{
         for(Department department : findAllDepartments()) {
             if(department.getName().equals(name)) {
                 return department;
             }
         }
         return null;
     }
DepositLocation org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findDepositLocation (Long id)
Find a deposit location object by id.
Parameters
id The location's unique id.
Returns
The deposit location, or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 517 of file JpaSettingsRepositoryImpl.java.
{
         return (DepositLocation) JpaDepositLocationImpl.findById(id);
     }
DepositLocation org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findDepositLocationByName (String name)
Find a deposit location by name.
Parameters
name The location's unique name.
Returns
The deposit location, or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 522 of file JpaSettingsRepositoryImpl.java.
{
         return JpaDepositLocationImpl.find("name = (?1)", name).first();
     }
DocumentType org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findDocumentType (Long id)
Find a document type by id.
Parameters
id The document type's id.
Returns
The document type object, or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 208 of file JpaSettingsRepositoryImpl.java.
{
         return (DocumentType) JpaDocumentTypeImpl.findById(id);
     }
EmailTemplate org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findEmailTemplate (Long id)
Find an email template by id.
Parameters
id The email template's id.
Returns
The email template object, or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 371 of file JpaSettingsRepositoryImpl.java.
{
         return (EmailTemplate) JpaEmailTemplateImpl.findById(id);
     }
EmailTemplate org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findEmailTemplateByName (String name)
Find an email template by it's name.
If a System email template name is passed in, a Custom version will be returned if it exists.
Parameters
name The name of the template.
Returns
The email template found, or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 376 of file JpaSettingsRepositoryImpl.java.
References org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findNonSystemEmailTemplateByName(), and org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findSystemEmailTemplateByName().
{
         // return a custom version if it exists
         EmailTemplate ret = findNonSystemEmailTemplateByName(name);
         // otherwise return the system version if it exists
         if (ret == null) {
             ret = findSystemEmailTemplateByName(name);
         }
         return ret;
     }
EmailWorkflowRule org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findEmailWorkflowRule (Long id)
Find a workflow email rule based upon their unique id.
Parameters
id Workflow Email Rules's id.
Returns
The Workflow Email Rule object or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 337 of file JpaSettingsRepositoryImpl.java.
{
         return (EmailWorkflowRule) JpaEmailWorkflowRuleImpl.findById(id);
     }
AbstractWorkflowRuleCondition org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findEmailWorkflowRuleCondition (Long id)
Find a workflow rule condition base upon their unique id.
Parameters
id - the workflow email rule condition's id.
Returns
- the workflow email rule condition or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 322 of file JpaSettingsRepositoryImpl.java.
{
         return (AbstractWorkflowRuleCondition) JpaEmailWorkflowRuleConditionImpl.findById(id);
     }
List<EmailWorkflowRule> org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findEmailWorkflowRulesByState (State type)
Find a Workflow Email Rule based on their associated state.
Parameters
state The Workflow Email Rule's associated state.
Returns
The Workflow Email Rule object or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 342 of file JpaSettingsRepositoryImpl.java.
{
         List<EmailWorkflowRule> rules = (List) JpaEmailWorkflowRuleImpl.findAll();
         List<EmailWorkflowRule> rulesByState = new ArrayList<EmailWorkflowRule>();
         for(EmailWorkflowRule rule: rules) {
             State thisRulesState = rule.getAssociatedState();
             if(thisRulesState.equals(state))
                 rulesByState.add(rule);
         }
         return rulesByState;
     }
EmbargoType org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findEmbargoType (Long id)
Find embargo type by id.
Parameters
id The embargo type's id.
Returns
The embargo type, or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 242 of file JpaSettingsRepositoryImpl.java.
{
         return (EmbargoType) JpaEmbargoTypeImpl.findById(id);
     }
GraduationMonth org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findGraduationMonth (Long id)
Find a graduation month by id.
Parameters
id The month's id.
Returns
The graduation month object, or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 276 of file JpaSettingsRepositoryImpl.java.
{
         return (GraduationMonth) JpaGraduationMonthImpl.findById(id);
     }
Language org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findLanguage (Long id)
Find a language by id.
Parameters
id The id of the language.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 432 of file JpaSettingsRepositoryImpl.java.
{
         return (Language) JpaLanguageImpl.findById(id);
     }
Language org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findLanguageByName (String name)
Find a language by the name
Parameters
name The name of the language.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 437 of file JpaSettingsRepositoryImpl.java.
{
         return (Language) JpaLanguageImpl.find("name = (?1)", name).first();
     }
Major org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findMajor (Long id)
Find major by unique id.
Parameters
id The major's id.
Returns
The major object or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 68 of file JpaSettingsRepositoryImpl.java.
{
         return (Major) JpaMajorImpl.findById(id);
     }
EmailTemplate org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findNonSystemEmailTemplateByName (String name)
Find a NonSystem email template by it's name.
Parameters
name The name of the NonSystem template.
Returns
The NonSystem email template found, or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 387 of file JpaSettingsRepositoryImpl.java.
Referenced by org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findEmailTemplateByName().
{
         // return a custom version if it exists
         return JpaEmailTemplateImpl.find("name = (?1) AND systemRequired = FALSE", name).first();
     }
EmbargoType org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findNonSystemEmbargoTypeByNameAndGuarantor (String name, EmbargoGuarantor guarantor)
Find the NonSystem embargo types object that matches name.
Parameters
name
Returns
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 257 of file JpaSettingsRepositoryImpl.java.
{
         return (EmbargoType) JpaEmbargoTypeImpl.find("name = (?1) AND guarantor = (?2) AND systemRequired = FALSE", name, guarantor).first();
     }
Program org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findProgram (Long id)
Find a program by unique id.
Parameters
id The program's id
Returns
The program object or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 118 of file JpaSettingsRepositoryImpl.java.
{
         return (Program) JpaProgramImpl.findById(id);
     }
Program org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findProgramByName (String name)
Find a program by unique name.
Parameters
name The program's name.
Returns
The program object or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 123 of file JpaSettingsRepositoryImpl.java.
References org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findAllPrograms().
{
         for(Program program : findAllPrograms()) {
             if(program.getName().equals(name)) {
                 return program;
             }
         }
         return null;
     }
EmailTemplate org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findSystemEmailTemplateByName (String name)
Find a System email template by it's name.
Parameters
name The name of the System template.
Returns
The System email template found, or null if not found.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 393 of file JpaSettingsRepositoryImpl.java.
Referenced by org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findEmailTemplateByName().
{
         // return the system version if it exists
         return JpaEmailTemplateImpl.find("name = (?1) AND systemRequired = TRUE", name).first();
     }
EmbargoType org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findSystemEmbargoTypeByNameAndGuarantor (String name, EmbargoGuarantor guarantor)
Find the System embargo types object that matches name.
Parameters
name
Returns
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 252 of file JpaSettingsRepositoryImpl.java.
{
         return (EmbargoType) JpaEmbargoTypeImpl.find("name = (?1) AND guarantor = (?2) AND systemRequired = TRUE", name, guarantor).first();
     }
boolean org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.getConfigBoolean (String name)
Find a system wide configuration and return it's boolean value. If the configuration parameter has any value at all it is considered true, if no configuration entry is defined for the parameter then it is considered false.
Parameters
name The name of the configuration object.
Returns
The value
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 482 of file JpaSettingsRepositoryImpl.java.
References org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.getConfigValue().
{
         return getConfigValue(name) != null ? true : false;
     }
String org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.getConfigValue (String name, String defaultValue)
Find a system wide configuration and return it's value. If the configuration parameter is not set, then return the default value supplied.
Parameters
name The name of the configuration object.
defaultValue The default value for the configuration object if not found.
Returns
The value
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 466 of file JpaSettingsRepositoryImpl.java.
References org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.findConfigurationByName(), and org.tdl.vireo.model.Configuration.getValue().
Referenced by org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.getConfigBoolean(), and org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.getConfigValue().
{
         Configuration config = findConfigurationByName(name);
         if (config == null || config.getValue() == null || config.getValue().trim().length() == 0)
             return defaultValue;
         else
             return config.getValue();
     }
String org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.getConfigValue (String name)
Find a system wide configuration and return it's value. If the configuration object does not exist the the Configuration.DEFAULTS registry will be consulted. If a default has been registered for the parameter then the default will be returned, otherwise null.
Parameters
name The name of the parameter.
Returns
The value, or null.
Implements org.tdl.vireo.model.SettingsRepository.
Definition at line 476 of file JpaSettingsRepositoryImpl.java.
References org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.getConfigValue().
{
         return getConfigValue(name,Configuration.DEFAULTS.get(name));
     }
void org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.setConfigurationDefaults (Map< String, String > defaults)
Set default configuration parameters from spring.
Parameters
defaults A map of name value pairs for default configuration paramaters.
Definition at line 500 of file JpaSettingsRepositoryImpl.java.
{
         for (String name : defaults.keySet()) {
             String value = defaults.get(name).trim();
             Configuration.DEFAULTS.register(name, value);
         }
     }
The documentation for this class was generated from the following file:
app/org/tdl/vireo/model/jpa/JpaSettingsRepositoryImpl.java