Vireo: org.tdl.vireo.search.impl.LuceneSearcherImpl Class Reference
org.tdl.vireo.search.impl.LuceneSearcherImpl Class Reference
Classes
class LuceneSearchResults< T extends AbstractModel >
class ModelComparator
Public Member Functions
void setLuceneIndexerImpl (LuceneIndexerImpl indexer)
void setSubmissionRepository (SubmissionRepository subRepo)
void setStateManager (StateManager stateManager)
SearchResult< Submission > submissionSearch (SearchFilter filter, SearchOrder orderBy, SearchDirection direction, int offset, int limit)
SearchResult< ActionLog > actionLogSearch (SearchFilter filter, SearchOrder orderBy, SearchDirection direction, int offset, int limit)
long[] submissionSearch (SearchFilter filter, SearchOrder orderBy, SearchDirection direction)
long[] actionLogSearch (SearchFilter filter, SearchOrder orderBy, SearchDirection direction)
void buildQuery (BooleanQuery andQuery, SearchFilter filter, boolean submissions)
Public Attributes
LuceneIndexerImpl indexer = null
SubmissionRepository subRepo = null
StateManager stateManager = null
Static Public Attributes
static String[] SORT_SUB_FIELDS = new String[SearchOrder.values().length]
static String[] SORT_LOG_FIELDS = new String[SearchOrder.values().length]
static int[] SORT_TYPES = new int[SearchOrder.values().length]
Package Functions
[instance initializer]
Detailed Description
Lucene implementation of the Searcher interface.
This implementation is directly tied to the LuceneIndexerImpl, in fact it requires it as a spring-based dependency.
Author
Scott Phillips
Definition at line 51 of file LuceneSearcherImpl.java.
Member Function Documentation
org.tdl.vireo.search.impl.LuceneSearcherImpl.[instance initializer] () package
SearchResult<ActionLog> org.tdl.vireo.search.impl.LuceneSearcherImpl.actionLogSearch (SearchFilter filter, SearchOrder orderBy, SearchDirection direction, int offset, int limit)
Search for all action logs which match the parameters and order specified below.
Parameters
filter The filter parameters describing which log items should be included.
orderBy How the logs items should be ordered.
direction The direction of the order.
offset The pagination offset.
limit The pagination limit of results per page.
Returns
The action log results object.
Implements org.tdl.vireo.search.Searcher.
Definition at line 201 of file LuceneSearcherImpl.java.
References org.tdl.vireo.search.SearchDirection.ASCENDING, org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery(), org.tdl.vireo.search.impl.LuceneSearcherImpl.SORT_LOG_FIELDS, and org.tdl.vireo.search.impl.LuceneSearcherImpl.SORT_TYPES.
{
         try {
             IndexReader reader = IndexReader.open(indexer.index);
             try {
                 IndexSearcher searcher = new IndexSearcher(reader);
                 BooleanQuery andQuery = new BooleanQuery();
                 andQuery.add(new TermQuery(new Term("type","actionlog")),Occur.MUST);
                 buildQuery(andQuery,filter,false); // <-- This does most of the work.
                 boolean reverse = (direction == SearchDirection.ASCENDING) ? false : true;
                 SortField dynamicSortField = new SortField(SORT_LOG_FIELDS[orderBy.ordinal()], SORT_TYPES[orderBy.ordinal()], reverse);
                 SortField idSortField = new SortField("logId",SortField.LONG,reverse);
                 Sort sort = new Sort(dynamicSortField, idSortField);
                 Logger.debug("Log Query: "+andQuery.toString());
                 // Run the search
                 TopDocs topDocs = searcher.search(andQuery, offset + limit, sort);
                 List<Long> sortedIds = new ArrayList<Long>();
                 for(int i=offset; i < offset + limit ; i++) {
                     if (i >= topDocs.scoreDocs.length )
                         break;
                     Document doc = searcher.doc(topDocs.scoreDocs[i].doc);
                     sortedIds.add(Long.valueOf(doc.get("logId")));
                 }
                 searcher.close();
                 List<ActionLog> results = subRepo.findActionLogs(sortedIds);
                 Collections.sort(results,new ModelComparator(sortedIds));
                 return new LuceneSearchResults<ActionLog>(filter, direction, orderBy, offset, limit, results, topDocs.totalHits);
             } finally {
                 reader.close();
             }
         } catch (IOException ioe) {
             Logger.error(ioe,"Unable to search");
         }
         return null;
     }
long [] org.tdl.vireo.search.impl.LuceneSearcherImpl.actionLogSearch (SearchFilter filter, SearchOrder orderBy, SearchDirection direction)
Search for the ids of all action logs which match the parameters and order specified below. This method is useful for batch operations where you want to operate on the entire set but don't want to have all the objects in memory for the entire time. This way you can get the list and iterate through the list one at a time clearing out all the previous objects each time.
Parameters
filter The filter parameters describing which log items should be included.
orderBy How the logs items should be ordered.
direction The direction of the order.
Returns
The action log results object.
Implements org.tdl.vireo.search.Searcher.
Definition at line 294 of file LuceneSearcherImpl.java.
References org.tdl.vireo.search.SearchDirection.ASCENDING, org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery(), org.tdl.vireo.search.impl.LuceneSearcherImpl.SORT_SUB_FIELDS, and org.tdl.vireo.search.impl.LuceneSearcherImpl.SORT_TYPES.
{
         try {
             IndexReader reader = IndexReader.open(indexer.index);
             try {
                 IndexSearcher searcher = new IndexSearcher(reader);
                 BooleanQuery andQuery = new BooleanQuery();
                 andQuery.add(new TermQuery(new Term("type","actionlog")),Occur.MUST);
                 buildQuery(andQuery,filter,true); // <-- This does most of the work.
                 boolean reverse = (direction == SearchDirection.ASCENDING) ? false : true;
                 SortField dynamicSortField = new SortField(SORT_SUB_FIELDS[orderBy.ordinal()], SORT_TYPES[orderBy.ordinal()], reverse);
                 SortField idSortField = new SortField("logId",SortField.LONG,reverse);
                 Sort sort = new Sort(dynamicSortField, idSortField);
                 Logger.debug("Log ID Query: "+andQuery.toString());
                 TopDocs topDocs = searcher.search(andQuery, Integer.MAX_VALUE, sort);
                 long[] sortedIds = new long[topDocs.scoreDocs.length];
                 for (int i = 0; i < topDocs.scoreDocs.length; i++) {
                     Document doc = searcher.doc(topDocs.scoreDocs[i].doc);
                     sortedIds[i] = Long.valueOf(doc.get("logId")).longValue();
                 }
                 searcher.close();
                 return sortedIds;
             } finally {
                 reader.close();
             }
         } catch (IOException ioe) {
             Logger.error(ioe,"Unable to search");
         }
         return null;
     }
void org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery (BooleanQuery andQuery, SearchFilter filter, boolean submissions)
This method produces the common part of the query handle the filter search clauses.
Parameters
andQuery The existing and-based query
filter The filter search paramaters.
submissions Whether this is for submissions or action logs
Definition at line 347 of file LuceneSearcherImpl.java.
References org.tdl.vireo.search.SearchFilter.getAssignees(), org.tdl.vireo.search.SearchFilter.getColleges(), org.tdl.vireo.search.SearchFilter.getCustomActions(), org.tdl.vireo.search.SearchFilter.getDateRangeEnd(), org.tdl.vireo.search.SearchFilter.getDateRangeStart(), org.tdl.vireo.search.SearchFilter.getDegrees(), org.tdl.vireo.search.SearchFilter.getDepartments(), org.tdl.vireo.state.State.getDisplayName(), org.tdl.vireo.search.SearchFilter.getDocumentTypes(), org.tdl.vireo.search.SearchFilter.getEmbargoTypes(), org.tdl.vireo.search.SearchFilter.getExcludedActionLogs(), org.tdl.vireo.search.SearchFilter.getExcludedSubmissions(), org.tdl.vireo.search.SearchFilter.getGraduationSemesters(), org.tdl.vireo.search.SearchFilter.getIncludedActionLogs(), org.tdl.vireo.search.SearchFilter.getIncludedSubmissions(), org.tdl.vireo.search.SearchFilter.getMajors(), org.tdl.vireo.search.SearchFilter.getPrograms(), org.tdl.vireo.search.SearchFilter.getSearchText(), org.tdl.vireo.search.SearchFilter.getStates(), org.tdl.vireo.search.SearchFilter.getUMIRelease(), org.tdl.vireo.search.impl.LuceneSearcherImpl.indexer, org.tdl.vireo.search.impl.LuceneIndexerImpl.standardAnalyzer, and org.tdl.vireo.search.impl.LuceneIndexerImpl.version.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.actionLogSearch(), and org.tdl.vireo.search.impl.LuceneSearcherImpl.submissionSearch().
{
         QueryParser parser = new QueryParser(indexer.version,"searchText",indexer.standardAnalyzer);
         // Include Submission filter
         if (filter.getIncludedSubmissions().size() > 0) {
             BooleanQuery orQuery = new BooleanQuery();
             for(Submission sub : filter.getIncludedSubmissions()) {
                 orQuery.add(new TermQuery(new Term("subId", NumericUtils.longToPrefixCoded(sub.getId()))), Occur.SHOULD);
             }
             andQuery.add(orQuery,Occur.MUST);
         }
         // Include Log filter
         if (filter.getIncludedActionLogs().size() > 0) {
             BooleanQuery orQuery = new BooleanQuery();
             for(ActionLog log : filter.getIncludedActionLogs()) {
                 orQuery.add(new TermQuery(new Term("logId", NumericUtils.longToPrefixCoded(log.getId()))), Occur.SHOULD);
             }
             andQuery.add(orQuery,Occur.MUST);
         }
         // Exclude Submission filter
         for(Submission sub : filter.getExcludedSubmissions()) {
             andQuery.add(new TermQuery(new Term("subId", NumericUtils.longToPrefixCoded(sub.getId()))), Occur.MUST_NOT);
         }
         // Exclude Log filter
         for(ActionLog log : filter.getExcludedActionLogs()) {
             andQuery.add(new TermQuery(new Term("logId", NumericUtils.longToPrefixCoded(log.getId()))), Occur.MUST_NOT);
         }
         // Search Text Filter
         if (filter.getSearchText().size() > 0) {
             BooleanQuery orQuery = new BooleanQuery();
             for(String searchText : filter.getSearchText()) {
                 try {
                     // First try to interpret it as a complex lucene search string.
                     orQuery.add(parser.parse(searchText),Occur.SHOULD);
                 } catch (ParseException e) {
                     // If that fails just fall back to a term query.
                     orQuery.add(new TermQuery(new Term("searchText", searchText)), Occur.SHOULD);
                 }
             }
             andQuery.add(orQuery,Occur.MUST);
         }
         // State Filter
         if (filter.getStates().size() > 0) {
             BooleanQuery orQuery = new BooleanQuery();
             for(String stateName : filter.getStates()) {
                 State state = stateManager.getState(stateName);
                 orQuery.add(new TermQuery(new Term("state", state.getDisplayName())), Occur.SHOULD);
             }
             andQuery.add(orQuery,Occur.MUST);
         }
         // Assignee Filter
         if (filter.getAssignees().size() > 0) {
             BooleanQuery orQuery = new BooleanQuery();
             for(Person assignee : filter.getAssignees()) {
                 long assigneeId = 0;
                 if (assignee != null)
                     assigneeId = assignee.getId();
                 orQuery.add(new TermQuery(new Term("searchAssigned", NumericUtils.longToPrefixCoded(assigneeId))), Occur.SHOULD);
             }
             andQuery.add(orQuery,Occur.MUST);
         }
         // Embargo Filter
         if (filter.getEmbargoTypes().size() > 0) {
             BooleanQuery orQuery = new BooleanQuery();
             for(EmbargoType embargo : filter.getEmbargoTypes()) {
                 orQuery.add(new TermQuery(new Term("embargo", embargo.getName())), Occur.SHOULD);
             }
             andQuery.add(orQuery,Occur.MUST);
         }
         // Graduation Semester Filter
         if (filter.getGraduationSemesters().size() > 0) {
             BooleanQuery orQuery = new BooleanQuery();
             for(Semester semester : filter.getGraduationSemesters()) {
                 // We can't index it if it dosn't have a date.
                 if (semester.year == null)
                     continue;
                 Calendar cal = Calendar.getInstance();
                 cal.clear();
                 cal.set(Calendar.YEAR, semester.year);
                 if (semester.month != null) {
                     cal.set(Calendar.MONTH,semester.month);
                 }
                 orQuery.add(new TermQuery(new Term("graduationSemester", NumericUtils.longToPrefixCoded(cal.getTimeInMillis()))), Occur.SHOULD);
             }
             andQuery.add(orQuery,Occur.MUST);
         }
         // Degree Filter
         if (filter.getDegrees().size() > 0) {
             BooleanQuery orQuery = new BooleanQuery();
             for(String degree : filter.getDegrees()) {
                 orQuery.add(new TermQuery(new Term("degree", degree)), Occur.SHOULD);
             }
             andQuery.add(orQuery,Occur.MUST);
         }
         // Department Filter
         if (filter.getDepartments().size() > 0) {
             BooleanQuery orQuery = new BooleanQuery();
             for(String dept : filter.getDepartments()) {
                 orQuery.add(new TermQuery(new Term("department", dept)), Occur.SHOULD);
             }
             andQuery.add(orQuery,Occur.MUST);
         }
         // Program Filter
         if (filter.getPrograms().size() > 0) {
             BooleanQuery orQuery = new BooleanQuery();
             for(String program : filter.getPrograms()) {
                 orQuery.add(new TermQuery(new Term("program", program)), Occur.SHOULD);
             }
             andQuery.add(orQuery,Occur.MUST);
         }
         // College Filter
         if (filter.getColleges().size() > 0) {
             BooleanQuery orQuery = new BooleanQuery();
             for(String college : filter.getColleges()) {
                 orQuery.add(new TermQuery(new Term("college", college)), Occur.SHOULD);
             }
             andQuery.add(orQuery,Occur.MUST);
         }
         // Major Filter
         if (filter.getMajors().size() > 0) {
             BooleanQuery orQuery = new BooleanQuery();
             for(String major : filter.getMajors()) {
                 orQuery.add(new TermQuery(new Term("major", major)), Occur.SHOULD);
             }
             andQuery.add(orQuery,Occur.MUST);
         }
         // Document Type Filter
         if (filter.getDocumentTypes().size() > 0) {
             BooleanQuery orQuery = new BooleanQuery();
             for(String docType : filter.getDocumentTypes()) {
                 orQuery.add(new TermQuery(new Term("documentType", docType)), Occur.SHOULD);
             }
             andQuery.add(orQuery,Occur.MUST);
         }
         // UMI Release Filter
         if (filter.getUMIRelease() != null) {
             if (filter.getUMIRelease()) {
                 andQuery.add(new TermQuery(new Term("umiRelease","yes")),Occur.MUST);
             } else {
                 andQuery.add(new TermQuery(new Term("umiRelease","no")),Occur.MUST);
             }
         }
         // Date Range Filter
         if (filter.getDateRangeStart() != null || filter.getDateRangeEnd() != null) {
             long startTime = 0;
             if (filter.getDateRangeStart() != null)
                 startTime = filter.getDateRangeStart().getTime();
             long endTime = Long.MAX_VALUE;
             if (filter.getDateRangeEnd() != null)
                 endTime = filter.getDateRangeEnd().getTime();
             if (submissions)
                 andQuery.add(NumericRangeQuery.newLongRange("submissionDate", startTime, endTime, true,true),Occur.MUST);
             else
                 andQuery.add(NumericRangeQuery.newLongRange("lastEventTime", startTime, endTime, true,true),Occur.MUST);
         }
         // Custom Action Filter
         if (filter.getCustomActions().size() > 0) {
             BooleanQuery orQuery = new BooleanQuery();
             for(CustomActionDefinition customAction : filter.getCustomActions()) {
                 orQuery.add(new TermQuery(new Term("customAction", customAction.getLabel())), Occur.SHOULD);
             }
             andQuery.add(orQuery,Occur.MUST);
         }
     }
void org.tdl.vireo.search.impl.LuceneSearcherImpl.setLuceneIndexerImpl (LuceneIndexerImpl indexer)
Spring injection for the LuceneIndexerImpl. Note that this implementation is tied directly to the indexer implementation, that is why the datatype is what it is.
Parameters
indexer The lucene indexer.
Definition at line 130 of file LuceneSearcherImpl.java.
References org.tdl.vireo.search.impl.LuceneSearcherImpl.indexer.
{
         this.indexer = indexer;
     }
void org.tdl.vireo.search.impl.LuceneSearcherImpl.setStateManager (StateManager stateManager)
Parameters
stateManager The state manager (used to resolve state names into display names)
Definition at line 147 of file LuceneSearcherImpl.java.
References org.tdl.vireo.search.impl.LuceneSearcherImpl.stateManager.
{
         this.stateManager = stateManager;
     }
void org.tdl.vireo.search.impl.LuceneSearcherImpl.setSubmissionRepository (SubmissionRepository subRepo)
Parameters
subRepo The submission repository
Definition at line 138 of file LuceneSearcherImpl.java.
References org.tdl.vireo.search.impl.LuceneSearcherImpl.subRepo.
{
         this.subRepo = subRepo;
     }
SearchResult<Submission> org.tdl.vireo.search.impl.LuceneSearcherImpl.submissionSearch (SearchFilter filter, SearchOrder orderBy, SearchDirection direction, int offset, int limit)
Search for all submissions which match the parameters and order specified below.
Parameters
filter The filter parameters describing which submissions should be included.
orderBy How the submissions should be ordered.
direction The direction of the order.
offset The pagination offset.
limit The pagination limit of results per page.
Returns
The submission results object.
Implements org.tdl.vireo.search.Searcher.
Definition at line 152 of file LuceneSearcherImpl.java.
References org.tdl.vireo.search.SearchDirection.ASCENDING, org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery(), org.tdl.vireo.search.impl.LuceneSearcherImpl.SORT_SUB_FIELDS, and org.tdl.vireo.search.impl.LuceneSearcherImpl.SORT_TYPES.
{
         try {
             IndexReader reader = IndexReader.open(indexer.index);
             try {
                 IndexSearcher searcher = new IndexSearcher(reader);
                 BooleanQuery andQuery = new BooleanQuery();
                 andQuery.add(new TermQuery(new Term("type","submission")),Occur.MUST);
                 buildQuery(andQuery,filter,true); // <-- This does most of the work.
                 boolean reverse = (direction == SearchDirection.ASCENDING) ? false : true;
                 SortField dynamicSortField = new SortField(SORT_SUB_FIELDS[orderBy.ordinal()], SORT_TYPES[orderBy.ordinal()], reverse);
                 SortField idSortField = new SortField("subId",SortField.LONG,reverse);
                 Sort sort = new Sort(dynamicSortField, idSortField);
                 Logger.debug("Submission Query: "+andQuery.toString());
                 // Run the search
                 TopDocs topDocs = searcher.search(andQuery, offset + limit, sort);
                 List<Long> sortedIds = new ArrayList<Long>();
                 for(int i=offset; i < offset + limit ; i++) {
                     if (i >= topDocs.scoreDocs.length )
                         break;
                     Document doc = searcher.doc(topDocs.scoreDocs[i].doc);
                     sortedIds.add(Long.valueOf(doc.get("subId")));
                 }
                 searcher.close();
                 List<Submission> results = subRepo.findSubmissions(sortedIds);
                 Collections.sort(results,new ModelComparator(sortedIds));
                 return new LuceneSearchResults<Submission>(filter, direction, orderBy, offset, limit, results, topDocs.totalHits);
             } finally {
                 reader.close();
             }
         } catch (IOException ioe) {
             Logger.error(ioe,"Unable to search");
         }
         return null;
     }
long [] org.tdl.vireo.search.impl.LuceneSearcherImpl.submissionSearch (SearchFilter filter, SearchOrder orderBy, SearchDirection direction)
Search for the ids of all submissions which match the parameters and order specified below. This method is useful for batch operations where you want to operate on the entire set but don't want to have all the objects in memory for the entire time. This way you can get the list and iterate through the list one at a time clearing out all the previous objects each time.
Parameters
filter The filter parameters describing which submissions should be included.
orderBy How the submissions should be ordered.
direction The direction of the order.
Returns
The submission results object.
Implements org.tdl.vireo.search.Searcher.
Definition at line 251 of file LuceneSearcherImpl.java.
References org.tdl.vireo.search.SearchDirection.ASCENDING, org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery(), org.tdl.vireo.search.impl.LuceneSearcherImpl.SORT_SUB_FIELDS, and org.tdl.vireo.search.impl.LuceneSearcherImpl.SORT_TYPES.
{
         try {
             IndexReader reader = IndexReader.open(indexer.index);
             try {
                 IndexSearcher searcher = new IndexSearcher(reader);
                 BooleanQuery andQuery = new BooleanQuery();
                 andQuery.add(new TermQuery(new Term("type","submission")),Occur.MUST);
                 buildQuery(andQuery,filter,true); // <-- This does most of the work.
                 boolean reverse = (direction == SearchDirection.ASCENDING) ? false : true;
                 SortField dynamicSortField = new SortField(SORT_SUB_FIELDS[orderBy.ordinal()], SORT_TYPES[orderBy.ordinal()], reverse);
                 SortField idSortField = new SortField("subId",SortField.LONG,reverse);
                 Sort sort = new Sort(dynamicSortField, idSortField);
                 Logger.debug("Submission ID Query: "+andQuery.toString());
                 TopDocs topDocs = searcher.search(andQuery, Integer.MAX_VALUE, sort);
                 long[] sortedIds = new long[topDocs.scoreDocs.length];
                 for (int i = 0; i < topDocs.scoreDocs.length; i++) {
                     Document doc = searcher.doc(topDocs.scoreDocs[i].doc);
                     sortedIds[i] = Long.valueOf(doc.get("subId")).longValue();
                 }
                 searcher.close();
                 return sortedIds;
             } finally {
                 reader.close();
             }
         } catch (IOException ioe) {
             Logger.error(ioe,"Unable to search");
         }
         return null;
     }
Member Data Documentation
LuceneIndexerImpl org.tdl.vireo.search.impl.LuceneSearcherImpl.indexer = null
Definition at line 118 of file LuceneSearcherImpl.java.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery(), and org.tdl.vireo.search.impl.LuceneSearcherImpl.setLuceneIndexerImpl().
String [] org.tdl.vireo.search.impl.LuceneSearcherImpl.SORT_LOG_FIELDS = new String[SearchOrder.values().length] static
Definition at line 55 of file LuceneSearcherImpl.java.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.actionLogSearch().
String [] org.tdl.vireo.search.impl.LuceneSearcherImpl.SORT_SUB_FIELDS = new String[SearchOrder.values().length] static
Definition at line 54 of file LuceneSearcherImpl.java.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.actionLogSearch(), and org.tdl.vireo.search.impl.LuceneSearcherImpl.submissionSearch().
int [] org.tdl.vireo.search.impl.LuceneSearcherImpl.SORT_TYPES = new int[SearchOrder.values().length] static
Definition at line 56 of file LuceneSearcherImpl.java.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.actionLogSearch(), and org.tdl.vireo.search.impl.LuceneSearcherImpl.submissionSearch().
StateManager org.tdl.vireo.search.impl.LuceneSearcherImpl.stateManager = null
Definition at line 120 of file LuceneSearcherImpl.java.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.setStateManager().
SubmissionRepository org.tdl.vireo.search.impl.LuceneSearcherImpl.subRepo = null
Definition at line 119 of file LuceneSearcherImpl.java.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.setSubmissionRepository().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/search/impl/LuceneSearcherImpl.java