Vireo: org.tdl.vireo.search.impl.LuceneIndexerImpl Class Reference
org.tdl.vireo.search.impl.LuceneIndexerImpl Class Reference
Public Member Functions
LuceneIndexerImpl () throws IOException
void setSubmissionRepository (SubmissionRepository subRepo)
void updated (Long submissionId)
void updated (List< Long > submissionIds)
boolean isUpdated (Long submissionId)
boolean isUpdated (Submission submission)
void rollback ()
void commit (boolean wait)
void rebuild (boolean wait)
void deleteAndRebuild (boolean wait)
boolean isJobRunning ()
String getCurrentJobLabel ()
long getCurrentJobProgress ()
long getCurrentJobTotal ()
synchronized void runNextJob (LuceneAbstractJobImpl newJob)
Public Attributes
ThreadLocal< Set< Long > > transactionLocal = new ThreadLocal<Set<Long>>()
final File indexFile
final Directory index
final Version version = Version.LUCENE_36
final Analyzer standardAnalyzer = new StandardAnalyzer(version)
SubmissionRepository subRepo = null
boolean corruptIndex = false
Package Functions
public< T extends
AbstractModel > void updated (T model)
Private Attributes
LuceneAbstractJobImpl currentJob = null
LuceneAbstractJobImpl nextJob = null
Detailed Description
The Lucene Search Indexer.
This class manages writing to the Lucene search index all updates. For each thread modifying data in the model a separate transaction of those changes will be maintained. So when a model is updated, it is expected that the model object will tell the indexer that it's contents have been modified. The indexer will receive that notification and keep the related submission's id in a set. Then after the database transaction has been committed the index transaction can be committed. Updating the index is handled by background threads, in a matter completely seemless to the outside observer.
Fields:
subId: The id of the submission, this is available for both submissions and action logs.
logId: The id of the action log, this is only available for action logs.
type: Either "submission" or "actionlog" depending on what type of record.
SEARCH INDEXES (SOME USED FOR SORTING)
searchText: search index for textual searches
state: The bean name of the current state. single token not analyzed (search and sort)
searchAssigned: search index for those who are assigned. The field is composed of either the id of the assigned person, or 0 for unassigned submissions.
sortAssigned: The full name of the person assigned
graduationSemester: The grad year & month converted into a date object and stored as milliseconds.
defenseDate: The date of the student's defense.
program: the program, a single token not analyzed (search and sort)
department: The department, single token not analyzed (search and sort)
college: The college, single token not analyzed (search and sort)
major: The major, single token not analyzed (search and sort)
embargo: The embargo name, single token not analyzed (search and sort)
degree: The degree, single token not analyzed (search and sort)
documentType: The document type's name, single token not analyzed (search and sort)
umiRelease: Either "yes", "no", or "" for the three possible states (search and sort)
submissionDate: The submission date for the submission as a numeric date stored as milliseconds.
customAction: The submission's completed custom actions (search and sort)
ONLY USED FOR SORTING:
studentName: The student name for sorting.
studentEmail: The student's email for sorting.
institutionalIdentifier: The student's institutional identifier
documentTitle: The document's title for sorting.
documentAbstract: The document's abstract for sorting.
documentKeywords: The document's keywords for sorting.
documentSubjects: The document's subjects for sorting.
documentLanguage: The document's language both code and name.
publishedMaterial: The description of previously published material
primaryDocument: The name of the primary document for sorting.
licenseAgreementDate: The date the license was agreed too for sorting.
approvalDate: The date the submission was approved for sorting.
committeeApprovalDate: The date the committee approved the submission for sorting.
committeeEmbargoApprovalDate: The date the committee approved the embargo for sorting.
committeeMembers: A single string strung together of all committee member's name for sorting.
committeeContactEmail: The committee email for sorting
degreeLevel: the degree level, single token not analyzed just for sorting
depositId: The deposit id for sorting
reviewerNotes: The notes from reviewers for sorting
lastEventEntry: The textual entry of the last log event for sorting.
lastEventTime: The date of the last entry for sorting.
orcid: The ORCID of the student.
Author
Scott Phillips
Definition at line 147 of file LuceneIndexerImpl.java.
Constructor & Destructor Documentation
org.tdl.vireo.search.impl.LuceneIndexerImpl.LuceneIndexerImpl () throws IOException
Construct a new LuceneIndexer
Definition at line 174 of file LuceneIndexerImpl.java.
References org.tdl.vireo.search.impl.LuceneIndexerImpl.index, and org.tdl.vireo.search.impl.LuceneIndexerImpl.indexFile.
{
         indexFile = new File(Play.applicationPath + File.separator + Play.configuration.getProperty("index.path","data/indexes"));
         index = FSDirectory.open(indexFile);
     }
Member Function Documentation
void org.tdl.vireo.search.impl.LuceneIndexerImpl.commit (boolean wait)
Commit the current transaction.
Create a new job and add it to the queue.
Implements org.tdl.vireo.search.Indexer.
Definition at line 292 of file LuceneIndexerImpl.java.
References org.tdl.vireo.search.impl.LuceneIndexerImpl.currentJob, org.tdl.vireo.search.impl.LuceneIndexerImpl.nextJob, and org.tdl.vireo.search.impl.LuceneIndexerImpl.runNextJob().
{
         Set<Long> txn = transactionLocal.get();
         if (txn != null && txn.size() > 0) {
             LuceneAbstractJobImpl newJob = new LuceneUpdateJob(this,txn);
             if (wait) {
                 // We will run this job in the current thread and wait for it to
                 // finish. However we have to wait around for all other background
                 // jobs to complete. We must also be thread safe about it.
                 while (true) {
                     synchronized (this) {
                         if (currentJob == null && nextJob == null) {
                             // Start the job now. Anyone attempting to schedule will
                             // block until the end of this synchronized block.
                             newJob.doJob();
                             return;
                         }
                     }
                     // Give all other thread a chance to do their thing now that we are out of the synchronized block.
                     Thread.yield();
                 }
             } else {
                 // Schedule the job as a background task.
                 runNextJob(newJob);
             }
         }
     }
void org.tdl.vireo.search.impl.LuceneIndexerImpl.deleteAndRebuild (boolean wait)
Delete the index and rebuild.
This method allows for recovery of corrupted indexes because it blows away whatever is in the index directory.
This method will (even with the wait flag turned off) will block until all the current jobs have been canceled and the index files have been deleted.
Implements org.tdl.vireo.search.Indexer.
Definition at line 363 of file LuceneIndexerImpl.java.
References org.tdl.vireo.search.impl.LuceneIndexerImpl.currentJob, org.tdl.vireo.search.impl.LuceneIndexerImpl.indexFile, org.tdl.vireo.search.impl.LuceneIndexerImpl.isJobRunning(), and org.tdl.vireo.search.impl.LuceneIndexerImpl.nextJob.
{
         Logger.info("Removing the entire lucene index at '"+indexFile.getPath()+"' and rebuilding.'");
         // First, cancel any currently running jobs.
         nextJob = null;
         if (currentJob != null)
             currentJob.cancelJob();
         synchronized(this) {
             // Wait for the jobs to stop
             while(isJobRunning()) {
                 Thread.yield();
             }
             // Delete everything in the index directory.
             if (indexFile != null && indexFile.exists() ) {
                 File[] files = indexFile.listFiles();
                 for (File file : files) {
                     file.delete();
                 }
             }
             // Create our job, and put it on the queue. This will prevent any other jobs from jumping before this one while we are in the synchronized queue.
             LuceneAbstractJobImpl newJob = new LuceneRebuildJobImpl(this);
             currentJob = newJob;
         }
         if (wait) {
             // Start the rebuild job in the current thread.
             currentJob.doJob();
         } else {
             // Start it as a background job.
             currentJob.now();
         }
     }
String org.tdl.vireo.search.impl.LuceneIndexerImpl.getCurrentJobLabel ()
Returns
The label of the current background process, either "Updating Index" or "Rebuilding Index"
Implements org.tdl.vireo.search.Indexer.
Definition at line 406 of file LuceneIndexerImpl.java.
{
         try {
             return currentJob.getLabel();
         } catch (Throwable t) {
             // We need this method to be thread safe, so use a try catch block
             // instead of an if block to check for the case where currentJob ==
             // null.
             return "None";
         }
     }
long org.tdl.vireo.search.impl.LuceneIndexerImpl.getCurrentJobProgress ()
Returns
The current progress of how many submissions have been indexed so far.
Implements org.tdl.vireo.search.Indexer.
Definition at line 418 of file LuceneIndexerImpl.java.
{
         try {
             return currentJob.getProgress();
         } catch (Throwable t) {
             // We need this method to be thread safe, so use a try catch block
             // instead of an if block to check for the case where currentJob ==
             // null.
             return -1;
         }
     }
long org.tdl.vireo.search.impl.LuceneIndexerImpl.getCurrentJobTotal ()
Returns
The total number of submissions that will be indexed by the background process.
Implements org.tdl.vireo.search.Indexer.
Definition at line 430 of file LuceneIndexerImpl.java.
{
         try {
             return currentJob.getTotal();
         } catch (Throwable t) {
             // We need this method to be thread safe, so use a try catch block
             // instead of an if block to check for the case where currentJob ==
             // null.
             return -1;
         }
     }
boolean org.tdl.vireo.search.impl.LuceneIndexerImpl.isJobRunning ()
Returns
True if a background process is currently updating the search index.
Implements org.tdl.vireo.search.Indexer.
Definition at line 401 of file LuceneIndexerImpl.java.
References org.tdl.vireo.search.impl.LuceneIndexerImpl.currentJob.
Referenced by org.tdl.vireo.search.impl.LuceneIndexerImpl.deleteAndRebuild().
{
         return !(currentJob == null);
     }
boolean org.tdl.vireo.search.impl.LuceneIndexerImpl.isUpdated (Long submissionId)
Parameters
submissionId The id of a submission object.
Returns
True if the identified submission is included in the current transaction.
Implements org.tdl.vireo.search.Indexer.
Definition at line 263 of file LuceneIndexerImpl.java.
References org.tdl.vireo.search.impl.LuceneIndexerImpl.transactionLocal.
Referenced by org.tdl.vireo.search.impl.LuceneIndexerImpl.isUpdated().
{
         if (transactionLocal.get() != null) {
             return transactionLocal.get().contains(submissionId);
         }
         return false;
     }
boolean org.tdl.vireo.search.impl.LuceneIndexerImpl.isUpdated (Submission submission)
Parameters
submission A submission object.
Returns
True if the submission object is included in the current transaction.
Implements org.tdl.vireo.search.Indexer.
Definition at line 272 of file LuceneIndexerImpl.java.
References org.tdl.vireo.model.AbstractModel.getId(), and org.tdl.vireo.search.impl.LuceneIndexerImpl.isUpdated().
{
         return isUpdated(submission.getId());
     }
void org.tdl.vireo.search.impl.LuceneIndexerImpl.rebuild (boolean wait)
Rebuild the entire search index from scratch.
Create a new job and add it to the queue.
Implements org.tdl.vireo.search.Indexer.
Definition at line 327 of file LuceneIndexerImpl.java.
References org.tdl.vireo.search.impl.LuceneIndexerImpl.currentJob, org.tdl.vireo.search.impl.LuceneIndexerImpl.nextJob, and org.tdl.vireo.search.impl.LuceneIndexerImpl.runNextJob().
{
         LuceneAbstractJobImpl newJob = new LuceneRebuildJobImpl(this);
         if (wait) {
             // We will run this job in the current thread and wait for it to
             // finish. However we have to wait around for all other background
             // jobs to complete. We must also be thread safe about it.
             while (true) {
                 synchronized (this) {
                     if (currentJob == null && nextJob == null) {
                         // Start the job now. Anyone attempting to schedule will
                         // block until the end of this synchronized block.
                         newJob.doJob();
                         return;
                     }
                 }
                 // Give all other thread a chance to do their thing now that we are out of the synchronized block.
                 Thread.yield();
             }
         } else {
             // Schedule the job as a background task.
             runNextJob(newJob);
         }
     }
void org.tdl.vireo.search.impl.LuceneIndexerImpl.rollback ()
Rollback the current transaction.
Just remove the threadLocal entry.
Implements org.tdl.vireo.search.Indexer.
Definition at line 282 of file LuceneIndexerImpl.java.
{
         transactionLocal.remove();
     }
synchronized void org.tdl.vireo.search.impl.LuceneIndexerImpl.runNextJob (LuceneAbstractJobImpl newJob)
Control processing of the next job. Any management of the current & next job pointers is handled by this method to ensure thread safety.
This method works under two scenarios:
1) A transaction has just been committed, generating a new index job. This method is called with the new index job. It will either be started right away and assigned as the current job. However if another job is already running then this job will be held until that finishes. We only keep track of one job in the future, so potentially if multiple jobs are waiting they will be merged into a single job covering all the submissions across them all.
2) The current job has finished processing and the next job in the queue needs to be run. For this case the parameter newJob is null. The nextJob pointer will move up to the currentJob freeing it's old position, and then it will be executed right away.
Parameters
newJob A new job to add to the queue, or null to run the next job (this should only be called by the current index job).
Definition at line 465 of file LuceneIndexerImpl.java.
References org.tdl.vireo.search.impl.LuceneIndexerImpl.currentJob, and org.tdl.vireo.search.impl.LuceneIndexerImpl.nextJob.
Referenced by org.tdl.vireo.search.impl.LuceneIndexerImpl.commit(), and org.tdl.vireo.search.impl.LuceneIndexerImpl.rebuild().
{
         if (newJob == null) {
             // This means the current job has finished, so we should move on to the next job.
             currentJob = nextJob;
             nextJob = null;
             if (currentJob != null)
                 currentJob.now();
             return;
         }
         if (currentJob == null) {
             // Nothing is running, so launch the job.
             currentJob = newJob;
             newJob.now();
         } else if (nextJob == null) {
             // The next job is free, so just put it there until ready.
             nextJob = newJob;
         } else {
             // We already have the next job in the queue, so merge the two jobs together.
             nextJob = nextJob.mergeJob(newJob);
         }
     }
void org.tdl.vireo.search.impl.LuceneIndexerImpl.setSubmissionRepository (SubmissionRepository subRepo)
Inject the submission repository.
Parameters
subRepo The submission repository
Definition at line 185 of file LuceneIndexerImpl.java.
References org.tdl.vireo.search.impl.LuceneIndexerImpl.subRepo.
{
         this.subRepo = subRepo;
     }
public<T extends AbstractModel> void org.tdl.vireo.search.impl.LuceneIndexerImpl.updated (T model) package
Receive the model and update the transactions with any submissions that need to be updated in the index. We may receive models of lots of different types, however we only care about a few specific ones, those that are connected with a particular submission. When one of those models comes through we exact the submission it is related to and update the transaction accordingly.
Parameters
model The model which was saved, created, or deleted.
Implements org.tdl.vireo.search.Indexer.
Definition at line 202 of file LuceneIndexerImpl.java.
References org.tdl.vireo.model.AbstractModel.getId().
Referenced by org.tdl.vireo.search.impl.LuceneIndexerImpl.updated().
{
         // If we get a null then there probably is a problem somewhere else than needs to be fixed.
         if (model == null)
             throw new IllegalArgumentException("Updated object must not be null");
         // If we haven't been persisted in the database yet then forget about it.
         if (model.getId() == null)
             return;
         // Check the type of object it is.
         Submission sub = null;
         if (model instanceof Submission) {
             sub = (Submission) model;
         } else if (model instanceof Attachment) {
             Attachment attachment = (Attachment) model;
             sub = attachment.getSubmission();
         } else if (model instanceof CommitteeMember) {
             CommitteeMember member = (CommitteeMember) model;
             sub = member.getSubmission();
         } else if (model instanceof CustomActionValue) {
             CustomActionValue action = (CustomActionValue) model;
             sub = action.getSubmission();
         } else if (model instanceof ActionLog) {
             ActionLog log = (ActionLog) model;
             sub = log.getSubmission();
         }
         // Add the submission to the transaction
         if (sub != null) {
             updated(sub.getId());
         }
     }
void org.tdl.vireo.search.impl.LuceneIndexerImpl.updated (Long submissionId)
This is a notification method to update the index for the provided submission Id. This works the same as the updated(model) varient however this may be more efficient in situations where the full object is not available. The indexer will keep track of these submissions until either rollback() or commit() is called from the same thread.
Parameters
submissionId The id of the submission which was created, saved, or deleted.
Implements org.tdl.vireo.search.Indexer.
Definition at line 237 of file LuceneIndexerImpl.java.
References org.tdl.vireo.search.impl.LuceneIndexerImpl.transactionLocal.
{
         if (submissionId == null)
             throw new IllegalArgumentException("An submission id is required");
         // Create a new transaction if needed.
         if (transactionLocal.get() == null)
             transactionLocal.set(new LinkedSet<Long>());
         // Add the submission to the transaction
         transactionLocal.get().add(submissionId);
     }
void org.tdl.vireo.search.impl.LuceneIndexerImpl.updated (List< Long > submissionIds)
This is a notification method to update the index for the provided list of submission ids. This works the same as the updated(model) varient however this may be more efficient in situations where the full object is not available. The indexer will keep track of these submissions until either rollback() or commit() is called from the same thread.
Parameters
submissionIds A list of submission ids which were created, saved, or deleted.
Implements org.tdl.vireo.search.Indexer.
Definition at line 252 of file LuceneIndexerImpl.java.
References org.tdl.vireo.search.impl.LuceneIndexerImpl.updated().
{
         if (submissionIds == null)
             throw new IllegalArgumentException("A list of submission ids are required");
         for (Long submissionId : submissionIds) {
             updated(submissionId);
         }
     }
Member Data Documentation
boolean org.tdl.vireo.search.impl.LuceneIndexerImpl.corruptIndex = false
Definition at line 169 of file LuceneIndexerImpl.java.
Referenced by org.tdl.vireo.search.impl.LuceneAbstractJobImpl.doJob().
LuceneAbstractJobImpl org.tdl.vireo.search.impl.LuceneIndexerImpl.currentJob = null private
Definition at line 154 of file LuceneIndexerImpl.java.
Referenced by org.tdl.vireo.search.impl.LuceneIndexerImpl.commit(), org.tdl.vireo.search.impl.LuceneIndexerImpl.deleteAndRebuild(), org.tdl.vireo.search.impl.LuceneIndexerImpl.isJobRunning(), org.tdl.vireo.search.impl.LuceneIndexerImpl.rebuild(), and org.tdl.vireo.search.impl.LuceneIndexerImpl.runNextJob().
final Directory org.tdl.vireo.search.impl.LuceneIndexerImpl.index
Definition at line 159 of file LuceneIndexerImpl.java.
Referenced by org.tdl.vireo.search.impl.LuceneIndexerImpl.LuceneIndexerImpl(), org.tdl.vireo.search.impl.LuceneRebuildJobImpl.writeIndex(), and org.tdl.vireo.search.impl.LuceneUpdateJob.writeIndex().
final File org.tdl.vireo.search.impl.LuceneIndexerImpl.indexFile
Definition at line 158 of file LuceneIndexerImpl.java.
Referenced by org.tdl.vireo.search.impl.LuceneIndexerImpl.deleteAndRebuild(), and org.tdl.vireo.search.impl.LuceneIndexerImpl.LuceneIndexerImpl().
LuceneAbstractJobImpl org.tdl.vireo.search.impl.LuceneIndexerImpl.nextJob = null private
Definition at line 155 of file LuceneIndexerImpl.java.
Referenced by org.tdl.vireo.search.impl.LuceneIndexerImpl.commit(), org.tdl.vireo.search.impl.LuceneIndexerImpl.deleteAndRebuild(), org.tdl.vireo.search.impl.LuceneIndexerImpl.rebuild(), and org.tdl.vireo.search.impl.LuceneIndexerImpl.runNextJob().
final Analyzer org.tdl.vireo.search.impl.LuceneIndexerImpl.standardAnalyzer = new StandardAnalyzer(version)
Definition at line 161 of file LuceneIndexerImpl.java.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery(), org.tdl.vireo.search.impl.LuceneRebuildJobImpl.writeIndex(), and org.tdl.vireo.search.impl.LuceneUpdateJob.writeIndex().
SubmissionRepository org.tdl.vireo.search.impl.LuceneIndexerImpl.subRepo = null
Definition at line 164 of file LuceneIndexerImpl.java.
Referenced by org.tdl.vireo.search.impl.LuceneRebuildJobImpl.LuceneRebuildJobImpl(), org.tdl.vireo.search.impl.LuceneIndexerImpl.setSubmissionRepository(), and org.tdl.vireo.search.impl.LuceneRebuildJobImpl.writeIndex().
ThreadLocal<Set<Long> > org.tdl.vireo.search.impl.LuceneIndexerImpl.transactionLocal = new ThreadLocal<Set<Long>>()
Definition at line 150 of file LuceneIndexerImpl.java.
Referenced by org.tdl.vireo.search.impl.LuceneIndexerImpl.isUpdated(), and org.tdl.vireo.search.impl.LuceneIndexerImpl.updated().
final Version org.tdl.vireo.search.impl.LuceneIndexerImpl.version = Version.LUCENE_36
Definition at line 160 of file LuceneIndexerImpl.java.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery(), org.tdl.vireo.search.impl.LuceneRebuildJobImpl.writeIndex(), and org.tdl.vireo.search.impl.LuceneUpdateJob.writeIndex().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/search/impl/LuceneIndexerImpl.java