Vireo: org.tdl.vireo.error.impl.ErrorLogImpl Class Reference
org.tdl.vireo.error.impl.ErrorLogImpl Class Reference
Public Member Functions
void setSecurityContext (SecurityContext context)
void setMaxReports (int max)
ErrorReport logError (Throwable exception, String where)
ErrorReport logError (Throwable exception, Request request)
ErrorReport logError (Throwable exception, JobMetadata job)
ErrorReport logError (Throwable exception)
List< ErrorReport > getRecentErrorReports ()
synchronized void clearRecentErrorReports ()
Public Attributes
SecurityContext context
int maxReports = 10
Protected Attributes
ConcurrentLinkedQueue
< ErrorReport > reports = new ConcurrentLinkedQueue<ErrorReport>()
Detailed Description
Simple queue implementation of the ErrorLog interface.
Author
Scott Phillips
Definition at line 28 of file ErrorLogImpl.java.
Member Function Documentation
synchronized void org.tdl.vireo.error.impl.ErrorLogImpl.clearRecentErrorReports ()
Clear out the list of recent errors;
Implements org.tdl.vireo.error.ErrorLog.
Definition at line 124 of file ErrorLogImpl.java.
{
         reports.clear();
     }
List<ErrorReport> org.tdl.vireo.error.impl.ErrorLogImpl.getRecentErrorReports ()
Returns
A list of recent error reports.
Implements org.tdl.vireo.error.ErrorLog.
Definition at line 113 of file ErrorLogImpl.java.
{
         List<ErrorReport> copy =  new ArrayList<ErrorReport>(this.reports);
         Collections.reverse(copy);
         return copy;
     }
ErrorReport org.tdl.vireo.error.impl.ErrorLogImpl.logError (Throwable exception, String where)
Report an error.
Parameters
exception The exception
where A message indicating where the error occured.
Returns
The ErrorReport.
Implements org.tdl.vireo.error.ErrorLog.
Definition at line 55 of file ErrorLogImpl.java.
References org.tdl.vireo.error.impl.ErrorLogImpl.context, org.tdl.vireo.security.SecurityContext.getPerson(), org.tdl.vireo.error.impl.ErrorLogImpl.maxReports, and org.tdl.vireo.error.impl.ErrorLogImpl.reports.
Referenced by org.tdl.vireo.error.impl.ErrorLogImpl.logError().
{
         try {
             ErrorReport report = new ErrorReportImpl(
                     context.getPerson(),
                     where,
                     exception);
             synchronized (this) {
                 while (reports.size() >= maxReports)
                     reports.poll();
                 reports.add(report);
             }
             return report;
         } catch (RuntimeException re) {
             // Error, while reporting errors... *head explodes*
             // We'll just log the error and go on our merry way.
             Logger.error(re, "Encountered an error while reporting another error that was encounted while '%s'.");
             return null;
         }
     }
ErrorReport org.tdl.vireo.error.impl.ErrorLogImpl.logError (Throwable exception, Request request)
Report an error.
Parameters
exception The exception
request The request generating the error (aka the where).
Returns
The ErrorReport.
Implements org.tdl.vireo.error.ErrorLog.
Definition at line 80 of file ErrorLogImpl.java.
References org.tdl.vireo.error.impl.ErrorLogImpl.logError().
{
         String where = String.format(
                 "HTTP request %s(): %s",
                 request.action,
                 request.url);
         return logError(exception, where);
     }
ErrorReport org.tdl.vireo.error.impl.ErrorLogImpl.logError (Throwable exception, JobMetadata job)
Report an error.
Parameters
exception The exception
job The job generating the error (aka the where)
Returns
The ErrorReport.
Implements org.tdl.vireo.error.ErrorLog.
Definition at line 91 of file ErrorLogImpl.java.
References org.tdl.vireo.error.impl.ErrorLogImpl.logError().
{
         String jobName = "unknown";
         if(null != job) {
             jobName = job.getName();
         }
         String message = String.format(
                 "Background job: %s",
                 jobName);
         return logError(exception, message);
     }
ErrorReport org.tdl.vireo.error.impl.ErrorLogImpl.logError (Throwable exception)
Report an error.
Parameters
exception The exception
Returns
The ErrorReport.
Implements org.tdl.vireo.error.ErrorLog.
Definition at line 105 of file ErrorLogImpl.java.
References org.tdl.vireo.error.impl.ErrorLogImpl.logError().
{
         return logError(exception, (String) null);
     }
void org.tdl.vireo.error.impl.ErrorLogImpl.setMaxReports (int max)
Set the maximum number of reports to keep in the queue;
Parameters
max
Definition at line 49 of file ErrorLogImpl.java.
{
         this.maxReports = max;
     }
void org.tdl.vireo.error.impl.ErrorLogImpl.setSecurityContext (SecurityContext context)
Inject the security context.
Parameters
context The security context
Definition at line 41 of file ErrorLogImpl.java.
References org.tdl.vireo.error.impl.ErrorLogImpl.context.
{
         this.context = context;
     }
Member Data Documentation
SecurityContext org.tdl.vireo.error.impl.ErrorLogImpl.context
Definition at line 31 of file ErrorLogImpl.java.
Referenced by org.tdl.vireo.error.impl.ErrorLogImpl.logError(), and org.tdl.vireo.error.impl.ErrorLogImpl.setSecurityContext().
int org.tdl.vireo.error.impl.ErrorLogImpl.maxReports = 10
Definition at line 32 of file ErrorLogImpl.java.
Referenced by org.tdl.vireo.error.impl.ErrorLogImpl.logError().
ConcurrentLinkedQueue<ErrorReport> org.tdl.vireo.error.impl.ErrorLogImpl.reports = new ConcurrentLinkedQueue<ErrorReport>() protected
Definition at line 35 of file ErrorLogImpl.java.
Referenced by org.tdl.vireo.error.impl.ErrorLogImpl.logError().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/error/impl/ErrorLogImpl.java