Vireo: controllers.JobTab Class Reference
controllers.JobTab Class Reference
Static Public Member Functions
static void adminStatus (String jobId)
static void updateJSON (String jobId)
Static Public Member Functions inherited from controllers.AbstractVireoController
static void injectRepositories ()
static void checkForFirstUser ()
static void handleError (Throwable throwable)
Static Public Attributes
static JobManager jobManager = Spring.getBeanOfType(JobManager.class)
Static Public Attributes inherited from controllers.AbstractVireoController
static SecurityContext context = Spring.getBeanOfType(SecurityContext.class)
static PersonRepository personRepo = Spring.getBeanOfType(PersonRepository.class)
static SubmissionRepository subRepo = Spring.getBeanOfType(SubmissionRepository.class)
static SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class)
static ProquestVocabularyRepository proquestRepo = Spring.getBeanOfType(ProquestVocabularyRepository.class)
static ErrorLog errorLog = Spring.getBeanOfType(ErrorLog.class)
static StateManager stateManager = Spring.getBeanOfType(StateManager.class)
static Indexer indexer = Spring.getBeanOfType(Indexer.class)
static Searcher searcher = Spring.getBeanOfType(Searcher.class)
static Boolean firstUser = null
Additional Inherited Members
Static Protected Member Functions inherited from controllers.AbstractVireoController
static boolean isEmpty (String value)
static boolean isNotEmpty (String value)
static String escapeJavaScript (String value)
static String toJSON (String[] values)
static String text2html (String value)
static boolean isFieldRequired (FieldConfig field)
Detailed Description
This is a simple controller to show a progress bar to track any log running background job.
Author
Scott Phillips
Definition at line 47 of file JobTab.java.
Member Function Documentation
static void controllers.JobTab.adminStatus (String jobId) static
Display the progress bar. If the job is currently active then javascript will repeataly update the state until the job is no longer active.
Parameters
jobId The UUID of the job.
Definition at line 60 of file JobTab.java.
{
         notFoundIfNull(jobId);
         UUID id = null;
         try {
             id = UUID.fromString(jobId);
         } catch (RuntimeException re) {/* ignore */}
         notFoundIfNull(id);
         JobMetadata job = jobManager.findJob(id);
         notFoundIfNull(job);
         for(JobStatus status : JobStatus.values()) {
             renderArgs.put(status.name(), status);
         }
         renderTemplate("JobTab/adminProgress.html",job);
     }
static void controllers.JobTab.updateJSON (String jobId) static
Get the most up-to-date status about a job and return it as a JSON payload.
Parameters
jobId The UUID of the job.
Definition at line 88 of file JobTab.java.
References org.tdl.vireo.job.JobMetadata.getMessage(), org.tdl.vireo.job.JobMetadata.getName(), org.tdl.vireo.job.JobMetadata.getProgress(), and org.tdl.vireo.job.JobMetadata.getStatus().
{
         UUID id = UUID.fromString(jobId);
         notFoundIfNull(id);
         JobMetadata job = jobManager.findJob(id);
         notFoundIfNull(job);
         jobId = escapeJavaScript(jobId);
         String name = escapeJavaScript(job.getName());
         String status = escapeJavaScript(job.getStatus().name());
         String progress = escapeJavaScript(job.getProgress().toString());
         String message = escapeJavaScript(job.getMessage());
         renderJSON("{ "+
                 "\"id\" : \"" + jobId + "\", " +
                 "\"name\" : \"" + name + "\", "+
                 "\"status\" : \"" + status + "\", "+
                 "\"progress\" : \"" + progress + "\", "+
                 "\"message\" : \"" + message + "\" "+
                 "}");
     }
Member Data Documentation
JobManager controllers.JobTab.jobManager = Spring.getBeanOfType(JobManager.class) static
Definition at line 50 of file JobTab.java.
The documentation for this class was generated from the following file:
app/controllers/JobTab.java