Vireo: controllers.settings.ApplicationSettingsTab Class Reference
controllers.settings.ApplicationSettingsTab Class Reference
Static Public Member Functions
static void applicationSettings ()
static void updateApplicationSettingsJSON (String field, String value)
static void addCustomActionJSON (String name, Boolean isStudentVisible)
static void editCustomActionJSON (String actionId, String name, Boolean level)
static void removeCustomActionJSON (String actionId)
static void reorderCustomActionsJSON (String actionIds)
static void updateDepositLocationList ()
static void loadDepositLocation (String depositLocationId)
static void saveDepositLocation (String depositLocationId)
static void removeDepositLocationJSON (String depositLocationId)
static void reorderDepositLocationsJSON (String depositLocationIds)
static void searchMembers (String query, Integer offset)
static void updatePersonRole (String personId, int role)
Static Public Member Functions inherited from controllers.SettingsTab
static void settingsRedirect ()
static void updateProfileJSON (String field, String value)
Static Public Member Functions inherited from controllers.AbstractVireoController
static void injectRepositories ()
static void checkForFirstUser ()
static void handleError (Throwable throwable)
Static Public Attributes
static final int SEARCH_MEMBERS_RESULTS_PER_PAGE = 5
static DepositService depositService = Spring.getBeanOfType(DepositService.class)
Static Public Attributes inherited from controllers.AbstractVireoController
static SecurityContext context = Spring.getBeanOfType(SecurityContext.class)
static PersonRepository personRepo = Spring.getBeanOfType(PersonRepository.class)
static SubmissionRepository subRepo = Spring.getBeanOfType(SubmissionRepository.class)
static SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class)
static ProquestVocabularyRepository proquestRepo = Spring.getBeanOfType(ProquestVocabularyRepository.class)
static ErrorLog errorLog = Spring.getBeanOfType(ErrorLog.class)
static StateManager stateManager = Spring.getBeanOfType(StateManager.class)
static Indexer indexer = Spring.getBeanOfType(Indexer.class)
static Searcher searcher = Spring.getBeanOfType(Searcher.class)
static Boolean firstUser = null
Static Protected Member Functions
static boolean isValidCurrentSemester (String value)
static String submitTestItem (DepositLocation location)
Static Protected Member Functions inherited from controllers.SettingsTab
static void saveModelOrder (List<?extends AbstractOrderedModel > models)
static
< TextendsAbstractOrderedModel >
List< T > resolveIds (String idString, Class< T > type)
static int monthNameToInt (String monthName)
Static Protected Member Functions inherited from controllers.AbstractVireoController
static boolean isEmpty (String value)
static boolean isNotEmpty (String value)
static String escapeJavaScript (String value)
static String URIEncode (String value)
static String toJSON (String[] values)
static String text2html (String value)
static boolean isFieldRequired (FieldConfig field)
Detailed Description
Application settings
Author
Scott Phillips
Definition at line 46 of file ApplicationSettingsTab.java.
Member Function Documentation
static void controllers.settings.ApplicationSettingsTab.addCustomActionJSON (String name, Boolean isStudentVisible) static
Add a new custom action value. The id and label of the new action will be returned.
Parameters
name The label of the new action
Definition at line 231 of file ApplicationSettingsTab.java.
{
         try {
             if (name == null || name.trim().length() == 0)
                 throw new IllegalArgumentException("Label is required");
             if(isStudentVisible == null) {
                 throw new IllegalArgumentException("isStudentVisible is required");
             }
             // Add the new action to the end of the list.
             List<CustomActionDefinition> actions = settingRepo.findAllCustomActionDefinition();
             CustomActionDefinition action = settingRepo.createCustomActionDefinition(name, isStudentVisible);
             actions.add(action);
             saveModelOrder(actions);
             name = escapeJavaScript(name);
             renderJSON("{ \"success\": \"true\", \"id\": "+action.getId()+", \"name\": \""+name+"\", \"level\": " + isStudentVisible + "}");
         } catch (IllegalArgumentException iae) {
             String message = escapeJavaScript(iae.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         } catch (PersistenceException pe) {
             name = escapeJavaScript(name);
             renderJSON("{ \"failure\": \"true\", \"message\": \"Another custom action already exists with the name: '"+name+"'\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to add custom action");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         }
     }
static void controllers.settings.ApplicationSettingsTab.applicationSettings () static
Display the application settings page.
Definition at line 58 of file ApplicationSettingsTab.java.
References org.tdl.vireo.model.RoleType.REVIEWER.
{
         renderArgs.put("SUBMISSIONS_OPEN", settingRepo.findConfigurationByName(SUBMISSIONS_OPEN));
         renderArgs.put("ALLOW_MULTIPLE_SUBMISSIONS", settingRepo.findConfigurationByName(ALLOW_MULTIPLE_SUBMISSIONS));
         renderArgs.put("CURRENT_SEMESTER", settingRepo.getConfigValue(CURRENT_SEMESTER, ""));
         renderArgs.put("GRANTOR", settingRepo.getConfigValue(GRANTOR, ""));
         renderArgs.put("SUBMIT_LICENSE_TEXT", settingRepo.getConfigValue(SUBMIT_LICENSE_TEXT));
         renderArgs.put("ORCID_VALIDATION", settingRepo.getConfigValue(ORCID_VALIDATION));
         renderArgs.put("ORCID_AUTHENTICATION", settingRepo.getConfigValue(ORCID_AUTHENTICATION));
         renderArgs.put("PROQUEST_INSTITUTION_CODE", settingRepo.getConfigValue(PROQUEST_INSTITUTION_CODE));
         renderArgs.put("PROQUEST_INDEXING", settingRepo.getConfigValue(PROQUEST_INDEXING));
         renderArgs.put("PROQUEST_LICENSE_TEXT", settingRepo.getConfigValue(PROQUEST_LICENSE_TEXT));
         List<String> degrees = new ArrayList<String>();
         for(Degree degree : settingRepo.findAllDegrees()) {
             if (!degrees.contains(degree.getName()))
                 degrees.add(degree.getName());
         }
         for (String degree : subRepo.findAllDegrees()) {
             if (!degrees.contains(degree))
                 degrees.add(degree);
         }
         List<String> proquestDegrees = new ArrayList<String>();
         for (ProquestDegree degree : proquestRepo.findAllDegrees()) {
             String sanatizedCode = degree.getCode().replaceAll("'","&#39;");
             if (!proquestDegrees.contains(sanatizedCode)) {
                 proquestDegrees.add(sanatizedCode);
             }
         }
         List<CustomActionDefinition> actions = settingRepo.findAllCustomActionDefinition();
         List<DepositLocation> locations = settingRepo.findAllDepositLocations();
         List<Packager> packagers = new ArrayList<Packager>( (Collection) Spring.getBeansOfType(Packager.class).values() );
         List<Depositor> depositors = new ArrayList<Depositor>( (Collection) Spring.getBeansOfType(Depositor.class).values() );
         List<Person> reviewers = personRepo.findPersonsByRole(RoleType.REVIEWER);
         int offset=0;
         int limit=SEARCH_MEMBERS_RESULTS_PER_PAGE;
         List<Person> searchResults = personRepo.searchPersons(null, offset, limit);
         String nav = "settings";
         String subNav = "application";
         renderTemplate("SettingTabs/applicationSettings.html",nav, subNav, degrees, proquestDegrees, actions, locations, packagers, depositors, reviewers, searchResults, offset, limit);
     }
static void controllers.settings.ApplicationSettingsTab.editCustomActionJSON (String actionId, String name, Boolean level) static
Edit an existing custom action's label. The id and the label will be returned.
Parameters
actionId The id of the action to be edited, in the fom "action_id"
name The new label of the action.
Definition at line 275 of file ApplicationSettingsTab.java.
{
         try {
             // Check input
             if (name == null || name.trim().length() == 0)
                 throw new IllegalArgumentException("Label is required");
             if(level == null) {
                 throw new IllegalArgumentException("isStudentVisible is required");
             }
             // Save the new label
             String[] parts = actionId.split("_");
             Long id = Long.valueOf(parts[1]);
             CustomActionDefinition action = settingRepo.findCustomActionDefinition(id);
             action.setLabel(name);
             action.setIsStudentVisible(level);
             action.save();
             name = escapeJavaScript(name);
             renderJSON("{ \"success\": \"true\", \"id\": "+action.getId()+", \"name\": \""+name+"\", \"level\": " + level + "}");
         } catch (IllegalArgumentException iae) {
             String message = escapeJavaScript(iae.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         } catch (PersistenceException pe) {
             name = escapeJavaScript(name);
             renderJSON("{ \"failure\": \"true\", \"message\": \"Another custom action already exists with the name: '"+name+"'\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to edit custom action");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         }
     }
static boolean controllers.settings.ApplicationSettingsTab.isValidCurrentSemester (String value) static protected
Validate the current semester string which must be of the format: month year.
Parameters
value The value to be validated.
Returns
Either true if valid, otherwise false.
Definition at line 801 of file ApplicationSettingsTab.java.
{
         try {
             if (value == null || value.trim().length() == 0)
                 // The blank value is also acceptable.
                 return true;
             String[] parts = value.split(" ");
             if (parts.length != 2)
                 return false;
             Integer month = monthNameToInt(parts[0]);
             Integer year = Integer.valueOf(parts[1]);
             return true;
         } catch (RuntimeException re) {
             return false;
         }
     }
static void controllers.settings.ApplicationSettingsTab.loadDepositLocation (String depositLocationId) static
Load a deposit loation into the modal dialog box. We will attempt to test the connection and return proper results just as the save() method would.
Parameters
depositLocationId The id of the depositlocation, or null if creating a new location.
Definition at line 380 of file ApplicationSettingsTab.java.
{
         String name = null;
         Packager packager = null;
         Depositor depositor = null;
         String username = null;
         String password = null;
         String onBehalfOf = null;
         String repository = null;
         Integer timeout = null;
         String collection = null;
         boolean connectionOk = false;
         Map<String,String> collectionsMap = null;
         if (depositLocationId != null) {
             String[] parts = depositLocationId.split("_");
             Long id = Long.valueOf(parts[1]);
             DepositLocation location = settingRepo.findDepositLocation(id);
             name = location.getName();
             packager = location.getPackager();
             depositor = location.getDepositor();
             username = location.getUsername();
             password = location.getPassword();
             onBehalfOf = location.getOnBehalfOf();
             repository = location.getRepository();
             timeout = location.getTimeout();
             collection = location.getCollection();
 // Don't try to connect on inital load because it could take too long.
 //          try {
 //              collectionsMap = depositor.getCollections(location);
 //              connectionOk = true;
 //
 //              if (collectionsMap == null || collectionsMap.size() == 0)
 //                  validation.addError("collection","The repository is not able to provide a list of collections.");
 //          } catch (DepositException de) {
 //
 //              if (de.isField(FIELD.REPOSITORY)) {
 //                  validation.addError("repository",de.getMessage());
 //              } else if (de.isField(FIELD.AUTHENTICATION)) {
 //                  validation.addError("auth",de.getMessage());
 //              } else {
 //                  validation.addError("general","Unable to communicate with deposit location: "+de.getMessage());
 //              }
 //
 //          } catch (RuntimeException re) {
 //              validation.addError("general","Unable to communicate with deposit location: "+re.getMessage());
 //          }
         }
         List<Packager> packagers = new ArrayList<Packager>( (Collection) Spring.getBeansOfType(Packager.class).values() );
         List<Depositor> depositors = new ArrayList<Depositor>( (Collection) Spring.getBeansOfType(Depositor.class).values() );
         String nav = "settings";
         String subNav = "deposit";
         renderTemplate("SettingTabs/editDepositLocation.include",nav, subNav, packagers, depositors, collectionsMap, connectionOk,
                 // Deposit location
                 depositLocationId, name, packager, depositor, username, password, onBehalfOf, repository, timeout, collection
                 );
     }
static void controllers.settings.ApplicationSettingsTab.removeCustomActionJSON (String actionId) static
Remove an existing custom action value.
Parameters
actionId The id of the action to be removed of the form "action_id"
Definition at line 316 of file ApplicationSettingsTab.java.
{
         try {
             // Delete the old action
             String[] parts = actionId.split("_");
             Long id = Long.valueOf(parts[1]);
             CustomActionDefinition action = settingRepo.findCustomActionDefinition(id);
             action.delete();
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to remove custom action");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         }
     }
static void controllers.settings.ApplicationSettingsTab.removeDepositLocationJSON (String depositLocationId) static
Remove the specified deposit location.
Parameters
depositLocationId The id of the location to be removed.
Definition at line 648 of file ApplicationSettingsTab.java.
References org.tdl.vireo.model.NameFormat.FIRST_LAST.
{
         try {
             // Delete the old template
             String[] parts = depositLocationId.split("_");
             Long id = Long.valueOf(parts[1]);
             DepositLocation location = settingRepo.findDepositLocation(id);
             location.delete();
             Logger.info("%s (%d: %s) has deleted deposit location #%d.\nDeposit Name = '%s'\nDeposit Packager = '%s'\nDeposit Depositor = '%s'\nDeposit Repository = '%s'\nDeposit Timeout = '%s'\nDeposit Username = '%s'\nDeposit On Behalf Of = '%s'\nDeposit Collection = '%s'",
                     context.getPerson().getFormattedName(NameFormat.FIRST_LAST),
                     context.getPerson().getId(),
                     context.getPerson().getEmail(),
                     location.getId(),
                     location.getName(),
                     location.getPackager()==null ? "null" : location.getPackager().getBeanName(),
                     location.getDepositor()==null ? "null" : location.getDepositor().getBeanName(),
                     location.getRepository(),
                     location.getTimeout(),
                     location.getUsername(),
                     location.getOnBehalfOf(),
                     location.getCollection());
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to remove deposit location");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message + "\" }");
         }
     }
static void controllers.settings.ApplicationSettingsTab.reorderCustomActionsJSON (String actionIds) static
Reorder a list of custom actions.
Parameters
actionIds An ordered list of ids in the form: "action_1,action3,action_2"
Definition at line 341 of file ApplicationSettingsTab.java.
{
         try {
             if (actionIds != null && actionIds.trim().length() > 0) {
                 // Save the new order
                 List<CustomActionDefinition> actions = resolveIds(actionIds,CustomActionDefinition.class);
                 saveModelOrder(actions);
             }
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to reorder custom action");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         }
     }
static void controllers.settings.ApplicationSettingsTab.reorderDepositLocationsJSON (String depositLocationIds) static
Reorder the list of deposit locations.
Parameters
depositLocationIds A comma seperated list of deposit location ids.
Definition at line 686 of file ApplicationSettingsTab.java.
{
         try {
             if (depositLocationIds != null && depositLocationIds.trim().length() > 0) {
                 // Save the new order
                 List<DepositLocation> locations = resolveIds(depositLocationIds, DepositLocation.class);
                 saveModelOrder(locations);
             }
             renderJSON("{ \"success\": \"true\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to reorder deposit locations");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \"" + message + "\" }");
         }
     }
static void controllers.settings.ApplicationSettingsTab.saveDepositLocation (String depositLocationId) static
Save the deposit location.
If the basic sanity checks pass we will save the new state. Then we will test the connection against the actual deposit server reporting any errors found.
Parameters
depositLocationId The id of the deposit location being edited, or null if this is a new one being created.
Definition at line 457 of file ApplicationSettingsTab.java.
References org.tdl.vireo.export.DepositException.FIELD.AUTHENTICATION, org.tdl.vireo.model.NameFormat.FIRST_LAST, org.tdl.vireo.model.DepositLocation.getDepositor(), org.tdl.vireo.model.DepositLocation.getName(), org.tdl.vireo.model.DepositLocation.getOnBehalfOf(), org.tdl.vireo.model.DepositLocation.getPackager(), org.tdl.vireo.model.DepositLocation.getTimeout(), org.tdl.vireo.export.DepositException.isField(), and org.tdl.vireo.export.DepositException.FIELD.REPOSITORY.
{
         // Get our paramaters
         String action = params.get("action");
         String name = params.get("name");
         String packagerBeanName = params.get("packager");
         String depositorBeanName = params.get("depositor");
         String username = params.get("username");
         String password = params.get("password");
         String onBehalfOf = params.get("onBehalfOf");
         String repository = params.get("repository");
         String sTimeout = params.get("timeout");
         String collection = params.get("collection");
         // Nullify things
         if (username != null && username.trim().length() == 0)
             username = null;
         if (password != null && password.length() == 0)
             password = null;
         if (onBehalfOf != null && onBehalfOf.trim().length() == 0)
             onBehalfOf = null;
         if (sTimeout != null && sTimeout.trim().length() == 0)
             sTimeout = null;
         // Validation and format conversions
         if (name == null || name.trim().length() == 0)
             validation.addError("name", "A name is required");
         Packager packager = null;
         try {
             packager = (Packager) Spring.getBean(packagerBeanName);
         } catch (RuntimeException re) {
             validation.addError("packager", "The format is invalid.");
         }
         Depositor depositor = null;
         try {
             depositor = (Depositor) Spring.getBean(depositorBeanName);
         } catch (RuntimeException re) {
             validation.addError("depositor", "The protocol is invalid.");
         }
         if (repository == null || repository.trim().length() == 0)
             validation.addError("repository", "The repository location is required");
         Integer timeout = null;
         try {
             timeout = Integer.parseInt(sTimeout);
         } catch (NumberFormatException e) {
             validation.addError("timeout", "The timeout value was invalid");
         }
         // If no errors then try and save location
         DepositLocation location = null;
         if (!validation.hasErrors()) {
             try {
                 // Save the values
                 Boolean created = false;
                 if (depositLocationId != null && depositLocationId.trim().length() > 0) {
                     String[] parts = depositLocationId.split("_");
                     Long id = Long.valueOf(parts[1]);
                     location = settingRepo.findDepositLocation(id);
                 } else {
                     location = settingRepo.createDepositLocation(name);
                     created = true;
                     // Make sure the new location is last on the list.
                     List<DepositLocation> locations = settingRepo.findAllDepositLocations();
                     locations.add(location);
                     saveModelOrder(locations);
                 }
                 // Check if we should update the password. We we display the
                 // password we use blanks. So if it's the same number of blanks
                 // leave the password alone.
                 String originalPassword = location.getPassword();
                 if (originalPassword != null && password != null) {
                     // Convert the original password to all spaces.
                     originalPassword = originalPassword.replaceAll(".", " ");
                     // Sometimes the browser gives us non breaking spaces, switch those out with normal ones.
                     password = password.replaceAll("\u00A0"," ");
                     if (!(originalPassword.length() == password.length() && password.trim().length() == 0)) {
                         location.setPassword(password);
                     }
                 } else {
                     location.setPassword(password);
                 }
                 location.setUsername(username);
                 location.setOnBehalfOf(onBehalfOf);
                 location.setRepository(repository);
                 location.setTimeout(timeout);
                 location.setCollection(collection);
                 location.setPackager(packager);
                 location.setDepositor(depositor);
                 location.setName(name);
                 location.save();
                 Logger.info("%s (%d: %s) has %s deposit location #%d.\nDeposit Name = '%s'\nDeposit Packager = '%s'\nDeposit Depositor = '%s'\nDeposit Repository = '%s'\nDeposit Timeout = '%s'\nDeposit Username = '%s'\nDeposit On Behalf Of = '%s'\nDeposit Collection = '%s'",
                         context.getPerson().getFormattedName(NameFormat.FIRST_LAST),
                         context.getPerson().getId(),
                         context.getPerson().getEmail(),
                         created ? "added" : "edited",
                         location.getId(),
                         location.getName(),
                         location.getPackager()==null ? "null" : location.getPackager().getBeanName(),
                         location.getDepositor()==null ? "null" : location.getDepositor().getBeanName(),
                         location.getRepository(),
                         location.getTimeout(),
                         location.getUsername(),
                         location.getOnBehalfOf(),
                         location.getCollection());
                 depositLocationId = "depositLocation_"+location.getId();
             } catch (PersistenceException pe) {
                 validation.addError("name", "Another deposit location already exists with the name.");
             } catch (RuntimeException re) {
                 Logger.error(re,"Unable to save Deposit Location");
                 validation.addError("general", "Unable to save form because: "+re.getMessage());
             }
         }
         // If there are still no errors, then try and get a list of all collections
         Map<String,String> collectionsMap = new HashMap<String,String>();
         boolean connectionOk = false;
         if (!validation.hasErrors() && location != null) {
             try {
                 collectionsMap = depositor.getCollections(location);
                 if (collectionsMap == null || collectionsMap.size() == 0)
                     validation.addError("collection","The repository is not able to provide a list of collections.");
                 connectionOk = true;
             } catch (DepositException de) {
                 if (de.isField(FIELD.REPOSITORY)) {
                     validation.addError("repository",de.getMessage());
                 } else if (de.isField(FIELD.AUTHENTICATION)) {
                     validation.addError("auth",de.getMessage());
                 } else {
                     validation.addError("general","Unable to communicate with deposit location: "+de.getMessage());
                 }
             } catch (RuntimeException re) {
                 validation.addError("general","Unable to communicate with deposit location: "+re.getMessage());
             }
             // Now at the end do a check to make sure the user has selected a collection url.
             if (!validation.hasErrors() && "depositLocation-save".equals(action) && collection == null) {
                 validation.addError("collection","A collection is required.");
             }
         }
         // IF the user want's let's test a real submission.
         String testDepositId = null;
         if (!validation.hasErrors() && location != null && "depositLocation-test-submit".equals(action)) {
             try {
                 testDepositId = submitTestItem(location);
             } catch (RuntimeException re) {
                 Logger.warn(re,"Unable to submit test item.");
                 validation.addError("general", "Unable to submit test item because: "+re.getMessage());
             }
         }
         List<Packager> packagers = new ArrayList<Packager>( (Collection) Spring.getBeansOfType(Packager.class).values() );
         List<Depositor> depositors = new ArrayList<Depositor>( (Collection) Spring.getBeansOfType(Depositor.class).values() );
         if (depositLocationId != null && depositLocationId.trim().length() == 0)
             depositLocationId = null;
         renderTemplate("SettingTabs/editDepositLocation.include", packagers, depositors, collectionsMap, testDepositId, connectionOk, action,
             // Deposit location
             depositLocationId, name, packager, depositor, username, password, onBehalfOf, repository, timeout, collection);
     }
static void controllers.settings.ApplicationSettingsTab.searchMembers (String query, Integer offset) static
Search the current list of members and generate. This action is designed to be invoked from an AJAX call but does not produce JSON. Instead it returns an HTML snipit that can be used to replace the contents of the Search Members modal dialog box.
Parameters
query The search query to look for new members, or null.
offset The offset into the list of people
Definition at line 717 of file ApplicationSettingsTab.java.
References org.tdl.vireo.model.RoleType.REVIEWER.
{
         if (offset == null || offset < 0)
             offset = 0;
         int limit = SEARCH_MEMBERS_RESULTS_PER_PAGE;
         List<Person> searchResults = personRepo.searchPersons(query, offset, limit);
         List<Person> reviewers = personRepo.findPersonsByRole(RoleType.REVIEWER);
         renderTemplate("SettingTabs/searchMembers.include",query, offset, limit, searchResults, reviewers);
     }
static String controllers.settings.ApplicationSettingsTab.submitTestItem (DepositLocation location) static protected
An internal method to submit a test item to the repository location and check if it works.
Parameters
location The location to deposit too.
Returns
The deposit id of the item submitted.
Definition at line 830 of file ApplicationSettingsTab.java.
References org.tdl.vireo.model.DegreeLevel.MASTERS.
{
         Submission sub = subRepo.createSubmission(context.getPerson());
         try {
             sub.save();
             sub.setStudentFirstName("Test");
             sub.setStudentLastName("Submitter");
             sub.setDocumentTitle("Test Submission");
             sub.setDocumentAbstract("This is a sample submission generated by Vireo to test the repository deposit features.");
             sub.setDocumentKeywords("Test; Vireo; Repository Deposit");
             sub.setDegree("Test Degree");
             sub.setDegreeLevel(DegreeLevel.MASTERS);
             sub.setDepartment("Test Department");
             sub.setCollege("Test College");
             sub.setMajor("Test Major");
             sub.setDocumentType("Test Document Type");
             sub.setGraduationMonth(new Date().getMonth());
             sub.setGraduationYear(new Date().getYear()+1900);
             CommitteeMember member = sub.addCommitteeMember("Test", "Advisor", null).save();
             member.addRole("Chair");
             member.save();
             sub.addCommitteeMember("Test", "Member 1", null).save();
             sub.addCommitteeMember("Test", "Member 2", null).save();
             sub.save();
             depositService.deposit(location, sub, null, true);
             return sub.getDepositId();
         } finally {
             if (sub != null)
                 sub.delete();
         }
     }
static void controllers.settings.ApplicationSettingsTab.updateApplicationSettingsJSON (String field, String value) static
Handle updating the individual values under the application settings tab.
If the field is defined as a boolean, then value should either be an null/empty string to be turned off, otherwise any other value will be interpreted as on.
Parameters
field The field being updated.
value The value of the new field.
Definition at line 123 of file ApplicationSettingsTab.java.
References org.tdl.vireo.model.NameFormat.FIRST_LAST.
{
         try {
             List<String> booleanFields = new ArrayList<String>();
             booleanFields.add(SUBMISSIONS_OPEN);
             booleanFields.add(ALLOW_MULTIPLE_SUBMISSIONS);
             List<String> textFields = new ArrayList<String>();
             textFields.add(CURRENT_SEMESTER);
             textFields.add(GRANTOR);
             textFields.add(SUBMIT_LICENSE_TEXT);
             textFields.add(ORCID_VALIDATION);
             textFields.add(ORCID_AUTHENTICATION);
             textFields.add(PROQUEST_INSTITUTION_CODE);
             textFields.add(PROQUEST_INDEXING);
             textFields.add(PROQUEST_LICENSE_TEXT);
             if (booleanFields.contains(field)) {
                 // This is a boolean field
                 boolean booleanValue = true;
                 if (value == null || value.trim().length() == 0)
                     booleanValue = false;
                 Configuration config = settingRepo.findConfigurationByName(field);
                 if (!booleanValue && config != null)
                     config.delete();
                 else if (booleanValue && config == null)
                     settingRepo.createConfiguration(field, "true").save();
             } else if (textFields.contains(field)) {
                 // This is a free-form text field
                 if (CURRENT_SEMESTER.toString().equals(field) && !isValidCurrentSemester(value)) {
                     throw new IllegalArgumentException("The current semester is invalid, it must be of the form: month year. I.g. 'May 2012'");
                 }
                 String oldValue = null;
                 Configuration config = settingRepo.findConfigurationByName(field);
                 if (config == null)
                     config = settingRepo.createConfiguration(field, value);
                 else {
                     oldValue = config.getValue();
                     config.setValue(value);
                 }
                 config.save();
                 if(SUBMIT_LICENSE_TEXT.equals(field)){
                     Logger.info("%s (%d: %s) has updated license aggreement from '%s' to '%s'.",
                             context.getPerson().getFormattedName(NameFormat.FIRST_LAST),
                             context.getPerson().getId(),
                             context.getPerson().getEmail(),
                             oldValue,
                             value);
                 }
                 if(PROQUEST_LICENSE_TEXT.equals(field)){
                     Logger.info("%s (%d: %s) has updated proquest license aggreement from '%s' to '%s'.",
                             context.getPerson().getFormattedName(NameFormat.FIRST_LAST),
                             context.getPerson().getId(),
                             context.getPerson().getEmail(),
                             oldValue,
                             value);
                 }
             } else if (field.startsWith(DEGREE_CODE_PREFIX)) {
                 // This is a free form degree code.
                 String oldValue = null;
                 Configuration config = settingRepo.findConfigurationByName(field);
                 if (config == null)
                     config = settingRepo.createConfiguration(field, value);
                 else {
                     oldValue = config.getValue();
                     config.setValue(value);
                 }
                 config.save();
             } else {
                 throw new IllegalArgumentException("Unknown field '"+field+"'");
             }
             field = escapeJavaScript(field);
             value = escapeJavaScript(value);
             renderJSON("{ \"success\": \"true\", \"field\": \""+field+"\", \"value\": \""+value+"\" }");
         } catch (IllegalArgumentException iae) {
             String message = escapeJavaScript(iae.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to update application settings");
             String message = escapeJavaScript(re.getMessage());
             renderJSON("{ \"failure\": \"true\", \"message\": \""+message+"\" }");
         }
     }
static void controllers.settings.ApplicationSettingsTab.updateDepositLocationList () static
Return the list of all deposit settings. This is called often after state changes so that we can be sure this list is up-to-date always.
Definition at line 366 of file ApplicationSettingsTab.java.
{
         List<DepositLocation> locations = settingRepo.findAllDepositLocations();
         renderTemplate("SettingTabs/listDepositLocations.include",locations);
     }
static void controllers.settings.ApplicationSettingsTab.updatePersonRole (String personId, int role) static
Modify the person's role. This action is designed to be invoked from an AJAK call but does not produce JSON. Instead it returns a snipit of HTML that can be used to replace the current list of reviewers.
Parameters
personId The id of the person, in the form "person_id"
role The id of the new role
Definition at line 741 of file ApplicationSettingsTab.java.
References org.tdl.vireo.model.NameFormat.FIRST_LAST, and org.tdl.vireo.model.RoleType.REVIEWER.
{
         try {
             RoleType newRole = RoleType.find(role);
             if (newRole.ordinal() > context.getPerson().getRole().ordinal())
                 throw new IllegalArgumentException("Unable to set a user's role to a higher level that the current user.");
             String[] parts = personId.split("_");
             Long id = Long.valueOf(parts[1]);
             Person updated = personRepo.findPerson(id);
             RoleType oldRole = updated.getRole();
             updated.setRole(newRole);
             updated.save();
             Logger.info("%s (%d: %s) has changed %s (%d: %s) role from %s to %s.",
                     context.getPerson().getFormattedName(NameFormat.FIRST_LAST),
                     context.getPerson().getId(),
                     context.getPerson().getEmail(),
                     updated.getFormattedName(NameFormat.FIRST_LAST),
                     updated.getId(),
                     updated.getEmail(),
                     oldRole.name(),
                     newRole.name());
             List<Person> reviewers = personRepo.findPersonsByRole(RoleType.REVIEWER);
             renderTemplate("SettingTabs/listMembers.include",reviewers,updated);
         } catch (RuntimeException re) {
             Logger.error(re,"Unable to update person's role");
             String error = re.getMessage();
             renderTemplate("SettingTabs/listMembers.include",error);
         }
     }
Member Data Documentation
DepositService controllers.settings.ApplicationSettingsTab.depositService = Spring.getBeanOfType(DepositService.class) static
Definition at line 52 of file ApplicationSettingsTab.java.
final int controllers.settings.ApplicationSettingsTab.SEARCH_MEMBERS_RESULTS_PER_PAGE = 5 static
Definition at line 49 of file ApplicationSettingsTab.java.
The documentation for this class was generated from the following file:
app/controllers/settings/ApplicationSettingsTab.java