Vireo: controllers.System Class Reference
controllers.System Class Reference
Classes
class TestSubmissionsJob
Static Public Member Functions
static void controlPanelRedirect ()
static void generalPanel ()
static void jobPanel ()
static void errorPanel ()
static void testEmail (String email)
static void testSubmissions (final int howMany) throws InterruptedException
static void rebuildIndex ()
Static Public Member Functions inherited from controllers.AbstractVireoController
static void injectRepositories ()
static void checkForFirstUser ()
static void handleError (Throwable throwable)
Static Public Attributes
static final String TEST_EMAIL_TEMPLATE = "SYSTEM Email Test"
static Indexer indexer = Spring.getBeanOfType(Indexer.class)
static EmailService emailService = Spring.getBeanOfType(EmailService.class)
static SystemEmailTemplateService templateService = Spring.getBeanOfType(SystemEmailTemplateService.class)
static SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class)
static JobManager jobManager = Spring.getBeanOfType(JobManager.class)
static ErrorLog errorLog = Spring.getBeanOfType(ErrorLog.class)
Static Public Attributes inherited from controllers.AbstractVireoController
static SecurityContext context = Spring.getBeanOfType(SecurityContext.class)
static PersonRepository personRepo = Spring.getBeanOfType(PersonRepository.class)
static SubmissionRepository subRepo = Spring.getBeanOfType(SubmissionRepository.class)
static SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class)
static ProquestVocabularyRepository proquestRepo = Spring.getBeanOfType(ProquestVocabularyRepository.class)
static ErrorLog errorLog = Spring.getBeanOfType(ErrorLog.class)
static StateManager stateManager = Spring.getBeanOfType(StateManager.class)
static Indexer indexer = Spring.getBeanOfType(Indexer.class)
static Searcher searcher = Spring.getBeanOfType(Searcher.class)
static Boolean firstUser = null
Additional Inherited Members
Static Protected Member Functions inherited from controllers.AbstractVireoController
static boolean isEmpty (String value)
static boolean isNotEmpty (String value)
static String escapeJavaScript (String value)
static String URIEncode (String value)
static String toJSON (String[] values)
static String text2html (String value)
static boolean isFieldRequired (FieldConfig field)
Detailed Description
System administrator control panel.
This is a way for administrators to access system information for debugging or testing. It is expected that this class will gain additional features and information feeds in the future.
Author
Scott Phillips
Definition at line 36 of file System.java.
Member Function Documentation
static void controllers.System.controlPanelRedirect () static
Redirect "system/" to "system/general" so it defaults to the general panel.
Definition at line 54 of file System.java.
{
         generalPanel();
     }
static void controllers.System.errorPanel () static
Display recent errors.
Definition at line 173 of file System.java.
{
         List<ErrorReport> reports = errorLog.getRecentErrorReports();
         renderTemplate("System/errorPanel.html",reports);
     }
static void controllers.System.generalPanel () static
Display vital statistic information about vireo and allow access to some administrator features.
Definition at line 63 of file System.java.
References org.tdl.vireo.search.Indexer.getCurrentJobProgress(), org.tdl.vireo.search.Indexer.getCurrentJobTotal(), and org.tdl.vireo.search.Indexer.isJobRunning().
{
         Runtime runtime = Runtime.getRuntime();
         // Java Information
         String javaVersion = java.lang.System.getProperty("java.version");
         String osName = java.lang.System.getProperty("os.name");
         String osArch = java.lang.System.getProperty("os.arch");
         String osVersion = java.lang.System.getProperty("os.version");
         int availableProcessors = runtime.availableProcessors();
         // Runtime Memory Information
         long maximumMemory = runtime.maxMemory() / 1024 / 1024;
         long allocatedMemory = runtime.totalMemory() / 1024 / 1024;
         long freeMemory = runtime.freeMemory() / 1024 / 1024;
         long usedMemory = allocatedMemory - freeMemory / 1024 / 1024;
         // Play Information
         String playMode = Play.mode.name();
         String frameworkId = Play.id;
         Date startedAt = new Date(Play.startedAt);
         String httpAddress = Play.configuration.getProperty("http.address","n/a");
         String httpPort = Play.configuration.getProperty("http.port","n/a");
         String httpPath = Play.configuration.getProperty("http.path","n/a");
         String logLevel = Play.configuration.getProperty("application.log","n/a");
         String db = Play.configuration.getProperty("db","n/a");
         String appPath = Play.applicationPath.getPath();
         String attachmentsPath = appPath + File.separator + Play.configuration.getProperty("attachments.path","n/a");
         String indexPath = appPath + File.separator + Play.configuration.getProperty("index.path","n/a");
         // Mail Information
         String mailMode = Play.configuration.getProperty("mail.smtp","n/a");
         String mailHost = Play.configuration.getProperty("mail.smtp.host","n/a");
         String mailUser = Play.configuration.getProperty("mail.smtp.user","n/a");
         String mailPass = Play.configuration.getProperty("mail.smtp.pass");
         String mailChannel = Play.configuration.getProperty("mail.smtp.channel","n/a");
         String mailFrom = Play.configuration.getProperty("mail.from","n/a");
         String mailReply = Play.configuration.getProperty("mail.replyto","n/a");
         if (mailPass != null) {
             mailPass = mailPass.replaceAll(".", "*");
         } else {
             mailPass = "n/a";
         }
         // Vireo Information
         String vireoVersion = Play.configuration.getProperty("vireo.version","Unknown");
         long personTotal = personRepo.findPersonsTotal();
         long submissionTotal = subRepo.findSubmissionsTotal();
         long actionLogTotal = subRepo.findActionLogsTotal();
         // Index Information
         String indexImpl = indexer.getClass().getSimpleName();
         String indexJob = "n/a";
         if (indexer.isJobRunning()) {
             indexJob = indexer.getCurrentJobLabel();
             float complete = 0;
             if (indexer.getCurrentJobTotal() > 0)
                 complete = (((float) indexer.getCurrentJobProgress()) / indexer.getCurrentJobTotal()) * 100;
             indexJob += String.format(" ( %.3f%% complete )",complete);
         }
         renderTemplate("System/generalPanel.html",
                 // Java Info
                 javaVersion, osName, osArch, osVersion, availableProcessors,
                 // Memory Info
                 maximumMemory, allocatedMemory, freeMemory, usedMemory,
                 // Play Info
                 playMode, frameworkId, httpAddress, httpPort, httpPath, startedAt, appPath, logLevel, db, attachmentsPath, indexPath,
                 // Mail Info
                 mailMode, mailHost, mailUser, mailPass, mailChannel, mailFrom, mailReply,
                 // Vireo Info
                 vireoVersion, personTotal, submissionTotal, actionLogTotal,
                 // Index Information
                 indexImpl, indexJob
                 );
     }
static void controllers.System.jobPanel () static
Display and manage background jobs.
Definition at line 156 of file System.java.
{
         // Job data
         List<JobMetadata> jobs = jobManager.findAllJobs();
         // Status Definitions
         for (JobStatus status : JobStatus.values()) {
             renderArgs.put(status.name(), status);
         }
         renderTemplate("System/jobPanel.html",jobs);
     }
static void controllers.System.rebuildIndex () static
Rebuild the index, either destructively or in place.
Definition at line 235 of file System.java.
{
         if (params.get("submit_rebuild") != null) {
             indexer.rebuild(false);
         } if (params.get("submit_deleteAndRebuild") != null) {
             indexer.deleteAndRebuild(false);
         }
         // Redirect back to the control pannel.
         generalPanel();
     }
static void controllers.System.testEmail (String email) static
Send a test email to the provided address.
Parameters
email The email address to send the test.
Definition at line 187 of file System.java.
{
         templateService.generateAllSystemEmailTemplates();
         EmailTemplate template = settingRepo.findEmailTemplateByName(TEST_EMAIL_TEMPLATE);
         VireoEmail vireoEmail = emailService.createEmail();
         vireoEmail.addTo(email);
         vireoEmail.setTemplate(template);
         emailService.sendEmail(vireoEmail,true);
         render();
     }
static void controllers.System.testSubmissions (final int howMany) throws InterruptedException static
Generate test submissions.
Parameters
howMany How many test submissions to generate.
Exceptions
InterruptedException
Definition at line 209 of file System.java.
{
         if (!Play.mode.isDev())
             error("Generating test submissions is only available in a DEV mode.");
         if (!"test".equals(Play.id))
             error("Generating test submissions is only available when runing under the '%test' framework id.");
         if (howMany < 1)
             error();
         long start = java.lang.System.currentTimeMillis();
         Job job = new TestSubmissionsJob(indexer,howMany);
         await(job.now());
         long stop = java.lang.System.currentTimeMillis();
         long totalTime = stop - start;
         long timePerSubmission = totalTime / howMany;
         renderTemplate("System/testSubmission.html", howMany, totalTime, timePerSubmission);
     }
Member Data Documentation
EmailService controllers.System.emailService = Spring.getBeanOfType(EmailService.class) static
Definition at line 43 of file System.java.
ErrorLog controllers.System.errorLog = Spring.getBeanOfType(ErrorLog.class) static
Definition at line 47 of file System.java.
Indexer controllers.System.indexer = Spring.getBeanOfType(Indexer.class) static
Definition at line 42 of file System.java.
JobManager controllers.System.jobManager = Spring.getBeanOfType(JobManager.class) static
Definition at line 46 of file System.java.
SettingsRepository controllers.System.settingRepo = Spring.getBeanOfType(SettingsRepository.class) static
Definition at line 45 of file System.java.
SystemEmailTemplateService controllers.System.templateService = Spring.getBeanOfType(SystemEmailTemplateService.class) static
Definition at line 44 of file System.java.
final String controllers.System.TEST_EMAIL_TEMPLATE = "SYSTEM Email Test" static
Definition at line 39 of file System.java.
The documentation for this class was generated from the following file:
app/controllers/System.java