Vireo: controllers.submit.License Class Reference
controllers.submit.License Class Reference
Static Public Member Functions
static void license (Long subId)
static boolean verify (Submission sub)
Static Public Member Functions inherited from controllers.AbstractVireoController
static void injectRepositories ()
static void checkForFirstUser ()
static void handleError (Throwable throwable)
Static Protected Member Functions
static void recordDisagreement (Submission sub, String licenseName, Boolean primaryAgreement)
static void recordAgreement (Submission sub, String licenseText, String licenseName, Boolean primaryAgreement)
static String stampLicense (String licenseText, Date agreementDate)
Static Protected Member Functions inherited from controllers.submit.AbstractSubmitStep
static Submission getSubmission ()
static boolean isFieldEnabled (FieldConfig field)
static boolean isFieldRequired (FieldConfig field)
Static Protected Member Functions inherited from controllers.AbstractVireoController
static boolean isEmpty (String value)
static boolean isNotEmpty (String value)
static String escapeJavaScript (String value)
static String toJSON (String[] values)
static String text2html (String value)
static boolean isFieldRequired (FieldConfig field)
Additional Inherited Members
Static Public Attributes inherited from controllers.AbstractVireoController
static SecurityContext context = Spring.getBeanOfType(SecurityContext.class)
static PersonRepository personRepo = Spring.getBeanOfType(PersonRepository.class)
static SubmissionRepository subRepo = Spring.getBeanOfType(SubmissionRepository.class)
static SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class)
static ProquestVocabularyRepository proquestRepo = Spring.getBeanOfType(ProquestVocabularyRepository.class)
static ErrorLog errorLog = Spring.getBeanOfType(ErrorLog.class)
static StateManager stateManager = Spring.getBeanOfType(StateManager.class)
static Indexer indexer = Spring.getBeanOfType(Indexer.class)
static Searcher searcher = Spring.getBeanOfType(Searcher.class)
static Boolean firstUser = null
Static Package Functions inherited from controllers.submit.AbstractSubmitStep
static void beforeSubmit ()
Detailed Description
The second step of the license process where the user must accept the provided license.
Author
Scott Phillips
Bill Ingram
Dan Galewsky
Definition at line 28 of file License.java.
Member Function Documentation
static void controllers.submit.License.license (Long subId) static
The second step of the submission process. Where the user must accept the provided license.
After accepting the license the text is stamped with the current user and agreement date. Then both the agreement date and stamped license text are saved to the submission.
Parameters
subId The id of the submission.
Definition at line 41 of file License.java.
References controllers.submit.AbstractSubmitStep.getSubmission(), org.tdl.vireo.model.Submission.getUMIRelease(), controllers.submit.License.recordAgreement(), controllers.submit.License.recordDisagreement(), controllers.AbstractVireoController.text2html(), and controllers.submit.License.verify().
Referenced by controllers.submit.License.verify().
{
         Submission sub = getSubmission();
         // Get the form data.
         String licenseAgreement = params.get("licenseAgreement");
         String licenseText = settingRepo.getConfigValue(SUBMIT_LICENSE_TEXT);
         String proquestAgreement = params.get("proquestAgreement");
         String proquestText = settingRepo.getConfigValue(PROQUEST_LICENSE_TEXT);
         // If it's blank, make it null.
         if (licenseAgreement != null && licenseAgreement.trim().length() == 0)
             licenseAgreement = null;
         if (proquestAgreement != null && proquestAgreement.trim().length() == 0)
             proquestAgreement = null;
         if ("license".equals(params.get("step"))) {
             // Save the state
             if (licenseAgreement == null) {
                 recordDisagreement(sub, "LICENSE", true);
             } else {
                 recordAgreement(sub, licenseText, "LICENSE", true);
             }
             if(proquestAgreement == null) {
                 recordDisagreement(sub, "PROQUEST_LICENSE", false);
                 sub.setUMIRelease(false);
             } else {
                 recordAgreement(sub, proquestText,"PROQUEST_LICENSE", false);
                 sub.setUMIRelease(true);
             }
             sub.save();
         } else {
             // load the state
             licenseAgreement = sub.getLicenseAgreementDate() != null ? "true" : null;
             proquestAgreement = sub.getUMIRelease() != null && sub.getUMIRelease() ? "true" : null;
         }
         // Verify the form if we are submitting or if jumping from the confirm step.
         if ("license".equals(params.get("step")) ||
             "confirm".equals(flash.get("from-step"))) {
             verify(sub);
         }
         if (params.get("submit_next") != null && !validation.hasErrors()) {
             // Display the license -- passing along the submission id
             DocumentInfo.documentInfo(subId);
         }
         // Format the license text for display
         licenseText = text2html(licenseText);
         proquestText = text2html(proquestText);
         renderTemplate("Submit/license.html",subId,licenseText,licenseAgreement,proquestText,proquestAgreement);
     }
static void controllers.submit.License.recordAgreement (Submission sub, String licenseText, String licenseName, Boolean primaryAgreement) static protected
Record that the user has agreed a license. We save the date, and the current license text.
Parameters
sub The submission.
licenseText The license text agreed to.
licenseName The string to name the file
primaryAgreement A boolean to designate if this the primary license to set the License Agreement Date on the submission. There must always be one license that is the primary license if you don't want the License Agreement Date to be null.
Definition at line 191 of file License.java.
References org.tdl.vireo.model.Submission.getAttachments(), org.tdl.vireo.model.AttachmentType.LICENSE, and controllers.submit.License.stampLicense().
Referenced by controllers.submit.License.license().
{
         Date agreementDate = new Date();
         // Set submission agreement date
         if (primaryAgreement)
             sub.setLicenseAgreementDate(agreementDate);
         licenseName += ".txt";
         // Check if another license has been selected been saved.
         for (Attachment attachment : sub.getAttachments()) {
             if (attachment.getType() == AttachmentType.LICENSE && licenseName.equals(attachment.getName())) {
                 // Remove the old license, and save the new one.
                 attachment.delete();
                 break;
             }
         }
         licenseText = stampLicense(licenseText,agreementDate);
         // Save the text that the student agreed too.
         try {
             sub.addAttachment(licenseText.getBytes(), licenseName, AttachmentType.LICENSE).save();
         } catch (IOException ioe) {
             throw new RuntimeException("Unable to save license aggreement.",ioe);
         }
     }
static void controllers.submit.License.recordDisagreement (Submission sub, String licenseName, Boolean primaryAgreement) static protected
Record that the user has disagreed with a license. We'll allow the user to change their mind and remove their previous agreement however we'll still count that as an error.
Parameters
sub The submission
licenseName The string to name the file
primaryAgreement A boolean to designate if this the primary license to remove the License Agreement Date on the submission. There must always be one license that is the primary license if you don't want the License Agreement Date to be null.
Definition at line 159 of file License.java.
References org.tdl.vireo.model.Submission.getAttachments().
Referenced by controllers.submit.License.license().
{
         // Remove the submission agreement date
         if (primaryAgreement)
             sub.setLicenseAgreementDate(null);
         licenseName += ".txt";
         // Remove any license text
         for (Attachment attachment : sub.getAttachments()) {
             if (attachment.getType() == AttachmentType.LICENSE && licenseName.equals(attachment.getName())) {
                 attachment.delete();
                 break;
             }
         }
     }
static String controllers.submit.License.stampLicense (String licenseText, Date agreementDate) static protected
Stamp the license with who is accepting the license and the current date. This way this information will be stored directly with the license text.
Parameters
licenseText The license text.
agreementDate The exact date of agreement.
Returns
The stamped license text
Definition at line 230 of file License.java.
References org.tdl.vireo.model.NameFormat.FIRST_LAST.
Referenced by controllers.submit.License.recordAgreement().
{
         SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy 'at' hh:mm a");
         Person submitter = context.getPerson();
         licenseText += "\n\n--------------------------------------------------------------------------\n";
         licenseText += "The license above was accepted by "+submitter.getFormattedName(NameFormat.FIRST_LAST)+" on "+formatter.format(agreementDate)+"\n";
         return licenseText;
     }
static boolean controllers.submit.License.verify (Submission sub) static
Verify the license agreement has been accepted.
Parameters
sub The submission to verify.
Returns
True if no errors were found, otherwise false.
Definition at line 107 of file License.java.
References controllers.submit.AbstractSubmitStep.isFieldRequired(), org.tdl.vireo.model.AttachmentType.LICENSE, and controllers.submit.License.license().
Referenced by controllers.submit.Confirm.confirm(), and controllers.submit.License.license().
{
         if (isFieldRequired(LICENSE_AGREEMENT)) {
             List<Attachment> licenses = sub.getAttachmentsByType(AttachmentType.LICENSE);
             boolean hasLicense = false;
             for(Attachment license : licenses) {
                 if ("LICENSE.txt".equals(license.getName()))
                     hasLicense = true;
             }
             if (hasLicense == false) {
                 validation.addError("licenseAgreement","You must agree to the license agreement before continuing");
             }
         } // isRequired
         if (isFieldRequired(UMI_RELEASE)) {
             List<Attachment> licenses = sub.getAttachmentsByType(AttachmentType.LICENSE);
             boolean hasLicense = false;
             for(Attachment license : licenses) {
                 if ("PROQUEST_LICENSE.txt".equals(license.getName()))
                     hasLicense = true;
             }
             if (hasLicense == false) {
                 validation.addError("proquestAgreement","You must agree to the ProQuest license agreement before continuing");
             }
         }
         if(validation.hasErrors()) {
             return false;
         }
         return true;
     }
The documentation for this class was generated from the following file:
app/controllers/submit/License.java