Vireo: org.tdl.vireo.services.Utilities Class Reference
org.tdl.vireo.services.Utilities Class Reference
Static Public Member Functions
static String scrubControl (String input)
static String scrubControl (String input, String replace)
static boolean validateOrcidFormat (String orcid)
static String formatOrcidAsDashedId (String unformattedOrcid)
static boolean verifyOrcid (String orcid)
static boolean verifyOrcid (String orcid, String firstName, String lastName)
static Element singleXPath (Document doc, String xpath) throws JDOMException
static Element singleXPath (Document doc, String xpath, List< Namespace > namespaces) throws JDOMException
static boolean validateEmailAddress (String email, Validation validation)
static List< String > processEmailDesigneeArray (String[] designees, Submission sub)
static boolean validateEmailAddress (String email)
static String insertPeriodically (String text, String insert, int period)
Static Private Attributes
static SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class)
static final String[] CONTROL_RANGES
static final String ORCID_API = "http://pub.orcid.org/#/orcid-bio"
static final Namespace ORCIDns = Namespace.getNamespace("orcid", "http://www.orcid.org/ns/orcid")
Detailed Description
A catch-all class for various Vireo utilities
Author
Alexey Maslov
James Creel (http://www.jamescreel.net)
Definition at line 33 of file Utilities.java.
Member Function Documentation
static String org.tdl.vireo.services.Utilities.formatOrcidAsDashedId (String unformattedOrcid) static
Vireo expects an ORCiD to be in the form "xxxx-xxxx-xxxx-xxxy", where x is numeric and y can be numeric or X. Sometimes you might receive an ORCiD as a URL such as "http://www.orcid.org/xxxx-xxxx-xxxx-xxxy", or without dashes. This function attempts to format a given string into the format Vireo would prefer.
Parameters
unformattedOrcid - An orcid as a string in various formats.
Returns
formattedOrcid - An orcid formatted as just an id with dashes. *
Definition at line 96 of file Utilities.java.
References org.tdl.vireo.services.Utilities.insertPeriodically(), and org.tdl.vireo.services.Utilities.validateOrcidFormat().
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), controllers.submit.PersonalInfo.personalInfo(), and controllers.submit.PersonalInfo.verify().
{
         String formattedOrcid = unformattedOrcid.toUpperCase();
         formattedOrcid = formattedOrcid.replaceAll("(HTTPS|HTTP|WWW|ORCID|ORG|COM|NET|[/:.\\s])","");
         if (validateOrcidFormat(formattedOrcid)) {
             return formattedOrcid;
         } else if (formattedOrcid.matches("[0-9]{15}[0-9X]")) {
             formattedOrcid = insertPeriodically(formattedOrcid, "-", 4);
             if(validateOrcidFormat(formattedOrcid))
                 return formattedOrcid;
             else
                 return unformattedOrcid;
         } else {
             return unformattedOrcid;
         }
     }
static String org.tdl.vireo.services.Utilities.insertPeriodically (String text, String insert, int period) static
A helper method to insert a specific character every X characters in a string.
Definition at line 330 of file Utilities.java.
Referenced by org.tdl.vireo.services.Utilities.formatOrcidAsDashedId().
         {
             StringBuilder builder = new StringBuilder(
                  text.length() + insert.length() * (text.length()/period)+1);
             int index = 0;
             String prefix = "";
             while (index < text.length())
             {
                 // Don't put the insert in the very first iteration.
                 // This is easier than appending it *after* each substring
                 builder.append(prefix);
                 prefix = insert;
                 builder.append(text.substring(index,
                     Math.min(index + period, text.length())));
                 index += period;
             }
             return builder.toString();
         }
static List<String> org.tdl.vireo.services.Utilities.processEmailDesigneeArray (String[] designees, Submission sub) static
Helper function to take an array of strings as (supplied from parameters in a form request with an autocomplete email field) These strings may be email addresses, RecipientType enum names, or AdminGroup names. Process it into an actual list of strings that are proper email addresses.
Parameters
designee_string_array - the heterogeneous string array of email addresses, RecipientTypes, and AdminGroups
Returns
- a list of strings that are proper email addresses
Definition at line 257 of file Utilities.java.
References org.tdl.vireo.model.SettingsRepository.findAllAdministrativeGroups(), org.tdl.vireo.model.EmailGroup.getEmails(), and org.tdl.vireo.services.Utilities.settingRepo.
     {
         List<String> addresses = new ArrayList<String>();
         for(String designee: designees) {
             if(designee.trim().length() != 0) {
                 RecipientType recipientType = null;
                 for(RecipientType oneRecipientType : RecipientType.values())
                 {
                     if(oneRecipientType.name().equals(designee.trim()))
                     {
                         recipientType = RecipientType.valueOf(designee.trim());
                         break;
                     }
                 }
                 if(recipientType != null) {
                     // this will work for all recipients except ones that are in Administrative Groups.
                     List<String> recipientEmailAddresses = EmailByRecipientType.getRecipients(sub, recipientType, null);
                     for(String recipientEmailAddress : recipientEmailAddresses)
                         addresses.add(recipientEmailAddress);
                 } else {
                     AdministrativeGroup admingroup = null;
                     for(AdministrativeGroup oneAdmingroup : settingRepo.findAllAdministrativeGroups())
                     {
                         if(oneAdmingroup.getName().equals(designee.trim()))
{
                             admingroup = oneAdmingroup;
                             break;
                         }
                     }
                     //if adminGroup is still null then the recipient is an arbitrary email address
                     if(admingroup == null) {
                         addresses.add(designee.trim());
                     } else {
                         for(String emailAddr : admingroup.getEmails().values()) {
                             addresses.add(emailAddr);
                         }
                     }
                 }
             }
         }
         return addresses;
     }
static String org.tdl.vireo.services.Utilities.scrubControl (String input) static
Scrub UNICODE control characters out of the provided string, deleteing them
Parameters
input
replace
Returns
Definition at line 54 of file Utilities.java.
{
         return scrubControl(input, "");
     }
static String org.tdl.vireo.services.Utilities.scrubControl (String input, String replace) static
Scrub UNICODE control characters out of the provided string, replacing them with the specified string
Parameters
input
replace
Returns
Definition at line 64 of file Utilities.java.
References org.tdl.vireo.services.Utilities.CONTROL_RANGES.
{
         if (input == null)
             return null;
         if ("".equals(input))
             return "";
         return input.replaceAll("[" + CONTROL_RANGES[0] + CONTROL_RANGES[1] +
                 CONTROL_RANGES[2] + CONTROL_RANGES[3] + CONTROL_RANGES[4] + "]", replace);
     }
static Element org.tdl.vireo.services.Utilities.singleXPath (Document doc, String xpath) throws JDOMException static
Utility method to execute an XPath expression and return back a single result
Parameters
doc a JDOM document that the XPath is being executed on
xpath an XPath expression encoded as a string
Returns
a JDOM element matching the query or null
Exceptions
JDOMException
Definition at line 210 of file Utilities.java.
Referenced by org.tdl.vireo.services.Utilities.verifyOrcid().
     {
         return singleXPath(doc, xpath, null);
     }
static Element org.tdl.vireo.services.Utilities.singleXPath (Document doc, String xpath, List< Namespace > namespaces) throws JDOMException static
Definition at line 215 of file Utilities.java.
     {
         XPath xp = XPath.newInstance(xpath);
         if (namespaces != null) {
             for (Namespace ns : namespaces)
                 xp.addNamespace(ns);
         }
         List<Element> results = xp.selectNodes(doc);
         if (results == null || results.size() == 0 || !(results.get(0) instanceof Element))
             return null;
         else
             return results.get(0);
     }
static boolean org.tdl.vireo.services.Utilities.validateEmailAddress (String email, Validation validation) static
Helper function to validate a single email address as a String
Parameters
email - the String of the email address to validate
validation - Play validation object of the calling controller that wants an email validated
Returns
- true or false if email address is valid
Definition at line 238 of file Utilities.java.
Referenced by controllers.settings.ConfigurableSettingsTab.createEmailsJsonAndAddToMap(), and controllers.settings.EmailSettingsTab.updateEmailSettingsJSON().
{
         try {
             new InternetAddress(email).validate();
         } catch (AddressException ae) {
             validation.addError("email", "The email provided is invalid.["+email+"]");
             return false;
         }
         return true;
     }
static boolean org.tdl.vireo.services.Utilities.validateEmailAddress (String email) static
Definition at line 318 of file Utilities.java.
{
         try {
             new InternetAddress(email).validate();
         } catch (AddressException ae) {
             return false;
         }
         return true;
     }
static boolean org.tdl.vireo.services.Utilities.validateOrcidFormat (String orcid) static
Vireo expects an ORCiD to be in the form "xxxx-xxxx-xxxx-xxxy", where x is numeric and y can be numeric or X. This function will determine is a give string is in the expected format.
Parameters
orcid A string that should be an ORCiD.
Returns
true if the string is in the proper format.
Definition at line 82 of file Utilities.java.
Referenced by org.tdl.vireo.services.Utilities.formatOrcidAsDashedId(), controllers.submit.PersonalInfo.personalInfo(), controllers.ViewTab.updateJSON(), and controllers.submit.PersonalInfo.verify().
{
         String pattern = "[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]";
         return orcid.matches(pattern);
     }
static boolean org.tdl.vireo.services.Utilities.verifyOrcid (String orcid) static
Given an ORCID identifier, this function will ping the ORCID public API and return true if a user is found.
Parameters
orcid id in standard ORCID form "xxxx-xxxx-xxxx-xxxx"
Returns
true if a user is found matching this id, false in all other cases
Definition at line 119 of file Utilities.java.
Referenced by controllers.submit.PersonalInfo.personalInfo(), controllers.ViewTab.updateJSON(), and controllers.Authentication.updateProfile().
{
         return verifyOrcid(orcid, null, null);
     }
static boolean org.tdl.vireo.services.Utilities.verifyOrcid (String orcid, String firstName, String lastName) static
Given an ORCID identifier, this function will ping the ORCID public API and return true if a user is found that matches the provided name and id combination.
Parameters
orcid id in standard ORCID form "xxxx-xxxx-xxxx-xxxx"
Returns
true if a user is found matching this id and name, false in all other cases
Definition at line 129 of file Utilities.java.
References org.tdl.vireo.services.Utilities.ORCID_API, org.tdl.vireo.services.Utilities.ORCIDns, and org.tdl.vireo.services.Utilities.singleXPath().
{
         try {
             URL orcidURL = new URL(ORCID_API.replace("#", orcid));
             SAXBuilder builder = new SAXBuilder();
             Document doc = builder.build(orcidURL);
             List<Namespace> ns = new ArrayList<Namespace>();
             ns.add(ORCIDns);
             // Basic sanity check on the document itself
             if (singleXPath(doc, "/orcid:orcid-message", ns) == null) {
                 Logger.warn("Failed to get an ORCID message");
                 return false;
             }
             // Check for the error (orcid not found) message
             if (singleXPath(doc, "//orcid:error-desc", ns) != null)
             {
                 Logger.info("Invalid ORCID specified");
                 return false;
             }
             // Validate the name
             Element personalDetails = singleXPath(doc, "//orcid:personal-details", ns);
             if (personalDetails != null) {
                 // If we are not actually checking the name, we are done
                 if (firstName == null || lastName == null) {
                     return true;
                 }
                 // Otherwise, do the comparison
                 /* <personal-details>
                     <given-names>Alexey</given-names>
                     <family-name>Maslov</family-name>
                 </personal-details> */
                 else {
                     Element orcidFirstName = personalDetails.getChild("given-names", ORCIDns);
                     Element orcidLastName = personalDetails.getChild("family-name", ORCIDns);
                     if (orcidFirstName == null || orcidLastName == null) {
                         Logger.warn("ORCID response had missing names");
                         return false;
                     }
                     else if (!firstName.equals(orcidFirstName.getTextNormalize()) ||
                             !lastName.equals(orcidLastName.getTextNormalize())) {
                         Logger.warn("ORCID response had wrong name. Expected " + firstName + " " + lastName + ", but got " +
                             orcidFirstName.getTextNormalize() + " " + orcidLastName.getTextNormalize() + ".");
                         return false;
                     }
                     // Anything that's made it through the gauntlet, should be fine
                     return true;
                 }
             }
         } catch (MalformedURLException muex) {
             Logger.warn("URL error occured while validating ORCID: " + muex.getMessage());
             //muex.printStackTrace();
             return false;
         } catch (JDOMException jdex) {
             Logger.warn("JDOM error occured while validating ORCID: " + jdex.getMessage());
             //jdex.printStackTrace();
             return false;
         } catch (IOException ioex) {
             Logger.warn("IO error occured while validating ORCID: " + ioex.getMessage());
             //ioex.printStackTrace();
             return false;
         }
         return false;
     }
Member Data Documentation
final String [] org.tdl.vireo.services.Utilities.CONTROL_RANGES static private
Initial value:
= {
        "\u0000-\u0009",
        "\u000B-\u000C",
        "\u000E-\u001F",
        "\u007F",
        "\u0080-\u009F"
    }
Definition at line 37 of file Utilities.java.
Referenced by org.tdl.vireo.services.Utilities.scrubControl().
final String org.tdl.vireo.services.Utilities.ORCID_API = "http://pub.orcid.org/#/orcid-bio" static private
Definition at line 45 of file Utilities.java.
Referenced by org.tdl.vireo.services.Utilities.verifyOrcid().
final Namespace org.tdl.vireo.services.Utilities.ORCIDns = Namespace.getNamespace("orcid", "http://www.orcid.org/ns/orcid") static private
Definition at line 46 of file Utilities.java.
Referenced by org.tdl.vireo.services.Utilities.verifyOrcid().
SettingsRepository org.tdl.vireo.services.Utilities.settingRepo = Spring.getBeanOfType(SettingsRepository.class) static private
Definition at line 35 of file Utilities.java.
Referenced by org.tdl.vireo.services.Utilities.processEmailDesigneeArray().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/services/Utilities.java