Vireo: org.tdl.vireo.export.impl.FilePackagerImpl Class Reference
org.tdl.vireo.export.impl.FilePackagerImpl Class Reference
Classes
class FilePackage
Public Member Functions
void setAttachmentTypeNames (LinkedHashMap< String, Properties > attachmentTypeNames)
void setEntryName (String entryName)
void setPackageType (String packageType)
String getExportServiceBeanName ()
ExportPackage generatePackage (Submission submission)
Public Member Functions inherited from org.tdl.vireo.export.impl.AbstractPackagerImpl
String getBeanName ()
void setBeanName (String beanName)
String getDisplayName ()
void setDisplayName (String displayName)
Public Attributes
List< AttachmentType > attachmentTypes = new ArrayList<AttachmentType>()
LinkedHashMap< String, Properties > attachmentAttributes = new LinkedHashMap<String, Properties>()
String entryName
String packageType = "dir"
Public Attributes inherited from org.tdl.vireo.export.impl.AbstractPackagerImpl
String beanName
String displayName
Detailed Description
Generic packager that uses a the standard play templating system to generate manifests for packages. Each packaged produced will consist of a manifest file, along with a series of files. This packaged is ziped together into a single bundle ready for deposit.
The values that define what format, which files, etc, are all injected by spring. This allows for many different package formats to be created by just adding a new spring bean definition. See each of the injection methods below for a description of the various injectable settings.
Author
Scott Phillips
Micah Cooper
Jeremy Huff
Gad Krumholz
Definition at line 49 of file FilePackagerImpl.java.
Member Function Documentation
ExportPackage org.tdl.vireo.export.impl.FilePackagerImpl.generatePackage (Submission submission)
Generate a new package for this submission.
The package returned will file system resources so it is very important that any caller who constructs a package also calls delete() to free those resources used.
Parameters
submission The submission
Returns
A package
Implements org.tdl.vireo.export.Packager.
Definition at line 110 of file FilePackagerImpl.java.
References org.tdl.vireo.model.AttachmentType.ACTIONLOG, org.tdl.vireo.export.impl.FilePackagerImpl.attachmentAttributes, org.tdl.vireo.export.impl.FilePackagerImpl.attachmentTypes, org.tdl.vireo.export.impl.FilePackagerImpl.entryName, org.tdl.vireo.model.AbstractModel.getId(), and org.tdl.vireo.export.impl.FilePackagerImpl.packageType.
{
         if (attachmentTypes.size() == 0 ) {
             throw new IllegalArgumentException("Unable to generate package because not attachment types have been defined.");
         }
         // Check that we have everything that we need.
         if (submission == null || submission.getId() == null)
             throw new IllegalArgumentException("Unable to generate a package because the submission is null, or has not been persisted.");
         try {
             //Set String replacement parameters
             Map<String, String> parameters = new HashMap<String, String>();
             parameters = StringVariableReplacement.setParameters(submission);
             //Customize Entry Name
             String entryNameTemplate = entryName;
             String customEntryName = StringVariableReplacement.applyParameterSubstitution(entryName, parameters);
             File pkg = null;
             List<Attachment> actionLogAttachments = new ArrayList<Attachment>();
             //Check the package type set in the spring configuration
             if(packageType.equals("zip")) {
                 pkg = File.createTempFile("template-export-", ".zip");
                 FileOutputStream fos = new FileOutputStream(pkg);
                 ZipOutputStream zos = new ZipOutputStream(fos);
                 byte[] buf = new byte[1024];
                 int len;
                 // Add all the attachments
                 List<Attachment> attachments = submission.getAttachments();
                 List<Attachment> actionLogs = submission.getAttachmentsByType(AttachmentType.ACTIONLOG);
                 // add them to this list to delete the temp files later
                 actionLogAttachments.addAll(actionLogs);
                 // add them to this list to add them to export
                 attachments.addAll(actionLogs);
                 for(Attachment attachment : attachments)
                 {
                     // Do we include this type?
                     if (!attachmentTypes.contains(attachment.getType()))
                         continue;
                     /* The string substitution only works on items we can retrieve from the submission
                      *      so we have to get the file name for each attachment here in the attachment loop.
                      */
                     String shortFileName = attachment.getName().replaceAll("."+FilenameUtils.getExtension(attachment.getName()), "");
                     String fileName = attachment.getName();
                     //Attachment Name Customization
                     if(attachmentAttributes.get(attachment.getType().name()).get("customName")!=null) {
                         fileName = attachmentAttributes.get(attachment.getType().name()).get("customName")+"."+FilenameUtils.getExtension(attachment.getName());
                         fileName = fileName.replace("{FILE_NAME}", shortFileName);
                         fileName = StringVariableReplacement.applyParameterSubstitution(fileName, parameters);
                     }
                     //Check fir custom directory structure set in spring
                     File exportFile = null;
                     Boolean hasDir = false;
                     if(attachmentAttributes.get(attachment.getType().name()).get("directory")!=null) {
                         String dirName = (String) attachmentAttributes.get(attachment.getType().name()).get("directory");
                         dirName = dirName.replace("{FILE_NAME}", shortFileName);
                         dirName = StringVariableReplacement.applyParameterSubstitution(dirName, parameters);
                         exportFile = new File(dirName,fileName);
                         fileName = dirName + fileName;
                         hasDir = true;
                     } else {
                         exportFile = new File(fileName);
                     }
                     FileUtils.copyFile(
                             attachment.getFile(),
                             exportFile
                             );
                     ZipEntry ze = new ZipEntry(fileName);
                     zos.putNextEntry(ze);
                     FileInputStream in = new FileInputStream(exportFile);
                     while ((len = in.read(buf)) > 0) {
                         zos.write(buf, 0, len);
                     }
                     in.close();
                     zos.closeEntry();
                     if(hasDir) {
                         FileUtils.deleteDirectory(exportFile.getParentFile());
                     } else {
                         exportFile.delete();
                     }
                 }
                 zos.close();
                 fos.close();
             } else {
                 pkg = File.createTempFile("template-export-", ".dir");
                 // The package has more than one file, so export as a directory.
                 pkg.delete();
                 pkg.mkdir();
                 // Add all the attachments
                 List<Attachment> attachments = submission.getAttachments();
                 List<Attachment> actionLogs = submission.getAttachmentsByType(AttachmentType.ACTIONLOG);
                 // add them to this list to delete the temp files later
                 actionLogAttachments.addAll(actionLogs);
                 // add them to this list to add them to export
                 attachments.addAll(actionLogs);
                 for(Attachment attachment : attachments)
                 {
                     // Do we include this type?
                     if (!attachmentTypes.contains(attachment.getType()))
                         continue;
                     /* The string substitution only works on items we can retrieve from the submission
                      *      so we have to get the file name for each attachment here in the attachment loop.
                      */
                     String shortFileName = attachment.getName().replaceAll("."+FilenameUtils.getExtension(attachment.getName()), "");
                     String fileName = attachment.getName();
                     //Customize Attachment Name
                     if(attachmentAttributes.get(attachment.getType().name()).get("customName")!=null) {
                         fileName = attachmentAttributes.get(attachment.getType().name()).get("customName")+"."+FilenameUtils.getExtension(attachment.getName());
                         fileName = fileName.replace("{FILE_NAME}", shortFileName);
                         fileName = StringVariableReplacement.applyParameterSubstitution(fileName, parameters);
                     }
                     //Check for Custom Directory Structure.
                     String pkgPath = pkg.getPath();
                     if(attachmentAttributes.get(attachment.getType().name()).get("directory")!=null) {
                         String dirName = (String) attachmentAttributes.get(attachment.getType().name()).get("directory");
                         dirName = dirName.replace("{FILE_NAME}", shortFileName);
                         dirName = StringVariableReplacement.applyParameterSubstitution(dirName, parameters);
                         pkgPath = pkgPath + File.separator + dirName;
                     }
                     File exportFile = new File(pkgPath, fileName);
                     FileUtils.copyFile(
                         attachment.getFile(),
                         exportFile
                         );
                 }//End for loop
             }
             this.setEntryName(entryNameTemplate);
             // Create the actual package!
             return new FilePackage(submission, pkg, customEntryName, actionLogAttachments);
         } catch (IOException ioe) {
             throw new RuntimeException("Unable to generate package",ioe);
         }
     }
String org.tdl.vireo.export.impl.FilePackagerImpl.getExportServiceBeanName ()
Returns
The technical spring bean name of this packager's ExportService implementation.
Implements org.tdl.vireo.export.Packager.
Definition at line 105 of file FilePackagerImpl.java.
{
         return "ExportService";
     }
void org.tdl.vireo.export.impl.FilePackagerImpl.setAttachmentTypeNames (LinkedHashMap< String, Properties > attachmentTypeNames)
(OPITONAL) Set the attachment types which will be included in the package. Since not all attachments should be deposited, this allows the package to filter which files to include. They must be the exact name (all uppercase) of types listed in the AttachmentType enum.
If no types are specified then no attachments will be included.
Parameters
attachmentTypeNames List of attachment types to include.
Definition at line 68 of file FilePackagerImpl.java.
{
         this.attachmentTypes = new ArrayList<AttachmentType>();
         this.attachmentAttributes = new LinkedHashMap<String, Properties>();
         if (attachmentTypeNames != null ) {
             this.attachmentAttributes = attachmentTypeNames;
             for (String name : attachmentTypeNames.keySet()) {
                 AttachmentType type = AttachmentType.valueOf(name);
                 this.attachmentTypes.add(type);
             }
         }
     }
void org.tdl.vireo.export.impl.FilePackagerImpl.setEntryName (String entryName)
(OPTIONAL) Set the name of the entry. The default will be submission_{submission ID}, but this can be customized in application-context.xml.
Parameters
entryName The name of the entry.
Definition at line 90 of file FilePackagerImpl.java.
References org.tdl.vireo.export.impl.FilePackagerImpl.entryName.
{
         this.entryName = entryName;
     }
void org.tdl.vireo.export.impl.FilePackagerImpl.setPackageType (String packageType)
(OPTIONAL) Inject the package type for the export.
Parameters
packageType Package Type (directory, zip, etc)
Definition at line 100 of file FilePackagerImpl.java.
References org.tdl.vireo.export.impl.FilePackagerImpl.packageType.
{
         this.packageType = packageType;
     }
Member Data Documentation
LinkedHashMap<String, Properties> org.tdl.vireo.export.impl.FilePackagerImpl.attachmentAttributes = new LinkedHashMap<String, Properties>()
Definition at line 53 of file FilePackagerImpl.java.
Referenced by org.tdl.vireo.export.impl.FilePackagerImpl.generatePackage().
List<AttachmentType> org.tdl.vireo.export.impl.FilePackagerImpl.attachmentTypes = new ArrayList<AttachmentType>()
Definition at line 52 of file FilePackagerImpl.java.
Referenced by org.tdl.vireo.export.impl.FilePackagerImpl.generatePackage().
String org.tdl.vireo.export.impl.FilePackagerImpl.entryName
Definition at line 54 of file FilePackagerImpl.java.
Referenced by org.tdl.vireo.export.impl.FilePackagerImpl.generatePackage(), and org.tdl.vireo.export.impl.FilePackagerImpl.setEntryName().
String org.tdl.vireo.export.impl.FilePackagerImpl.packageType = "dir"
Definition at line 55 of file FilePackagerImpl.java.
Referenced by org.tdl.vireo.export.impl.FilePackagerImpl.generatePackage(), and org.tdl.vireo.export.impl.FilePackagerImpl.setPackageType().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/export/impl/FilePackagerImpl.java