Vireo: org.tdl.vireo.export.impl.ExcelPackagerImpl Class Reference
org.tdl.vireo.export.impl.ExcelPackagerImpl Class Reference
Classes
class ExcelFilePackage
class ExcelWorkbookPackage
Public Member Functions
XSSFWorkbook testWorkbook (List< Submission > submissions, List< SearchOrder > columns)
XSSFWorkbook writeWorkbook (Submission sub, List< SearchOrder > columns)
void setAttachmentTypeNames (LinkedHashMap< String, Properties > attachmentTypeNames)
void setAggregated (Boolean aggregated)
String getExportServiceBeanName ()
ExportExcel generateExcelPackage (Submission submission, List< SearchOrder > columns)
ExportPackage generatePackage (Submission submission)
Public Member Functions inherited from org.tdl.vireo.export.impl.AbstractExcelPackagerImpl
ExportExcel generateExcelPackage (Submission submission, List< SearchOrder > columns) throws Exception
Public Member Functions inherited from org.tdl.vireo.export.impl.AbstractPackagerImpl
String getBeanName ()
void setBeanName (String beanName)
String getDisplayName ()
void setDisplayName (String displayName)
Public Attributes
List< AttachmentType > attachmentTypes = new ArrayList<AttachmentType>()
Boolean aggregated = false
LinkedHashMap< String, Properties > attachmentAttributes = new LinkedHashMap<String, Properties>()
Public Attributes inherited from org.tdl.vireo.export.impl.AbstractPackagerImpl
String beanName
String displayName
Static Public Attributes
static final String sheetName = "vireo-export"
static final SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy")
Private Member Functions
void processWorkbookRow (XSSFRow header, XSSFRow row, Submission sub, List< SearchOrder > SearchOrderList)
Detailed Description
This will export the current FilterTab results as an Excel spreadsheet.
Author
willi.nosp@m.am_m.nosp@m.ckinn.nosp@m.ey@h.nosp@m.arvar.nosp@m.d.ed.nosp@m.u
Gad Krumholz
Definition at line 46 of file ExcelPackagerImpl.java.
Member Function Documentation
ExportExcel org.tdl.vireo.export.impl.ExcelPackagerImpl.generateExcelPackage (Submission submission, List< SearchOrder > columns)
This is used for ExportExcel implementations
Parameters
submission
the Submission
columns
the SearchOrder columns to export
Returns
- the ExportExcel object
Definition at line 471 of file ExcelPackagerImpl.java.
References org.tdl.vireo.export.impl.ExcelPackagerImpl.writeWorkbook().
{
         // make sure we have columns to export
         if (columns.size() == 0) {
             columns = getDefaultColumns(SUBMISSION);
         }
         XSSFWorkbook wbook = writeWorkbook(submission, columns);
         return new ExcelWorkbookPackage(submission, wbook);
     }
ExportPackage org.tdl.vireo.export.impl.ExcelPackagerImpl.generatePackage (Submission submission)
This is used for ExportPackage implementations
Parameters
submission
the Submission
Returns
- the ExportPackage object
Implements org.tdl.vireo.export.Packager.
Definition at line 488 of file ExcelPackagerImpl.java.
References org.tdl.vireo.model.AttachmentType.ACTIONLOG, org.tdl.vireo.export.impl.ExcelPackagerImpl.attachmentAttributes, org.tdl.vireo.export.impl.ExcelPackagerImpl.attachmentTypes, org.tdl.vireo.model.AbstractModel.getId(), and org.tdl.vireo.export.impl.ExcelPackagerImpl.writeWorkbook().
{
         if (attachmentTypes.size() == 0) {
             throw new IllegalArgumentException("Unable to generate package because not attachment types have been defined.");
         }
         // Check that we have everything that we need.
         if (submission == null || submission.getId() == null)
             throw new IllegalArgumentException("Unable to generate a package because the submission is null, or has not been persisted.");
         try {
             // Set String replacement parameters
             Map<String, String> parameters = new HashMap<String, String>();
             parameters = StringVariableReplacement.setParameters(submission);
             File pkg = null;
             List<Attachment> actionLogAttachments = new ArrayList<Attachment>();
             pkg = File.createTempFile("template-export-", ".dir");
             // The package has more than one file, so export as a directory.
             pkg.delete();
             pkg.mkdir();
             File xl = new File(pkg.getPath(), "data.xlsx");
             if (xl.exists() || xl.isDirectory()) {
                 xl.delete();
                 xl.createNewFile();
             }
             XSSFWorkbook wbook = writeWorkbook(submission, Arrays.asList(SearchOrder.values()));
             FileOutputStream os = new FileOutputStream(xl);
             wbook.write(os);
             os.close();
             // Add all the attachments
             List<Attachment> attachments = submission.getAttachments();
             List<Attachment> actionLogs = submission.getAttachmentsByType(AttachmentType.ACTIONLOG);
             // add them to this list to delete the temp files later
             actionLogAttachments.addAll(actionLogs);
             // add them to this list to add them to export
             attachments.addAll(actionLogs);
             for (Attachment attachment : attachments) {
                 // Do we include this type?
                 if (!attachmentTypes.contains(attachment.getType()))
                     continue;
                 /*
                  * The string substitution only works on items we can retrieve from the submission so we have to get the file name for each attachment here in the attachment loop.
                  */
                 String shortFileName = attachment.getName().replaceAll("." + FilenameUtils.getExtension(attachment.getName()), "");
                 String fileName = attachment.getName();
                 // Customize Attachment Name
                 if (attachmentAttributes.get(attachment.getType().name()).get("customName") != null) {
                     fileName = attachmentAttributes.get(attachment.getType().name()).get("customName") + "." + FilenameUtils.getExtension(attachment.getName());
                     fileName = fileName.replace("{FILE_NAME}", shortFileName);
                     fileName = StringVariableReplacement.applyParameterSubstitution(fileName, parameters);
                 }
                 // Check for Custom Directory Structure.
                 String pkgPath = pkg.getPath();
                 if (attachmentAttributes.get(attachment.getType().name()).get("directory") != null) {
                     String dirName = (String) attachmentAttributes.get(attachment.getType().name()).get("directory");
                     dirName = dirName.replace("{FILE_NAME}", shortFileName);
                     dirName = StringVariableReplacement.applyParameterSubstitution(dirName, parameters);
                     pkgPath = pkgPath + File.separator + dirName;
                 }
                 File exportFile = new File(pkgPath, fileName);
                 FileUtils.copyFile(attachment.getFile(), exportFile);
             }// End for loop
             // Create the actual package!
             return new ExcelFilePackage(submission, pkg, null, actionLogAttachments);
         } catch (Exception ioe) {
             throw new RuntimeException("Unable to generate package", ioe);
         }
     }
String org.tdl.vireo.export.impl.ExcelPackagerImpl.getExportServiceBeanName ()
Returns
The technical spring bean name of this packager's ExportService implementation.
Implements org.tdl.vireo.export.Packager.
Definition at line 453 of file ExcelPackagerImpl.java.
References org.tdl.vireo.export.impl.ExcelPackagerImpl.aggregated.
{
         String ret = "ExportService";
         if (aggregated) {
             ret = "ExportExcelService";
         }
         return ret;
     }
void org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow (XSSFRow header, XSSFRow row, Submission sub, List< SearchOrder > SearchOrderList) private
Definition at line 109 of file ExcelPackagerImpl.java.
References org.tdl.vireo.model.Submission.getApprovalDate(), org.tdl.vireo.model.Submission.getAssignee(), org.tdl.vireo.model.Submission.getCollege(), org.tdl.vireo.model.Submission.getCommitteeApprovalDate(), org.tdl.vireo.model.Submission.getCommitteeContactEmail(), org.tdl.vireo.model.Submission.getCommitteeEmbargoApprovalDate(), org.tdl.vireo.model.Submission.getCommitteeMembers(), org.tdl.vireo.model.Submission.getCustomActions(), org.tdl.vireo.model.Submission.getDefenseDate(), org.tdl.vireo.model.Submission.getDegree(), org.tdl.vireo.model.Submission.getDegreeLevel(), org.tdl.vireo.model.Submission.getDepartment(), org.tdl.vireo.model.Submission.getDepositId(), org.tdl.vireo.export.impl.AbstractPackagerImpl.getDisplayName(), org.tdl.vireo.model.Submission.getDocumentAbstract(), org.tdl.vireo.model.Submission.getDocumentKeywords(), org.tdl.vireo.model.Submission.getDocumentLanguage(), org.tdl.vireo.model.Submission.getDocumentSubjects(), org.tdl.vireo.model.Submission.getDocumentTitle(), org.tdl.vireo.model.Submission.getDocumentType(), org.tdl.vireo.model.CommitteeMember.getFormattedRoles(), org.tdl.vireo.model.Submission.getGraduationMonth(), org.tdl.vireo.model.Submission.getGraduationYear(), org.tdl.vireo.model.EmbargoType.getGuarantor(), org.tdl.vireo.model.AbstractModel.getId(), org.tdl.vireo.model.Submission.getLastLogDate(), org.tdl.vireo.model.Submission.getLastLogEntry(), org.tdl.vireo.model.Submission.getLicenseAgreementDate(), org.tdl.vireo.model.Submission.getMajor(), org.tdl.vireo.model.Submission.getOrcid(), org.tdl.vireo.model.Submission.getPrimaryDocument(), org.tdl.vireo.model.Submission.getProgram(), org.tdl.vireo.model.Submission.getPublishedMaterial(), org.tdl.vireo.model.Submission.getReviewerNotes(), org.tdl.vireo.model.CommitteeMember.getRoles(), org.tdl.vireo.model.Submission.getState(), org.tdl.vireo.model.Submission.getStudentFormattedName(), org.tdl.vireo.model.Submission.getSubmissionDate(), org.tdl.vireo.model.Submission.getSubmitter(), org.tdl.vireo.model.Submission.getUMIRelease(), and org.tdl.vireo.model.NameFormat.LAST_FIRST.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.testWorkbook(), and org.tdl.vireo.export.impl.ExcelPackagerImpl.writeWorkbook().
{
         int j = 0; // cell counter
         for (SearchOrder column : SearchOrderList) {
             switch (column) {
             case ID:
                 header.createCell(j).setCellValue("ID");
                 if (null != sub.getId())
                     row.createCell(j).setCellValue(sub.getId());
                 j++;
                 break;
             case STUDENT_EMAIL:
                 header.createCell(j).setCellValue("Student email");
                 if (null != sub.getSubmitter() && null != sub.getSubmitter().getEmail())
                     row.createCell(j).setCellValue(sub.getSubmitter().getEmail());
                 j++;
                 break;
             case STUDENT_NAME:
                 header.createCell(j).setCellValue("Student name");
                 row.createCell(j).setCellValue(sub.getStudentFormattedName(org.tdl.vireo.model.NameFormat.LAST_FIRST_MIDDLE_BIRTH));
                 j++;
                 break;
             case STUDENT_ID:
                 header.createCell(j).setCellValue("Student ID");
                 if (sub.getSubmitter() != null && sub.getSubmitter().getInstitutionalIdentifier() != null)
                     row.createCell(j).setCellValue(sub.getSubmitter().getInstitutionalIdentifier());
                 j++;
                 break;
             case STATE:
                 header.createCell(j).setCellValue("Status");
                 if (null != sub.getState())
                     row.createCell(j).setCellValue(sub.getState().getDisplayName());
                 j++;
                 break;
             case ASSIGNEE:
                 header.createCell(j).setCellValue("Assignee");
                 if (null != sub.getAssignee())
                     row.createCell(j).setCellValue(sub.getAssignee().getFormattedName(org.tdl.vireo.model.NameFormat.FIRST_LAST));
                 j++;
                 break;
             case DOCUMENT_TITLE:
                 header.createCell(j).setCellValue("Title");
                 if (null != sub.getDocumentTitle())
                     row.createCell(j).setCellValue(sub.getDocumentTitle());
                 j++;
                 break;
             case DOCUMENT_ABSTRACT:
                 header.createCell(j).setCellValue("Abstract");
                 if (null != sub.getDocumentAbstract())
                     row.createCell(j).setCellValue(sub.getDocumentAbstract());
                 j++;
                 break;
             case DOCUMENT_SUBJECTS:
                 header.createCell(j).setCellValue("Subjects");
                 if (null != sub.getDocumentSubjects())
                     row.createCell(j).setCellValue(StringUtils.join(sub.getDocumentSubjects(), ";"));
                 j++;
                 break;
             case DOCUMENT_LANGUAGE:
                 header.createCell(j).setCellValue("Language");
                 if (null != sub.getDocumentLanguage())
                     row.createCell(j).setCellValue(sub.getDocumentLanguage());
                 j++;
                 break;
             case PUBLISHED_MATERIAL:
                 header.createCell(j).setCellValue("Published material");
                 if (null != sub.getPublishedMaterial())
                     row.createCell(j).setCellValue("Yes - " + sub.getPublishedMaterial());
                 j++;
                 break;
             case PRIMARY_DOCUMENT:
                 header.createCell(j).setCellValue("Primary document");
                 if (null != sub.getPrimaryDocument())
                     row.createCell(j).setCellValue(sub.getPrimaryDocument().getName());
                 j++;
                 break;
             case GRADUATION_DATE:
                 header.createCell(j).setCellValue("Graduation date");
                 StringBuilder sb = new StringBuilder();
                 String monthName = null;
                 if (sub.getGraduationMonth() != null && sub.getGraduationMonth() >= 0 && sub.getGraduationMonth() <= 11)
                     monthName = new java.text.DateFormatSymbols().getMonths()[sub.getGraduationMonth()];
                 if (sub.getGraduationYear() != null)
                     sb.append(sub.getGraduationYear());
                 if (monthName != null)
                     sb.append(" ").append(monthName);
                 row.createCell(j).setCellValue(sb.toString());
                 j++;
                 break;
             case DEFENSE_DATE:
                 header.createCell(j).setCellValue("Defense date");
                 if (sub.getDefenseDate() != null)
                     row.createCell(j).setCellValue(sdf.format(sub.getDefenseDate()));
                 j++;
                 break;
             case SUBMISSION_DATE:
                 header.createCell(j).setCellValue("Submission date");
                 if (sub.getSubmissionDate() != null)
                     row.createCell(j).setCellValue(sdf.format(sub.getSubmissionDate()));
                 j++;
                 break;
             case LICENSE_AGREEMENT_DATE:
                 header.createCell(j).setCellValue("License agreement date");
                 if (sub.getLicenseAgreementDate() != null)
                     row.createCell(j).setCellValue(sdf.format(sub.getLicenseAgreementDate()));
                 j++;
                 break;
             case APPROVAL_DATE:
                 header.createCell(j).setCellValue("Approval date");
                 if (sub.getApprovalDate() != null)
                     row.createCell(j).setCellValue(sdf.format(sub.getApprovalDate()));
                 j++;
                 break;
             case COMMITTEE_APPROVAL_DATE:
                 header.createCell(j).setCellValue("Committee approval date");
                 if (sub.getCommitteeApprovalDate() != null)
                     row.createCell(j).setCellValue(sdf.format(sub.getCommitteeApprovalDate()));
                 j++;
                 break;
             case COMMITTEE_EMBARGO_APPROVAL_DATE:
                 header.createCell(j).setCellValue("Committee embargo approval date");
                 if (sub.getCommitteeEmbargoApprovalDate() != null)
                     row.createCell(j).setCellValue(sdf.format(sub.getCommitteeEmbargoApprovalDate()));
                 j++;
                 break;
             case COMMITTEE_MEMBERS:
                 header.createCell(j).setCellValue("Committee members");
                 StringBuilder cm = new StringBuilder();
                 int i = 0;
                 for (i = 0; i < sub.getCommitteeMembers().size(); i++) {
                     CommitteeMember member = sub.getCommitteeMembers().get(i);
                     cm.append(member.getFormattedName(NameFormat.LAST_FIRST));
                     if (member.getRoles().size() > 0) {
                         cm.append(" (").append(member.getFormattedRoles()).append(")");
                     }
                     if ((i + 1) < sub.getCommitteeMembers().size()) {
                         cm.append(";");
                     }
                 }
                 row.createCell(j).setCellValue(cm.toString());
                 j++;
                 break;
             case COMMITTEE_CONTACT_EMAIL:
                 header.createCell(j).setCellValue("Committee contact email");
                 if (sub.getCommitteeContactEmail() != null)
                     row.createCell(j).setCellValue(sub.getCommitteeContactEmail());
                 j++;
                 break;
             case DEGREE:
                 header.createCell(j).setCellValue("Degree");
                 if (sub.getDegree() != null)
                     row.createCell(j).setCellValue(sub.getDegree());
                 j++;
                 break;
             case DEGREE_LEVEL:
                 header.createCell(j).setCellValue("Degree level");
                 if (sub.getDegreeLevel() != null)
                     row.createCell(j).setCellValue(sub.getDegreeLevel().name());
                 j++;
                 break;
             case PROGRAM:
                 header.createCell(j).setCellValue("Program");
                 if (sub.getProgram() != null)
                     row.createCell(j).setCellValue(sub.getProgram());
                 j++;
                 break;
             case COLLEGE:
                 header.createCell(j).setCellValue("College");
                 if (sub.getCollege() != null)
                     row.createCell(j).setCellValue(sub.getCollege());
                 j++;
                 break;
             case DEPARTMENT:
                 header.createCell(j).setCellValue("Department");
                 if (sub.getDepartment() != null)
                     row.createCell(j).setCellValue(sub.getDepartment());
                 j++;
                 break;
             case MAJOR:
                 header.createCell(j).setCellValue("Major");
                 if (sub.getMajor() != null)
                     row.createCell(j).setCellValue(sub.getMajor());
                 j++;
                 break;
             case EMBARGO_TYPE:
                 header.createCell(j).setCellValue("Embargo type");
                 String sEmbargos = "";
                 List<EmbargoType> embargoTypes = sub.getEmbargoTypes();
                 for (int k = 0; k < embargoTypes.size(); k++) {
                     EmbargoType embargoType = embargoTypes.get(k);
                     sEmbargos += embargoType.getName() + (embargoType.getGuarantor() != EmbargoGuarantor.DEFAULT ? " (" + embargoType.getGuarantor().name() + ")" : "") + ((k + 1) < embargoTypes.size() ? ";" : "");
                 }
                 row.createCell(j).setCellValue(sEmbargos);
                 j++;
                 break;
             case DOCUMENT_TYPE:
                 header.createCell(j).setCellValue("Document type");
                 if (sub.getDocumentType() != null)
                     row.createCell(j).setCellValue(sub.getDocumentType());
                 j++;
                 break;
             case UMI_RELEASE:
                 header.createCell(j).setCellValue("UMI release");
                 if (sub.getUMIRelease() != null) {
                     if (sub.getUMIRelease()) {
                         row.createCell(j).setCellValue("Yes");
                     } else {
                         row.createCell(j).setCellValue("No");
                     }
                 }
                 j++;
                 break;
             case CUSTOM_ACTIONS:
                 header.createCell(j).setCellValue("Custom actions");
                 String sActions = "";
                 SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class);
                 List<CustomActionDefinition> customActions = settingRepo.findAllCustomActionDefinition();
                 for (int k = 0; k < customActions.size(); k++) {
                     CustomActionDefinition systemAction = customActions.get(k);
                     boolean found = false;
                     for (org.tdl.vireo.model.CustomActionValue subAction : sub.getCustomActions()) {
                         if (systemAction.equals(subAction.getDefinition())) {
                             sActions += " " + subAction.getDefinition().getLabel();
                             found = true;
                         }
                     }
                     if (!found) {
                         sActions += " " + systemAction.getLabel();
                     }
                     if ((k + 1) < customActions.size()) {
                         sActions += '\n';
                     }
                 }
                 row.createCell(j).setCellValue(sActions);
                 j++;
                 break;
             case DEPOSIT_ID:
                 header.createCell(j).setCellValue("Deposit ID");
                 if (sub.getDepositId() != null)
                     row.createCell(j).setCellValue(sub.getDepositId());
                 j++;
                 break;
             case REVIEWER_NOTES:
                 header.createCell(j).setCellValue("Reviewer notes");
                 if (sub.getReviewerNotes() != null)
                     row.createCell(j).setCellValue(sub.getReviewerNotes());
                 j++;
                 break;
             case DOCUMENT_KEYWORDS:
                 header.createCell(j).setCellValue("Document Keywords");
                 if (sub.getDocumentKeywords() != null)
                     row.createCell(j).setCellValue(sub.getDocumentKeywords());
                 j++;
                 break;
             case LAST_EVENT_ENTRY:
                 header.createCell(j).setCellValue("Last Event Entry");
                 if (sub.getLastLogEntry() != null)
                     row.createCell(j).setCellValue(sub.getLastLogEntry());
                 j++;
                 break;
             case LAST_EVENT_TIME:
                 header.createCell(j).setCellValue("Last Event Time");
                 if (sub.getLastLogDate() != null)
                     row.createCell(j).setCellValue(sub.getLastLogDate());
                 j++;
                 break;
             case ORCID:
                 header.createCell(j).setCellValue("ORCID");
                 if (sub.getOrcid() != null)
                     row.createCell(j).setCellValue(sub.getOrcid());
                 j++;
                 break;
             }
         }
     }
void org.tdl.vireo.export.impl.ExcelPackagerImpl.setAggregated (Boolean aggregated)
(OPTIONAL) Inject whether we're aggregating Excel data into one file, no file attachments
Parameters
filtered Boolean of whether we're aggregating Excel data into one file, no file attachments
Definition at line 448 of file ExcelPackagerImpl.java.
References org.tdl.vireo.export.impl.ExcelPackagerImpl.aggregated.
{
         this.aggregated = aggregated;
     }
void org.tdl.vireo.export.impl.ExcelPackagerImpl.setAttachmentTypeNames (LinkedHashMap< String, Properties > attachmentTypeNames)
(OPITONAL) Set the attachment types which will be included in the package. Since not all attachments should be deposited, this allows the package to filter which files to include. They must be the exact name (all uppercase) of types listed in the AttachmentType enum.
If no types are specified then no attachments will be included.
Parameters
attachmentTypeNames List of attachment types to include.
Definition at line 428 of file ExcelPackagerImpl.java.
{
         this.attachmentTypes = new ArrayList<AttachmentType>();
         this.attachmentAttributes = new LinkedHashMap<String, Properties>();
         if (attachmentTypeNames != null) {
             this.attachmentAttributes = attachmentTypeNames;
             for (String name : attachmentTypeNames.keySet()) {
                 AttachmentType type = AttachmentType.valueOf(name);
                 this.attachmentTypes.add(type);
             }
         }
     }
XSSFWorkbook org.tdl.vireo.export.impl.ExcelPackagerImpl.testWorkbook (List< Submission > submissions, List< SearchOrder > columns)
This function is used by Unit Test to export a XSSFWorkbook with all of the submissions as separate rows
This is needed because the Unit Test does not run through the ExportService (which is the iterator of List Submission)
Parameters
submissions
list of submissions
columns
the columns to include in the sheet
Returns
- The Excel workbook file (xssf format only)
Definition at line 70 of file ExcelPackagerImpl.java.
References org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), and org.tdl.vireo.export.impl.ExcelPackagerImpl.sheetName.
{
         XSSFWorkbook wb = new XSSFWorkbook();
         XSSFSheet sheet = wb.createSheet(sheetName);
         XSSFRow header = sheet.createRow(0);
         int i = 1; // row counter
         for (Submission sub : submissions) {
             XSSFRow row = sheet.createRow(i);
             processWorkbookRow(header, row, sub, columns);
             i++;
         }
         return wb;
     }
XSSFWorkbook org.tdl.vireo.export.impl.ExcelPackagerImpl.writeWorkbook (Submission sub, List< SearchOrder > columns)
Takes XSSFWorkbook argument, a single Submission, and a List of SearchOrder.
Creates a new XSSFSheet in the XSSFWorkbook and adds a header XSSFRow and a data XSSFRow.
Passes the header row, the data row, the submission, and the SearchOrder List to processWorkbookRow()
Parameters
wb
the workbook to modify in-place
sub
the submission to add to the workbook
columns
the columns to include in the sheet
Definition at line 100 of file ExcelPackagerImpl.java.
References org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), and org.tdl.vireo.export.impl.ExcelPackagerImpl.sheetName.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.generateExcelPackage(), and org.tdl.vireo.export.impl.ExcelPackagerImpl.generatePackage().
{
         XSSFWorkbook wb = new XSSFWorkbook();
         XSSFSheet sheet = wb.createSheet(sheetName);
         XSSFRow header = sheet.createRow(0);
         XSSFRow row = sheet.createRow(1);
         processWorkbookRow(header, row, sub, columns);
         return wb;
     }
Member Data Documentation
Boolean org.tdl.vireo.export.impl.ExcelPackagerImpl.aggregated = false
Definition at line 50 of file ExcelPackagerImpl.java.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.getExportServiceBeanName(), and org.tdl.vireo.export.impl.ExcelPackagerImpl.setAggregated().
LinkedHashMap<String, Properties> org.tdl.vireo.export.impl.ExcelPackagerImpl.attachmentAttributes = new LinkedHashMap<String, Properties>()
Definition at line 57 of file ExcelPackagerImpl.java.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.generatePackage().
List<AttachmentType> org.tdl.vireo.export.impl.ExcelPackagerImpl.attachmentTypes = new ArrayList<AttachmentType>()
Definition at line 49 of file ExcelPackagerImpl.java.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.generatePackage().
final SimpleDateFormat org.tdl.vireo.export.impl.ExcelPackagerImpl.sdf = new SimpleDateFormat("MM/dd/yyyy") static
Definition at line 54 of file ExcelPackagerImpl.java.
final String org.tdl.vireo.export.impl.ExcelPackagerImpl.sheetName = "vireo-export" static
Definition at line 53 of file ExcelPackagerImpl.java.
Referenced by org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.doJob(), org.tdl.vireo.export.impl.ExcelPackagerImpl.testWorkbook(), and org.tdl.vireo.export.impl.ExcelPackagerImpl.writeWorkbook().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/export/impl/ExcelPackagerImpl.java