Vireo: org.tdl.vireo.search.impl.LuceneRebuildJobImpl Class Reference
org.tdl.vireo.search.impl.LuceneRebuildJobImpl Class Reference
Public Member Functions
LuceneRebuildJobImpl (LuceneIndexerImpl indexer)
String getLabel ()
LuceneAbstractJobImpl mergeJob (LuceneAbstractJobImpl job)
void writeIndex () throws CorruptIndexException, LockObtainFailedException, IOException, InterruptedException
Public Member Functions inherited from org.tdl.vireo.search.impl.LuceneAbstractJobImpl
LuceneAbstractJobImpl (LuceneIndexerImpl indexer)
abstract LuceneAbstractJobImpl mergeJob (LuceneAbstractJobImpl job)
abstract String getLabel ()
int getProgress ()
int getTotal ()
void cancelJob ()
void doJob ()
abstract void writeIndex () throws CorruptIndexException, LockObtainFailedException, IOException, InterruptedException
void indexSubmission (IndexWriter writer, Submission sub) throws CorruptIndexException, IOException
Additional Inherited Members
Public Attributes inherited from org.tdl.vireo.search.impl.LuceneAbstractJobImpl
final LuceneIndexerImpl indexer
int progress = 0
int total = 0
boolean cancel = false
Detailed Description
This is the background job to rebuild the entire search index.
Rebuilding may take quite some time to complete depending upon the size of the search index. This is a non-destructive rebuild, meaning that searches may continue without effect while the rebuilding is occurring.
Author
Scott Phillips
Definition at line 21 of file LuceneRebuildJobImpl.java.
Constructor & Destructor Documentation
org.tdl.vireo.search.impl.LuceneRebuildJobImpl.LuceneRebuildJobImpl (LuceneIndexerImpl indexer)
Construct a new rebuild index job.
Definition at line 26 of file LuceneRebuildJobImpl.java.
References org.tdl.vireo.model.SubmissionRepository.findSubmissionsTotal(), org.tdl.vireo.search.impl.LuceneAbstractJobImpl.progress, org.tdl.vireo.search.impl.LuceneIndexerImpl.subRepo, and org.tdl.vireo.search.impl.LuceneAbstractJobImpl.total.
{
         super(indexer);
         progress = 0;
         total = (int) indexer.subRepo.findSubmissionsTotal();
     }
Member Function Documentation
String org.tdl.vireo.search.impl.LuceneRebuildJobImpl.getLabel ()
Definition at line 33 of file LuceneRebuildJobImpl.java.
Referenced by org.tdl.vireo.search.impl.LuceneRebuildJobImpl.writeIndex().
{
         return "Rebuild Index";
     }
LuceneAbstractJobImpl org.tdl.vireo.search.impl.LuceneRebuildJobImpl.mergeJob (LuceneAbstractJobImpl job)
Definition at line 38 of file LuceneRebuildJobImpl.java.
{
         // we're rebuilding the entire index and haven't started, so we can
         // merge with any job.
         return this;
     }
void org.tdl.vireo.search.impl.LuceneRebuildJobImpl.writeIndex () throws CorruptIndexException, LockObtainFailedException, IOException, InterruptedException
Definition at line 45 of file LuceneRebuildJobImpl.java.
References org.tdl.vireo.search.impl.LuceneAbstractJobImpl.cancel, org.tdl.vireo.model.SubmissionRepository.findSubmissionsTotal(), org.tdl.vireo.search.impl.LuceneRebuildJobImpl.getLabel(), org.tdl.vireo.search.impl.LuceneIndexerImpl.index, org.tdl.vireo.search.impl.LuceneAbstractJobImpl.indexer, org.tdl.vireo.search.impl.LuceneAbstractJobImpl.indexSubmission(), org.tdl.vireo.search.impl.LuceneAbstractJobImpl.progress, org.tdl.vireo.search.impl.LuceneIndexerImpl.standardAnalyzer, org.tdl.vireo.search.impl.LuceneIndexerImpl.subRepo, org.tdl.vireo.search.impl.LuceneAbstractJobImpl.total, and org.tdl.vireo.search.impl.LuceneIndexerImpl.version.
{
         progress = 0;
         total = (int) indexer.subRepo.findSubmissionsTotal();
         IndexWriterConfig writerConfig = new IndexWriterConfig(indexer.version,
                 indexer.standardAnalyzer);
         IndexWriter writer = new IndexWriter(indexer.index, writerConfig);
         try {
             writer.deleteAll();
             Iterator<Submission> itr = indexer.subRepo.findAllSubmissions();
             int count = 0;
             while (itr.hasNext()) {
                 indexSubmission(writer, itr.next());
                 progress++;
                 // Have we been asked to stop?
                 if (cancel) {
                     writer.rollback();
                     writer = null;
                     throw new InterruptedException("Lucene '"+this.getLabel()+"' job recieved a cancel request after processing "+progress+" number of submissions, rolling back changes.");
                 }
                 // Keep memory usage under control
                 if (count > 100) {
                     System.gc();
                     count = 0;
                 } else {
                     count++;
                 }
             }
         } finally {
             if (writer != null)
                 writer.close();
         }
     }
The documentation for this class was generated from the following file:
app/org/tdl/vireo/search/impl/LuceneRebuildJobImpl.java