Vireo: controllers.Advisor Class Reference
controllers.Advisor Class Reference
Static Public Member Functions
static void reviewJSON (String token)
static void review (String token)
static void viewAttachment (String token, Long attachmentId, String name)
Static Public Member Functions inherited from controllers.AbstractVireoController
static void injectRepositories ()
static void checkForFirstUser ()
static void handleError (Throwable throwable)
Static Public Attributes
static final String AFFILIATION_CONFIG = "advisor.affiliation.restrict"
Static Public Attributes inherited from controllers.AbstractVireoController
static SecurityContext context = Spring.getBeanOfType(SecurityContext.class)
static PersonRepository personRepo = Spring.getBeanOfType(PersonRepository.class)
static SubmissionRepository subRepo = Spring.getBeanOfType(SubmissionRepository.class)
static SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class)
static ProquestVocabularyRepository proquestRepo = Spring.getBeanOfType(ProquestVocabularyRepository.class)
static ErrorLog errorLog = Spring.getBeanOfType(ErrorLog.class)
static StateManager stateManager = Spring.getBeanOfType(StateManager.class)
static Indexer indexer = Spring.getBeanOfType(Indexer.class)
static Searcher searcher = Spring.getBeanOfType(Searcher.class)
static Boolean firstUser = null
Additional Inherited Members
Static Protected Member Functions inherited from controllers.AbstractVireoController
static boolean isEmpty (String value)
static boolean isNotEmpty (String value)
static String escapeJavaScript (String value)
static String URIEncode (String value)
static String toJSON (String[] values)
static String text2html (String value)
static boolean isFieldRequired (FieldConfig field)
Detailed Description
Definition at line 25 of file Advisor.java.
Member Function Documentation
static void controllers.Advisor.review (String token) static
Display the faculty advisor's review page where the user can approve or reject a submission. Theoretically we can identify the advisor based upon their use of the security token. If they have that token then they can access the submission. We still require that they authenticate first so we atleast have a user account associated with them.
Parameters
token The advisor's sort-of-security token.
Definition at line 96 of file Advisor.java.
References org.tdl.vireo.model.AttachmentType.ADMINISTRATIVE, org.tdl.vireo.model.AttachmentType.FEEDBACK, org.tdl.vireo.model.NameFormat.FIRST_LAST, org.tdl.vireo.model.Person.getAffiliations(), org.tdl.vireo.model.AbstractModel.getId(), org.tdl.vireo.constant.AppConfig.GRANTOR, org.tdl.vireo.model.AttachmentType.SOURCE, and org.tdl.vireo.model.AttachmentType.SUPPLEMENTAL.
{
         // Security check:
         // 1) Managers can access this page, with no other checks
         // 2) Non-managers need to have a specific affiliation before they can
         // access this page. (Optional)
         //
         // If there is no affiliation check, then basically anyone who has
         // access to the security token can access this page.
         Person person = context.getPerson();
         if (context.isManager()) {
             String affiliationConfig = Play.configuration.getProperty(AFFILIATION_CONFIG, "");
             if ("".equals(affiliationConfig)) {
                 // We are configured to require affiliations before accessing this page.
                 for (String affiliation : affiliationConfig.split(";")) {
                     if (person.getAffiliations().contains(affiliation.trim())) {
                         unauthorized("Only those with an affiliation of " + affiliationConfig + " or managers are able to access this advisor review page.");
                     }
                 }
             }
         }
         notFoundIfNull(token);
         Submission sub = subRepo.findSubmissionByEmailHash(token);
         notFoundIfNull(sub);
         Logger.info("%s (%d: %s) has viewed submission #%d.", person.getFormattedName(NameFormat.FIRST_LAST), person.getId(), person.getEmail(), sub.getId());
         String grantor = settingRepo.getConfigValue(AppConfig.GRANTOR, "Unknown Institution");
         List<EmbargoType> allEmbargos = settingRepo.findAllEmbargoTypes();
         Person submitter = sub.getSubmitter();
         List<ActionLog> logs = subRepo.findActionLog(sub);
         Attachment primaryDocument = sub.getPrimaryDocument();
         List<Attachment> additionalDocuments = sub.getAttachmentsByType(AttachmentType.SUPPLEMENTAL, AttachmentType.ADMINISTRATIVE, AttachmentType.SOURCE);
         List<Attachment> feedbackDocuments = sub.getAttachmentsByType(AttachmentType.FEEDBACK);
         for (FieldConfig field : FieldConfig.values()) {
             renderArgs.put(field.name(), field);
         }
         renderTemplate("Advisor/view.html", token, sub, submitter, logs, primaryDocument, additionalDocuments, feedbackDocuments, grantor, allEmbargos);
     }
static void controllers.Advisor.reviewJSON (String token) static
Handle adding a message from an AJAX request
Parameters
subId The submission id.
Definition at line 36 of file Advisor.java.
References org.tdl.vireo.model.NameFormat.FIRST_LAST, and org.tdl.vireo.model.AbstractModel.getId().
{
         Person person = context.getPerson();
         notFoundIfNull(token);
         Submission sub = subRepo.findSubmissionByEmailHash(token);
         notFoundIfNull(sub);
         Logger.info("%s (%d: %s) has viewed submission #%d.", person.getFormattedName(NameFormat.FIRST_LAST), person.getId(), person.getEmail(), sub.getId());
         boolean inputRecieved = false;
         String error = "";
         try {
             context.turnOffAuthorization();
             Date agreementDate = new Date();
             boolean messageReceived = false;
             if (params.get("advisorMessage") != null && params.get("advisorMessage").trim().length() > 0) {
                 sub.logAction("Advisor comments : '" + params.get("advisorMessage") + "'");
                 inputRecieved = true;
                 messageReceived = true;
             }
             if ("approve".equals(params.get("embargoApproval"))) {
                 sub.setCommitteeEmbargoApprovalDate(agreementDate);
                 inputRecieved = true;
             } else if ("unapprove".equals(params.get("embargoApproval")) || "reject".equals(params.get("embargoApproval"))) {
                 if (messageReceived) {
                     sub.setCommitteeEmbargoApprovalDate(null);
                     inputRecieved = true;
                 } else {
                     error += "You need to enter in a comment to " + params.get("embargoApproval") + " an embargo approval<br/>";
                 }
             }
             if ("approve".equals(params.get("committeeApproval"))) {
                 sub.setCommitteeApprovalDate(agreementDate);
                 inputRecieved = true;
             } else if ("unapprove".equals(params.get("committeeApproval")) || "reject".equals(params.get("committeeApproval"))) {
                 if (messageReceived) {
                     sub.setCommitteeApprovalDate(null);
                     inputRecieved = true;
                 } else {
                     error += "You need to enter in a comment to " + params.get("committeeApproval") + " an application approval<br/>";
                 }
             }
             sub.save();
         } finally {
             context.restoreAuthorization();
         }
         if(error == "")
             renderJSON("{ \"success\": true, \"inputReceived\": "+inputRecieved+"}");
         else
             renderJSON("{ \"success\": false, \"error\": \""+error+"\"}");
     }
static void controllers.Advisor.viewAttachment (String token, Long attachmentId, String name) static
Helper method to view an attachment specifically for advisors to handle their permissions.
Parameters
token The token identifying the submission
attachmentId The attachment id.
name The name of the attachment. (not used)
Definition at line 153 of file Advisor.java.
{
         notFoundIfNull(token);
         notFoundIfNull(attachmentId);
         Submission sub = subRepo.findSubmissionByEmailHash(token);
         Attachment attachment = subRepo.findAttachment(attachmentId);
         notFoundIfNull(sub);
         notFoundIfNull(attachment);
         response.setContentTypeIfNotSet(attachment.getMimeType());
         // Fix problem with no-cache headers and ie8
         response.setHeader("Pragma", "public");
         response.setHeader("Cache-Control", "public");
         try {
             renderBinary(new FileInputStream(attachment.getFile()), attachment.getName(), attachment.getFile().length(), true);
         } catch (FileNotFoundException ex) {
             error("File not found");
         }
     }
Member Data Documentation
final String controllers.Advisor.AFFILIATION_CONFIG = "advisor.affiliation.restrict" static
Definition at line 27 of file Advisor.java.
The documentation for this class was generated from the following file:
app/controllers/Advisor.java