Vireo: controllers.Student Class Reference
controllers.Student Class Reference
Static Public Member Functions
static void submissionList ()
static void submissionRemoveAdditionalDocumentsJSON (Long subId)
static void submissionUploadAdditionalDocumentJSON (Long subId)
static void submissionUploadPrimaryDocumentJSON (Long subId)
static void submissionAddMessageJSON (Long subId)
static void submissionView (Long subId)
static void correctionsComplete (Long subId)
static void submissionDelete (Long subId)
static boolean uploadPrimaryDocument (Submission sub)
static boolean uploadAdditional (Submission sub)
static boolean removeAdditional (Submission sub)
static void viewAttachment (Long subId, Long attachmentId, String name)
static boolean verify (Submission sub)
Static Public Member Functions inherited from controllers.AbstractVireoController
static void injectRepositories ()
static void checkForFirstUser ()
static void handleError (Throwable throwable)
Static Protected Member Functions
static Submission getSubmission ()
Static Protected Member Functions inherited from controllers.AbstractVireoController
static boolean isEmpty (String value)
static boolean isNotEmpty (String value)
static String escapeJavaScript (String value)
static String toJSON (String[] values)
static String text2html (String value)
static boolean isFieldRequired (FieldConfig field)
Additional Inherited Members
Static Public Attributes inherited from controllers.AbstractVireoController
static SecurityContext context = Spring.getBeanOfType(SecurityContext.class)
static PersonRepository personRepo = Spring.getBeanOfType(PersonRepository.class)
static SubmissionRepository subRepo = Spring.getBeanOfType(SubmissionRepository.class)
static SettingsRepository settingRepo = Spring.getBeanOfType(SettingsRepository.class)
static ProquestVocabularyRepository proquestRepo = Spring.getBeanOfType(ProquestVocabularyRepository.class)
static ErrorLog errorLog = Spring.getBeanOfType(ErrorLog.class)
static StateManager stateManager = Spring.getBeanOfType(StateManager.class)
static Indexer indexer = Spring.getBeanOfType(Indexer.class)
static Searcher searcher = Spring.getBeanOfType(Searcher.class)
static Boolean firstUser = null
Detailed Description
THIS CONTROLLER IS BEING REFACTORED.
Please don't touch right now.
Definition at line 47 of file Student.java.
Member Function Documentation
static void controllers.Student.correctionsComplete (Long subId) static
Splash screen after a student has submitted corrections.
Parameters
subId The submission
Definition at line 284 of file Student.java.
References org.tdl.vireo.constant.AppConfig.CORRECTION_INSTRUCTIONS.
{
         // Get the post corrections instructions for display
         String instructions = settingRepo.getConfigValue(AppConfig.CORRECTION_INSTRUCTIONS);
         instructions = text2html(instructions);
         renderTemplate("Student/complete.html",instructions);
     }
static Submission controllers.Student.getSubmission () static protected
Retrieve the submission object and make sure it's in a proper state. This is slightly different that the version that is in the submission steps because it does not restrict the submission to be in an initial state.
Returns
The submission object.
Definition at line 56 of file Student.java.
References org.tdl.vireo.model.Submission.getSubmitter().
{
         // We require an sub id.
         Long subId = params.get("subId", Long.class);
         if (subId == null) {
             error("Did not receive the expected submission id.");
         }
         // And the submission must exist.
         Submission sub = subRepo.findSubmission(subId);
         if (sub == null) {
             error("Unable to find the submission #"+subId);
         }
         // Check that we are the owner of the submission.
         Person submitter = context.getPerson();
         if (sub.getSubmitter() != submitter)
             unauthorized();
         return sub;
     }
static boolean controllers.Student.removeAdditional (Submission sub) static
Helper method to handle removing additional files from a submission. We check that the attachments are associated with the submission, and that they are SUPPLEMENTAL, ADMINISTRATIVE or SOURCE files to prevent deletion of other attachments.
Parameters
sub The submission to remove attachments from.
Definition at line 423 of file Student.java.
References org.tdl.vireo.model.AbstractModel.delete(), org.tdl.vireo.model.AttachmentType.SOURCE, and org.tdl.vireo.model.AttachmentType.SUPPLEMENTAL.
Referenced by controllers.submit.FileUpload.fileUpload().
{
         // Get values from all check boxes
         String[] idsToRemove = params.getAll("attachmentToRemove[]");
         if (idsToRemove != null) {
             // Iterate over all checked check boxes - removing attachments as we go
             for (String idString : idsToRemove) {
                 Long id = Long.valueOf(idString);
                 Attachment attachment = subRepo.findAttachment(id);
                 if (attachment.getSubmission() == sub &&
                         (attachment.getType() == AttachmentType.SUPPLEMENTAL ||
                         attachment.getType() == AttachmentType.ADMINISTRATIVE ||
                         attachment.getType() == AttachmentType.SOURCE))
                     attachment.delete();
             }
         }
         return true;
     }
static void controllers.Student.submissionAddMessageJSON (Long subId) static
Handle adding a message from an AJAX request
Parameters
subId The submission id.
Definition at line 157 of file Student.java.
{
         String studentMessage = null;
         if (!params.get("message").equals("")) {
             studentMessage = params.get("message");
             // Locate the submission
             Submission sub = subRepo.findSubmission(subId);
             // Check that we are the owner of the submission.
             Person submitter = context.getPerson();
             if (sub.getSubmitter() != submitter)
                 unauthorized();
             sub.logAction("Message added : '" + studentMessage + "'").save();
             renderJSON("{ \"success\": \"true\"}");
         }
         renderJSON("{ \"success\": \"false\"}");
     }
static void controllers.Student.submissionDelete (Long subId) static
Delete a given submission
Parameters
subId The submission to delete.
Definition at line 302 of file Student.java.
References org.tdl.vireo.model.NameFormat.FIRST_LAST, org.tdl.vireo.model.AbstractModel.getId(), org.tdl.vireo.model.Submission.getSubmitter(), and controllers.Application.index().
{
         Submission sub = getSubmission();
         // Check that we are the owner of the submission.
         Person submitter = context.getPerson();
         if (sub.getSubmitter() != submitter)
             unauthorized();
         sub.delete();
         Logger.info("%s (%d: %s) has deleted submission #%d.",
                 submitter.getFormattedName(NameFormat.FIRST_LAST),
                 submitter.getId(),
                 submitter.getEmail(),
                 sub.getId());
         List<Submission> submissions = subRepo.findSubmission(submitter);
         if (submissions.size() == 0)
             // No other submissions, send you back to the index.
             Application.index();
         else
             // Go back to the list of other submissions.
             submissionList();
     }
static void controllers.Student.submissionList () static
This is a general swiss army of a controller method. This is where the student should go to start anything. If they come here and don't have anything then they will be redirected to start a new submission. However if they have other submissions then they will see a list. If the configuration is not to have multiple submissions then the student will be shutteled either to their inprogress submission, or view the status of the previous submission.
Definition at line 89 of file Student.java.
Referenced by controllers.submit.AbstractSubmitStep.beforeSubmit().
{
         List<Submission> submissions = subRepo.findSubmission(context.getPerson());
         SubmissionStatus subStatus = new SubmissionStatus();
         renderTemplate("Student/list.html",submissions, subStatus);
     }
static void controllers.Student.submissionRemoveAdditionalDocumentsJSON (Long subId) static
Remove additional document(s) via AJAX request
Parameters
subId The submission id.
Definition at line 102 of file Student.java.
References org.tdl.vireo.model.Submission.getSubmitter().
{
         // Locate the submission
         Submission sub = subRepo.findSubmission(subId);
         // Check that we are the owner of the submission.
         Person submitter = context.getPerson();
         if (sub.getSubmitter() != submitter)
             unauthorized();
         removeAdditional(sub);
         renderJSON("{ \"success\": \"true\"}");
     }
static void controllers.Student.submissionUploadAdditionalDocumentJSON (Long subId) static
Handle uploading an Additional Document from an AJAX request
Parameters
subId The submission id.
Definition at line 119 of file Student.java.
References org.tdl.vireo.model.Submission.getSubmitter().
{
         // Locate the submission
         Submission sub = subRepo.findSubmission(subId);
         if(params.get("additionalDocument",File.class) != null) {
             // Check that we are the owner of the submission.
             Person submitter = context.getPerson();
             if (sub.getSubmitter() != submitter)
                 unauthorized();
             uploadAdditional(sub);
             renderJSON("{ \"success\": \"true\"}");
         }
         renderJSON("{ \"success\": \"false\"}");
     }
static void controllers.Student.submissionUploadPrimaryDocumentJSON (Long subId) static
Handle uploading a Primary Document from an AJAX request
Parameters
subId The submission id.
Definition at line 138 of file Student.java.
References org.tdl.vireo.model.Submission.getSubmitter().
{
         if(params.get("primaryDocument",File.class) != null) {
             // Locate the submission
             Submission sub = subRepo.findSubmission(subId);
             // Check that we are the owner of the submission.
             Person submitter = context.getPerson();
             if (sub.getSubmitter() != submitter)
                 unauthorized();
             uploadPrimaryDocument(sub);
             renderJSON("{ \"success\": \"true\"}");
         }
         renderJSON("{ \"success\": \"false\"}");
     }
static void controllers.Student.submissionView (Long subId) static
Student view of the submission. The form in all cases allows the student to leave comments for reviewers.
However, if the submission is in a state that allows editing by students then they may modify the documents associated with the submission, before confirming their corrections.
Parameters
subId The submission id.
Definition at line 184 of file Student.java.
References org.tdl.vireo.model.AttachmentType.ADMINISTRATIVE, org.tdl.vireo.constant.AppConfig.ALLOW_MULTIPLE_SUBMISSIONS, org.tdl.vireo.model.AttachmentType.FEEDBACK, org.tdl.vireo.model.NameFormat.FIRST_LAST, org.tdl.vireo.model.AbstractModel.getId(), org.tdl.vireo.model.Submission.getState(), org.tdl.vireo.model.Submission.getSubmitter(), org.tdl.vireo.constant.AppConfig.GRANTOR, org.tdl.vireo.model.AttachmentType.SOURCE, and org.tdl.vireo.model.AttachmentType.SUPPLEMENTAL.
{
         // Locate the submission
         Submission sub = subRepo.findSubmission(subId);
         if(sub == null){
             error("Submission with id: " + subId + " was not found!");
         }
         // Check that we are the owner of the submission.
         Person submitter = context.getPerson();
         if (sub.getSubmitter() != submitter)
             unauthorized();
         Logger.info("%s (%d: %s) has viewed submission #%d.",
                 submitter.getFormattedName(NameFormat.FIRST_LAST),
                 submitter.getId(),
                 submitter.getEmail(),
                 sub.getId());
         boolean allowMultiple = settingRepo.getConfigBoolean(AppConfig.ALLOW_MULTIPLE_SUBMISSIONS);
         if (sub.getState().isEditableByStudent()) {
             // If the replace manuscript button is pressed - then delete the manuscript
             if (params.get("replacePrimary") != null) {
                 Attachment primaryDoc = sub.getPrimaryDocument();
                 if (primaryDoc != null) {
                     primaryDoc.archive();
                     primaryDoc.save();
                     sub.save();
                 }
             }
             // Handle the remove supplementary document button
             if (params.get("removeAdditional") != null) {
                 removeAdditional(sub);
             }
             if(params.get("primaryDocument",File.class) != null) {
                 uploadPrimaryDocument(sub);
                 renderArgs.put("formSubmitter","replacePrimary");
             }
             if(params.get("additionalDocument",File.class) != null) {
                 uploadAdditional(sub);
                 renderArgs.put("formSubmitter","removeAdditional");
             }
             verify(sub);
             if (params.get("submit_corrections") != null && !validation.hasErrors()) {
                 try {
                     context.turnOffAuthorization();
                     State nextState = sub.getState().getTransitions(sub).get(0);
                     sub.setState(nextState);
                     sub.save();
                     correctionsComplete(sub.getId());
                 } finally {
                     context.restoreAuthorization();
                 }
             }
         }
         String grantor = settingRepo.getConfigValue(AppConfig.GRANTOR,"Unknown Institution");
         List<Submission> allSubmissions = subRepo.findSubmission(submitter);
         List<ActionLog> logs = subRepo.findActionLog(sub);
         Attachment primaryDocument = sub.getPrimaryDocument();
         List<Attachment> additionalDocuments = sub.getAttachmentsByType(AttachmentType.SUPPLEMENTAL,AttachmentType.SOURCE,AttachmentType.ADMINISTRATIVE);
         List<Attachment> feedbackDocuments = sub.getAttachmentsByType(AttachmentType.FEEDBACK);
         for(FieldConfig field : FieldConfig.values()) {
             renderArgs.put(field.name(),field );
         }
         List<String> attachmentTypes = new ArrayList<String>();
         for(AttachmentType type : AttachmentType.values()){
             attachmentTypes.add(type.toString());
         }
         // get all the custom actions available in the system
         List<CustomActionDefinition> allActions = settingRepo.findAllCustomActionDefinition();
         List<CustomActionDefinition> visibleActions = new ArrayList<CustomActionDefinition>();
         for(CustomActionDefinition action : allActions) {
             if(action.isStudentVisible()) {
                 visibleActions.add(action);
             }
         }
         renderTemplate("Student/view.html",subId, sub, submitter, logs, primaryDocument, additionalDocuments, feedbackDocuments, allSubmissions, grantor, allowMultiple, attachmentTypes, visibleActions);
     }
static boolean controllers.Student.uploadAdditional (Submission sub) static
Helper method to handle uploading supplementary files.
Parameters
sub The submission to add the attachment too.
Definition at line 378 of file Student.java.
{
         // If the upload supplementary button is pressed - then add the manuscript as an attachment
         File additionalDocument = params.get("additionalDocument",File.class);
         if (additionalDocument == null)
             return false;
         AttachmentType type = null;
         if(!params.get("attachmentType").isEmpty())
             type = AttachmentType.valueOf(params.get("attachmentType"));
         else
             return false;
         Attachment attachment = null;
         try {
             attachment = sub.addAttachment(additionalDocument, type);
             attachment.save();
             sub.save();
         } catch (IOException ioe) {
             Logger.error(ioe,"Unable to upload additional document");
             validation.addError("additionalDocument","Error uploading additional document.");
         } catch (IllegalArgumentException iae) {
             Logger.error(iae,"Unable to upload additional document");
             if (iae.getMessage().contains("already exists for this submission"))
                 validation.addError("additionalDocument", "A file with that name already exists; please use a different name or remove the other file.");
             else
                 validation.addError("additionalDocument","Error uploading additional document.");
         }
         return true;
     }
static boolean controllers.Student.uploadPrimaryDocument (Submission sub) static
Helper method to handle uploading a primary document.
Parameters
sub The submission to add the attachment too.
Definition at line 339 of file Student.java.
References org.tdl.vireo.model.AttachmentType.PRIMARY.
Referenced by controllers.submit.FileUpload.fileUpload().
{
         File primaryDocument = params.get("primaryDocument",File.class);
         if (primaryDocument == null)
             return false;
         String mimetype = MimeTypes.getContentType(primaryDocument.getName());
         if (!"application/pdf".equals(mimetype)) {
             validation.addError("primaryDocument", "Primary document must be a PDF file.");
             return false;
         }
         try {
             Attachment attachment = sub.addAttachment(primaryDocument, AttachmentType.PRIMARY);
             attachment.save();
             sub.save();
         } catch (IOException ioe) {
             Logger.error(ioe,"Unable to upload primary document");
             validation.addError("primaryDocument","Error uploading primary document.");
         } catch (IllegalArgumentException iae) {
             Logger.error(iae,"Unable to upload primary document");
             if (iae.getMessage().contains("already exists for this submission"))
                 validation.addError("primaryDocument", "A file with that name already exists; please use a different name or remove the other file.");
             else
                 validation.addError("primaryDocument","Error uploading primary document.");
         }
         return true;
     }
static boolean controllers.Student.verify (Submission sub) static
Verify that the user has supplied a primary document. This will be used from both the fileUpload form and the confirmation page.
Returns
True if the primary document exists, otherwise false.
Definition at line 496 of file Student.java.
References org.tdl.vireo.model.AttachmentType.ADMINISTRATIVE, org.tdl.vireo.model.Submission.getAttachmentsByType(), org.tdl.vireo.model.Submission.getPrimaryDocument(), org.tdl.vireo.model.AttachmentType.SOURCE, and org.tdl.vireo.model.AttachmentType.SUPPLEMENTAL.
{
         int numberOfErrorsBefore = validation.errors().size();
         if (isFieldRequired(PRIMARY_ATTACHMENT) && sub.getPrimaryDocument() == null )
             validation.addError("primaryDocument", "A manuscript file must be uploaded.");
         if (isFieldRequired(SUPPLEMENTAL_ATTACHMENT) &&
                 sub.getAttachmentsByType(AttachmentType.SUPPLEMENTAL).size() == 0)
             validation.addError("supplementalDocument", "At least one supplemental file is required.");
         if (isFieldRequired(SOURCE_ATTACHMENT) &&
                 sub.getAttachmentsByType(AttachmentType.SOURCE).size() == 0)
             validation.addError("sourceDocument", "At least one source file is required.");
         if (isFieldRequired(ADMINISTRATIVE_ATTACHMENT) &&
                 sub.getAttachmentsByType(AttachmentType.ADMINISTRATIVE).size() == 0)
             validation.addError("administrativeDocument", "At least one administrative file is required.");
         if (numberOfErrorsBefore == validation.errors().size())
             return true;
         else
             return false;
     }
static void controllers.Student.viewAttachment (Long subId, Long attachmentId, String name) static
Helper method to view an attachment. In many places through the submission interface there are references to view attachments. All of them point here to download the file.
Parameters
subId The submission id.
attachmentId The attachment id.
name The name of the attachment (not used)
Definition at line 459 of file Student.java.
References org.tdl.vireo.model.Attachment.getFile(), org.tdl.vireo.model.Attachment.getName(), org.tdl.vireo.model.Attachment.getSubmission(), and org.tdl.vireo.model.Submission.getSubmitter().
{
         if (attachmentId == null)
             error();
         Submission sub = getSubmission();
         // Check that we are the owner of the submission.
         Person submitter = context.getPerson();
         if (sub.getSubmitter() != submitter)
             unauthorized();
         Attachment attachment = subRepo.findAttachment(attachmentId);
         if (attachment == null)
             error();
         if (attachment.getSubmission() != sub)
             unauthorized();
         response.setContentTypeIfNotSet(attachment.getMimeType());
         // Fix problem with no-cache headers and ie8
         response.setHeader("Pragma", "public");
         response.setHeader("Cache-Control","public");
         try {
             renderBinary(new FileInputStream(attachment.getFile()), attachment.getName(), attachment.getFile().length(), true);
         } catch (FileNotFoundException ex) {
             error("File not found");
         }
     }
The documentation for this class was generated from the following file:
app/controllers/Student.java