Vireo: org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl Class Reference
org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl Class Reference
Public Member Functions
void setLoginForceSSL (boolean loginForceSSL)
void setLoginURL (String loginURL)
void setLogoutURL (String logoutURL)
void setMock (boolean mock)
void setMockAttributes (Map< String, String > mockAttributes)
void setPrimaryIdentifier (String primaryIdentifier)
void setLogoutEnabled (boolean enabled)
void setAttributeMap (Map< String, String > attributeMap)
String startAuthentication (Request request, ActionDefinition returnAction)
AuthenticationResult authenticate (Request request)
String getFailureMessage (Request request, AuthenticationResult result)
String logout (Request request, String returnURL)
Public Member Functions inherited from org.tdl.vireo.security.impl.AbstractAuthenticationMethodImpl.AbstractImplicitAuthenticationMethod
String getFailureMessage (Request request, AuthenticationResult result)
String logout (Request request, String returnURL)
Public Member Functions inherited from org.tdl.vireo.security.impl.AbstractAuthenticationMethodImpl
void setBeanName (String beanName)
String getBeanName ()
boolean isEnabled ()
void setEnabled (boolean enabled)
boolean isVisible ()
void setVisible (boolean visible)
String getDisplayName ()
void setDisplayName (String displayName)
String getDisplayDescription ()
void setDisplayDescription (String displayDescription)
boolean getAllowNewRegistration ()
void setAllowNewRegistration (boolean allow)
boolean getAllowPasswordRecovery ()
void setAllowPasswordRecovery (boolean allow)
boolean getAllowUpdatePassword (Request request, Person person)
void setAllowUpdatePassword (boolean allow)
boolean getAllowUpdateProfile (Request request, Person person)
void setAllowUpdateProfile (boolean allow)
void setPersonRepository (PersonRepository personRepo)
void setSecurityContext (SecurityContext context)
void personCreated (Request request, Person person)
void personUpdated (Request request, Person person)
Public Attributes
boolean mock = (Play.configuration.getProperty("auth.shib.mock").equals("true") || Play.mode == Mode.DEV)
boolean logShib = Play.configuration.getProperty("auth.shib.log").equals("true")
String loginURL = "/Shibboleth.sso/Login?target=%1s"
String logoutURL = "/Shibboleth.sso/Logout?return=%1s"
boolean loginForceSSL = false
boolean useNetIdAsIdentifier = true
boolean logoutEnabled = false
String headerNetId = "SHIB_netid"
String headerEmail = "SHIB_mail"
String headerInstitutionalIdentifier = "SHIB_uin"
String headerFirstName = "SHIB_givenname"
String headerMiddleName = "SHIB_initials"
String headerLastName = "SHIB_sn"
String headerBirthYear = "SHIB_dateOfBirth"
String headerAffiliations = "SHIB_eduPersonAffilation"
String headerCurrentPhoneNumber = "SHIB_phone"
String headerCurrentPostalAddress = "SHIB_postal"
String headerCurrentEmailAddress = "SHIB_mail"
String headerPermanentPhoneNumber = "SHIB_permanentPhone"
String headerPermanentPostalAddress = "SHIB_permanentPostal"
String headerPermanentEmailAddress = "SHIB_permanentMail"
String headerCurrentDegree = "SHIB_degree"
String headerCurrentDepartment = "SHIB_department"
String headerCurrentCollege = "SHIB_college"
String headerCurrentMajor = "SHIB_major"
String headerCurrentGraduationYear = "SHIB_gradYear"
String headerCurrentGraduationMonth = "SHIB_gradMonth"
String headerOrcid = "SHIB_orcid"
Map< String, String > mockAttributes = new HashMap<String,String>()
Public Attributes inherited from org.tdl.vireo.security.impl.AbstractAuthenticationMethodImpl
String beanName
boolean enabled = false
boolean visible = true
String displayName
String displayDescription
boolean allowNewRegistration = false
boolean allowPasswordRecovery = false
boolean allowUpdatePassword = false
boolean allowUpdateProfile = false
PersonRepository personRepo
SecurityContext context
Protected Member Functions
String getSingleAttribute (Request request, String attribute)
List< String > getAttributes (Request request, String attribute)
Static Private Member Functions
static boolean isEmpty (String value)
Detailed Description
Shibboleth Authentication
TODO: Lots more documentation about how to configure this thing.
Author
Scott Phillips
Definition at line 29 of file ShibbolethAuthenticationMethodImpl.java.
Member Function Documentation
AuthenticationResult org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate (Request request)
Authenticate this request. If the is successfully then the user will be logged into Vireo's SecurityContext, and an AuthenticationResult.SUCCESSFULL result.
If authentication is anything other than successful then one of the failure result codes should be returned.
MISSING_CREDENTIALS: Some or all of the required credentials were missing from the authentication request.
BAD_CREDENTIALS: All the required credentials were available but they were not be able to be verified as valid.
UNKNOWN_FAILURE: This is the catch all case for unforeseen errors conditions.
Parameters
request The HTTP request to be authenticated.
Returns
The result of authentication.
Implements org.tdl.vireo.security.AuthenticationMethod.Implicit.
Definition at line 253 of file ShibbolethAuthenticationMethodImpl.java.
References org.tdl.vireo.security.AuthenticationResult.BAD_CREDENTIALS, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.getAttributes(), org.tdl.vireo.model.Person.getBirthYear(), org.tdl.vireo.model.Person.getCurrentCollege(), org.tdl.vireo.model.Person.getCurrentDegree(), org.tdl.vireo.model.Person.getCurrentDepartment(), org.tdl.vireo.model.Person.getCurrentEmailAddress(), org.tdl.vireo.model.Person.getCurrentGraduationMonth(), org.tdl.vireo.model.Person.getCurrentGraduationYear(), org.tdl.vireo.model.Person.getCurrentMajor(), org.tdl.vireo.model.Person.getCurrentPhoneNumber(), org.tdl.vireo.model.Person.getCurrentPostalAddress(), org.tdl.vireo.model.Person.getMiddleName(), org.tdl.vireo.model.Person.getOrcid(), org.tdl.vireo.model.Person.getPermanentEmailAddress(), org.tdl.vireo.model.Person.getPermanentPhoneNumber(), org.tdl.vireo.model.Person.getPermanentPostalAddress(), org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.getSingleAttribute(), org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerAffiliations, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerBirthYear, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentCollege, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentDegree, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentDepartment, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentEmailAddress, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentGraduationMonth, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentGraduationYear, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentMajor, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentPhoneNumber, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentPostalAddress, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerEmail, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerFirstName, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerInstitutionalIdentifier, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerLastName, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerMiddleName, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerNetId, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerOrcid, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerPermanentEmailAddress, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerPermanentPhoneNumber, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerPermanentPostalAddress, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.isEmpty(), org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.logShib, org.tdl.vireo.security.AuthenticationResult.MISSING_CREDENTIALS, org.tdl.vireo.model.Person.setCurrentCollege(), org.tdl.vireo.model.Person.setCurrentDegree(), org.tdl.vireo.model.Person.setCurrentDepartment(), org.tdl.vireo.model.Person.setCurrentEmailAddress(), org.tdl.vireo.model.Person.setCurrentMajor(), org.tdl.vireo.model.Person.setCurrentPhoneNumber(), org.tdl.vireo.model.Person.setCurrentPostalAddress(), org.tdl.vireo.model.Person.setMiddleName(), org.tdl.vireo.model.Person.setOrcid(), org.tdl.vireo.model.Person.setPermanentEmailAddress(), org.tdl.vireo.model.Person.setPermanentPhoneNumber(), org.tdl.vireo.model.Person.setPermanentPostalAddress(), org.tdl.vireo.model.RoleType.STUDENT, org.tdl.vireo.security.AuthenticationResult.SUCCESSFULL, and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.useNetIdAsIdentifier.
{
         // 1. Log all headers received, if tracing (it fills up the logs fast!)
         if (Logger.isTraceEnabled() || logShib) {
             String log = "Shib: Recieved the following headers: \n";
             if(request != null) {
                 for (String name : request.headers.keySet()) {
                     for (String value : request.headers.get(name).values) {
                         log += "    '" + name + "' = '" + value + "'\n";
                     }
                 }
             } else {
                 log += "NONE!";
             }
             // save configured level
             String configuredLogLevel = Play.configuration.getProperty("application.log", "");
             //only override log-level if:
             // 1) Logger is not already at TRACE level
             // 2) Logger was not configured manually
             // and
             // 3) we can put it back
             if(!Logger.isTraceEnabled() && !Logger.configuredManually && !configuredLogLevel.isEmpty()) {
                 Logger.setUp("TRACE");
             }
             else {
                 configuredLogLevel = "";
             }
             if (Logger.isTraceEnabled()) {
                 Logger.trace(log);
             }
             // if we overrode the log-level, put it back
             if(!configuredLogLevel.isEmpty()) {
                 // restore configured level
                 Logger.setUp(configuredLogLevel);
             }
         }
         // 2. Get required attributes.
         String netid = getSingleAttribute(request, headerNetId);
         String email = getSingleAttribute(request, headerEmail);
         String firstName = getSingleAttribute(request, headerFirstName);
         String lastName = getSingleAttribute(request, headerLastName);
         if (useNetIdAsIdentifier && netid == null) {
             Logger.error("Shib: Missing required NetId attributes because netid is the primary account identifier. Netid attribute header = %1s.", headerNetId);
             return AuthenticationResult.MISSING_CREDENTIALS;
         }
         if (email == null ) {
             Logger.error("Shib: Missing required email address attributes. Email address attribute header = %1s.", headerEmail);
             return AuthenticationResult.MISSING_CREDENTIALS;
         }
         if (firstName == null && lastName == null) {
             Logger.error("Shib: Missing required first and last name attributes. First Name attribute header = %1s, Last Name attribute header = %2s", headerFirstName, headerLastName);
             return AuthenticationResult.MISSING_CREDENTIALS;
         }
         // 3. Lookup the person based upon the primary identifier
         Person person;
         try {
             context.turnOffAuthorization();
             if (useNetIdAsIdentifier) {
                 person = personRepo.findPersonByNetId(netid);
             } else {
                 person = personRepo.findPersonByEmail(email);
             }
             if (person == null) {
                 // Create the new person
                 try {
                     person = personRepo.createPerson(netid, email, firstName, lastName, RoleType.STUDENT).save();
                 } catch (RuntimeException re) {
                     // Unable to create new person, probably because the email or netid already exist.
                     Logger.error(re,"Shib: Unable to create new eperson.");
                     return AuthenticationResult.BAD_CREDENTIALS;
                 }
             } else {
                 // Update required fields.
                 if (netid != null)
                     person.setNetId(netid);
                 person.setEmail(email);
                 person.setFirstName(firstName);
                 person.setLastName(lastName);
             }
             // 4. Update Optional attributes:
             if (headerInstitutionalIdentifier != null) {
                 String identifier = getSingleAttribute(request, headerInstitutionalIdentifier);
                 if (!isEmpty(identifier))
                     person.setInstitutionalIdentifier(identifier);
             }
             if (headerMiddleName != null) {
                 String middleName = getSingleAttribute(request, headerMiddleName);
                 if (!isEmpty(middleName) && person.getMiddleName() == null)
                     person.setMiddleName(middleName);
             }
             if (headerBirthYear != null) {
                 String birthYearString = getSingleAttribute(request, headerBirthYear);
                 if (!isEmpty(birthYearString) && person.getBirthYear() == null) {
                     try {
                         Integer birthYear = Integer.valueOf(birthYearString);
                         person.setBirthYear(birthYear);
                     } catch (NumberFormatException nfe) {
                         Logger.warn("Shib: Unable to interpret birth year attribute '"+headerBirthYear+"'='"+birthYearString+"' as an integer.");
                     }
                 }
             }
             if (headerAffiliations != null) {
                 List<String> affiliations = getAttributes(request, headerAffiliations);
                 if (affiliations != null && affiliations.size() > 0) {
                     person.getAffiliations().clear();
                     if (affiliations != null)
                         person.getAffiliations().addAll(affiliations);
                 }
             }
             if (headerCurrentPhoneNumber != null) {
                 String currentPhoneNumber = getSingleAttribute(request, headerCurrentPhoneNumber);
                 if (!isEmpty(currentPhoneNumber) && person.getCurrentPhoneNumber() == null)
                     person.setCurrentPhoneNumber(currentPhoneNumber);
             }
             if (headerCurrentPostalAddress != null) {
                 String currentPostalAddress = getSingleAttribute(request, headerCurrentPostalAddress);
                 if (!isEmpty(currentPostalAddress) && person.getCurrentPostalAddress() == null)
                     person.setCurrentPostalAddress(currentPostalAddress);
             }
             if (headerCurrentEmailAddress != null) {
                 String currentEmailAddress = getSingleAttribute(request, headerCurrentEmailAddress);
                 if (!isEmpty(currentEmailAddress) && person.getCurrentEmailAddress() == null)
                     person.setCurrentEmailAddress(currentEmailAddress);
             }
             if (headerPermanentPhoneNumber != null) {
                 String permanentPhoneNumber = getSingleAttribute(request, headerPermanentPhoneNumber);
                 if (!isEmpty(permanentPhoneNumber) && person.getPermanentPhoneNumber() == null)
                     person.setPermanentPhoneNumber(permanentPhoneNumber);
             }
             if (headerPermanentPostalAddress != null) {
                 String permanentPostalAddress = getSingleAttribute(request, headerPermanentPostalAddress);
                 if (!isEmpty(permanentPostalAddress) && person.getPermanentPostalAddress() == null)
                     person.setPermanentPostalAddress(permanentPostalAddress);
             }
             if (headerPermanentEmailAddress != null) {
                 String permanentEmailAddress = getSingleAttribute(request, headerPermanentEmailAddress);
                 if (!isEmpty(permanentEmailAddress) && person.getPermanentEmailAddress() == null)
                     person.setPermanentEmailAddress(permanentEmailAddress);
             }
             if (headerCurrentDegree != null) {
                 String currentDegree = getSingleAttribute(request, headerCurrentDegree);
                 if (!isEmpty(currentDegree) && person.getCurrentDegree() == null)
                     person.setCurrentDegree(currentDegree);
             }
             if (headerCurrentDepartment != null) {
                 String currentDepartment = getSingleAttribute(request, headerCurrentDepartment);
                 if (!isEmpty(currentDepartment) && person.getCurrentDepartment() == null)
                     person.setCurrentDepartment(currentDepartment);
             }
             if (headerCurrentCollege != null) {
                 String currentCollege = getSingleAttribute(request, headerCurrentCollege);
                 if (!isEmpty(currentCollege) && person.getCurrentCollege() == null)
                     person.setCurrentCollege(currentCollege);
             }
             if (headerCurrentMajor != null) {
                 String currentMajor = getSingleAttribute(request, headerCurrentMajor);
                 if (!isEmpty(currentMajor) && person.getCurrentMajor() == null)
                     person.setCurrentMajor(currentMajor);
             }
             if (headerCurrentGraduationYear != null) {
                 String currentGraduationYearString = getSingleAttribute(request, headerCurrentGraduationYear);
                 if (!isEmpty(currentGraduationYearString) && person.getCurrentGraduationYear() == null) {
                     try {
                         Integer currentGraduationYear = Integer.valueOf(currentGraduationYearString);
                         person.setCurrentGraduationYear(currentGraduationYear);
                     } catch (NumberFormatException nfe) {
                         Logger.warn("Shib: Unable to interpret current graduation year attribute '"+headerCurrentGraduationYear+"'='"+currentGraduationYearString+"' as an integer.");
                     }
                 }
             }
             if (headerCurrentGraduationMonth != null) {
                 String currentGraduationMonthString = getSingleAttribute(request, headerCurrentGraduationMonth);
                 if (!isEmpty(currentGraduationMonthString) && person.getCurrentGraduationMonth() == null) {
                     try {
                         Integer currentGraduationMonth = Integer.valueOf(currentGraduationMonthString);
                         person.setCurrentGraduationMonth(currentGraduationMonth);
                     } catch (NumberFormatException nfe) {
                         Logger.warn("Shib: Unable to interpret current graduation month attribute '"+headerCurrentGraduationMonth+"'='"+currentGraduationMonthString+"' as an integer.");
                     } catch (IllegalArgumentException iae) {
                         Logger.warn("Shib: Illegal value for current graduation month attribute '"+headerCurrentGraduationMonth+"'='"+currentGraduationMonthString+"', 0=January, 11=Dember. Any values outside this range are illegal.");
                     }
                 }
             }
             if (headerOrcid != null) {
                 String orcidString = getSingleAttribute(request, headerOrcid);
                 if (!isEmpty(orcidString) && person.getOrcid() == null)
                     person.setOrcid(orcidString);
             }
             person.save();
         } finally {
             context.restoreAuthorization();
         }
         context.login(person);
         return AuthenticationResult.SUCCESSFULL;
     }
List<String> org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.getAttributes (Request request, String attribute) protected
Internal method for retrieving a list of shibboleth attribute values. Shibboleth attributes may contain multiple values separated by a semicolon and semicolons are escaped with a backslash. This method will split all the attributes into a list and unescape semicolons.
Parameters
request The HTTP request object
attribute The name of the attribute header.
Returns
A list of attributes, or null if not found.
Definition at line 561 of file ShibbolethAuthenticationMethodImpl.java.
References org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.mock.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.getSingleAttribute().
{
         // Get the attribute header
         String valueString = null;
         if (mock) {
             valueString = mockAttributes.get(attribute);
         } else {
             Header header = request.headers.get(attribute);
             if (header == null || header.values == null || header.values.size() == 0)
                 return null;
             if (header.values.size() > 1)
                 Logger.warn("Shib: Recieved multiple shibboleth attributes for '" + attribute
                         + "'. Using the first one and ignoring the rest.");
             valueString = header.value();
         }
         if (valueString == null) {
             Logger.warn("Shib: Recieved shibboleth attribute for '" + attribute
                     + "' but the value was null.");
             return null;
         }
         // Split the attribute into it's individual components.
         List<String> valueList = new ArrayList<String>();
         int idx = 0;
         do {
             idx = valueString.indexOf(';', idx);
             if (idx == 0) {
                 // if the string starts with a semicolon just remove it. This
                 // will
                 // prevent an endless loop in an error condition.
                 valueString = valueString.substring(1, valueString.length());
                 continue;
             }
             if (idx > 0 && valueString.charAt(idx - 1) == '\\') {
                 idx++;
                 continue;
             }
             if (idx > 0 ) {
                 // First extract the value and store it on the list.
                 String value = valueString.substring(0, idx);
                 value = value.replaceAll("\\\\;", ";");
                 valueList.add(value);
                 // Next, remove the value from the string and continue to scan.
                 valueString = valueString.substring(idx + 1, valueString.length());
                 idx = 0;
             }
         } while (idx >= 0);
         // The last attribute will still be left on the values string, put it
         // into the list.
         if (valueString.length() > 0) {
             valueString = valueString.replaceAll("\\\\;", ";");
             valueList.add(valueString);
         }
         return valueList;
     }
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.getFailureMessage (Request request, AuthenticationResult result)
After an authentication failure from an implicit login an error message will be displayed. This message may be customized by the authentication method to provide additional details about why the error occurred and maybe some hits as to how to fix it.
For example the shibboleth plugin may list the headers that it received aiding the user, vireo administrator, and shibboleth administrator in debuging what the problem is.
If this method returns null then the UI will display a generalized message based upon the Authentication Result provided.
Parameters
request The same request that caused an Authentication failure.
Returns
An additional error message, or null if there is none.
Implements org.tdl.vireo.security.AuthenticationMethod.Implicit.
Definition at line 460 of file ShibbolethAuthenticationMethodImpl.java.
References org.tdl.vireo.security.AuthenticationResult.BAD_CREDENTIALS, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.getSingleAttribute(), org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerEmail, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerFirstName, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerLastName, and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerNetId.
{
         StringBuilder msg = new StringBuilder();
         if (AuthenticationResult.BAD_CREDENTIALS == result ) {
             msg.append("<p>Shibboleth authentication recieved the required attributes but was unable to create a new account. The most likely cause is because an account with the same netid or email already exists in the system.</p>");
         } else {
             msg.append("<p>Shibboleth authentication failed because it did not recieve enough information from your Shibboleth Identity Provider. Vireo requires four attributes Netid, Email, and your First and Last name. If any of these are missing then authentication will fail. Below is a listing of the attributes we did recieve:</p>");
         }
         msg.append("<dl class=\"dl-horizontal\">");
         msg.append("<dt>NetId:</dt>");
         String netid = getSingleAttribute(request, headerNetId);
         if (netid != null)
             msg.append("<dd><code>'"+headerNetId+"' = '"+netid+"'</code></dd>");
         else
             msg.append("<dd><code>'"+headerNetId+"' = null</code></dd>");
         msg.append("<br/>");
         msg.append("<dt>Email Address:</dt>");
         String email = getSingleAttribute(request, headerEmail);
         if (email != null)
             msg.append("<dd><code>'"+headerEmail+"' = '"+email+"'</code></dd>");
         else
             msg.append("<dd><code>'"+headerEmail+"' = null</code></dd>");
         msg.append("<br/>");
         msg.append("<dt>First Name:</dt>");
         String firstName = getSingleAttribute(request, headerFirstName);
         if (firstName != null)
             msg.append("<dd><code>'"+headerFirstName+"' = '"+firstName+"'</code></dd>");
         else
             msg.append("<dd><code>'"+headerFirstName+"' = null</code></dd>");
         msg.append("<br/>");
         msg.append("<dt>Last Name:</dt>");
         String lastName = getSingleAttribute(request, headerLastName);
         if (lastName != null)
             msg.append("<dd><code>'"+headerLastName+"' = '"+lastName+"'</code></dd>");
         else
             msg.append("<dd><code>'"+headerLastName+"' = null</code></dd>");
         msg.append("</dl>");
         msg.append("<p>Please contact your university Information Technology support at your local campus for trouble shooting this problem.</p>");
         return msg.toString();
     }
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.getSingleAttribute (Request request, String attribute) protected
Internal method for retrieving a single shibboleth attribute value. If there are multiple values encoded in the header then only the first one is returned and all others are ignored.
Parameters
request The HTTP Request object
attribute The name of the attribute header.
Returns
The attribute value, or null if not found.
Definition at line 538 of file ShibbolethAuthenticationMethodImpl.java.
References org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.getAttributes().
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.getFailureMessage().
{
         List<String> attributes = getAttributes(request, attribute);
         if (attributes == null || attributes.size() == 0)
             return null;
         return attributes.get(0);
     }
static boolean org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.isEmpty (String value) static private
Parameters
value The value to be tested.
Returns
true if the value is either null, or only consists of whitespace. Otherwise return false.
Definition at line 627 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate().
{
         if (value == null)
             return true;
         if (value.trim().length() == 0)
             return true;
         return false;
     }
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.logout (Request request, String returnURL)
Logout the user out of this implicit authentication. This may require redirecting the user off to an external service to complete the logout. If so this method should return the URL to redirect the user to, and the included returnURL is where the user should be sent after successfully logging out.
If no redirection is required then null should be returned. This will still cause the user to be logged out of the application and their session cleared.
Parameters
request The HTTP request
returnURL The URL where the user should be redirected to back to the Application after logging.
Returns
The URL to initiate a logout request, or null if no redirection is required.
Implements org.tdl.vireo.security.AuthenticationMethod.Implicit.
Definition at line 510 of file ShibbolethAuthenticationMethodImpl.java.
References org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.logoutEnabled, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.logoutURL, and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.mock.
{
         // If we are mocking a shibboleth connection we don't do a full shib logout.
         if (mock)
             return null;
         // Is logout enabled?
         if (!logoutEnabled)
             return null;
         // Generate the URL to initiate a shibboleth session
         String encodedReturnURL = URLEncoder.encode(returnURL);
         String completeLoginoutURL = String.format(logoutURL,encodedReturnURL);
         return completeLoginoutURL;
     }
void org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap (Map< String, String > attributeMap)
Set the shibboleth header mapping to Vireo attributes. The keys of the map must equal one of the keys defined bellow. Then the value of that key must be the expected header name for that particular attribute. For a definition of what each attribute is, see the Person model.
Required Mappings: netId*, email, firstName, lastName.
Optional Mappings: middleName, displayName, birthYear, currentPhoneNumber, currentPostalAddress, currentEmailAddress, permanentPhoneNumber, permanentPostalAddress, permanentEmailAddress, currentDepartment, currentCollege, currentMajor, currentGraduationYear, currentGraduationMonth.
netId is only required if useNetIdAsIdentifier is turned on.
Parameters
attributeMap
Definition at line 197 of file ShibbolethAuthenticationMethodImpl.java.
References org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerAffiliations, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerBirthYear, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentCollege, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentDegree, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentDepartment, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentEmailAddress, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentGraduationMonth, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentGraduationYear, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentMajor, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentPhoneNumber, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentPostalAddress, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerEmail, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerFirstName, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerInstitutionalIdentifier, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerLastName, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerMiddleName, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerNetId, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerOrcid, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerPermanentEmailAddress, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerPermanentPhoneNumber, and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerPermanentPostalAddress.
{
         // Check for required mappings
         headerNetId = attributeMap.get("netId");
         headerEmail = attributeMap.get("email");
         headerFirstName = attributeMap.get("firstName");
         headerLastName = attributeMap.get("lastName");
         if (headerEmail == null || headerFirstName == null || headerLastName == null) {
             throw new IllegalArgumentException("Missing required attributes in the provided attributeMap.");
         }
         // Store all the optional attributes.
         headerInstitutionalIdentifier = attributeMap.get("institutionalIdentifier");
         headerMiddleName = attributeMap.get("middleName");
         headerBirthYear = attributeMap.get("birthYear");
         headerAffiliations = attributeMap.get("affiliations");
         headerCurrentPhoneNumber = attributeMap.get("currentPhoneNumber");
         headerCurrentPostalAddress = attributeMap.get("currentPostalAddress");
         headerCurrentEmailAddress = attributeMap.get("currentEmailAddress");
         headerPermanentPhoneNumber = attributeMap.get("permanentPhoneNumber");
         headerPermanentPostalAddress = attributeMap.get("permanentPostalAddress");
         headerPermanentEmailAddress = attributeMap.get("permanentEmailAddress");
         headerCurrentDegree = attributeMap.get("currentDegree");
         headerCurrentDepartment = attributeMap.get("currentDepartment");
         headerCurrentCollege = attributeMap.get("currentCollege");
         headerCurrentMajor = attributeMap.get("currentMajor");
         headerCurrentGraduationYear = attributeMap.get("currentGraduationYear");
         headerCurrentGraduationMonth = attributeMap.get("currentGraduationMonth");
         headerOrcid = attributeMap.get("orcid");
     }
void org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setLoginForceSSL (boolean loginForceSSL)
Set whether the current protocol should be overridden for any login request to force it to SSL. If this is turned off then login requests will be handled using the protocol under which they were received.
Parameters
loginForceSSL Whether to force SSL for login.
Definition at line 91 of file ShibbolethAuthenticationMethodImpl.java.
References org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.loginForceSSL.
{
         this.loginForceSSL = loginForceSSL;
     }
void org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setLoginURL (String loginURL)
Set the shibboleth login initiation url. This is a standard java format string, where the first parameter is a string representation of the return url. The return url is where shibboleth should send the user to after successfully authenticating via shibboleth. The application will intercept this url, and send the request to be authenticated by this plugin.
Parameters
loginURL The shibboleth login initiator
Definition at line 105 of file ShibbolethAuthenticationMethodImpl.java.
References org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.loginURL.
{
         this.loginURL = loginURL;
     }
void org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setLogoutEnabled (boolean enabled)
Parameters
enabled True if shibboleth logout should be enabled by this application. If this is enabled make sure to set the logoutURL initator as well.
Definition at line 175 of file ShibbolethAuthenticationMethodImpl.java.
References org.tdl.vireo.security.impl.AbstractAuthenticationMethodImpl.enabled.
{
         this.logoutEnabled = enabled;
     }
void org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setLogoutURL (String logoutURL)
Set the shibboleth logout initaitor url. This is a standard java format string, where the first paramater is a string representation of the return url. The url is where shibboleth should send the user after succesfully logging out.
Note: for this value to take effect you also need to enable the logout feature: setLogoutEnabled(true);
Parameters
logoutURL The shibboleth logout initiator
Definition at line 120 of file ShibbolethAuthenticationMethodImpl.java.
References org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.logoutURL.
{
         this.logoutURL = logoutURL;
     }
void org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setMock (boolean mock)
Parameters
mock True if shibboleth authentication should be mocked with test attributes. This allows you to use the application without it actualy running behind a shibboleth.
Definition at line 130 of file ShibbolethAuthenticationMethodImpl.java.
References org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.mock.
{
         this.mock = mock;
     }
void org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setMockAttributes (Map< String, String > mockAttributes)
If this authentication method is configured to Mock a shibboleth connection then these are the shibboleth attributes that will be assumed when authenticating.
The map should contain the configured Shibboleth HTTP Header names as keys to the map, while the value should be the actual value (or values) of the shibboleth attribute.
Parameters
mockAttributes A map of mock shibboleth attributes.
Definition at line 146 of file ShibbolethAuthenticationMethodImpl.java.
References org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.mockAttributes.
{
         this.mockAttributes = mockAttributes;
     }
void org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setPrimaryIdentifier (String primaryIdentifier)
Set the primary account identifier, the only valid responses are "netid", or "email". The field set will be used to uniquely identify person objects.
Parameters
primaryIdentifier Either "netid" or "email".
Definition at line 158 of file ShibbolethAuthenticationMethodImpl.java.
References org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.useNetIdAsIdentifier.
{
         if ("netid".equals(primaryIdentifier)) {
             useNetIdAsIdentifier = true;
         } else if ("email".equals(primaryIdentifier)) {
             useNetIdAsIdentifier = false;
         } else {
             throw new IllegalArgumentException("Invalid primary identifier: "+primaryIdentifier+", the only valid options are 'netid' or 'email'.");
         }
     }
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.startAuthentication (Request request, ActionDefinition returnAction)
Start the implicit authentication process. If the process requires the user to be redirected to an external service then the URL where the user should be redirected to is to be returned. After users have successfully authenticated with the external service they must return to vireo using the returnURL provided.
If this method does not require redirection, such as in the case of X.509 certificates then null should be returned. In that case the authentication method will be immediately called.
Parameters
request The HTTP request object.
returnAction The Play action to handle return authentication.
Returns
The URL to redirect the user initiating authentication, or null if no redirection is required.
Implements org.tdl.vireo.security.AuthenticationMethod.Implicit.
Definition at line 231 of file ShibbolethAuthenticationMethodImpl.java.
References org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.loginForceSSL, org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.loginURL, and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.mock.
{
         // If we are mocking a shibboleth connection then we can proceed straight to authentication.
         if (mock)
             return null;
         String returnURL = returnAction.url;
         if (loginForceSSL) {
             returnAction.absolute();
             returnURL = returnAction.url;
             if (returnURL.startsWith("http://"))
                 returnURL = "https://"+returnURL.substring(7);
         }
         // Generate the URL to initiate a shibboleth session
         String encodedReturnURL = URLEncoder.encode(returnURL);
         String completeLoginURL = String.format(loginURL,encodedReturnURL);
         return completeLoginURL;
     }
Member Data Documentation
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerAffiliations = "SHIB_eduPersonAffilation"
Definition at line 64 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerBirthYear = "SHIB_dateOfBirth"
Definition at line 63 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentCollege = "SHIB_college"
Definition at line 73 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentDegree = "SHIB_degree"
Definition at line 71 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentDepartment = "SHIB_department"
Definition at line 72 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentEmailAddress = "SHIB_mail"
Definition at line 67 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentGraduationMonth = "SHIB_gradMonth"
Definition at line 76 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentGraduationYear = "SHIB_gradYear"
Definition at line 75 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentMajor = "SHIB_major"
Definition at line 74 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentPhoneNumber = "SHIB_phone"
Definition at line 65 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerCurrentPostalAddress = "SHIB_postal"
Definition at line 66 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerEmail = "SHIB_mail"
Definition at line 58 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.getFailureMessage(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerFirstName = "SHIB_givenname"
Definition at line 60 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.getFailureMessage(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerInstitutionalIdentifier = "SHIB_uin"
Definition at line 59 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerLastName = "SHIB_sn"
Definition at line 62 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.getFailureMessage(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerMiddleName = "SHIB_initials"
Definition at line 61 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerNetId = "SHIB_netid"
Definition at line 57 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.getFailureMessage(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerOrcid = "SHIB_orcid"
Definition at line 77 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerPermanentEmailAddress = "SHIB_permanentMail"
Definition at line 70 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerPermanentPhoneNumber = "SHIB_permanentPhone"
Definition at line 68 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.headerPermanentPostalAddress = "SHIB_permanentPostal"
Definition at line 69 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setAttributeMap().
boolean org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.loginForceSSL = false
Definition at line 48 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setLoginForceSSL(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.startAuthentication().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.loginURL = "/Shibboleth.sso/Login?target=%1s"
Definition at line 44 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setLoginURL(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.startAuthentication().
boolean org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.logoutEnabled = false
Definition at line 54 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.logout().
String org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.logoutURL = "/Shibboleth.sso/Logout?return=%1s"
Definition at line 45 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.logout(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setLogoutURL().
boolean org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.logShib = Play.configuration.getProperty("auth.shib.log").equals("true")
Definition at line 41 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate().
boolean org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.mock = (Play.configuration.getProperty("auth.shib.mock").equals("true") || Play.mode == Mode.DEV)
Definition at line 38 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.getAttributes(), org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.logout(), org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setMock(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.startAuthentication().
Map<String,String> org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.mockAttributes = new HashMap<String,String>()
Definition at line 80 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setMockAttributes().
boolean org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.useNetIdAsIdentifier = true
Definition at line 51 of file ShibbolethAuthenticationMethodImpl.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.setPrimaryIdentifier().
The documentation for this class was generated from the following file:
app/org/tdl/vireo/security/impl/ShibbolethAuthenticationMethodImpl.java