Vireo: org.tdl.vireo.model.RoleType Enum Reference
org.tdl.vireo.model.RoleType Enum Reference
Public Member Functions
int getId ()
Static Public Member Functions
static RoleType find (int id)
Public Attributes
NONE =(0)
STUDENT =(1)
REVIEWER =(2)
MANAGER =(3)
ADMINISTRATOR =(4)
Private Member Functions
RoleType (int id)
Private Attributes
int id
Detailed Description
The possible roles a person may be within vireo.
Author
Scott Phillips
Definition at line 8 of file RoleType.java.
Constructor & Destructor Documentation
org.tdl.vireo.model.RoleType.RoleType (int id) private
Private constructor for the defined role types listed above.
Parameters
id The id of the degree level.
Definition at line 26 of file RoleType.java.
{
         this.id = id;
     }
Member Function Documentation
static RoleType org.tdl.vireo.model.RoleType.find (int id) static
Locate a role type based upon it's id.
Parameters
id The id of the desired role.
Returns
The role, or null if not found.
Definition at line 44 of file RoleType.java.
{
         for (RoleType role : RoleType.values()) {
             if (role.id == id)
                 return role;
         }
         return null;
     }
int org.tdl.vireo.model.RoleType.getId ()
Returns
The id of this role.
Definition at line 33 of file RoleType.java.
{
         return id;
     }
Member Data Documentation
org.tdl.vireo.model.RoleType.ADMINISTRATOR =(4)
Definition at line 13 of file RoleType.java.
Referenced by controllers.FirstUser.createUser(), org.tdl.vireo.security.impl.SecurityContextImpl.isAdministrator(), org.tdl.vireo.security.impl.SecurityContextImpl.isManager(), org.tdl.vireo.security.impl.SecurityContextImpl.isReviewer(), org.tdl.vireo.security.impl.SecurityContextImpl.isStudent(), and org.tdl.vireo.model.jpa.JpaPersonImpl.setRole().
int org.tdl.vireo.model.RoleType.id private
Definition at line 18 of file RoleType.java.
org.tdl.vireo.model.RoleType.MANAGER =(3)
Definition at line 12 of file RoleType.java.
Referenced by org.tdl.vireo.security.impl.SecurityContextImpl.isManager(), org.tdl.vireo.security.impl.SecurityContextImpl.isReviewer(), org.tdl.vireo.security.impl.SecurityContextImpl.isStudent(), and org.tdl.vireo.model.jpa.JpaPersonImpl.setRole().
org.tdl.vireo.model.RoleType.NONE =(0)
Definition at line 9 of file RoleType.java.
org.tdl.vireo.model.RoleType.REVIEWER =(2)
Definition at line 11 of file RoleType.java.
Referenced by controllers.settings.ApplicationSettingsTab.applicationSettings(), org.tdl.vireo.security.impl.SecurityContextImpl.isReviewer(), org.tdl.vireo.security.impl.SecurityContextImpl.isStudent(), controllers.FilterTab.list(), controllers.settings.ApplicationSettingsTab.searchMembers(), org.tdl.vireo.model.jpa.JpaPersonImpl.setRole(), controllers.settings.ApplicationSettingsTab.updatePersonRole(), and controllers.ViewTab.view().
org.tdl.vireo.model.RoleType.STUDENT =(1)
Definition at line 10 of file RoleType.java.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), org.tdl.vireo.security.impl.SecurityContextImpl.isStudent(), controllers.Authentication.register(), and org.tdl.vireo.model.jpa.JpaPersonImpl.setRole().
The documentation for this enum was generated from the following file:
app/org/tdl/vireo/model/RoleType.java