Vireo: org.tdl.vireo.search.SearchFacet Enum Reference
org.tdl.vireo.search.SearchFacet Enum Reference
Public Member Functions
int getId ()
Static Public Member Functions
static SearchFacet find (int id)
Public Attributes
TEXT =(1)
STATE =(2)
ASSIGNEE =(3)
GRADUATION_SEMESTER =(4)
DEPARTMENT =(5)
PROGRAM =(6)
COLLEGE =(7)
MAJOR =(8)
EMBARGO =(9)
DEGREE =(10)
DOCUMENT_TYPE =(11)
UMI_RELEASE =(12)
DATE_CHOOSE =(13)
DATE_RANGE =(14)
CUSTOM_ACTIONS =(15)
Private Member Functions
SearchFacet (int id)
Private Attributes
int id
Detailed Description
List of filter paramater types. These values may be set as various datatypes in on the SearchFilter object. The main purpose of this class is to provide a listing of all possible search parameters and assigned ids for easier retrieval.
Author
Scott Phillips
Definition at line 11 of file SearchFacet.java.
Constructor & Destructor Documentation
org.tdl.vireo.search.SearchFacet.SearchFacet (int id) private
Private constructor for the defined search facet listed above.
Parameters
id The id of the search facet.
Definition at line 38 of file SearchFacet.java.
{
         this.id = id;
     }
Member Function Documentation
static SearchFacet org.tdl.vireo.search.SearchFacet.find (int id) static
Locate a search facet based upon it's id.
Parameters
id The of the search facet.
Returns
The search facet, or null if not found.
Definition at line 56 of file SearchFacet.java.
{
         for (SearchFacet searchFacet : SearchFacet.values()) {
             if (searchFacet.id == id)
                 return searchFacet;
         }
         return null;
     }
int org.tdl.vireo.search.SearchFacet.getId ()
Returns
The code of this search facet.
Definition at line 45 of file SearchFacet.java.
{
         return id;
     }
Member Data Documentation
org.tdl.vireo.search.SearchFacet.ASSIGNEE =(3)
Definition at line 15 of file SearchFacet.java.
Referenced by controllers.FilterTab.getDefaultFacets().
org.tdl.vireo.search.SearchFacet.COLLEGE =(7)
Definition at line 19 of file SearchFacet.java.
org.tdl.vireo.search.SearchFacet.CUSTOM_ACTIONS =(15)
Definition at line 27 of file SearchFacet.java.
org.tdl.vireo.search.SearchFacet.DATE_CHOOSE =(13)
Definition at line 25 of file SearchFacet.java.
org.tdl.vireo.search.SearchFacet.DATE_RANGE =(14)
Definition at line 26 of file SearchFacet.java.
Referenced by controllers.FilterTab.getDefaultFacets().
org.tdl.vireo.search.SearchFacet.DEGREE =(10)
Definition at line 22 of file SearchFacet.java.
org.tdl.vireo.search.SearchFacet.DEPARTMENT =(5)
Definition at line 17 of file SearchFacet.java.
org.tdl.vireo.search.SearchFacet.DOCUMENT_TYPE =(11)
Definition at line 23 of file SearchFacet.java.
org.tdl.vireo.search.SearchFacet.EMBARGO =(9)
Definition at line 21 of file SearchFacet.java.
org.tdl.vireo.search.SearchFacet.GRADUATION_SEMESTER =(4)
Definition at line 16 of file SearchFacet.java.
Referenced by controllers.FilterTab.getDefaultFacets().
int org.tdl.vireo.search.SearchFacet.id private
Definition at line 30 of file SearchFacet.java.
org.tdl.vireo.search.SearchFacet.MAJOR =(8)
Definition at line 20 of file SearchFacet.java.
org.tdl.vireo.search.SearchFacet.PROGRAM =(6)
Definition at line 18 of file SearchFacet.java.
org.tdl.vireo.search.SearchFacet.STATE =(2)
Definition at line 14 of file SearchFacet.java.
Referenced by controllers.FilterTab.getDefaultFacets().
org.tdl.vireo.search.SearchFacet.TEXT =(1)
Definition at line 13 of file SearchFacet.java.
Referenced by controllers.FilterTab.getDefaultFacets().
org.tdl.vireo.search.SearchFacet.UMI_RELEASE =(12)
Definition at line 24 of file SearchFacet.java.
The documentation for this enum was generated from the following file:
app/org/tdl/vireo/search/SearchFacet.java