Vireo: org.tdl.vireo.model.DegreeLevel Enum Reference
org.tdl.vireo.model.DegreeLevel Enum Reference
Public Member Functions
int getId ()
Static Public Member Functions
static DegreeLevel find (int id)
Public Attributes
NONE =(1)
UNDERGRADUATE =(2)
MASTERS =(3)
DOCTORAL =(4)
Private Member Functions
DegreeLevel (int id)
Private Attributes
int id
Detailed Description
The possible degree levels supported by vireo.
Author
Scott Phillips
Definition at line 9 of file DegreeLevel.java.
Constructor & Destructor Documentation
org.tdl.vireo.model.DegreeLevel.DegreeLevel (int id) private
Private constructor for the defined degree levels listed above.
Parameters
id The id of the degree level.
Definition at line 24 of file DegreeLevel.java.
{
         this.id = id;
     }
Member Function Documentation
static DegreeLevel org.tdl.vireo.model.DegreeLevel.find (int id) static
Locate a degree level based upon it's id.
Parameters
id The id of the desired level.
Returns
The level, or null if not found.
Definition at line 42 of file DegreeLevel.java.
{
         for (DegreeLevel level : DegreeLevel.values()) {
             if (level.id == id)
                 return level;
         }
         return null;
     }
int org.tdl.vireo.model.DegreeLevel.getId ()
Returns
The id of this level.
Definition at line 31 of file DegreeLevel.java.
{
         return id;
     }
Member Data Documentation
org.tdl.vireo.model.DegreeLevel.DOCTORAL =(4)
Definition at line 13 of file DegreeLevel.java.
Referenced by controllers.settings.ConfigurableSettingsTab.configurableSettings(), and controllers.FirstUser.createUser().
int org.tdl.vireo.model.DegreeLevel.id private
Definition at line 16 of file DegreeLevel.java.
org.tdl.vireo.model.DegreeLevel.MASTERS =(3)
Definition at line 12 of file DegreeLevel.java.
Referenced by controllers.settings.ConfigurableSettingsTab.configurableSettings(), controllers.FirstUser.createUser(), and controllers.settings.ApplicationSettingsTab.submitTestItem().
org.tdl.vireo.model.DegreeLevel.NONE =(1)
Definition at line 10 of file DegreeLevel.java.
org.tdl.vireo.model.DegreeLevel.UNDERGRADUATE =(2)
Definition at line 11 of file DegreeLevel.java.
Referenced by controllers.settings.ConfigurableSettingsTab.configurableSettings(), and controllers.FirstUser.createUser().
The documentation for this enum was generated from the following file:
app/org/tdl/vireo/model/DegreeLevel.java