Vireo: org.tdl.vireo.job.JobStatus Enum Reference
org.tdl.vireo.job.JobStatus Enum Reference
Public Member Functions
JobStatus (boolean active)
boolean isActive ()
Public Attributes
WAITING =(true)
READY =(true)
RUNNING =(true)
SUCCESS =(false)
FAILED =(false)
CANCELLED =(false)
Static Public Attributes
staticJobStatus[] ACTIVE = { WAITING, READY, RUNNING }
staticJobStatus[] COMPLETED = { SUCCESS, FAILED, CANCELLED }
Private Attributes
boolean active
Detailed Description
Potential states a job may be in.
Author
Scott Phillips
Definition at line 8 of file JobStatus.java.
Constructor & Destructor Documentation
org.tdl.vireo.job.JobStatus.JobStatus (boolean active)
Private status constructor
Parameters
active Weather the state is active or inactive.
Definition at line 37 of file JobStatus.java.
{
         this.active = active;
     }
Member Function Documentation
boolean org.tdl.vireo.job.JobStatus.isActive ()
Returns
true if the state is active, otherwise false.
Definition at line 44 of file JobStatus.java.
{
         return active;
     }
Member Data Documentation
boolean org.tdl.vireo.job.JobStatus.active private
Definition at line 29 of file JobStatus.java.
static JobStatus [] org.tdl.vireo.job.JobStatus.ACTIVE = { WAITING, READY, RUNNING } static
Definition at line 49 of file JobStatus.java.
Referenced by org.tdl.vireo.job.impl.JobManagerImpl.waitForJobs().
org.tdl.vireo.job.JobStatus.CANCELLED =(false)
Definition at line 26 of file JobStatus.java.
static JobStatus [] org.tdl.vireo.job.JobStatus.COMPLETED = { SUCCESS, FAILED, CANCELLED } static
Definition at line 50 of file JobStatus.java.
org.tdl.vireo.job.JobStatus.FAILED =(false)
Definition at line 23 of file JobStatus.java.
Referenced by org.tdl.vireo.batch.impl.DeleteServiceImpl.DeleteJob.doJob(), org.tdl.vireo.batch.impl.AssignServiceImpl.AssignJob.doJob(), org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.doJob(), org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.doJob(), org.tdl.vireo.export.impl.DepositServiceImpl.DepositJob.doJob(), and org.tdl.vireo.batch.impl.CommentServiceImpl.CommentJob.doJob().
org.tdl.vireo.job.JobStatus.READY =(true)
Definition at line 14 of file JobStatus.java.
Referenced by org.tdl.vireo.batch.impl.AssignServiceImpl.AssignJob.AssignJob(), org.tdl.vireo.batch.impl.CommentServiceImpl.CommentJob.CommentJob(), org.tdl.vireo.batch.impl.DeleteServiceImpl.DeleteJob.DeleteJob(), org.tdl.vireo.export.impl.DepositServiceImpl.DepositJob.DepositJob(), org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.ExportJob(), org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.ExportJob(), and org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.TransitionJob().
org.tdl.vireo.job.JobStatus.RUNNING =(true)
Definition at line 17 of file JobStatus.java.
Referenced by org.tdl.vireo.batch.impl.DeleteServiceImpl.DeleteJob.doJob(), org.tdl.vireo.batch.impl.AssignServiceImpl.AssignJob.doJob(), org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.doJob(), org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.doJob(), org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.doJob(), org.tdl.vireo.export.impl.DepositServiceImpl.DepositJob.doJob(), and org.tdl.vireo.batch.impl.CommentServiceImpl.CommentJob.doJob().
org.tdl.vireo.job.JobStatus.SUCCESS =(false)
Definition at line 20 of file JobStatus.java.
Referenced by org.tdl.vireo.batch.impl.DeleteServiceImpl.DeleteJob.doJob(), org.tdl.vireo.batch.impl.AssignServiceImpl.AssignJob.doJob(), org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.doJob(), org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.doJob(), org.tdl.vireo.export.impl.DepositServiceImpl.DepositJob.doJob(), and org.tdl.vireo.batch.impl.CommentServiceImpl.CommentJob.doJob().
org.tdl.vireo.job.JobStatus.WAITING =(true)
Definition at line 11 of file JobStatus.java.
The documentation for this enum was generated from the following file:
app/org/tdl/vireo/job/JobStatus.java