Vireo: org.tdl.vireo.search.SearchOrder Enum Reference
org.tdl.vireo.search.SearchOrder Enum Reference
Public Member Functions
int getId ()
Static Public Member Functions
static SearchOrder find (int id)
Public Attributes
ID =(1)
STUDENT_EMAIL =(2)
STUDENT_NAME =(3)
STUDENT_ID =(4)
STATE =(5)
ASSIGNEE =(6)
DOCUMENT_TITLE =(7)
DOCUMENT_ABSTRACT =(8)
DOCUMENT_KEYWORDS =(9)
DOCUMENT_SUBJECTS =(10)
DOCUMENT_LANGUAGE =(11)
PUBLISHED_MATERIAL =(12)
PRIMARY_DOCUMENT =(13)
GRADUATION_DATE =(14)
DEFENSE_DATE =(15)
SUBMISSION_DATE =(16)
LICENSE_AGREEMENT_DATE =(17)
APPROVAL_DATE =(18)
COMMITTEE_APPROVAL_DATE =(19)
COMMITTEE_EMBARGO_APPROVAL_DATE =(20)
COMMITTEE_MEMBERS =(21)
COMMITTEE_CONTACT_EMAIL =(22)
DEGREE =(23)
DEGREE_LEVEL =(24)
PROGRAM =(25)
COLLEGE =(26)
DEPARTMENT =(27)
MAJOR =(28)
EMBARGO_TYPE =(29)
DOCUMENT_TYPE =(30)
UMI_RELEASE =(31)
CUSTOM_ACTIONS =(32)
DEPOSIT_ID =(33)
REVIEWER_NOTES =(34)
LAST_EVENT_ENTRY =(35)
LAST_EVENT_TIME =(36)
ORCID =(37)
Private Member Functions
SearchOrder (int id)
Private Attributes
int id
Detailed Description
List of all possible ordering of Vireo submissions.
Author
Scott Phillips
Definition at line 8 of file SearchOrder.java.
Constructor & Destructor Documentation
org.tdl.vireo.search.SearchOrder.SearchOrder (int id) private
Private constructor for the defined search orders listed above.
Parameters
id The id of the search order.
Definition at line 74 of file SearchOrder.java.
{
         this.id = id;
     }
Member Function Documentation
static SearchOrder org.tdl.vireo.search.SearchOrder.find (int id) static
Locate a search order based upon it's id.
Parameters
id The of the search order.
Returns
The search order, or null if not found.
Definition at line 92 of file SearchOrder.java.
Referenced by controllers.FilterTab.modifySearch().
{
         for (SearchOrder searchOrder : SearchOrder.values()) {
             if (searchOrder.id == id)
                 return searchOrder;
         }
         return null;
     }
int org.tdl.vireo.search.SearchOrder.getId ()
Returns
The code of this search order.
Definition at line 81 of file SearchOrder.java.
{
         return id;
     }
Member Data Documentation
org.tdl.vireo.search.SearchOrder.APPROVAL_DATE =(18)
Definition at line 33 of file SearchOrder.java.
Referenced by controllers.FilterTab.getDefaultColumns().
org.tdl.vireo.search.SearchOrder.ASSIGNEE =(6)
Definition at line 17 of file SearchOrder.java.
Referenced by controllers.FilterTab.getDefaultColumns().
org.tdl.vireo.search.SearchOrder.COLLEGE =(26)
Definition at line 44 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.COMMITTEE_APPROVAL_DATE =(19)
Definition at line 35 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.COMMITTEE_CONTACT_EMAIL =(22)
Definition at line 38 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.COMMITTEE_EMBARGO_APPROVAL_DATE =(20)
Definition at line 36 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.COMMITTEE_MEMBERS =(21)
Definition at line 37 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.CUSTOM_ACTIONS =(32)
Definition at line 53 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.DEFENSE_DATE =(15)
Definition at line 30 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.DEGREE =(23)
Definition at line 40 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.DEGREE_LEVEL =(24)
Definition at line 41 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.DEPARTMENT =(27)
Definition at line 45 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.DEPOSIT_ID =(33)
Definition at line 55 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.DOCUMENT_ABSTRACT =(8)
Definition at line 20 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.DOCUMENT_KEYWORDS =(9)
Definition at line 21 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.DOCUMENT_LANGUAGE =(11)
Definition at line 23 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.DOCUMENT_SUBJECTS =(10)
Definition at line 22 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.DOCUMENT_TITLE =(7)
Definition at line 19 of file SearchOrder.java.
Referenced by controllers.FilterTab.getDefaultColumns().
org.tdl.vireo.search.SearchOrder.DOCUMENT_TYPE =(30)
Definition at line 49 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.EMBARGO_TYPE =(29)
Definition at line 48 of file SearchOrder.java.
Referenced by controllers.FilterTab.getDefaultColumns().
org.tdl.vireo.search.SearchOrder.GRADUATION_DATE =(14)
Definition at line 29 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.ID =(1)
Definition at line 10 of file SearchOrder.java.
Referenced by org.tdl.vireo.batch.impl.DeleteServiceImpl.DeleteJob.doJob(), org.tdl.vireo.batch.impl.AssignServiceImpl.AssignJob.doJob(), org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.doJob(), org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.doJob(), org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.doJob(), org.tdl.vireo.batch.impl.CommentServiceImpl.CommentJob.doJob(), controllers.FilterTab.getDefaultColumns(), controllers.FilterTab.list(), and controllers.FilterTab.log().
int org.tdl.vireo.search.SearchOrder.id private
Definition at line 66 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.LAST_EVENT_ENTRY =(35)
Definition at line 59 of file SearchOrder.java.
Referenced by controllers.FilterTab.getDefaultColumns().
org.tdl.vireo.search.SearchOrder.LAST_EVENT_TIME =(36)
Definition at line 60 of file SearchOrder.java.
Referenced by controllers.FilterTab.getDefaultColumns().
org.tdl.vireo.search.SearchOrder.LICENSE_AGREEMENT_DATE =(17)
Definition at line 32 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.MAJOR =(28)
Definition at line 46 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.ORCID =(37)
Definition at line 62 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.PRIMARY_DOCUMENT =(13)
Definition at line 27 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.PROGRAM =(25)
Definition at line 43 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.PUBLISHED_MATERIAL =(12)
Definition at line 25 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.REVIEWER_NOTES =(34)
Definition at line 57 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.STATE =(5)
Definition at line 15 of file SearchOrder.java.
Referenced by controllers.FilterTab.getDefaultColumns().
org.tdl.vireo.search.SearchOrder.STUDENT_EMAIL =(2)
Definition at line 11 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.STUDENT_ID =(4)
Definition at line 13 of file SearchOrder.java.
org.tdl.vireo.search.SearchOrder.STUDENT_NAME =(3)
Definition at line 12 of file SearchOrder.java.
Referenced by controllers.FilterTab.getDefaultColumns().
org.tdl.vireo.search.SearchOrder.SUBMISSION_DATE =(16)
Definition at line 31 of file SearchOrder.java.
Referenced by controllers.FilterTab.getDefaultColumns().
org.tdl.vireo.search.SearchOrder.UMI_RELEASE =(31)
Definition at line 51 of file SearchOrder.java.
The documentation for this enum was generated from the following file:
app/org/tdl/vireo/search/SearchOrder.java