Vireo: org.tdl.vireo.search.SearchDirection Enum Reference
org.tdl.vireo.search.SearchDirection Enum Reference
Public Member Functions
int getId ()
Static Public Member Functions
static SearchDirection find (int id)
Public Attributes
ASCENDING =(0)
DESCENDING =(1)
Private Member Functions
SearchDirection (int id)
Private Attributes
int id
Detailed Description
The possible directions an ordered set of submissions/actionlogs may be ordered by.
Author
Scott Phillips
Definition at line 9 of file SearchDirection.java.
Constructor & Destructor Documentation
org.tdl.vireo.search.SearchDirection.SearchDirection (int id) private
Private constructor for the defined search directions listed above.
Parameters
id The id of the search direction.
Definition at line 22 of file SearchDirection.java.
{
         this.id = id;
     }
Member Function Documentation
static SearchDirection org.tdl.vireo.search.SearchDirection.find (int id) static
Locate a search direction based upon it's id.
Parameters
id The of the search direction.
Returns
The search direction, or null if not found.
Definition at line 40 of file SearchDirection.java.
{
         for (SearchDirection searchDirection : SearchDirection.values()) {
             if (searchDirection.id == id)
                 return searchDirection;
         }
         return null;
     }
int org.tdl.vireo.search.SearchDirection.getId ()
Returns
The id of this search direction.
Definition at line 29 of file SearchDirection.java.
{
         return id;
     }
Member Data Documentation
org.tdl.vireo.search.SearchDirection.ASCENDING =(0)
Definition at line 10 of file SearchDirection.java.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.actionLogSearch(), org.tdl.vireo.batch.impl.DeleteServiceImpl.DeleteJob.doJob(), org.tdl.vireo.batch.impl.AssignServiceImpl.AssignJob.doJob(), org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.doJob(), org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.doJob(), org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.doJob(), org.tdl.vireo.batch.impl.CommentServiceImpl.CommentJob.doJob(), controllers.FilterTab.list(), controllers.FilterTab.log(), controllers.FilterTab.modifySearch(), and org.tdl.vireo.search.impl.LuceneSearcherImpl.submissionSearch().
org.tdl.vireo.search.SearchDirection.DESCENDING =(1)
Definition at line 11 of file SearchDirection.java.
Referenced by controllers.FilterTab.list(), and controllers.FilterTab.log().
int org.tdl.vireo.search.SearchDirection.id private
Definition at line 14 of file SearchDirection.java.
The documentation for this enum was generated from the following file:
app/org/tdl/vireo/search/SearchDirection.java