Vireo: org.tdl.vireo.search.SearchFilter Interface Reference
org.tdl.vireo.search.SearchFilter Interface Reference
Public Member Functions
List< Submission > getIncludedSubmissions ()
void addIncludedSubmission (Submission sub)
void removeIncludedSubmission (Submission sub)
List< ActionLog > getExcludedActionLogs ()
void addExcludedActionLog (ActionLog log)
void removeExcludedActionLog (ActionLog log)
List< ActionLog > getIncludedActionLogs ()
void addIncludedActionLog (ActionLog log)
void removeIncludedActionLog (ActionLog log)
List< Submission > getExcludedSubmissions ()
void addExcludedSubmission (Submission sub)
void removeExcludedSubmission (Submission sub)
List< String > getSearchText ()
void addSearchText (String text)
void removeSearchText (String text)
List< String > getStates ()
void addState (String state)
void removeState (String state)
List< Person > getAssignees ()
void addAssignee (Person assignee)
void removeAssignee (Person assignee)
List< EmbargoType > getEmbargoTypes ()
void addEmbargoType (EmbargoType type)
void removeEmbargoType (EmbargoType type)
List< Semester > getGraduationSemesters ()
void addGraduationSemester (Semester semester)
void removeGraduationSemester (Semester semester)
void addGraduationSemester (Integer year, Integer month)
void removeGraduationSemester (Integer year, Integer month)
List< String > getDegrees ()
void addDegree (String degree)
void removeDegree (String degree)
List< String > getDepartments ()
void addDepartment (String department)
void removeDepartment (String department)
List< String > getPrograms ()
void addProgram (String program)
void removeProgram (String program)
List< String > getColleges ()
void addCollege (String college)
void removeCollege (String college)
List< String > getMajors ()
void addMajor (String major)
void removeMajor (String major)
List< String > getDocumentTypes ()
void addDocumentType (String documentType)
void removeDocumentType (String documentType)
Boolean getUMIRelease ()
void setUMIRelease (Boolean value)
Date getDateRangeStart ()
void setDateRangeStart (Date start)
Date getDateRangeEnd ()
void setDateRangeEnd (Date end)
List< CustomActionDefinition > getCustomActions ()
void addCustomAction (CustomActionDefinition customAction)
void removeCustomAction (CustomActionDefinition customAction)
List< SearchOrder > getColumns ()
void setColumns (List< SearchOrder > columns)
Detailed Description
A filter search is a set of parameters to search for a set of Vireo submission. The object is used by the SubmissionRepository to filter the set of all submissions by particular criteria.
Implementers should pick on of the child interfaces instead of implementing this interface directly. The two child interfaces are NamedSearchfilter, and ActiveSearchFilter. The named version is designed to be persisted in the database, while the active search filter is designed to be serialized to a cookie value. Both types may be feed to the filter search to produce search results.
Author
Scott Phillips
Definition at line 26 of file SearchFilter.java.
Member Function Documentation
void org.tdl.vireo.search.SearchFilter.addAssignee (Person assignee)
Parameters
assignee A new assignee to add to the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.addCollege (String college)
Parameters
college Add a new college to the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.addCustomAction (CustomActionDefinition customAction)
Parameters
customAction The custom action to add to the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.addDegree (String degree)
Parameters
degree A a new degree to the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.addDepartment (String department)
Parameters
department Add a new department to the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.addDocumentType (String documentType)
Parameters
documentType add a new documentType to the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.addEmbargoType (EmbargoType type)
Parameters
type The embargo type to add to the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.addExcludedActionLog (ActionLog log)
Parameters
log Add an individual logs this filter will exclude.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.addExcludedSubmission (Submission sub)
Parameters
sub Add an individual submission this filter will exclude.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.addGraduationSemester (Semester semester)
Parameters
semester The graduation semester to add to the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.addGraduationSemester (Integer year, Integer month)
Add a graduation semester with the provided year and month.
Parameters
year The graduation year.
month The graduation month.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.addIncludedActionLog (ActionLog log)
Parameters
log Add an individual log this filter is limmitted too.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.addIncludedSubmission (Submission sub)
Parameters
sub Add an individual submission this filter is limmitted too.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.addMajor (String major)
Parameters
major Add a new major to the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.addProgram (String program)
Parameters
program Add a new program to the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.addSearchText (String text)
Parameters
text The new text search to add.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.addState (String state)
Parameters
status The new state to add to the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
List<Person> org.tdl.vireo.search.SearchFilter.getAssignees ()
Returns
The list of assignees to filter for.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery().
List<String> org.tdl.vireo.search.SearchFilter.getColleges ()
Returns
The list of colleges
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery().
List<SearchOrder> org.tdl.vireo.search.SearchFilter.getColumns ()
Returns
The list of columns associated with this SearchFilter
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
List<CustomActionDefinition> org.tdl.vireo.search.SearchFilter.getCustomActions ()
Returns
The custom actions
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery().
Date org.tdl.vireo.search.SearchFilter.getDateRangeEnd ()
Returns
The end of the current date range search.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery().
Date org.tdl.vireo.search.SearchFilter.getDateRangeStart ()
Returns
The start of the current date range search.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery().
List<String> org.tdl.vireo.search.SearchFilter.getDegrees ()
Returns
The list of degrees
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery().
List<String> org.tdl.vireo.search.SearchFilter.getDepartments ()
Returns
The list of departments.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery().
List<String> org.tdl.vireo.search.SearchFilter.getDocumentTypes ()
Returns
The list of document types
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery().
List<EmbargoType> org.tdl.vireo.search.SearchFilter.getEmbargoTypes ()
Returns
The list of embago types to filter for.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery().
List<ActionLog> org.tdl.vireo.search.SearchFilter.getExcludedActionLogs ()
Returns
A list of individual logs this filter will exclude.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery().
List<Submission> org.tdl.vireo.search.SearchFilter.getExcludedSubmissions ()
Returns
A list of individual submissions this filter will exclude.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery().
List<Semester> org.tdl.vireo.search.SearchFilter.getGraduationSemesters ()
Returns
The graduation semesters
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery().
List<ActionLog> org.tdl.vireo.search.SearchFilter.getIncludedActionLogs ()
Returns
A list of individual logs this filter is restricted too.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery().
List<Submission> org.tdl.vireo.search.SearchFilter.getIncludedSubmissions ()
Returns
A list of individual submissions this filter is restricted too.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery().
List<String> org.tdl.vireo.search.SearchFilter.getMajors ()
Returns
The list of majors
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery().
List<String> org.tdl.vireo.search.SearchFilter.getPrograms ()
Returns
The list of programs
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery().
List<String> org.tdl.vireo.search.SearchFilter.getSearchText ()
Returns
The list of all free-form search parameters
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery().
List<String> org.tdl.vireo.search.SearchFilter.getStates ()
Returns
The list of all submission states to search for. Only valid Spring Bean Names should be included in this list.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery().
Boolean org.tdl.vireo.search.SearchFilter.getUMIRelease ()
True -> applications are set to be released to UMI
False -> applications are not set to be released.
Null -> Either released or not.
Returns
How to filter for UMI release
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery().
void org.tdl.vireo.search.SearchFilter.removeAssignee (Person assignee)
Parameters
assignee The assignee to remove from the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.removeCollege (String college)
Parameters
college Remove a college from the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.removeCustomAction (CustomActionDefinition customAction)
Parameters
customAction The custom action to remove from the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.removeDegree (String degree)
Parameters
degree Remove a degree from the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.removeDepartment (String department)
Parameters
department remove a department from the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.removeDocumentType (String documentType)
Parameters
documentType Remove a document type from the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.removeEmbargoType (EmbargoType type)
Parameters
type The embargo type to remove from the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.removeExcludedActionLog (ActionLog log)
Parameters
log Remove an individual logs from this filter this filter will no longer exclude.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.removeExcludedSubmission (Submission sub)
Parameters
sub Remove an individual submission from this filter this filter will no longer exclude.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.removeGraduationSemester (Semester semester)
Parameters
semester The graduation semester to remove from the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.removeGraduationSemester (Integer year, Integer month)
Remove a graduation semester with the provided year and month.
Parameters
year The graduation year.
month The graduation month.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.removeIncludedActionLog (ActionLog log)
Parameters
log Remove an individual log from this filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.removeIncludedSubmission (Submission sub)
Parameters
sub Remove an individual submission from this filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.removeMajor (String major)
Parameters
major Remove a major from the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.removeProgram (String program)
Parameters
program Remove a program from the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.removeSearchText (String text)
Parameters
text The text search to remove
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.removeState (String state)
Parameters
status Remove the state from the filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.setColumns (List< SearchOrder > columns)
Parameters
columns - The list of columns associated with this SearchFilter
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.setDateRangeEnd (Date end)
Parameters
end The new end of the date range, may be null for infinite
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.setDateRangeStart (Date start)
Parameters
start The new start of the date range, may be null for infinite.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
void org.tdl.vireo.search.SearchFilter.setUMIRelease (Boolean value)
Parameters
value Set the UMI release filter.
Implemented in org.tdl.vireo.model.jpa.JpaNamedSearchFilterImpl, and org.tdl.vireo.search.impl.UriActiveSearchFilterImpl.
The documentation for this interface was generated from the following file:
app/org/tdl/vireo/search/SearchFilter.java