Vireo: org.tdl.vireo.model.SubmissionRepository Interface Reference
org.tdl.vireo.model.SubmissionRepository Interface Reference
Public Member Functions
Submission createSubmission (Person submitter)
Submission findSubmission (Long id)
List< Submission > findSubmissions (List< Long > submissionIds)
Submission findSubmissionByEmailHash (String emailHash)
List< Submission > findSubmission (Person Submitter)
Iterator< Submission > findAllSubmissions ()
long findSubmissionsTotal ()
List< Semester > findAllGraduationSemesters ()
List< Integer > findAllSubmissionYears ()
List< String > findAllPrograms ()
List< String > findAllColleges ()
List< String > findAllDepartments ()
List< String > findAllMajors ()
List< String > findAllDegrees ()
List< String > findAllLanguages ()
Attachment findAttachment (Long id)
CommitteeMember findCommitteeMember (Long id)
CustomActionValue findCustomActionValue (Long id)
ActionLog findActionLog (Long id)
List< ActionLog > findActionLogs (List< Long > logIds)
List< ActionLog > findActionLog (Submission submission)
Iterator< ActionLog > findAllActionLogs ()
long findActionLogsTotal ()
NamedSearchFilter createSearchFilter (Person creator, String name)
NamedSearchFilter findSearchFilter (Long id)
List< NamedSearchFilter > findSearchFiltersByCreatorOrPublic (Person creator)
NamedSearchFilter findSearchFilterByCreatorAndName (Person creator, String name)
List< NamedSearchFilter > findAllSearchFilters ()
Detailed Description
The Vireo persistent repository for submissions. This object follows the spring repository pattern, where this is the source for creating and locating all persistent model objects. It is intended that this object will be injected into all other spring beans that need access to vireo submissions.
Author
Scott Phillips
Definition at line 17 of file SubmissionRepository.java.
Member Function Documentation
NamedSearchFilter org.tdl.vireo.model.SubmissionRepository.createSearchFilter (Person creator, String name)
Create a brand new search filter.
Parameters
creator The person who is creating and owns this search filter.
name A unique filter name among all those created by this user.
Returns
The new filter.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
Submission org.tdl.vireo.model.SubmissionRepository.createSubmission (Person submitter)
Start a brand new submission for this submitter.
Parameters
submitter The submitter of the submission.
Returns
A new submission.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
ActionLog org.tdl.vireo.model.SubmissionRepository.findActionLog (Long id)
Find an action log by unique id.
Parameters
id The id of the action log.
Returns
The action log or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
List<ActionLog> org.tdl.vireo.model.SubmissionRepository.findActionLog (Submission submission)
Find all action logs for a particular submission order by date.
Parameters
submission The submission
Returns
A list of action logs, or an empty list of none or found.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
List<ActionLog> org.tdl.vireo.model.SubmissionRepository.findActionLogs (List< Long > logIds)
Find all the action log objects for the given list of ids. Some implementations may impose a limit on the number of ids that are permissible. If a log object was not found for the particular id, then it will not appear in the resulting list and no exception will be thrown. The result list may be in any order.
Parameters
logIds The ids of all the action log objects.
Returns
A list of action log objects.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
long org.tdl.vireo.model.SubmissionRepository.findActionLogsTotal ()
Find how many action logs are stored in the persistent repository.
Returns
the number total number of action logs stored in the persistent repository.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
Iterator<ActionLog> org.tdl.vireo.model.SubmissionRepository.findAllActionLogs ()
Find all Action Logs in Vireo. Since this can be potentially huge, we return an iterator. After each object is cycled by the iterator it may potentially be removed from the current database connection.
Returns
An iterator over all action logs.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
List<String> org.tdl.vireo.model.SubmissionRepository.findAllColleges ()
Returns
A list of all colleges for which submissions have been submitted under.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
List<String> org.tdl.vireo.model.SubmissionRepository.findAllDegrees ()
Returns
A list of all degrees for which degrees have been submitted under.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
List<String> org.tdl.vireo.model.SubmissionRepository.findAllDepartments ()
Returns
A list of all departments for which departments have been submitted under.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
List<Semester> org.tdl.vireo.model.SubmissionRepository.findAllGraduationSemesters ()
Returns
A list of all graduation semesters for which there are submissions recorded for.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
List<String> org.tdl.vireo.model.SubmissionRepository.findAllLanguages ()
Returns
A list of all languages
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
List<String> org.tdl.vireo.model.SubmissionRepository.findAllMajors ()
Returns
A list of all majors for which majors have been submitted under.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
List<String> org.tdl.vireo.model.SubmissionRepository.findAllPrograms ()
Returns
A list of all programs for which submissions have been submitted under.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
List<NamedSearchFilter> org.tdl.vireo.model.SubmissionRepository.findAllSearchFilters ()
Find all search filters regardless of who they owned by or whether they are flagged as public.
Returns
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
Iterator<Submission> org.tdl.vireo.model.SubmissionRepository.findAllSubmissions ()
Find all submissions in Vireo. Since this can be potentially huge, we return an iterator. After each object is cycled by the iterator it may potentially be removed from the current database connection.
Returns
An iterator over all submissions.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
List<Integer> org.tdl.vireo.model.SubmissionRepository.findAllSubmissionYears ()
Returns
A list of all years for which submissions occured during that year.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
Attachment org.tdl.vireo.model.SubmissionRepository.findAttachment (Long id)
Find an attachment by id.
Parameters
id The unique id of the attachment.
Returns
The attachment object or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
CommitteeMember org.tdl.vireo.model.SubmissionRepository.findCommitteeMember (Long id)
Find an committee member by id.
Parameters
id The unique id of the committee member.
Returns
The committee member object or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
CustomActionValue org.tdl.vireo.model.SubmissionRepository.findCustomActionValue (Long id)
Find an custom action value by id.
Parameters
id The unique id of the custom action value.
Returns
The custom action value object or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
NamedSearchFilter org.tdl.vireo.model.SubmissionRepository.findSearchFilter (Long id)
Find a search filter by unique id.
Parameters
id The id of the search filter.
Returns
The search filter, or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
NamedSearchFilter org.tdl.vireo.model.SubmissionRepository.findSearchFilterByCreatorAndName (Person creator, String name)
Find the named search filter that was created by this user.
Parameters
creator The filter's creator
name The unique name of the filter
Returns
The search filter, or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
List<NamedSearchFilter> org.tdl.vireo.model.SubmissionRepository.findSearchFiltersByCreatorOrPublic (Person creator)
Find all search filters that are either owned by this user, or are flagged as public.
Parameters
creator The potential creator, may be null. In this case all public filters are returned.
Returns
The unordered list of search filters.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
Submission org.tdl.vireo.model.SubmissionRepository.findSubmission (Long id)
Find a submission by id.
Parameters
id The unique id of the submission.
Returns
The submission object or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
List<Submission> org.tdl.vireo.model.SubmissionRepository.findSubmission (Person Submitter)
Find all submissions for a particular submitter.
Parameters
Submitter The submitter
Returns
A list of all submissions for the submitter, or an empty set if there are none.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
Submission org.tdl.vireo.model.SubmissionRepository.findSubmissionByEmailHash (String emailHash)
Find a submission by email hash
Parameters
id The email hash of the submission.
Returns
The submission object or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
Referenced by controllers.submit.Confirm.generateCommitteEmailHash().
List<Submission> org.tdl.vireo.model.SubmissionRepository.findSubmissions (List< Long > submissionIds)
Find all the submission objects for the given list of ids. Some implementations may impose a limit on the number of ids that are permissible. If an submission object was not found for the particular id, then it will not appear in the resulting list and no exception will be thrown. The result list may be in any order.
Parameters
submissionIds The ids of all the submission objects.
Returns
A list of submission objects.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
long org.tdl.vireo.model.SubmissionRepository.findSubmissionsTotal ()
Find how many submissions are stored in the persistent repository.
Returns
the number total number of submissions stored in the persistent repository.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionRepositoryImpl.
Referenced by org.tdl.vireo.search.impl.LuceneRebuildJobImpl.LuceneRebuildJobImpl(), and org.tdl.vireo.search.impl.LuceneRebuildJobImpl.writeIndex().
The documentation for this interface was generated from the following file:
app/org/tdl/vireo/model/SubmissionRepository.java