Vireo: org.tdl.vireo.model.EmbargoType Interface Reference
org.tdl.vireo.model.EmbargoType Interface Reference
Public Member Functions
String getName ()
void setName (String name)
String getDescription ()
void setDescription (String description)
Integer getDuration ()
void setDuration (Integer duration)
boolean isActive ()
void setActive (boolean active)
boolean isSystemRequired ()
void setSystemRequired (boolean required)
EmbargoGuarantor getGuarantor ()
void setGuarantor (EmbargoGuarantor guarantor)
List< Submission > getSubmissions ()
Public Member Functions inherited from org.tdl.vireo.model.AbstractOrderedModel
int getDisplayOrder ()
void setDisplayOrder (int displayOrder)
Public Member Functions inherited from org.tdl.vireo.model.AbstractModel
Long getId ()
public< T extends AbstractModel > T save ()
public< T extends AbstractModel > T delete ()
public< T extends AbstractModel > T refresh ()
public< T extends AbstractModel > T merge ()
public< T extends AbstractModel > T detach ()
Detailed Description
Embargoes restrict the release of a submission for a length of time. If an embargo type is active then it may be selected by a student for any new application. Each embargo may have a pre-defined duration before it can be released. The duration is defined in months. If the type has no pre-defined duration then the duration should be set to Null, and a duration of zero means no embargo.
Author
Scott Phillips
Definition at line 15 of file EmbargoType.java.
Member Function Documentation
String org.tdl.vireo.model.EmbargoType.getDescription ()
Returns
The English description for this embargo type.
Implemented in org.tdl.vireo.model.jpa.JpaEmbargoTypeImpl.
Referenced by controllers.settings.ConfigurableSettingsTab.editEmbargoTypeJSON(), and org.tdl.vireo.services.SystemDataLoader.generateAllSystemEmbargos().
Integer org.tdl.vireo.model.EmbargoType.getDuration ()
Returns
Return the static duration for this embargo type measured in months. If there is no predefined duration then null is returned. A duration of "zero" means there is no embargo. Negative durations are not permitted.
Implemented in org.tdl.vireo.model.jpa.JpaEmbargoTypeImpl.
Referenced by controllers.settings.ConfigurableSettingsTab.editEmbargoTypeJSON(), org.tdl.vireo.services.SystemDataLoader.generateAllSystemEmbargos(), and controllers.settings.ConfigurableSettingsTab.getModelCompator().
EmbargoGuarantor org.tdl.vireo.model.EmbargoType.getGuarantor ()
Returns
The guarantor of the embargo in enum.
Implemented in org.tdl.vireo.model.jpa.JpaEmbargoTypeImpl.
Referenced by controllers.settings.ConfigurableSettingsTab.editEmbargoTypeJSON(), org.tdl.vireo.services.SystemDataLoader.generateAllSystemEmbargos(), org.tdl.vireo.model.jpa.JpaSubmissionImpl.getEmbargoTypeByGuarantor(), and org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow().
String org.tdl.vireo.model.EmbargoType.getName ()
Returns
The name of this embargo type
Implemented in org.tdl.vireo.model.jpa.JpaEmbargoTypeImpl.
Referenced by org.tdl.vireo.model.jpa.JpaSubmissionImpl.addEmbargoType(), controllers.settings.ConfigurableSettingsTab.editEmbargoTypeJSON(), and controllers.settings.ConfigurableSettingsTab.getModelCompator().
List<Submission> org.tdl.vireo.model.EmbargoType.getSubmissions ()
Returns
The list of associated submissions.
Implemented in org.tdl.vireo.model.jpa.JpaEmbargoTypeImpl.
boolean org.tdl.vireo.model.EmbargoType.isActive ()
Returns
true if this embargo type is active.
Implemented in org.tdl.vireo.model.jpa.JpaEmbargoTypeImpl.
boolean org.tdl.vireo.model.EmbargoType.isSystemRequired ()
Returns
True, if this embargo is required by the system. These embargos may not be deleted.
Implemented in org.tdl.vireo.model.jpa.JpaEmbargoTypeImpl.
void org.tdl.vireo.model.EmbargoType.setActive (boolean active)
Parameters
active Set the new active value for this type.
Implemented in org.tdl.vireo.model.jpa.JpaEmbargoTypeImpl.
void org.tdl.vireo.model.EmbargoType.setDescription (String description)
Parameters
description The new English description for this embargo type.
Implemented in org.tdl.vireo.model.jpa.JpaEmbargoTypeImpl.
void org.tdl.vireo.model.EmbargoType.setDuration (Integer duration)
Parameters
duration The new duration of this embargo type measured in months.
Implemented in org.tdl.vireo.model.jpa.JpaEmbargoTypeImpl.
void org.tdl.vireo.model.EmbargoType.setGuarantor (EmbargoGuarantor guarantor)
Parameters
guarantor The guarantor of the embargo.
Implemented in org.tdl.vireo.model.jpa.JpaEmbargoTypeImpl.
void org.tdl.vireo.model.EmbargoType.setName (String name)
Parameters
name The new name of this embargo type
Implemented in org.tdl.vireo.model.jpa.JpaEmbargoTypeImpl.
void org.tdl.vireo.model.EmbargoType.setSystemRequired (boolean required)
Parameters
required Set weather this embargo is required by the system. These embargos bay not be renamed or deleted.
Implemented in org.tdl.vireo.model.jpa.JpaEmbargoTypeImpl.
The documentation for this interface was generated from the following file:
app/org/tdl/vireo/model/EmbargoType.java