Vireo: org.tdl.vireo.job.JobMetadata Interface Reference
org.tdl.vireo.job.JobMetadata Interface Reference
Classes
class Progress
Public Member Functions
UUID getId ()
long getStartTime ()
Long getOwnerId ()
String getName ()
JobStatus getStatus ()
void setStatus (JobStatus status)
Progress getProgress ()
Job getJob ()
void setJob (Job job)
String getMessage ()
void setMessage (String message)
Detailed Description
Metadata about a background job.
This is not the actual job, instead it only contains information about a job. This allows the metadata to persist after the job has completed.
Author
Scott Phillips
Definition at line 16 of file JobMetadata.java.
Member Function Documentation
UUID org.tdl.vireo.job.JobMetadata.getId ()
Returns
The unique ID assigned to this job. This id is set upon creation of the object.
Implemented in org.tdl.vireo.job.impl.JobMetadataImpl.
Referenced by org.tdl.vireo.job.impl.JobManagerImpl.register().
Job org.tdl.vireo.job.JobMetadata.getJob ()
Returns
The running job, this may be null. Most jobs are detached from their metadata after the job has completed. But that is up to the individual job to manage.
Implemented in org.tdl.vireo.job.impl.JobMetadataImpl.
String org.tdl.vireo.job.JobMetadata.getMessage ()
Returns
An optional message associated with this job. Typically this is an error message resulting from an unexpected condition but it may be any message.
Implemented in org.tdl.vireo.job.impl.JobMetadataImpl.
Referenced by controllers.JobTab.updateJSON().
String org.tdl.vireo.job.JobMetadata.getName ()
Returns
The displayable name of the job.
Implemented in org.tdl.vireo.job.impl.JobMetadataImpl.
Referenced by controllers.JobTab.updateJSON().
Long org.tdl.vireo.job.JobMetadata.getOwnerId ()
Returns
The owner or person responsible for this job. This may be null if the job is iniated by a system event.
Implemented in org.tdl.vireo.job.impl.JobMetadataImpl.
Progress org.tdl.vireo.job.JobMetadata.getProgress ()
Returns
The job's progress object. This object maintains metadata about how for along the job has completed processing.
Implemented in org.tdl.vireo.job.impl.JobMetadataImpl.
Referenced by org.tdl.vireo.batch.impl.DeleteServiceImpl.DeleteJob.doJob(), org.tdl.vireo.batch.impl.AssignServiceImpl.AssignJob.doJob(), org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.doJob(), org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.doJob(), org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.doJob(), org.tdl.vireo.batch.impl.CommentServiceImpl.CommentJob.doJob(), and controllers.JobTab.updateJSON().
long org.tdl.vireo.job.JobMetadata.getStartTime ()
Returns
The start time of when this job was created.
Implemented in org.tdl.vireo.job.impl.JobMetadataImpl.
JobStatus org.tdl.vireo.job.JobMetadata.getStatus ()
Returns
The status of the job.
Implemented in org.tdl.vireo.job.impl.JobMetadataImpl.
Referenced by controllers.JobTab.updateJSON(), and org.tdl.vireo.job.impl.JobManagerImpl.waitForJobs().
void org.tdl.vireo.job.JobMetadata.setJob (Job job)
Set the running job.
Parameters
job The job.
Implemented in org.tdl.vireo.job.impl.JobMetadataImpl.
void org.tdl.vireo.job.JobMetadata.setMessage (String message)
Set the job's message.
Parameters
message The new message, or null for no message.
Implemented in org.tdl.vireo.job.impl.JobMetadataImpl.
Referenced by org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.doJob().
void org.tdl.vireo.job.JobMetadata.setStatus (JobStatus status)
Set a new status for the job.
Parameters
status New job status.
Implemented in org.tdl.vireo.job.impl.JobMetadataImpl.
The documentation for this interface was generated from the following file:
app/org/tdl/vireo/job/JobMetadata.java