Vireo: org.tdl.vireo.security.SecurityContext Interface Reference
org.tdl.vireo.security.SecurityContext Interface Reference
Public Member Functions
void login (Person person)
void logout ()
Person getPerson ()
boolean isAdministrator ()
boolean isManager ()
boolean isReviewer ()
boolean isStudent ()
boolean isAuthenticated ()
void turnOffAuthorization ()
void restoreAuthorization ()
boolean isAuthorizationActive ()
Detailed Description
This singleton interface keeps track of the current security context that Vireo is operating within.
When a user is authenticated by the UI the security context is notified via the login() method. The login will be kept track of (using a ThreadLocal-based mechanism) of the currently authenticated user. This means that whenever a component needs to access the currently authenticated user they can just query the current security context.
Examples:
SecurityContext context = Spring.getBeanOfType(SecurityContext.class);
Person authenticated = context.getPerson();
Or if you just need to make a quick decision based upon the person's current role you can ask one of the isRole methods such as:
if (context.isAdministrator()) { // Do something very special. }
Author
Scott Phillips
Definition at line 28 of file SecurityContext.java.
Member Function Documentation
Person org.tdl.vireo.security.SecurityContext.getPerson ()
Returns
The currently authenticated person, or null if none one is authenticated.
Implemented in org.tdl.vireo.security.impl.SecurityContextImpl.
Referenced by org.tdl.vireo.batch.impl.AssignServiceImpl.AssignJob.AssignJob(), controllers.Authentication.checkForceSSL(), org.tdl.vireo.batch.impl.CommentServiceImpl.CommentJob.CommentJob(), org.tdl.vireo.batch.impl.DeleteServiceImpl.DeleteJob.DeleteJob(), org.tdl.vireo.export.impl.DepositServiceImpl.DepositJob.DepositJob(), org.tdl.vireo.batch.impl.CommentServiceImpl.CommentJob.doJob(), org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.ExportJob(), org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.ExportJob(), org.tdl.vireo.error.impl.ErrorLogImpl.logError(), controllers.Authentication.loginMethod(), controllers.Authentication.loginReturn(), org.tdl.vireo.email.impl.EmailServiceImpl.EmailJob.logMessage(), controllers.Authentication.logout(), controllers.Authentication.recover(), controllers.Authentication.register(), and org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.TransitionJob().
boolean org.tdl.vireo.security.SecurityContext.isAdministrator ()
Returns
true if the current user has the role ADMINISTRATOR
Implemented in org.tdl.vireo.security.impl.SecurityContextImpl.
boolean org.tdl.vireo.security.SecurityContext.isAuthenticated ()
Returns
true if there is a currently authenticated person.
Implemented in org.tdl.vireo.security.impl.SecurityContextImpl.
boolean org.tdl.vireo.security.SecurityContext.isAuthorizationActive ()
Returns
whether authorization checks have been deactivated.
Implemented in org.tdl.vireo.security.impl.SecurityContextImpl.
Referenced by org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.assertAdministrator(), org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.assertAdministratorOrOwner(), org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.assertManager(), org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.assertManagerOrOwner(), org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.assertReviewer(), org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.assertReviewerOrOwner(), org.tdl.vireo.batch.impl.AssignServiceImpl.assign(), org.tdl.vireo.batch.impl.CommentServiceImpl.comment(), org.tdl.vireo.batch.impl.DeleteServiceImpl.delete(), org.tdl.vireo.export.impl.DepositServiceImpl.DepositJob.DepositJob(), org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.ExportJob(), org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.ExportJob(), and org.tdl.vireo.batch.impl.TransitionServiceImpl.transition().
boolean org.tdl.vireo.security.SecurityContext.isManager ()
Returns
true if the current user has the role MANAGER or above.
Implemented in org.tdl.vireo.security.impl.SecurityContextImpl.
boolean org.tdl.vireo.security.SecurityContext.isReviewer ()
Returns
true if the current user has the role REVIEWER or above.
Implemented in org.tdl.vireo.security.impl.SecurityContextImpl.
Referenced by org.tdl.vireo.export.impl.DepositServiceImpl.DepositJob.DepositJob(), org.tdl.vireo.export.impl.ExportExcelServiceImpl.ExportJob.ExportJob(), and org.tdl.vireo.export.impl.ExportServiceImpl.ExportJob.ExportJob().
boolean org.tdl.vireo.security.SecurityContext.isStudent ()
Returns
true if the current user has the role STUDENT or above.
Implemented in org.tdl.vireo.security.impl.SecurityContextImpl.
void org.tdl.vireo.security.SecurityContext.login (Person person)
After a user's credentials have been verified log the user into the current security context. This allows other vireo components to access the currently authenticated user easily.
Parameters
person The authenticated person.
Implemented in org.tdl.vireo.security.impl.SecurityContextImpl.
Referenced by org.tdl.vireo.security.impl.PasswordAuthenticationMethodImpl.authenticate().
void org.tdl.vireo.security.SecurityContext.logout ()
Logout the current user, effectively resetting the security context.
Implemented in org.tdl.vireo.security.impl.SecurityContextImpl.
void org.tdl.vireo.security.SecurityContext.restoreAuthorization ()
Restore the authorization state to it's original state before the paired turnOffAuthorizations was called.
Implemented in org.tdl.vireo.security.impl.SecurityContextImpl.
void org.tdl.vireo.security.SecurityContext.turnOffAuthorization ()
Turn off the authorization system. The caller must always pair this call with a restoration of authorization.
Implemented in org.tdl.vireo.security.impl.SecurityContextImpl.
The documentation for this interface was generated from the following file:
app/org/tdl/vireo/security/SecurityContext.java