Vireo: org.tdl.vireo.model.DepositLocation Interface Reference
org.tdl.vireo.model.DepositLocation Interface Reference
Public Member Functions
String getName ()
void setName (String name)
String getRepository ()
void setRepository (String location)
String getCollection ()
void setCollection (String location)
String getUsername ()
void setUsername (String username)
String getPassword ()
void setPassword (String password)
String getOnBehalfOf ()
void setOnBehalfOf (String onBehalfOf)
Packager getPackager ()
void setPackager (Packager packager)
Depositor getDepositor ()
void setDepositor (Depositor depositor)
Public Member Functions inherited from org.tdl.vireo.model.AbstractOrderedModel
int getDisplayOrder ()
void setDisplayOrder (int displayOrder)
Public Member Functions inherited from org.tdl.vireo.model.AbstractModel
Long getId ()
public< T extends AbstractModel > T save ()
public< T extends AbstractModel > T delete ()
public< T extends AbstractModel > T refresh ()
public< T extends AbstractModel > T merge ()
public< T extends AbstractModel > T detach ()
Detailed Description
A pre-configured deposit location. While technically this may mean deposit into anything, the design use-cases are for sword deposit into a repository such as DSpace or Fedora.
This object contains all the connection information required to deposit, along with the specific implementations that should be used to make that happen.
Author
Scott Phillips
Definition at line 17 of file DepositLocation.java.
Member Function Documentation
String org.tdl.vireo.model.DepositLocation.getCollection ()
Returns
The collection id or location within the designated repository. This will likely be a URI.
Implemented in org.tdl.vireo.model.jpa.JpaDepositLocationImpl.
Referenced by org.tdl.vireo.export.impl.DepositServiceImpl.deposit(), org.tdl.vireo.export.impl.FileDepositorImpl.deposit(), org.tdl.vireo.export.impl.Sword1DepositorImpl.deposit(), and org.tdl.vireo.batch.impl.TransitionServiceImpl.transition().
Depositor org.tdl.vireo.model.DepositLocation.getDepositor ()
Returns
The depositor implementation who is responsible for depositing the generated package.
Implemented in org.tdl.vireo.model.jpa.JpaDepositLocationImpl.
Referenced by org.tdl.vireo.export.impl.DepositServiceImpl.deposit(), and org.tdl.vireo.batch.impl.TransitionServiceImpl.transition().
String org.tdl.vireo.model.DepositLocation.getName ()
Returns
The name of this deposit location.
Implemented in org.tdl.vireo.model.jpa.JpaDepositLocationImpl.
String org.tdl.vireo.model.DepositLocation.getOnBehalfOf ()
Returns
The onBehalfOf user, a string identifying a user within the repository that the deposit should occur on behalf of. Null if no onBehalfOf user is specified.
Implemented in org.tdl.vireo.model.jpa.JpaDepositLocationImpl.
Referenced by org.tdl.vireo.export.impl.Sword1DepositorImpl.deposit(), and org.tdl.vireo.export.impl.Sword1DepositorImpl.getCollections().
Packager org.tdl.vireo.model.DepositLocation.getPackager ()
Returns
The packager implementation who is responsible for generating depositable packages.
Implemented in org.tdl.vireo.model.jpa.JpaDepositLocationImpl.
Referenced by org.tdl.vireo.export.impl.DepositServiceImpl.deposit(), and org.tdl.vireo.batch.impl.TransitionServiceImpl.transition().
String org.tdl.vireo.model.DepositLocation.getPassword ()
Returns
The authentication password, only used if the username is not null.
Implemented in org.tdl.vireo.model.jpa.JpaDepositLocationImpl.
Referenced by org.tdl.vireo.export.impl.Sword1DepositorImpl.deposit(), and org.tdl.vireo.export.impl.Sword1DepositorImpl.getCollections().
String org.tdl.vireo.model.DepositLocation.getRepository ()
Returns
The location of the repository, this will likely be a URI.
Implemented in org.tdl.vireo.model.jpa.JpaDepositLocationImpl.
Referenced by org.tdl.vireo.export.impl.DepositServiceImpl.deposit(), org.tdl.vireo.export.impl.FileDepositorImpl.deposit(), org.tdl.vireo.export.impl.Sword1DepositorImpl.deposit(), org.tdl.vireo.export.impl.Sword1DepositorImpl.getCollections(), and org.tdl.vireo.batch.impl.TransitionServiceImpl.transition().
String org.tdl.vireo.model.DepositLocation.getUsername ()
Returns
The authentication username, null if no authentication is required.
Implemented in org.tdl.vireo.model.jpa.JpaDepositLocationImpl.
Referenced by org.tdl.vireo.export.impl.Sword1DepositorImpl.deposit(), and org.tdl.vireo.export.impl.Sword1DepositorImpl.getCollections().
void org.tdl.vireo.model.DepositLocation.setCollection (String location)
Parameters
location The new collection id or location within the designated repository. This will likely be a URI.
Implemented in org.tdl.vireo.model.jpa.JpaDepositLocationImpl.
void org.tdl.vireo.model.DepositLocation.setDepositor (Depositor depositor)
Parameters
depositor The new depositor implementation
Implemented in org.tdl.vireo.model.jpa.JpaDepositLocationImpl.
void org.tdl.vireo.model.DepositLocation.setName (String name)
Parameters
name The new name of this deposit location. May not be null.
Implemented in org.tdl.vireo.model.jpa.JpaDepositLocationImpl.
void org.tdl.vireo.model.DepositLocation.setOnBehalfOf (String onBehalfOf)
Parameters
onBehalfOf The new onBehalfOf User
Implemented in org.tdl.vireo.model.jpa.JpaDepositLocationImpl.
void org.tdl.vireo.model.DepositLocation.setPackager (Packager packager)
Parameters
packager The new packager implementation.
Implemented in org.tdl.vireo.model.jpa.JpaDepositLocationImpl.
void org.tdl.vireo.model.DepositLocation.setPassword (String password)
Parameters
password The new password.
Implemented in org.tdl.vireo.model.jpa.JpaDepositLocationImpl.
void org.tdl.vireo.model.DepositLocation.setRepository (String location)
Parameters
location The new location of the repository. This will likely be a URI.
Implemented in org.tdl.vireo.model.jpa.JpaDepositLocationImpl.
void org.tdl.vireo.model.DepositLocation.setUsername (String username)
Parameters
username The new username.
Implemented in org.tdl.vireo.model.jpa.JpaDepositLocationImpl.
The documentation for this interface was generated from the following file:
app/org/tdl/vireo/model/DepositLocation.java