Vireo: org.tdl.vireo.state.State Interface Reference
org.tdl.vireo.state.State Interface Reference
Public Member Functions
String getBeanName ()
String getDisplayName ()
boolean isInProgress ()
boolean isActive ()
boolean isArchived ()
boolean isEditableByStudent ()
boolean isEditableByReviewer ()
boolean isDeletable ()
boolean isDepositable ()
boolean isApproved ()
List< State > getTransitions (Submission submission)
boolean isInWorkflow ()
Detailed Description
A discrete vireo submission state.
Author
Scott Phillips
Definition at line 12 of file State.java.
Member Function Documentation
String org.tdl.vireo.state.State.getBeanName ()
Returns
The technical name of this state.
Implemented in org.tdl.vireo.state.impl.StateImpl.
Referenced by org.tdl.vireo.model.jpa.JpaSubmissionImpl.setState().
String org.tdl.vireo.state.State.getDisplayName ()
Returns
The english display name of this state.
Implemented in org.tdl.vireo.state.impl.StateImpl.
Referenced by org.tdl.vireo.search.impl.LuceneSearcherImpl.buildQuery(), controllers.submit.Confirm.confirm(), and org.tdl.vireo.model.jpa.JpaSubmissionImpl.setState().
List<State> org.tdl.vireo.state.State.getTransitions (Submission submission)
Return a list of valid transitions for this submission.
Parameters
submission The submission in its current state.
Returns
A list of transitions.
Implemented in org.tdl.vireo.state.impl.StateImpl.
boolean org.tdl.vireo.state.State.isActive ()
Returns
Whether this state is considered under active review by reviewers. I.e. after a student has submitted the submission. But before it has been approved & published.
Implemented in org.tdl.vireo.state.impl.StateImpl.
boolean org.tdl.vireo.state.State.isApproved ()
Returns
Whether a submission transitioned into this state should be considered approved. If so then the approvalDate will be set of the submission.
Implemented in org.tdl.vireo.state.impl.StateImpl.
Referenced by org.tdl.vireo.model.jpa.JpaSubmissionImpl.setState().
boolean org.tdl.vireo.state.State.isArchived ()
Returns
Whether this state is in a terminal state such as published, cancelled, etc.,
Implemented in org.tdl.vireo.state.impl.StateImpl.
boolean org.tdl.vireo.state.State.isDeletable ()
Returns
Whether this state should display the option to permanently remove the submission.
Implemented in org.tdl.vireo.state.impl.StateImpl.
boolean org.tdl.vireo.state.State.isDepositable ()
Returns
Whether this state should be deposited in to a repository when transitioning into this state.
Implemented in org.tdl.vireo.state.impl.StateImpl.
Referenced by org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.doJob(), and org.tdl.vireo.batch.impl.TransitionServiceImpl.TransitionJob.TransitionJob().
boolean org.tdl.vireo.state.State.isEditableByReviewer ()
Returns
Whether a reviewer can edit the submission during this state.
Implemented in org.tdl.vireo.state.impl.StateImpl.
boolean org.tdl.vireo.state.State.isEditableByStudent ()
Returns
Whether the student can edit the submission during this state.
Implemented in org.tdl.vireo.state.impl.StateImpl.
boolean org.tdl.vireo.state.State.isInProgress ()
Returns
Whether this state is considered to be in-progress by the student. I.e. are they still editing it prior to submission.
Implemented in org.tdl.vireo.state.impl.StateImpl.
boolean org.tdl.vireo.state.State.isInWorkflow ()
Implemented in org.tdl.vireo.state.impl.StateImpl.
The documentation for this interface was generated from the following file:
app/org/tdl/vireo/state/State.java