Vireo: org.tdl.vireo.search.Indexer Interface Reference
org.tdl.vireo.search.Indexer Interface Reference
Public Member Functions
public< T extends
AbstractModel > void updated (T model)
void updated (Long submissionId)
void updated (List< Long > submissionIds)
boolean isUpdated (Long submissionId)
boolean isUpdated (Submission submission)
void rollback ()
void commit (boolean wait)
void rebuild (boolean wait)
void deleteAndRebuild (boolean wait)
boolean isJobRunning ()
String getCurrentJobLabel ()
long getCurrentJobProgress ()
long getCurrentJobTotal ()
Detailed Description
Search indexer.
The purpose of this interface is to receive updates to various model objects and update the search index. Typically the implementation of this interface is also tied to the implementation of the sister interface: Searcher.
Author
Scott Phillips
Definition at line 18 of file Indexer.java.
Member Function Documentation
void org.tdl.vireo.search.Indexer.commit (boolean wait)
Commit the updated models to the search index.
Parameters
wait If true the method will not return until rebuilding the index is completed, otherwise rebuilding will take place in a background thread.
Implemented in org.tdl.vireo.search.impl.LuceneIndexerImpl.
void org.tdl.vireo.search.Indexer.deleteAndRebuild (boolean wait)
Delete the entire search index and rebuild it from scratch. This will cancel any index jobs currently in progress, and the index will be irrevocably deleted. Following the deletion, the index will be rebuild.
While this index is rebuilding searches may not be performed against the index. Any search that does process will result in an exception.
Parameters
wait If true the method will not return until rebuilding the index is completed, otherwise rebuilding will take place in a background thread.
Implemented in org.tdl.vireo.search.impl.LuceneIndexerImpl.
String org.tdl.vireo.search.Indexer.getCurrentJobLabel ()
Returns
The label of the current background process, either "Updating Index" or "Rebuilding Index"
Implemented in org.tdl.vireo.search.impl.LuceneIndexerImpl.
long org.tdl.vireo.search.Indexer.getCurrentJobProgress ()
Returns
The current progress of how many submissions have been indexed so far.
Implemented in org.tdl.vireo.search.impl.LuceneIndexerImpl.
Referenced by controllers.System.generalPanel().
long org.tdl.vireo.search.Indexer.getCurrentJobTotal ()
Returns
The total number of submissions that will be indexed by the background process.
Implemented in org.tdl.vireo.search.impl.LuceneIndexerImpl.
Referenced by controllers.System.generalPanel().
boolean org.tdl.vireo.search.Indexer.isJobRunning ()
Returns
True if a background process is currently updating the search index.
Implemented in org.tdl.vireo.search.impl.LuceneIndexerImpl.
Referenced by controllers.System.generalPanel().
boolean org.tdl.vireo.search.Indexer.isUpdated (Long submissionId)
Parameters
submissionId The id of a submission object.
Returns
True if the identified submission is included in the current transaction.
Implemented in org.tdl.vireo.search.impl.LuceneIndexerImpl.
boolean org.tdl.vireo.search.Indexer.isUpdated (Submission submission)
Parameters
submission A submission object.
Returns
True if the submission object is included in the current transaction.
Implemented in org.tdl.vireo.search.impl.LuceneIndexerImpl.
void org.tdl.vireo.search.Indexer.rebuild (boolean wait)
Rebuild the entire search index from scratch.
This will remove all entries in the search index and rebuild it.
Parameters
wait If true the method will not return until rebuilding the index is completed, otherwise rebuilding will take place in a background thread.
Implemented in org.tdl.vireo.search.impl.LuceneIndexerImpl.
void org.tdl.vireo.search.Indexer.rollback ()
Roll back the current proposed changes to the model. This is typically called after an exception and database rollback. When called the indexer will forget the previous updated() models.
Implemented in org.tdl.vireo.search.impl.LuceneIndexerImpl.
public<T extends AbstractModel> void org.tdl.vireo.search.Indexer.updated (T model)
This is a notification method that the provided model object has been updated (either created, saved, or deleted), but has not been committed to the database yet. The indexer will keep this proposed update until either rollback() or commit() is called from the same thread.
Parameters
model The model object which was created, saved, or deleted.
Implemented in org.tdl.vireo.search.impl.LuceneIndexerImpl.
void org.tdl.vireo.search.Indexer.updated (Long submissionId)
This is a notification method to update the index for the provided submission Id. This works the same as the updated(model) varient however this may be more efficient in situations where the full object is not available. The indexer will keep track of these submissions until either rollback() or commit() is called from the same thread.
Parameters
submissionId The id of the submission which was created, saved, or deleted.
Implemented in org.tdl.vireo.search.impl.LuceneIndexerImpl.
void org.tdl.vireo.search.Indexer.updated (List< Long > submissionIds)
This is a notification method to update the index for the provided list of submission ids. This works the same as the updated(model) varient however this may be more efficient in situations where the full object is not available. The indexer will keep track of these submissions until either rollback() or commit() is called from the same thread.
Parameters
submissionIds A list of submission ids which were created, saved, or deleted.
Implemented in org.tdl.vireo.search.impl.LuceneIndexerImpl.
The documentation for this interface was generated from the following file:
app/org/tdl/vireo/search/Indexer.java