Vireo: org.tdl.vireo.model.SettingsRepository Interface Reference
org.tdl.vireo.model.SettingsRepository Interface Reference
Public Member Functions
Degree createDegree (String name, DegreeLevel level)
Degree findDegree (Long id)
Degree findDegreeByName (String name)
List< Degree > findAllDegrees ()
Major createMajor (String name)
Major findMajor (Long id)
List< Major > findAllMajors ()
College createCollege (String name)
College createCollege (String name, HashMap< Integer, String > emails)
College findCollege (Long id)
College findCollegeByName (String name)
List< College > findAllColleges ()
Program createProgram (String name)
Program createProgram (String name, HashMap< Integer, String > emails)
Program findProgram (Long id)
Program findProgramByName (String name)
List< Program > findAllPrograms ()
Department createDepartment (String name)
Department createDepartment (String name, HashMap< Integer, String > emails)
Department findDepartment (Long id)
Department findDepartmentByName (String name)
List< Department > findAllDepartments ()
AdministrativeGroup createAdministrativeGroup (String name)
AdministrativeGroup createAdministrativeGroup (String name, HashMap< Integer, String > emails)
AdministrativeGroup findAdministrativeGroup (Long id)
AdministrativeGroup findAdministrativeGroupByName (String name)
List< AdministrativeGroup > findAllAdministrativeGroups ()
DocumentType createDocumentType (String name, DegreeLevel level)
DocumentType findDocumentType (Long id)
List< DocumentType > findAllDocumentTypes (DegreeLevel level)
List< DocumentType > findAllDocumentTypes ()
Language createLanguage (String name)
Language findLanguage (Long id)
Language findLanguageByName (String name)
List< Language > findAllLanguages ()
EmbargoType createEmbargoType (String name, String description, Integer duration, boolean active)
EmbargoType createEmbargoType (String name, String description, Integer duration, boolean active, EmbargoGuarantor guarantor)
EmbargoType findEmbargoType (Long id)
List< EmbargoType > findAllEmbargoTypes ()
EmbargoType findSystemEmbargoTypeByNameAndGuarantor (String name, EmbargoGuarantor guarantor)
EmbargoType findNonSystemEmbargoTypeByNameAndGuarantor (String name, EmbargoGuarantor guarantor)
List< EmbargoType > findAllActiveEmbargoTypes ()
GraduationMonth createGraduationMonth (int month)
GraduationMonth findGraduationMonth (Long id)
List< GraduationMonth > findAllGraduationMonths ()
CommitteeMemberRoleType createCommitteeMemberRoleType (String name, DegreeLevel level)
CommitteeMemberRoleType findCommitteeMemberRoleType (Long id)
List< CommitteeMemberRoleType > findAllCommitteeMemberRoleTypes (DegreeLevel level)
List< CommitteeMemberRoleType > findAllCommitteeMemberRoleTypes ()
AbstractWorkflowRuleCondition createEmailWorkflowRuleCondition (ConditionType condition)
AbstractWorkflowRuleCondition findEmailWorkflowRuleCondition (Long id)
List
< AbstractWorkflowRuleCondition > findAllEmailWorkflowRuleConditions ()
EmailWorkflowRule createEmailWorkflowRule (State associatedState)
EmailWorkflowRule findEmailWorkflowRule (Long id)
List< EmailWorkflowRule > findEmailWorkflowRulesByState (State type)
List< EmailWorkflowRule > findAllEmailWorkflowRules ()
EmailTemplate createEmailTemplate (String name, String subject, String message)
EmailTemplate findEmailTemplate (Long id)
EmailTemplate findEmailTemplateByName (String name)
EmailTemplate findSystemEmailTemplateByName (String name)
EmailTemplate findNonSystemEmailTemplateByName (String name)
List< EmailTemplate > findAllEmailTemplates ()
CustomActionDefinition createCustomActionDefinition (String label, Boolean isStudentVisible)
CustomActionDefinition findCustomActionDefinition (Long id)
List< CustomActionDefinition > findAllCustomActionDefinition ()
Configuration createConfiguration (String name, String value)
Configuration findConfiguration (Long id)
Configuration findConfigurationByName (String name)
String getConfigValue (String name, String defaultValue)
String getConfigValue (String name)
boolean getConfigBoolean (String name)
List< Configuration > findAllConfigurations ()
DepositLocation createDepositLocation (String name)
DepositLocation findDepositLocation (Long id)
DepositLocation findDepositLocationByName (String name)
List< DepositLocation > findAllDepositLocations ()
Detailed Description
The Vireo persistent repository for application-level settings. This object follows the spring repository pattern, where this is the source for creating and locating all persistent model objects. It is intended that this object will be injected into all other spring beans that need access application settings.
Author
Scott Phillips
Definition at line 17 of file SettingsRepository.java.
Member Function Documentation
AdministrativeGroup org.tdl.vireo.model.SettingsRepository.createAdministrativeGroup (String name)
Create a new administrative group object.
Parameters
name The name of the administrative group.
Returns
A new administrative group object.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
AdministrativeGroup org.tdl.vireo.model.SettingsRepository.createAdministrativeGroup (String name, HashMap< Integer, String > emails)
Create a new administrative group object with email.
Parameters
name The name of the administrative group.
emails A list of emails.
Returns
A new administrative group object.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
College org.tdl.vireo.model.SettingsRepository.createCollege (String name)
Create a new college object.
Parameters
name The name of the college.
Returns
A new college object.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
College org.tdl.vireo.model.SettingsRepository.createCollege (String name, HashMap< Integer, String > emails)
Create a new college object with email.
Parameters
name The name of the college.
emails A list of emails.
Returns
A new college object.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
CommitteeMemberRoleType org.tdl.vireo.model.SettingsRepository.createCommitteeMemberRoleType (String name, DegreeLevel level)
Create a new committee member role type
Parameters
name The name of the role.
level The level this role is available for.
Returns
A role type object.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Configuration org.tdl.vireo.model.SettingsRepository.createConfiguration (String name, String value)
Create a new system wide configuration.
Parameters
name The name of the canfiguration parameter.
value The value.
Returns
A new configuration object.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
CustomActionDefinition org.tdl.vireo.model.SettingsRepository.createCustomActionDefinition (String label, Boolean isStudentVisible)
Create a new custom action definition
Parameters
label The action's label
Returns
A new custom action definition.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Degree org.tdl.vireo.model.SettingsRepository.createDegree (String name, DegreeLevel level)
Create a new Degree object
Parameters
name Name of the degree.
level Level of the degree.
Returns
A new degree object.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Department org.tdl.vireo.model.SettingsRepository.createDepartment (String name)
Create a new department object.
Parameters
name The name of the department.
Returns
A new department object.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Department org.tdl.vireo.model.SettingsRepository.createDepartment (String name, HashMap< Integer, String > emails)
Create a new department object with email.
Parameters
name The name of the department.
emails A list of emails.
Returns
A new department object.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
DepositLocation org.tdl.vireo.model.SettingsRepository.createDepositLocation (String name)
Create a new deposit location
Parameters
name The name of the new deposit location.
Returns
A new deposit location object.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
DocumentType org.tdl.vireo.model.SettingsRepository.createDocumentType (String name, DegreeLevel level)
Create a new document type object.
Parameters
name The name of the document type.
level The level this document type is applicable for.
Returns
A new document type object.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
EmailTemplate org.tdl.vireo.model.SettingsRepository.createEmailTemplate (String name, String subject, String message)
Create a new email template
Parameters
name The template's name
subject The template's subject
message The template's messages
Returns
A new email template object.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
EmailWorkflowRule org.tdl.vireo.model.SettingsRepository.createEmailWorkflowRule (State associatedState)
Create a new EmailWorkflowRule model.
Parameters
associatedState - Workflow Email Rules's Associated State.
Returns
- a new EmailWorkflowRule
Exceptions
SecurityException
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
AbstractWorkflowRuleCondition org.tdl.vireo.model.SettingsRepository.createEmailWorkflowRuleCondition (ConditionType condition)
Create a new EmailWorkflowRuleCondition
Parameters
condition - Workflow Rule's associated condition type
Returns
- a new EmailWorkflowRuleCondition
Exceptions
SecurityException
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
EmbargoType org.tdl.vireo.model.SettingsRepository.createEmbargoType (String name, String description, Integer duration, boolean active)
Create a new embargo type.
Parameters
name The unique name of the embargo type
description A description of the embargo.
duration How long the embargo should last messured in months. Null for ideterminate, zero for no embargo, and negative numbers are not allowed.
active Weather the embargo is currently active.
Returns
A new embargo type.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
EmbargoType org.tdl.vireo.model.SettingsRepository.createEmbargoType (String name, String description, Integer duration, boolean active, EmbargoGuarantor guarantor)
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
GraduationMonth org.tdl.vireo.model.SettingsRepository.createGraduationMonth (int month)
Create a new graduation month.
Parameters
month The graduation month.
Returns
A new graduation month object.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Language org.tdl.vireo.model.SettingsRepository.createLanguage (String name)
Create a language
Parameters
name The description provided by Proquest of the language.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Major org.tdl.vireo.model.SettingsRepository.createMajor (String name)
Create a new Major object.
Parameters
name The name of the major.
Returns
A new major object.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Program org.tdl.vireo.model.SettingsRepository.createProgram (String name)
Create a new program object.
Parameters
name The name of the program
Returns
A new program object.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Program org.tdl.vireo.model.SettingsRepository.createProgram (String name, HashMap< Integer, String > emails)
Create a new program object with email.
Parameters
name The name of the program.
emails A list of emails.
Returns
A new program object.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
AdministrativeGroup org.tdl.vireo.model.SettingsRepository.findAdministrativeGroup (Long id)
Find a administrative group by unique id.
Parameters
id The administrative group's id.
Returns
The administrative group object or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
AdministrativeGroup org.tdl.vireo.model.SettingsRepository.findAdministrativeGroupByName (String name)
Find a administrative group by unique name.
Parameters
name The administrative group's name.
Returns
The administrative group object or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
List<EmbargoType> org.tdl.vireo.model.SettingsRepository.findAllActiveEmbargoTypes ()
Find all embargo types objects in order.
Returns
A list of all embargo types, or an empty list if there are none.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
List<AdministrativeGroup> org.tdl.vireo.model.SettingsRepository.findAllAdministrativeGroups ()
Find all administrative groups objects in order.
Returns
A list of all administrative groups, or an empty list if there are none.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Referenced by org.tdl.vireo.services.Utilities.processEmailDesigneeArray().
List<College> org.tdl.vireo.model.SettingsRepository.findAllColleges ()
Find all college objects in order.
Returns
A list of all colleges, or an empty list if there are none.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Referenced by controllers.submit.PersonalInfo.isValidCollege().
List<CommitteeMemberRoleType> org.tdl.vireo.model.SettingsRepository.findAllCommitteeMemberRoleTypes (DegreeLevel level)
Find all committee member role type objects in order that are valid for a particular degree level.
Parameters
level The degree level to find.
Returns
A list of all role types, or an empty list if there are none.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
List<CommitteeMemberRoleType> org.tdl.vireo.model.SettingsRepository.findAllCommitteeMemberRoleTypes ()
Find all committee role type objects in order.
Returns
A list of all role types, or an empty list if there are none.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
List<Configuration> org.tdl.vireo.model.SettingsRepository.findAllConfigurations ()
Find all system wide configuration parameters.
Returns
A list of all system wide configuration parameters, or an empty list if there are none.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
List<CustomActionDefinition> org.tdl.vireo.model.SettingsRepository.findAllCustomActionDefinition ()
Find all custom action definitions in order.
Returns
A list of all custom action definitions, or an empty list if there are none.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
List<Degree> org.tdl.vireo.model.SettingsRepository.findAllDegrees ()
Find all degree objects in order.
Returns
A list of all degrees, or an empty list if there are none.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Referenced by controllers.submit.PersonalInfo.isValidDegree().
List<Department> org.tdl.vireo.model.SettingsRepository.findAllDepartments ()
Find all department objects in order.
Returns
A list of all departments, or an empty list if there are none.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Referenced by controllers.submit.PersonalInfo.isValidDepartment().
List<DepositLocation> org.tdl.vireo.model.SettingsRepository.findAllDepositLocations ()
Find all defined deposit locations.
Returns
A list of all deposit locations.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
List<DocumentType> org.tdl.vireo.model.SettingsRepository.findAllDocumentTypes (DegreeLevel level)
Find all document type objects in order that are valid for a particular degree level.
Parameters
level The degree level to find.
Returns
A list of all document types, or an empty list if there are none.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
List<DocumentType> org.tdl.vireo.model.SettingsRepository.findAllDocumentTypes ()
Find all document type objects in order.
Returns
A list of all document types, or an empty list if there are none.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
List<EmailTemplate> org.tdl.vireo.model.SettingsRepository.findAllEmailTemplates ()
Find all email templates in order.
Returns
A list of all email templates, or an empty list if there are none.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
List<AbstractWorkflowRuleCondition> org.tdl.vireo.model.SettingsRepository.findAllEmailWorkflowRuleConditions ()
Returns
- All of the EmailWorkflowRuleCondition objects
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
List<EmailWorkflowRule> org.tdl.vireo.model.SettingsRepository.findAllEmailWorkflowRules ()
Returns
All Workflow Email Rule objects
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
List<EmbargoType> org.tdl.vireo.model.SettingsRepository.findAllEmbargoTypes ()
Find all embargo types objects in order.
Returns
A list of all embargo types, or an empty list if there are none.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
List<GraduationMonth> org.tdl.vireo.model.SettingsRepository.findAllGraduationMonths ()
Find all graduation months in order.
Returns
A list of all graduation months, or an empty list if there are none.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Referenced by controllers.submit.DocumentInfo.isValidDegreeMonth().
List<Language> org.tdl.vireo.model.SettingsRepository.findAllLanguages ()
Find all available languages.
Returns
A list of all available languages, or an empty list if there are none.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
List<Major> org.tdl.vireo.model.SettingsRepository.findAllMajors ()
Find all majors objects in order.
Returns
A list of all majors, or an empty list if there are none.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Referenced by controllers.submit.PersonalInfo.isValidMajor().
List<Program> org.tdl.vireo.model.SettingsRepository.findAllPrograms ()
Find all program objects in order.
Returns
A list of all programs, or an empty list if there are none.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Referenced by controllers.submit.PersonalInfo.isValidProgram().
College org.tdl.vireo.model.SettingsRepository.findCollege (Long id)
Find a college by unique id.
Parameters
id The college's id.
Returns
The college object or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
College org.tdl.vireo.model.SettingsRepository.findCollegeByName (String name)
Find a college by unique name.
Parameters
name The college's name.
Returns
The college object or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
CommitteeMemberRoleType org.tdl.vireo.model.SettingsRepository.findCommitteeMemberRoleType (Long id)
Find a committee member role type by id.
Parameters
id The type's id.
Returns
The role type object, or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Configuration org.tdl.vireo.model.SettingsRepository.findConfiguration (Long id)
Find a system wide configuration object by id.
Parameters
id The configuration's id.
Returns
The configuration object, or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Configuration org.tdl.vireo.model.SettingsRepository.findConfigurationByName (String name)
Find a system wide configuration object by name.
Parameters
name The configuration's name.
Returns
The configuration object, or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
CustomActionDefinition org.tdl.vireo.model.SettingsRepository.findCustomActionDefinition (Long id)
Find custom action definition by id.
Parameters
id The action's id.
Returns
The custom action definition, or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Degree org.tdl.vireo.model.SettingsRepository.findDegree (Long id)
Find degree by unique id.
Parameters
id The degree's id.
Returns
The degree object or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Degree org.tdl.vireo.model.SettingsRepository.findDegreeByName (String name)
Find degree by name.
Parameters
name The name given to the degree.
Returns
The degree object or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Referenced by controllers.submit.PersonalInfo.personalInfo().
Department org.tdl.vireo.model.SettingsRepository.findDepartment (Long id)
Find department by unique id
Parameters
id The department's id.
Returns
The department object or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Department org.tdl.vireo.model.SettingsRepository.findDepartmentByName (String name)
Find department by unique name
Parameters
name The department's name.
Returns
The department object or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
DepositLocation org.tdl.vireo.model.SettingsRepository.findDepositLocation (Long id)
Find a deposit location object by id.
Parameters
id The location's unique id.
Returns
The deposit location, or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
DepositLocation org.tdl.vireo.model.SettingsRepository.findDepositLocationByName (String name)
Find a deposit location by name.
Parameters
name The location's unique name.
Returns
The deposit location, or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
DocumentType org.tdl.vireo.model.SettingsRepository.findDocumentType (Long id)
Find a document type by id.
Parameters
id The document type's id.
Returns
The document type object, or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
EmailTemplate org.tdl.vireo.model.SettingsRepository.findEmailTemplate (Long id)
Find an email template by id.
Parameters
id The email template's id.
Returns
The email template object, or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
EmailTemplate org.tdl.vireo.model.SettingsRepository.findEmailTemplateByName (String name)
Find an email template by it's name.
If a System email template name is passed in, a Custom version will be returned if it exists.
Parameters
name The name of the template.
Returns
The email template found, or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
EmailWorkflowRule org.tdl.vireo.model.SettingsRepository.findEmailWorkflowRule (Long id)
Find a workflow email rule based upon their unique id.
Parameters
id Workflow Email Rules's id.
Returns
The Workflow Email Rule object or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
AbstractWorkflowRuleCondition org.tdl.vireo.model.SettingsRepository.findEmailWorkflowRuleCondition (Long id)
Find a workflow rule condition base upon their unique id.
Parameters
id - the workflow email rule condition's id.
Returns
- the workflow email rule condition or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
List<EmailWorkflowRule> org.tdl.vireo.model.SettingsRepository.findEmailWorkflowRulesByState (State type)
Find a Workflow Email Rule based on their associated state.
Parameters
state The Workflow Email Rule's associated state.
Returns
The Workflow Email Rule object or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
EmbargoType org.tdl.vireo.model.SettingsRepository.findEmbargoType (Long id)
Find embargo type by id.
Parameters
id The embargo type's id.
Returns
The embargo type, or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
GraduationMonth org.tdl.vireo.model.SettingsRepository.findGraduationMonth (Long id)
Find a graduation month by id.
Parameters
id The month's id.
Returns
The graduation month object, or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Language org.tdl.vireo.model.SettingsRepository.findLanguage (Long id)
Find a language by id.
Parameters
id The id of the language.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Language org.tdl.vireo.model.SettingsRepository.findLanguageByName (String name)
Find a language by the name
Parameters
name The name of the language.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Major org.tdl.vireo.model.SettingsRepository.findMajor (Long id)
Find major by unique id.
Parameters
id The major's id.
Returns
The major object or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
EmailTemplate org.tdl.vireo.model.SettingsRepository.findNonSystemEmailTemplateByName (String name)
Find a NonSystem email template by it's name.
Parameters
name The name of the NonSystem template.
Returns
The NonSystem email template found, or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
EmbargoType org.tdl.vireo.model.SettingsRepository.findNonSystemEmbargoTypeByNameAndGuarantor (String name, EmbargoGuarantor guarantor)
Find the NonSystem embargo types object that matches name.
Parameters
name
Returns
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Program org.tdl.vireo.model.SettingsRepository.findProgram (Long id)
Find a program by unique id.
Parameters
id The program's id
Returns
The program object or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Program org.tdl.vireo.model.SettingsRepository.findProgramByName (String name)
Find a program by unique name.
Parameters
name The program's name.
Returns
The program object or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
EmailTemplate org.tdl.vireo.model.SettingsRepository.findSystemEmailTemplateByName (String name)
Find a System email template by it's name.
Parameters
name The name of the System template.
Returns
The System email template found, or null if not found.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
EmbargoType org.tdl.vireo.model.SettingsRepository.findSystemEmbargoTypeByNameAndGuarantor (String name, EmbargoGuarantor guarantor)
Find the System embargo types object that matches name.
Parameters
name
Returns
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
boolean org.tdl.vireo.model.SettingsRepository.getConfigBoolean (String name)
Find a system wide configuration and return it's boolean value. If the configuration parameter has any value at all it is considered true, if no configuration entry is defined for the parameter then it is considered false.
Parameters
name The name of the configuration object.
Returns
The value
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Referenced by controllers.submit.PersonalInfo.personalInfo(), and controllers.Authentication.updateProfile().
String org.tdl.vireo.model.SettingsRepository.getConfigValue (String name, String defaultValue)
Find a system wide configuration and return it's value. If the configuration parameter is not set, then return the default value supplied.
Parameters
name The name of the configuration object.
defaultValue The default value for the configuration object if not found.
Returns
The value
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
Referenced by controllers.submit.FieldTags.isEnabled(), and controllers.submit.FieldTags.isRequired().
String org.tdl.vireo.model.SettingsRepository.getConfigValue (String name)
Find a system wide configuration and return it's value. If the configuration object does not exist the the Configuration.DEFAULTS registry will be consulted. If a default has been registered for the parameter then the default will be returned, otherwise null.
Parameters
name The name of the parameter.
Returns
The value, or null.
Implemented in org.tdl.vireo.model.jpa.JpaSettingsRepositoryImpl.
The documentation for this interface was generated from the following file:
app/org/tdl/vireo/model/SettingsRepository.java