Vireo: org.tdl.vireo.model.Attachment Interface Reference
org.tdl.vireo.model.Attachment Interface Reference
Public Member Functions
void archive ()
Submission getSubmission ()
String getName ()
void setName (String name)
AttachmentType getType ()
void setType (AttachmentType type)
String getMimeType ()
long getSize ()
String getDisplaySize ()
File getFile ()
Person getPerson ()
Date getDate ()
Public Member Functions inherited from org.tdl.vireo.model.AbstractModel
Long getId ()
public< T extends AbstractModel > T save ()
public< T extends AbstractModel > T delete ()
public< T extends AbstractModel > T refresh ()
public< T extends AbstractModel > T merge ()
public< T extends AbstractModel > T detach ()
Detailed Description
A file attachment associated with a particular submission such as the primary document, supplemental content, or feedback. The metadata about an attachment, it's name, or mimetype, may be changed but the contents of the file is immutable. If you need to modify the attachments contents then just delete the attachment and create a new document for the updated content.
Author
Scott Phillips
Definition at line 15 of file Attachment.java.
Member Function Documentation
void org.tdl.vireo.model.Attachment.archive ()
Archive this attachment.
This means changing the type to be ARCHIVED, and modifying the name to denote that it is an archive file (so that the name can be re-used)
This will fail if the attachment is already an archive.
Implemented in org.tdl.vireo.model.jpa.JpaAttachmentImpl, and org.tdl.vireo.model.jpa.ActionLogAttachment.
Date org.tdl.vireo.model.Attachment.getDate ()
Returns
The date the attachment was uploaded.
Implemented in org.tdl.vireo.model.jpa.JpaAttachmentImpl, and org.tdl.vireo.model.jpa.ActionLogAttachment.
Referenced by controllers.ViewTab.AttachmentSortByDate.compare().
String org.tdl.vireo.model.Attachment.getDisplaySize ()
Returns
The displayable size of this file, such as "12 MB".
Implemented in org.tdl.vireo.model.jpa.JpaAttachmentImpl, and org.tdl.vireo.model.jpa.ActionLogAttachment.
File org.tdl.vireo.model.Attachment.getFile ()
Returns
The file.
Implemented in org.tdl.vireo.model.jpa.JpaAttachmentImpl, and org.tdl.vireo.model.jpa.ActionLogAttachment.
Referenced by controllers.Student.viewAttachment().
String org.tdl.vireo.model.Attachment.getMimeType ()
Returns
The mimetype of the file.
Implemented in org.tdl.vireo.model.jpa.JpaAttachmentImpl, and org.tdl.vireo.model.jpa.ActionLogAttachment.
String org.tdl.vireo.model.Attachment.getName ()
The name of the file will be how the file is named on disk with an extension following the normal conventions of file names. Some examples are: "myresearch.pdf", "survey_data.xsls", etc...
Returns
The technical name of the file.
Implemented in org.tdl.vireo.model.jpa.JpaAttachmentImpl, and org.tdl.vireo.model.jpa.ActionLogAttachment.
Referenced by controllers.Student.viewAttachment().
Person org.tdl.vireo.model.Attachment.getPerson ()
Returns
The person that uploaded the attachment.
Implemented in org.tdl.vireo.model.jpa.JpaAttachmentImpl, and org.tdl.vireo.model.jpa.ActionLogAttachment.
long org.tdl.vireo.model.Attachment.getSize ()
Returns
The file size measured in bytes.
Implemented in org.tdl.vireo.model.jpa.JpaAttachmentImpl, and org.tdl.vireo.model.jpa.ActionLogAttachment.
Submission org.tdl.vireo.model.Attachment.getSubmission ()
Returns
The submission this attachment belongs too.
Implemented in org.tdl.vireo.model.jpa.JpaAttachmentImpl, and org.tdl.vireo.model.jpa.ActionLogAttachment.
Referenced by controllers.Student.viewAttachment().
AttachmentType org.tdl.vireo.model.Attachment.getType ()
Returns
The attachment types.
Implemented in org.tdl.vireo.model.jpa.JpaAttachmentImpl, and org.tdl.vireo.model.jpa.ActionLogAttachment.
void org.tdl.vireo.model.Attachment.setName (String name)
Parameters
name The new technical name of the file.
Implemented in org.tdl.vireo.model.jpa.JpaAttachmentImpl, and org.tdl.vireo.model.jpa.ActionLogAttachment.
Referenced by controllers.ViewTab.editFile().
void org.tdl.vireo.model.Attachment.setType (AttachmentType type)
Parameters
type The new type of this attachment.
Implemented in org.tdl.vireo.model.jpa.JpaAttachmentImpl, and org.tdl.vireo.model.jpa.ActionLogAttachment.
The documentation for this interface was generated from the following file:
app/org/tdl/vireo/model/Attachment.java