Vireo: org.tdl.vireo.model.Submission Interface Reference
org.tdl.vireo.model.Submission Interface Reference
Public Member Functions
Person getSubmitter ()
String getStudentFirstName ()
void setStudentFirstName (String firstName)
String getStudentLastName ()
void setStudentLastName (String lastName)
String getStudentMiddleName ()
void setStudentMiddleName (String middleName)
Integer getStudentBirthYear ()
void setStudentBirthYear (Integer year)
String getOrcid ()
void setOrcid (String orcidString)
String getStudentFormattedName (NameFormat format)
String getDocumentTitle ()
void setDocumentTitle (String title)
String getDocumentAbstract ()
void setDocumentAbstract (String docAbstract)
String getDocumentKeywords ()
void setDocumentKeywords (String keywords)
List< String > getDocumentSubjects ()
void addDocumentSubject (String subject)
void removeDocumentSubject (String subject)
void setDocumentLanguage (String language)
String getDocumentLanguage ()
Locale getDocumentLanguageLocale ()
void setPublishedMaterial (String material)
String getPublishedMaterial ()
List< EmbargoType > getEmbargoTypes ()
void addEmbargoType (EmbargoType embargo)
void removeEmbargoType (EmbargoType embargo)
EmbargoType getEmbargoTypeByGuarantor (EmbargoGuarantor guarantor)
Attachment getPrimaryDocument ()
List< Attachment > getSupplementalDocuments ()
List< Attachment > getAttachments ()
List< Attachment > getAttachmentsByType (AttachmentType...types)
Attachment addAttachment (File file, AttachmentType type) throws IOException
Attachment addAttachment (byte[] content, String filename, AttachmentType type) throws IOException
Attachment findAttachmentById (Long id)
Attachment findAttachmentByName (String name)
List< CommitteeMember > getCommitteeMembers ()
CommitteeMember addCommitteeMember (String firstName, String lastName, String middleName)
String getCommitteeContactEmail ()
void setCommitteeContactEmail (String email)
String getCommitteeEmailHash ()
void setCommitteeEmailHash (String hash)
Date getCommitteeApprovalDate ()
void setCommitteeApprovalDate (Date date)
Date getCommitteeEmbargoApprovalDate ()
void setCommitteeEmbargoApprovalDate (Date date)
Date getSubmissionDate ()
void setSubmissionDate (Date date)
Date getApprovalDate ()
void setApprovalDate (Date date)
Date getLicenseAgreementDate ()
void setLicenseAgreementDate (Date date)
Date getDefenseDate ()
void setDefenseDate (Date date)
String getDegree ()
void setDegree (String degree)
DegreeLevel getDegreeLevel ()
void setDegreeLevel (DegreeLevel level)
String getDepartment ()
void setDepartment (String department)
Long getDepartmentId ()
void setDepartmentId (Long id)
String getCollege ()
void setCollege (String college)
Long getCollegeId ()
void setCollegeId (Long id)
String getProgram ()
void setProgram (String program)
Long getProgramId ()
void setProgramId (Long id)
String getMajor ()
void setMajor (String major)
String getDocumentType ()
void setDocumentType (String documentType)
Integer getGraduationYear ()
void setGraduationYear (Integer year)
Integer getGraduationMonth ()
void setGraduationMonth (Integer month)
State getState ()
void setState (State state)
Person getAssignee ()
void setAssignee (Person assignee)
Boolean getUMIRelease ()
void setUMIRelease (Boolean umiRelease)
List< CustomActionValue > getCustomActions ()
CustomActionValue getCustomAction (CustomActionDefinition definition)
CustomActionValue addCustomAction (CustomActionDefinition definition, Boolean value)
String getDepositId ()
void setDepositId (String depositId)
Date getDepositDate ()
void setDepositDate (Date depositDate)
String getReviewerNotes ()
void setReviewerNotes (String notes)
String getLastLogEntry ()
Date getLastLogDate ()
ActionLog logAction (String entry)
Public Member Functions inherited from org.tdl.vireo.model.AbstractModel
Long getId ()
public< T extends AbstractModel > T save ()
public< T extends AbstractModel > T delete ()
public< T extends AbstractModel > T refresh ()
public< T extends AbstractModel > T merge ()
public< T extends AbstractModel > T detach ()
Detailed Description
The submission object is really the heart of the vireo workflow data model. It represents the student's ETD application. The only absolutely required parameters are the system assigned identifier, and the original person submitting. Instead of treating committee members as first class person objects like we do for students we specialize their treatment as a separate object type. The reason for this is because the institution may not be able to authenticate the committee member through shibboleth because there are cases where the committee member is outside of the university, perhaps because this is a joint degree program or they have retired. To handle this case, when vireo sends an email to the faculty member for approval an email hash is generated the chair is expected to use the hash to authenticate their return to vireo where they can approve the application.
Author
Scott Phillips
Definition at line 29 of file Submission.java.
Member Function Documentation
Attachment org.tdl.vireo.model.Submission.addAttachment (File file, AttachmentType type) throws IOException
Add a new attachment from a file.
Parameters
file The new attachment file.
type The type of the attachment.
Returns
The newly created attachment.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Attachment org.tdl.vireo.model.Submission.addAttachment (byte[] content, String filename, AttachmentType type) throws IOException
Add a new attachment from a byte arra.
Parameters
content The contents of the new attachment.
filename The filename of the file.
type The type of attachment.
Returns
The newly created attachment.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
CommitteeMember org.tdl.vireo.model.Submission.addCommitteeMember (String firstName, String lastName, String middleName)
Add a new committeeMember
Parameters
firstName The first name of the new member.
lastName The last name of the new member.
middleName The middle name of the new member.
Returns
The newly created member.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
CustomActionValue org.tdl.vireo.model.Submission.addCustomAction (CustomActionDefinition definition, Boolean value)
Add a new custom action.
Parameters
definition The custom action definition.
value The value of the custom action.
Returns
The newly created custom action value.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.addDocumentSubject (String subject)
Add a new subject to the end of the list of subjects for this document.
Parameters
subject The subject to add.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.submit.DocumentInfo.documentInfo().
void org.tdl.vireo.model.Submission.addEmbargoType (EmbargoType embargo)
Parameters
embargo The new embargo type.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.ViewTab.embargoJSON().
Attachment org.tdl.vireo.model.Submission.findAttachmentById (Long id)
Returns
The specific attachment
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Attachment org.tdl.vireo.model.Submission.findAttachmentByName (String name)
Returns
the specific attachment
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Date org.tdl.vireo.model.Submission.getApprovalDate ()
Returns
The date the submission was approved for release, or null if it has not been approved.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow().
Person org.tdl.vireo.model.Submission.getAssignee ()
Returns
The assigned reviewer for this submission.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.services.EmailByRecipientType.getRecipients(), org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), and org.tdl.vireo.services.StringVariableReplacement.setParameters().
List<Attachment> org.tdl.vireo.model.Submission.getAttachments ()
Returns
The unordered list of all attachments.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.MultipleTemplatePackagerImpl.generatePackage(), org.tdl.vireo.export.impl.TemplatePackagerImpl.generatePackage(), controllers.submit.License.recordAgreement(), controllers.submit.License.recordDisagreement(), and controllers.submit.FileUpload.verify().
List<Attachment> org.tdl.vireo.model.Submission.getAttachmentsByType (AttachmentType... types)
Parameters
type The type of attachment.
Returns
Return a list of all attachments of the given type.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.submit.FileUpload.verify(), and controllers.Student.verify().
String org.tdl.vireo.model.Submission.getCollege ()
Returns
The college that will award this degree.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), and controllers.submit.PersonalInfo.verify().
Long org.tdl.vireo.model.Submission.getCollegeId ()
Returns
- The college id that will award this degree
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Date org.tdl.vireo.model.Submission.getCommitteeApprovalDate ()
Returns
The date the committee approved this submission, or null if it has not been approved.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow().
String org.tdl.vireo.model.Submission.getCommitteeContactEmail ()
Returns
Get the committee's contact email address.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.submit.DocumentInfo.documentInfo(), org.tdl.vireo.services.EmailByRecipientType.getRecipients(), org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), and controllers.submit.DocumentInfo.verify().
String org.tdl.vireo.model.Submission.getCommitteeEmailHash ()
Returns
The secrete committee email hash for approvals.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.ViewTab.getAdvisorURL(), and org.tdl.vireo.services.StringVariableReplacement.setParameters().
Date org.tdl.vireo.model.Submission.getCommitteeEmbargoApprovalDate ()
Returns
The date the committee approved the embargo type of this submission, or null if it has not been approved.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow().
List<CommitteeMember> org.tdl.vireo.model.Submission.getCommitteeMembers ()
Returns
The a list of all committee mebers associated with this submission.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.submit.DocumentInfo.loadCommitteeMembers(), org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), and controllers.submit.DocumentInfo.saveCommitteeMembers().
CustomActionValue org.tdl.vireo.model.Submission.getCustomAction (CustomActionDefinition definition)
Parameters
definition The definition of the single action to return.
Returns
The value for the provided custom action definition, otherwise null if no value found for the definition.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.ViewTab.updateCustomActionsJSON().
List<CustomActionValue> org.tdl.vireo.model.Submission.getCustomActions ()
Returns
An unordered list of all custom action values.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow().
Date org.tdl.vireo.model.Submission.getDefenseDate ()
Returns
The date of the submitter's defense.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.submit.DocumentInfo.documentInfo(), org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), controllers.ViewTab.updateJSON(), and controllers.submit.DocumentInfo.verify().
String org.tdl.vireo.model.Submission.getDegree ()
Returns
The degree for this submission.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.submit.DocumentInfo.getValidDocumentTypes(), org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), and controllers.submit.PersonalInfo.verify().
DegreeLevel org.tdl.vireo.model.Submission.getDegreeLevel ()
Returns
The degree level for this submission
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow().
String org.tdl.vireo.model.Submission.getDepartment ()
Returns
The degree department that will award this degree.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), and controllers.submit.PersonalInfo.verify().
Long org.tdl.vireo.model.Submission.getDepartmentId ()
Returns
- The department id that will award this degree
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Date org.tdl.vireo.model.Submission.getDepositDate ()
Returns
The date the submission was deposited.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
String org.tdl.vireo.model.Submission.getDepositId ()
Returns
The deposit id associated with submission. It usually is a URL but different repositories may use another identifier type.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), and org.tdl.vireo.services.StringVariableReplacement.setParameters().
String org.tdl.vireo.model.Submission.getDocumentAbstract ()
Returns
The document abstract
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.submit.DocumentInfo.documentInfo(), org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), and controllers.submit.DocumentInfo.verify().
String org.tdl.vireo.model.Submission.getDocumentKeywords ()
Returns
A list of document keywords
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), and controllers.submit.DocumentInfo.verify().
String org.tdl.vireo.model.Submission.getDocumentLanguage ()
Returns
Language of the document
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), and controllers.submit.DocumentInfo.verify().
Locale org.tdl.vireo.model.Submission.getDocumentLanguageLocale ()
Returns
The locale of the document language, or null if not set or invalid.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
List<String> org.tdl.vireo.model.Submission.getDocumentSubjects ()
Returns
the mutable list of document subjects. So you may use the add/remove/clear methods available on the list interface to modify this data. The list in it's current form will be saved when the submission object is receives a save() action.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), and controllers.submit.DocumentInfo.verify().
String org.tdl.vireo.model.Submission.getDocumentTitle ()
Returns
The document title.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.submit.DocumentInfo.documentInfo(), org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), org.tdl.vireo.services.StringVariableReplacement.setParameters(), and controllers.submit.DocumentInfo.verify().
String org.tdl.vireo.model.Submission.getDocumentType ()
Returns
The document type for this submission.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), org.tdl.vireo.services.StringVariableReplacement.setParameters(), and controllers.submit.DocumentInfo.verify().
EmbargoType org.tdl.vireo.model.Submission.getEmbargoTypeByGuarantor (EmbargoGuarantor guarantor)
Parameters
guarantor The guarantor of the embargo.
Returns
The type of embargo for this submission, affiliated with the specifed guarantor.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.state.impl.StateImpl.getTransitions().
List<EmbargoType> org.tdl.vireo.model.Submission.getEmbargoTypes ()
Returns
The type of embargo for this submission. Either requested or approved.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.model.jpa.JpaEmbargoTypeImpl.getSubmissions().
Integer org.tdl.vireo.model.Submission.getGraduationMonth ()
Returns
The graduation month
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.submit.DocumentInfo.documentInfo(), org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), org.tdl.vireo.services.StringVariableReplacement.setParameters(), controllers.ViewTab.updateJSON(), controllers.submit.DocumentInfo.verify(), and controllers.ViewTab.view().
Integer org.tdl.vireo.model.Submission.getGraduationYear ()
Returns
The graduation year
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), org.tdl.vireo.services.StringVariableReplacement.setParameters(), and controllers.submit.DocumentInfo.verify().
Date org.tdl.vireo.model.Submission.getLastLogDate ()
This is a short cut method to improve the performance of displaying search results. It is suggested that implementors cache the date of the last action log to improve performance.
Returns
The date of the last log event to affect this submission.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow().
String org.tdl.vireo.model.Submission.getLastLogEntry ()
This is a short cut method to improve the performance of displaying search results. It is suggested that implementors cache the entry of the last action log item to improve performance.
Returns
The entry of the last log event to affect this submission.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow().
Date org.tdl.vireo.model.Submission.getLicenseAgreementDate ()
Returns
The date the submitter agreed to the license for this submission, or null if the submitter has not agreed.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow().
String org.tdl.vireo.model.Submission.getMajor ()
Returns
The major that will award this degree.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), and controllers.submit.PersonalInfo.verify().
String org.tdl.vireo.model.Submission.getOrcid ()
Returns
The ORCID identifier of the student who authored this submission.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.submit.PersonalInfo.verify().
Attachment org.tdl.vireo.model.Submission.getPrimaryDocument ()
Returns
The attachment who's type is PRIMARY.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), controllers.submit.FileUpload.verify(), and controllers.Student.verify().
String org.tdl.vireo.model.Submission.getProgram ()
Returns
The program associated with the submission
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), and controllers.submit.PersonalInfo.verify().
Long org.tdl.vireo.model.Submission.getProgramId ()
Returns
- The program id that will award this degree
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
String org.tdl.vireo.model.Submission.getPublishedMaterial ()
Whether this submission contains material which has been previously published. Null indicates that no material has been previously published, otherwise a human readable description of the published material is supplied.
Returns
Previously published descriptor
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), and controllers.submit.DocumentInfo.verify().
String org.tdl.vireo.model.Submission.getReviewerNotes ()
Returns
Return the current reviewer notes. May only be accessed if a reviewer or above.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow().
State org.tdl.vireo.model.Submission.getState ()
Returns
The current application's state
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.submit.Confirm.confirm(), controllers.submit.AbstractSubmitStep.getSubmission(), org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), org.tdl.vireo.services.EmailRuleService.runEmailRules(), org.tdl.vireo.services.StringVariableReplacement.setParameters(), and controllers.Student.submissionView().
Integer org.tdl.vireo.model.Submission.getStudentBirthYear ()
Returns
The birth year for the student woh authored this submission.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.submit.PersonalInfo.verify().
String org.tdl.vireo.model.Submission.getStudentFirstName ()
Returns
The first name of the student who authored this submission.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.services.StringVariableReplacement.setParameters(), controllers.ViewTab.updateJSON(), and controllers.submit.PersonalInfo.verify().
String org.tdl.vireo.model.Submission.getStudentFormattedName (NameFormat format)
Parameters
format The format specifying how the name should be constructed.
Returns
The student's name according to the format specified.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow().
String org.tdl.vireo.model.Submission.getStudentLastName ()
Returns
The last name of the student who authored this submission.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.services.StringVariableReplacement.setParameters(), and controllers.submit.PersonalInfo.verify().
String org.tdl.vireo.model.Submission.getStudentMiddleName ()
Returns
The middle name of the student who authored this submission.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.submit.PersonalInfo.verify().
Date org.tdl.vireo.model.Submission.getSubmissionDate ()
Returns
The date the submission was submitted for review.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow().
Person org.tdl.vireo.model.Submission.getSubmitter ()
Returns
The original submitter who created this submission. This may not necessarily the graduating student. In cases where the submission is being made by a proxy like by a staff member then the submitter would be the person object for the staff member who original created the submission.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by org.tdl.vireo.services.EmailByRecipientType.getRecipients(), controllers.submit.AbstractSubmitStep.getSubmission(), controllers.Student.getSubmission(), org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), controllers.Student.submissionDelete(), controllers.Student.submissionRemoveAdditionalDocumentsJSON(), controllers.Student.submissionUploadAdditionalDocumentJSON(), controllers.Student.submissionUploadPrimaryDocumentJSON(), controllers.Student.submissionView(), controllers.submit.PersonalInfo.verify(), and controllers.Student.viewAttachment().
List<Attachment> org.tdl.vireo.model.Submission.getSupplementalDocuments ()
Returns
The unordered list of attachments who's type is SUPPLEMENTAL
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Boolean org.tdl.vireo.model.Submission.getUMIRelease ()
Returns
Weather the student has selected to release this submission to UMI.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.submit.License.license(), and org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow().
ActionLog org.tdl.vireo.model.Submission.logAction (String entry)
Create an action log entry about this submission.
Parameters
entry The entry text to be saved, note " by User" will be appended to the end of this entry text recording who made the action.
Returns
The unsaved action log object.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.removeDocumentSubject (String subject)
Remove the first occurrence of the subject from the list of subjects for this document..
Parameters
subject The subject to remove.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.removeEmbargoType (EmbargoType embargo)
Parameters
embargo The new embargo type.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.ViewTab.embargoJSON().
void org.tdl.vireo.model.Submission.setApprovalDate (Date date)
Parameters
date The new date this submission was approved.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setAssignee (Person assignee)
Parameters
assignee The new assigned reviewer.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setCollege (String college)
Parameters
college The new college.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setCollegeId (Long id)
Parameters
id - the college id that will award this degree
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setCommitteeApprovalDate (Date date)
Parameters
date Set the date the committee approved this submission.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setCommitteeContactEmail (String email)
Parameters
email Set the committee's contact email address.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setCommitteeEmailHash (String hash)
Parameters
hash The new secrete committee email hash.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setCommitteeEmbargoApprovalDate (Date date)
Parameters
date Set the date the committee approved the embargo type of this submission.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setDefenseDate (Date date)
Parameters
date The date of the submitter's defense.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setDegree (String degree)
Parameters
degree The new degree for this submission.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setDegreeLevel (DegreeLevel level)
Parameters
level The new degree level for this submission
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setDepartment (String department)
Parameters
department The new department.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setDepartmentId (Long id)
Parameters
id - the department id that will award this degree
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setDepositDate (Date depositDate)
Parameters
depositDate The date the submission was deposited.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setDepositId (String depositId)
Parameters
depositId Set the deposit id for this submission.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setDocumentAbstract (String docAbstract)
Parameters
docAbstract The new document abstract
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setDocumentKeywords (String keywords)
Parameters
keywords A new list of document keywords
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.submit.DocumentInfo.documentInfo().
void org.tdl.vireo.model.Submission.setDocumentLanguage (String language)
Parameters
language The new language of the document. Must be a valid java locale.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.submit.DocumentInfo.documentInfo().
void org.tdl.vireo.model.Submission.setDocumentTitle (String title)
Parameters
title The new document title.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.submit.DocumentInfo.documentInfo().
void org.tdl.vireo.model.Submission.setDocumentType (String documentType)
Parameters
documentType The new document type.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
Referenced by controllers.submit.DocumentInfo.documentInfo().
void org.tdl.vireo.model.Submission.setGraduationMonth (Integer month)
Parameters
month The new graduation month.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setGraduationYear (Integer year)
Parameters
year The new graduation year
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setLicenseAgreementDate (Date date)
Parameters
date The new date the submitter agreed to the license.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setMajor (String major)
Parameters
major The new major.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setOrcid (String orcidString)
Parameters
orcidString The ORCID identifier of the student who authored this submission.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setProgram (String program)
Parameters
program The program associated with the submission
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setProgramId (Long id)
Parameters
id - the program id that will award this degree
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setPublishedMaterial (String material)
Set whether this submission contains any material that has been previously published. If the value is null, then no material has been previously published. If it is not null then some material may have been previously published and the contents of this field should indicate which material has been published.
Parameters
material English description identifying the material previously published.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setReviewerNotes (String notes)
Set new reviewer notes, may only be set by reviewers or above. Changes are logged in the action log, but will be marked as private.
Parameters
notes The new notes for this submission.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setState (State state)
Parameters
state The new state of this submission
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setStudentBirthYear (Integer year)
Parameters
year The new birth year for the student.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setStudentFirstName (String firstName)
Parameters
firstName The new first name of the student.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setStudentLastName (String lastName)
Parameters
lastName The new last name of the student.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setStudentMiddleName (String middleName)
Parameters
middleName The new middle name of the student.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setSubmissionDate (Date date)
Parameters
data The new date the submission was submitted for review.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
void org.tdl.vireo.model.Submission.setUMIRelease (Boolean umiRelease)
Parameters
umiRelease The new UMI release status.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl.
The documentation for this interface was generated from the following file:
app/org/tdl/vireo/model/Submission.java