Vireo: org.tdl.vireo.model.Person Interface Reference
org.tdl.vireo.model.Person Interface Reference
Public Member Functions
String getNetId ()
void setNetId (String netId)
String getEmail ()
void setEmail (String email)
void setPassword (String password)
boolean validatePassword (String password)
String getInstitutionalIdentifier ()
void setInstitutionalIdentifier (String identifier)
String getFirstName ()
void setFirstName (String firstName)
String getMiddleName ()
void setMiddleName (String middleName)
String getLastName ()
void setLastName (String lastName)
String getFormattedName (NameFormat format)
String getDisplayName ()
void setDisplayName (String displayName)
Integer getBirthYear ()
void setBirthYear (Integer year)
List< String > getAffiliations ()
void addAffiliation (String affiliation)
void removeAffilation (String affiliation)
String getCurrentPhoneNumber ()
void setCurrentPhoneNumber (String phoneNumber)
String getCurrentPostalAddress ()
void setCurrentPostalAddress (String postalAddress)
String getCurrentEmailAddress ()
void setCurrentEmailAddress (String email)
String getPermanentPhoneNumber ()
void setPermanentPhoneNumber (String phoneNumber)
String getPermanentPostalAddress ()
void setPermanentPostalAddress (String postalAddress)
String getPermanentEmailAddress ()
void setPermanentEmailAddress (String email)
String getCurrentDegree ()
void setCurrentDegree (String degree)
String getCurrentDepartment ()
void setCurrentDepartment (String department)
String getCurrentProgram ()
void setCurrentProgram (String program)
String getCurrentCollege ()
void setCurrentCollege (String college)
String getCurrentMajor ()
void setCurrentMajor (String major)
Integer getCurrentGraduationYear ()
void setCurrentGraduationYear (Integer year)
Integer getCurrentGraduationMonth ()
void setCurrentGraduationMonth (Integer month)
List< Preference > getPreferences ()
Preference getPreference (String name)
Preference addPreference (String name, String value)
RoleType getRole ()
void setRole (RoleType role)
void setOrcid (String orcid)
String getOrcid ()
Public Member Functions inherited from org.tdl.vireo.model.AbstractModel
Long getId ()
public< T extends AbstractModel > T save ()
public< T extends AbstractModel > T delete ()
public< T extends AbstractModel > T refresh ()
public< T extends AbstractModel > T merge ()
public< T extends AbstractModel > T detach ()
Detailed Description
The person object is used for both students, reviewers, and administrators and is the central authentication object for Vireo. When one of these types of users login to the system either an existing Person object is identified, or a new person object is created. The one exception to this is for committee chairs, they use a separate authentication system based upon an email hash.
All of the student oriented attributes are optional, and will hopefully be supplied by the originating institution either through Shibboleth, LDAP, or another security mechanism that may be implemented. Since these values may come from external sources a student's current attributes such as Department, College, Major, etc may not be in the approved list of values for those fields this is why the datatypes are uncontrolled string values. It is intended when a student fills out their submission at that time if their attributes differ from the approved list then they will have to select the correct value from the list.
Another important change from the previous version of Vireo is that the students contact information has moved from the submission object onto the person object. This will allow the student to keep this information up-to-date across multiple submissions.
Author
Scott Phillips
Definition at line 29 of file Person.java.
Member Function Documentation
void org.tdl.vireo.model.Person.addAffiliation (String affiliation)
Parameters
affiliation The new affilation to add for this person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Preference org.tdl.vireo.model.Person.addPreference (String name, String value)
Create a new preference for this person.
Parameters
name The name of the new preference.
value The value of the new preference.
Returns
The new preference object for convenience.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
List<String> org.tdl.vireo.model.Person.getAffiliations ()
Returns
The list of affiliations this person has. Typically this is things like "Student", "Staff", "Faculty", etc and are designated by the authentication source.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by controllers.Advisor.review().
Integer org.tdl.vireo.model.Person.getBirthYear ()
Returns
The birth year for the person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), controllers.submit.PersonalInfo.personalInfo(), controllers.Authentication.profile(), and controllers.Authentication.updateProfile().
String org.tdl.vireo.model.Person.getCurrentCollege ()
Returns
The current non-controlled college.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and controllers.submit.PersonalInfo.personalInfo().
String org.tdl.vireo.model.Person.getCurrentDegree ()
Returns
The current non-controlled degree.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and controllers.submit.PersonalInfo.personalInfo().
String org.tdl.vireo.model.Person.getCurrentDepartment ()
Returns
The current non-controlled department.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and controllers.submit.PersonalInfo.personalInfo().
String org.tdl.vireo.model.Person.getCurrentEmailAddress ()
Returns
The current email address. If no specific email address is specified here, then the user's primary email address (aka getEmail()) will be returned.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), org.tdl.vireo.email.impl.VireoEmailImpl.createAddress(), and org.tdl.vireo.email.impl.VireoEmailImpl.VireoEmailImpl().
Integer org.tdl.vireo.model.Person.getCurrentGraduationMonth ()
Returns
The current non-controlled graduation month.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate().
Integer org.tdl.vireo.model.Person.getCurrentGraduationYear ()
Returns
The current graduation year.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate().
String org.tdl.vireo.model.Person.getCurrentMajor ()
Returns
The current non-controlled major.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and controllers.submit.PersonalInfo.personalInfo().
String org.tdl.vireo.model.Person.getCurrentPhoneNumber ()
Returns
The current phone number.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), controllers.submit.PersonalInfo.personalInfo(), and controllers.Authentication.updateProfile().
String org.tdl.vireo.model.Person.getCurrentPostalAddress ()
Returns
The current postal address
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and controllers.submit.PersonalInfo.personalInfo().
String org.tdl.vireo.model.Person.getCurrentProgram ()
Returns
The current non-controlled program.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by controllers.submit.PersonalInfo.personalInfo().
String org.tdl.vireo.model.Person.getDisplayName ()
Returns
The preferred display name for the person. If no specific displayName is specified then the results from getFullName() will be returned instead.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
String org.tdl.vireo.model.Person.getEmail ()
Returns
The official email address assigned by the instutiton for this person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
String org.tdl.vireo.model.Person.getFirstName ()
Returns
The first name of the person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by controllers.submit.PersonalInfo.personalInfo(), and controllers.Authentication.updateProfile().
String org.tdl.vireo.model.Person.getFormattedName (NameFormat format)
Parameters
format The format specifying how the name should be constructed.
Returns
The person's name according to the format specified.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.model.jpa.JpaSubmissionImpl.setAssignee().
String org.tdl.vireo.model.Person.getInstitutionalIdentifier ()
Returns
The institutional identifier for this person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
String org.tdl.vireo.model.Person.getLastName ()
By the time this object is saved, either a first or a last name must exist on the person.
Returns
The last name of the person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by controllers.submit.PersonalInfo.personalInfo().
String org.tdl.vireo.model.Person.getMiddleName ()
Returns
The middle name of the person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), controllers.submit.PersonalInfo.personalInfo(), and controllers.Authentication.updateProfile().
String org.tdl.vireo.model.Person.getNetId ()
Returns
The unique non-public identifier assigned by the institution for this person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
String org.tdl.vireo.model.Person.getOrcid ()
Returns
Return the orcid id of this person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and controllers.submit.PersonalInfo.personalInfo().
String org.tdl.vireo.model.Person.getPermanentEmailAddress ()
Returns
The permanent email address
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), controllers.submit.PersonalInfo.personalInfo(), and controllers.Authentication.updateProfile().
String org.tdl.vireo.model.Person.getPermanentPhoneNumber ()
Returns
The permanent phone number.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), controllers.submit.PersonalInfo.personalInfo(), and controllers.Authentication.updateProfile().
String org.tdl.vireo.model.Person.getPermanentPostalAddress ()
Returns
The permanent postal address.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and controllers.submit.PersonalInfo.personalInfo().
Preference org.tdl.vireo.model.Person.getPreference (String name)
Find the preference with the given name for this user.
Parameters
name The name of the preference
Returns
The preference
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.email.impl.VireoEmailImpl.VireoEmailImpl().
List<Preference> org.tdl.vireo.model.Person.getPreferences ()
Returns
return all the preferences for this person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
RoleType org.tdl.vireo.model.Person.getRole ()
Returns
Return the vireo role of this person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
void org.tdl.vireo.model.Person.removeAffilation (String affiliation)
Parameters
affiliation Remove this affilation from this person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
void org.tdl.vireo.model.Person.setBirthYear (Integer year)
Parameters
year The new birth year for the person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
void org.tdl.vireo.model.Person.setCurrentCollege (String college)
Parameters
college The new college.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate().
void org.tdl.vireo.model.Person.setCurrentDegree (String degree)
Parameters
department The new degree
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate().
void org.tdl.vireo.model.Person.setCurrentDepartment (String department)
Parameters
department The new department
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate().
void org.tdl.vireo.model.Person.setCurrentEmailAddress (String email)
Parameters
email The new current email address.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate().
void org.tdl.vireo.model.Person.setCurrentGraduationMonth (Integer month)
Parameters
month The new graduation month.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
void org.tdl.vireo.model.Person.setCurrentGraduationYear (Integer year)
Parameters
year The new graduation year.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
void org.tdl.vireo.model.Person.setCurrentMajor (String major)
Parameters
major The new major.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate().
void org.tdl.vireo.model.Person.setCurrentPhoneNumber (String phoneNumber)
Parameters
phoneNumber The new current phone number.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate().
void org.tdl.vireo.model.Person.setCurrentPostalAddress (String postalAddress)
Parameters
postalAddress The new current postal address.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and controllers.submit.PersonalInfo.personalInfo().
void org.tdl.vireo.model.Person.setCurrentProgram (String program)
Parameters
program The new program
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
void org.tdl.vireo.model.Person.setDisplayName (String displayName)
Parameters
displayName The new preferred display name for the person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
void org.tdl.vireo.model.Person.setEmail (String email)
Parameters
email The new official email address assigned by the institution for this person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
void org.tdl.vireo.model.Person.setFirstName (String firstName)
By the time this object is saved, either a first or a last name must exist on the person.
Parameters
firstName The new first name of the person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
void org.tdl.vireo.model.Person.setInstitutionalIdentifier (String identifier)
Parameters
identifier Set the institutional identifier for this person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
void org.tdl.vireo.model.Person.setLastName (String lastName)
Parameters
lastName The new last name of the person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
void org.tdl.vireo.model.Person.setMiddleName (String middleName)
Parameters
middleName The new middle name of the person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate().
void org.tdl.vireo.model.Person.setNetId (String netId)
Parameters
netId The new unique non-public identifier assigned by the institution for this person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
void org.tdl.vireo.model.Person.setOrcid (String orcid)
Parameters
orcid The orcid id of this person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate().
void org.tdl.vireo.model.Person.setPassword (String password)
It is highly recommended that all implementations store the password as a hash in any persistent storage mechanism.
Parameters
password Update this person's password to the new password. Or null to remove a password from this person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
void org.tdl.vireo.model.Person.setPermanentEmailAddress (String email)
Parameters
email The new permanent email address.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and controllers.submit.PersonalInfo.personalInfo().
void org.tdl.vireo.model.Person.setPermanentPhoneNumber (String phoneNumber)
Parameters
phoneNumber The new permanent phone number.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate(), and controllers.submit.PersonalInfo.personalInfo().
void org.tdl.vireo.model.Person.setPermanentPostalAddress (String postalAddress)
Parameters
postalAddress The new permanent postal address
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by org.tdl.vireo.security.impl.ShibbolethAuthenticationMethodImpl.authenticate().
void org.tdl.vireo.model.Person.setRole (RoleType role)
Parameters
role The new role of this person.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
boolean org.tdl.vireo.model.Person.validatePassword (String password)
Parameters
password The password to validate.
Returns
True if the provided password matches the stored password for this person. If the person's current password is null, then this method will always return false.
Implemented in org.tdl.vireo.model.jpa.JpaPersonImpl.
Referenced by controllers.Authentication.updatePassword().
The documentation for this interface was generated from the following file:
app/org/tdl/vireo/model/Person.java