Vireo: org.tdl.vireo.model.AbstractModel Interface Reference
org.tdl.vireo.model.AbstractModel Interface Reference
Public Member Functions
Long getId ()
public< T extends AbstractModel > T save ()
public< T extends AbstractModel > T delete ()
public< T extends AbstractModel > T refresh ()
public< T extends AbstractModel > T merge ()
public< T extends AbstractModel > T detach ()
Detailed Description
This is the abstract parent interface for all Vireo model objects. It defines the very basic information that is expected of all model objects such as a unique identifier, along with save and delete actions to control persistence.
Author
Scott Phillips
Parameters
<T> The specific type of vireo model.
Definition at line 14 of file AbstractModel.java.
Member Function Documentation
public<T extends AbstractModel> T org.tdl.vireo.model.AbstractModel.delete ()
Remove the object from persistent storage.
Returns
The deleted object, for convenience.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl, org.tdl.vireo.model.jpa.JpaAttachmentImpl, org.tdl.vireo.model.jpa.JpaPersonImpl, org.tdl.vireo.model.jpa.JpaEmailWorkflowRuleImpl, org.tdl.vireo.model.jpa.JpaCommitteeMemberImpl, org.tdl.vireo.model.jpa.JpaActionLogImpl, org.tdl.vireo.model.jpa.JpaEmbargoTypeImpl, org.tdl.vireo.model.jpa.JpaCustomActionValueImpl, org.tdl.vireo.model.jpa.JpaDepositLocationImpl, org.tdl.vireo.model.jpa.JpaEmailTemplateImpl, org.tdl.vireo.model.jpa.ActionLogAttachment, org.tdl.vireo.model.jpa.JpaPreferenceImpl, org.tdl.vireo.model.jpa.JpaCollegeImpl, org.tdl.vireo.model.jpa.JpaCommitteeMemberRoleTypeImpl, org.tdl.vireo.model.jpa.JpaAdministrativeGroupImpl, org.tdl.vireo.model.jpa.JpaDegreeImpl, org.tdl.vireo.model.jpa.JpaDepartmentImpl, org.tdl.vireo.model.jpa.JpaDocumentTypeImpl, org.tdl.vireo.model.jpa.JpaProgramImpl, org.tdl.vireo.model.jpa.JpaCustomActionDefinitionImpl, org.tdl.vireo.model.jpa.JpaLanguageImpl, org.tdl.vireo.model.jpa.JpaEmailWorkflowRuleConditionImpl, org.tdl.vireo.model.jpa.JpaConfigurationImpl, org.tdl.vireo.model.jpa.JpaGraduationMonthImpl, org.tdl.vireo.model.jpa.JpaMajorImpl, and org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.
Referenced by controllers.Student.removeAdditional().
public<T extends AbstractModel> T org.tdl.vireo.model.AbstractModel.detach ()
Remove this object as a currently managed entity. After calling this method accessing relationship information may result in an exception, and it is no longer valid to call any persistence method. In order to restore the object to a persistable state the merge() method needs to be called.
Returns
the detached model, for convienence
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl, org.tdl.vireo.model.jpa.JpaActionLogImpl, org.tdl.vireo.model.jpa.ActionLogAttachment, and org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.
Long org.tdl.vireo.model.AbstractModel.getId ()
Returns
The unique identifier of this object. Some implementation may use a unique identifier across Vireo models, while other implementations may have ids that are unique only among all objects of the same type.
Implemented in org.tdl.vireo.model.jpa.ActionLogAttachment.
Referenced by org.tdl.vireo.model.jpa.JpaSubmissionImpl.addEmbargoType(), controllers.submit.Confirm.confirm(), org.tdl.vireo.export.impl.DepositServiceImpl.deposit(), org.tdl.vireo.export.impl.FileDepositorImpl.deposit(), controllers.settings.ConfigurableSettingsTab.editEmbargoTypeJSON(), org.tdl.vireo.error.impl.ErrorReportImpl.ErrorReportImpl(), org.tdl.vireo.job.impl.JobManagerImpl.findJobsByOwner(), org.tdl.vireo.export.impl.FilePackagerImpl.generatePackage(), org.tdl.vireo.export.impl.MultipleTemplatePackagerImpl.generatePackage(), org.tdl.vireo.export.impl.TemplatePackagerImpl.generatePackage(), org.tdl.vireo.export.impl.ExcelPackagerImpl.generatePackage(), org.tdl.vireo.search.impl.LuceneIndexerImpl.isUpdated(), controllers.Authentication.loginMethod(), controllers.Authentication.loginReturn(), controllers.submit.PersonalInfo.personalInfo(), org.tdl.vireo.export.impl.ExcelPackagerImpl.processWorkbookRow(), org.tdl.vireo.model.jpa.JpaSubmissionImpl.removeEmbargoType(), controllers.Advisor.review(), controllers.Advisor.reviewJSON(), controllers.Student.submissionDelete(), controllers.Student.submissionView(), org.tdl.vireo.search.impl.LuceneIndexerImpl.updated(), controllers.Authentication.updatePassword(), and controllers.Authentication.updateProfile().
public<T extends AbstractModel> T org.tdl.vireo.model.AbstractModel.merge ()
Merge this object to obtain a managed entity. Note the object returned may be a new instance of the object merged into the current transaction.
Returns
The merged model
Implemented in org.tdl.vireo.model.jpa.ActionLogAttachment, and org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.
public<T extends AbstractModel> T org.tdl.vireo.model.AbstractModel.refresh ()
Refresh the entity state. This will reset any in memory changes to the object and reload the state from the persistent storage.
Returns
the refreshed object, for convenience.
Implemented in org.tdl.vireo.model.jpa.ActionLogAttachment, and org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.
public<T extends AbstractModel> T org.tdl.vireo.model.AbstractModel.save ()
Persist any changes made to this object.
Returns
The saved object, for convenience.
Implemented in org.tdl.vireo.model.jpa.JpaSubmissionImpl, org.tdl.vireo.model.jpa.JpaAttachmentImpl, org.tdl.vireo.model.jpa.JpaPersonImpl, org.tdl.vireo.model.jpa.JpaEmailWorkflowRuleImpl, org.tdl.vireo.model.jpa.JpaEmbargoTypeImpl, org.tdl.vireo.model.jpa.JpaActionLogImpl, org.tdl.vireo.model.jpa.JpaCommitteeMemberImpl, org.tdl.vireo.model.jpa.JpaDepositLocationImpl, org.tdl.vireo.model.jpa.JpaCustomActionValueImpl, org.tdl.vireo.model.jpa.JpaEmailTemplateImpl, org.tdl.vireo.model.jpa.ActionLogAttachment, org.tdl.vireo.model.jpa.JpaPreferenceImpl, org.tdl.vireo.model.jpa.JpaCollegeImpl, org.tdl.vireo.model.jpa.JpaCommitteeMemberRoleTypeImpl, org.tdl.vireo.model.jpa.JpaAdministrativeGroupImpl, org.tdl.vireo.model.jpa.JpaDegreeImpl, org.tdl.vireo.model.jpa.JpaDepartmentImpl, org.tdl.vireo.model.jpa.JpaDocumentTypeImpl, org.tdl.vireo.model.jpa.JpaProgramImpl, org.tdl.vireo.model.jpa.JpaCustomActionDefinitionImpl, org.tdl.vireo.model.jpa.JpaLanguageImpl, org.tdl.vireo.model.jpa.JpaConfigurationImpl, org.tdl.vireo.model.jpa.JpaGraduationMonthImpl, org.tdl.vireo.model.jpa.JpaMajorImpl, org.tdl.vireo.model.jpa.JpaEmailWorkflowRuleConditionImpl, and org.tdl.vireo.model.jpa.JpaAbstractModel< T extends JpaAbstractModel >.
The documentation for this interface was generated from the following file:
app/org/tdl/vireo/model/AbstractModel.java