vireo.constant("SubmissionStates", {
  NONE: "NONE",
	IN_PROGRESS: "IN_PROGRESS",
	SUBMITTED: "SUBMITTED",
	UNDER_REVIEW: "UNDER_REVIEW",
	NEEDS_CORRECTION: "NEEDS_CORRECTION",
	CORRECTIONS_RECEIVED: "CORRECTIONS_RECEIVED",
	WAITING_ON_REQUIREMENTS: "WAITING_ON_REQUIREMENTS",
	APPROVED: "APPROVED",
	PENDING_PUBLICATION: "PENDING_PUBLICATION",
	PUBLISHED: "PUBLISHED",
	ON_HOLD: "ON_HOLD",
	WITHDRAWN: "WITHDRAWN",
	CANCELLED: "CANCELLED"
});