vireo.constant("EmailRecipientType", {
    SUBMITTER: "SUBMITTER",
    ADVISOR: "ADVISOR",
    ASSIGNEE: "ASSIGNEE",
    ORGANIZATION: "ORGANIZATION",
    CONTACT: "CONTACT",
    PLAIN_ADDRESS: "PLAIN_ADDRESS"
});
