vireo.constant("InputTypes", {
	INPUT_CHECKBOX: "INPUT_CHECKBOX",
	INPUT_CONTACT: "INPUT_CONTACT",
	INPUT_DEGREEDATE: "INPUT_DEGREEDATE",
	INPUT_DATETIME: "INPUT_DATETIME",
	INPUT_EMAIL: "INPUT_EMAIL",
	INPUT_FILE: "INPUT_FILE",
	INPUT_RADIO: "INPUT_RADIO",
	INPUT_SELECT: "INPUT_SELECT",
	INPUT_TEL: "INPUT_TEL",
	INPUT_TEXT: "INPUT_TEXT",
	INPUT_TEXTAREA: "INPUT_TEXTAREA",
	INPUT_URL: "INPUT_URL",
	INPUT_LICENSE: "INPUT_LICENSE",
	INPUT_PROQUEST: "INPUT_PROQUEST"
});
