package org.tdl.vireo.model.export.enums;

public enum DefaultSettingKey {
    APPLICATION_GRANTOR,
    EXPORT_RELEASE_STUDENT_CONTACT_INFORMATION,
    PROQUEST_INDEXING,
    PROQUEST_EXTERNAL_ID,
    PROQUEST_INSTITUTION_CODE,
    PROQUEST_APPLY_FOR_COPYRIGHT,
    PROQUEST_SALE_RESTRICTION_CODE,
    PROQUEST_SALE_RESTRICTION_REMOVE,
    PROQUEST_FORMAT_RESTRICTION_CODE,
    PROQUEST_FORMAT_RESTRICTION_REMOVE
}
