package org.tdl.vireo.model.export.enums;

public enum DSpaceSimpleKey {
    STUDENT_FULL_NAME_WITH_BIRTH_YEAR,
    USER_ORCID,
    TITLE,
    ABSTRACT,
    ABSTRACT_LINES,
    SUBJECT_FIELD_VALUES,
    COMMITTEE_CHAIR,
    COMMITTEE_MEMBER_FIELD_VALUES,
    GRADUATION_DATE_YEAR_MONTH_STRING,
    GRADUATION_DATE_MONTH_YEAR_STRING,
    APPROVAL_DATE_STRING,
    PRIMARY_DOCUMENT_MIMETYPE,
    PROQUEST_LANGUAGE_CODE,
    SUBMISSION_TYPE,
    DEPOSIT_URL,
    STUDENT_SHORT_NAME,
    DEGREE_NAME,
    DEGREE_LEVEL,
    DEGREE_MAJOR,
    DEPARTMENT,
    DEGREE_COLLEGE,
    DEGREE_SCHOOL,
    DEGREE_PROGRAM,
    FORMATTED_COMMITTEE_APPROVED_EMBARGO_LIFT_DATE
}
