package org.tdl.vireo.model.export.enums;

public enum DSpaceMETSKey {
    AGENT,
    STUDENT_SHORT_NAME,
    STUDENT_FULL_NAME_WITH_BIRTH_YEAR,
    SUBMISSION_TYPE,
    DEPOSIT_URL,
    PRIMARY_DOCUMENT_MIMETYPE,
    PRIMARY_DOCUMENT_FIELD_VALUE,
    SUPPLEMENTAL_AND_SOURCE_DOCUMENT_FIELD_VALUES,
    LICENSE_DOCUMENT_FIELD_VALUES,
    METS_FIELD_VALUES,
    GRADUATION_MONTH_YEAR,
    GRADUATION_YEAR_MONTH,
    GRANTOR
}
