package org.tdl.vireo.model.export.enums;

public enum MarcXML21Key {
    SUBMITTER_GRADUATION_YEAR,
    STUDENT_FULL_NAME_WITH_BIRTH_YEAR,
    TITLE,
    TITLE_IND2,
    DEGREE_LEVEL,
    DEGREE_NAME,
    MAJOR,
    DEPOSIT_URL,
    ABSTRACT,
    KEYWORD_FIELD_VALUES,
    DEPARTMENT,
    COMMITTEE_CHAIR_FIELD_VALUES,
    COMMITTEE_MEMBER_FIELD_VALUES,
    PRIMARY_DOCUMENT_MIMETYPE
}
