package org.tdl.vireo.model.export.enums;

public enum ProQuestUMIKey {
    TIME,
    AGENT,
    FILE_HELPER,
    SUBMISSION,
    SUBMISSION_ID,
    FIELD_VALUES,
    STUDENT_SHORT_NAME,
    STUDENT_FULL_NAME_WITH_BIRTH_YEAR,
    PRIMARY_DOCUMENT_MIMETYPE,
    LICENSE_AGREEMENT_DATE,
    SUBMISSION_DATE,
    SUBMISSION_TYPE,
    COMMITTEE_APPROVAL_DATE,
    APPROVAL_DATE,
    PRIMARY_DOCUMENT_FIELD_VALUE,
    SUPPLEMENTAL_AND_SOURCE_DOCUMENT_FIELD_VALUES,
    LICENSE_DOCUMENT_FIELD_VALUES
}
