package org.tdl.vireo.model.export.enums;

public enum SubmissionPropertyKey {
    SUBMISSION_ID,
    FIELD_VALUES,
    FORMATTED_APPLICATION_APPROVAL_DATE,
    LICENSE_AGREEMENT_DATE,
    FORMATTED_LICENSE_AGREEMENT_DATE,
    SUBMISSION_DATE,
    FORMATTED_SUBMISSION_DATE,
    COMMITTEE_APPROVAL_DATE,
    FORMATTED_COMMITTEE_APPROVAL_DATE,
    COMMITTEE_EMBARGO_APPROVAL_DATE,
    FORMATTED_COMMITTEE_EMBARGO_APPROVAL_DATE,
    APPROVAL_DATE,
    FORMATTED_APPROVAL_DATE

    //ADVISOR_APPROVAL_DATE,
    //FORMATTED_APPROVAL_DATE,
}
